const SONGS_RNB = [
  { id: 6001, rank: 1, title: "Respect", artist: "Aretha Franklin", genre: "R&B", year: 1967, album: "I Never Loved a Man the Way I Love You" },
  { id: 6002, rank: 2, title: "(You Make Me Feel Like) A Natural Woman", artist: "Aretha Franklin", genre: "R&B", year: 1967, album: "Lady Soul" },
  { id: 6003, rank: 3, title: "Chain of Fools", artist: "Aretha Franklin", genre: "R&B", year: 1967, album: "Lady Soul" },
  { id: 6004, rank: 4, title: "Think", artist: "Aretha Franklin", genre: "R&B", year: 1968, album: "Aretha Now" },
  { id: 6005, rank: 5, title: "I Say a Little Prayer", artist: "Aretha Franklin", genre: "R&B", year: 1968, album: "Aretha Now" },
  { id: 6006, rank: 6, title: "Spanish Harlem", artist: "Aretha Franklin", genre: "R&B", year: 1971, album: "Aretha's Gold" },
  { id: 6007, rank: 7, title: "Rock Steady", artist: "Aretha Franklin", genre: "R&B", year: 1971, album: "Young, Gifted and Black" },
  { id: 6008, rank: 8, title: "Until You Come Back to Me", artist: "Aretha Franklin", genre: "R&B", year: 1973, album: "Let Me in Your Life" },
  { id: 6009, rank: 9, title: "Who's Zoomin' Who", artist: "Aretha Franklin", genre: "R&B", year: 1985, album: "Who's Zoomin' Who?" },
  { id: 6010, rank: 10, title: "Freeway of Love", artist: "Aretha Franklin", genre: "R&B", year: 1985, album: "Who's Zoomin' Who?" },
  { id: 6011, rank: 11, title: "I Knew You Were Waiting (For Me)", artist: "Aretha Franklin", genre: "R&B", year: 1987, album: "Aretha" },
  { id: 6012, rank: 12, title: "A Rose Is Still a Rose", artist: "Aretha Franklin", genre: "R&B", year: 1998, album: "A Rose Is Still a Rose" },
  { id: 6013, rank: 13, title: "What's Going On", artist: "Marvin Gaye", genre: "R&B", year: 1971, album: "What's Going On" },
  { id: 6014, rank: 14, title: "Let's Get It On", artist: "Marvin Gaye", genre: "R&B", year: 1973, album: "Let's Get It On" },
  { id: 6015, rank: 15, title: "Mercy Mercy Me (The Ecology)", artist: "Marvin Gaye", genre: "R&B", year: 1971, album: "What's Going On" },
  { id: 6016, rank: 16, title: "Sexual Healing", artist: "Marvin Gaye", genre: "R&B", year: 1982, album: "Midnight Love" },
  { id: 6017, rank: 17, title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", genre: "R&B", year: 1968, album: "In the Groove" },
  { id: 6018, rank: 18, title: "Ain't No Mountain High Enough", artist: "Marvin Gaye", genre: "R&B", year: 1967, album: "United" },
  { id: 6019, rank: 19, title: "Trouble Man", artist: "Marvin Gaye", genre: "R&B", year: 1972, album: "Trouble Man" },
  { id: 6020, rank: 20, title: "Inner City Blues (Make Me Wanna Holler)", artist: "Marvin Gaye", genre: "R&B", year: 1971, album: "What's Going On" },
  { id: 6021, rank: 21, title: "Got to Give It Up", artist: "Marvin Gaye", genre: "R&B", year: 1977, album: "Live! At the London Palladium" },
  { id: 6022, rank: 22, title: "Distant Lover", artist: "Marvin Gaye", genre: "R&B", year: 1974, album: "Let's Get It On" },
  { id: 6023, rank: 23, title: "How Sweet It Is (To Be Loved by You)", artist: "Marvin Gaye", genre: "R&B", year: 1964, album: "How Sweet It Is to Be Loved by You" },
  { id: 6024, rank: 24, title: "Stubborn Kind of Fellow", artist: "Marvin Gaye", genre: "R&B", year: 1962, album: "That Stubborn Kinda Fellow" },
  { id: 6025, rank: 25, title: "Superstition", artist: "Stevie Wonder", genre: "R&B", year: 1972, album: "Talking Book" },
  { id: 6026, rank: 26, title: "Sir Duke", artist: "Stevie Wonder", genre: "R&B", year: 1977, album: "Songs in the Key of Life" },
  { id: 6027, rank: 27, title: "Isn't She Lovely", artist: "Stevie Wonder", genre: "R&B", year: 1976, album: "Songs in the Key of Life" },
  { id: 6028, rank: 28, title: "Higher Ground", artist: "Stevie Wonder", genre: "R&B", year: 1973, album: "Innervisions" },
  { id: 6029, rank: 29, title: "Living for the City", artist: "Stevie Wonder", genre: "R&B", year: 1973, album: "Innervisions" },
  { id: 6030, rank: 30, title: "I Wish", artist: "Stevie Wonder", genre: "R&B", year: 1976, album: "Songs in the Key of Life" },
  { id: 6031, rank: 31, title: "Part-Time Lover", artist: "Stevie Wonder", genre: "R&B", year: 1985, album: "In Square Circle" },
  { id: 6032, rank: 32, title: "For Once in My Life", artist: "Stevie Wonder", genre: "R&B", year: 1968, album: "For Once in My Life" },
  { id: 6033, rank: 33, title: "My Cherie Amour", artist: "Stevie Wonder", genre: "R&B", year: 1969, album: "My Cherie Amour" },
  { id: 6034, rank: 34, title: "You Are the Sunshine of My Life", artist: "Stevie Wonder", genre: "R&B", year: 1972, album: "Talking Book" },
  { id: 6035, rank: 35, title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", genre: "R&B", year: 1970, album: "Signed Sealed & Delivered" },
  { id: 6036, rank: 36, title: "Uptight (Everything's Alright)", artist: "Stevie Wonder", genre: "R&B", year: 1965, album: "Up-Tight Everything's Alright" },
  { id: 6037, rank: 37, title: "I Just Called to Say I Love You", artist: "Stevie Wonder", genre: "R&B", year: 1984, album: "The Woman in Red" },
  { id: 6038, rank: 38, title: "Overjoyed", artist: "Stevie Wonder", genre: "R&B", year: 1985, album: "In Square Circle" },
  { id: 6039, rank: 39, title: "Master Blaster (Jammin')", artist: "Stevie Wonder", genre: "R&B", year: 1980, album: "Hotter than July" },
  { id: 6040, rank: 40, title: "Happy Birthday", artist: "Stevie Wonder", genre: "R&B", year: 1980, album: "Hotter than July" },
  { id: 6041, rank: 41, title: "I Got You (I Feel Good)", artist: "James Brown", genre: "R&B", year: 1965, album: "Out of Sight" },
  { id: 6042, rank: 42, title: "Papa's Got a Brand New Bag", artist: "James Brown", genre: "R&B", year: 1965, album: "Papa's Got a Brand New Bag" },
  { id: 6043, rank: 43, title: "Sex Machine", artist: "James Brown", genre: "R&B", year: 1970, album: "Sex Machine" },
  { id: 6044, rank: 44, title: "Super Bad", artist: "James Brown", genre: "R&B", year: 1970, album: "Super Bad" },
  { id: 6045, rank: 45, title: "Say It Loud – I'm Black and I'm Proud", artist: "James Brown", genre: "R&B", year: 1968, album: "A Soulful Christmas" },
  { id: 6046, rank: 46, title: "Get Up (I Feel Like Being a) Sex Machine", artist: "James Brown", genre: "R&B", year: 1970, album: "Sex Machine" },
  { id: 6047, rank: 47, title: "The Payback", artist: "James Brown", genre: "R&B", year: 1974, album: "The Payback" },
  { id: 6048, rank: 48, title: "Funky Drummer", artist: "James Brown", genre: "R&B", year: 1969, album: "In the Jungle Groove" },
  { id: 6049, rank: 49, title: "It's a Man's Man's Man's World", artist: "James Brown", genre: "R&B", year: 1966, album: "It's a Man's Man's Man's World" },
  { id: 6050, rank: 50, title: "Cold Sweat", artist: "James Brown", genre: "R&B", year: 1967, album: "Cold Sweat" },
  { id: 6051, rank: 51, title: "Please, Please, Please", artist: "James Brown", genre: "R&B", year: 1956, album: "Please, Please, Please" },
  { id: 6052, rank: 52, title: "Soul Power", artist: "James Brown", genre: "R&B", year: 1971, album: "Revolution of the Mind" },
  { id: 6053, rank: 53, title: "Georgia on My Mind", artist: "Ray Charles", genre: "R&B", year: 1960, album: "The Genius Hits the Road" },
  { id: 6054, rank: 54, title: "Hit the Road Jack", artist: "Ray Charles", genre: "R&B", year: 1961, album: "Hit the Road Jack" },
  { id: 6055, rank: 55, title: "What'd I Say", artist: "Ray Charles", genre: "R&B", year: 1959, album: "What'd I Say" },
  { id: 6056, rank: 56, title: "Unchain My Heart", artist: "Ray Charles", genre: "R&B", year: 1961, album: "Unchain My Heart" },
  { id: 6057, rank: 57, title: "I Can't Stop Loving You", artist: "Ray Charles", genre: "R&B", year: 1962, album: "Modern Sounds in Country and Western Music" },
  { id: 6058, rank: 58, title: "Hallelujah I Love Her So", artist: "Ray Charles", genre: "R&B", year: 1956, album: "Ray Charles" },
  { id: 6059, rank: 59, title: "A Fool for You", artist: "Ray Charles", genre: "R&B", year: 1955, album: "Ray Charles" },
  { id: 6060, rank: 60, title: "Drown in My Own Tears", artist: "Ray Charles", genre: "R&B", year: 1956, album: "Ray Charles" },
  { id: 6061, rank: 61, title: "(Sittin' On) The Dock of the Bay", artist: "Otis Redding", genre: "R&B", year: 1968, album: "The Dock of the Bay" },
  { id: 6062, rank: 62, title: "Try a Little Tenderness", artist: "Otis Redding", genre: "R&B", year: 1966, album: "Complete & Unbelievable" },
  { id: 6063, rank: 63, title: "I've Been Loving You Too Long", artist: "Otis Redding", genre: "R&B", year: 1965, album: "Otis Blue" },
  { id: 6064, rank: 64, title: "Respect", artist: "Otis Redding", genre: "R&B", year: 1965, album: "Otis Blue" },
  { id: 6065, rank: 65, title: "Mr. Pitiful", artist: "Otis Redding", genre: "R&B", year: 1964, album: "Pain in My Heart" },
  { id: 6066, rank: 66, title: "These Arms of Mine", artist: "Otis Redding", genre: "R&B", year: 1963, album: "Pain in My Heart" },
  { id: 6067, rank: 67, title: "Shake", artist: "Otis Redding", genre: "R&B", year: 1967, album: "King & Queen" },
  { id: 6068, rank: 68, title: "A Change Is Gonna Come", artist: "Sam Cooke", genre: "R&B", year: 1964, album: "Ain't That Good News" },
  { id: 6069, rank: 69, title: "Wonderful World", artist: "Sam Cooke", genre: "R&B", year: 1960, album: "The Two Sides of Sam Cooke" },
  { id: 6070, rank: 70, title: "Chain Gang", artist: "Sam Cooke", genre: "R&B", year: 1960, album: "Cooke's Tour" },
  { id: 6071, rank: 71, title: "Twistin' the Night Away", artist: "Sam Cooke", genre: "R&B", year: 1962, album: "Twistin' the Night Away" },
  { id: 6072, rank: 72, title: "Another Saturday Night", artist: "Sam Cooke", genre: "R&B", year: 1963, album: "Ain't That Good News" },
  { id: 6073, rank: 73, title: "You Send Me", artist: "Sam Cooke", genre: "R&B", year: 1957, album: "Sam Cooke" },
  { id: 6074, rank: 74, title: "Bring It On Home to Me", artist: "Sam Cooke", genre: "R&B", year: 1962, album: "Twistin' the Night Away" },
  { id: 6075, rank: 75, title: "That's Where It's At", artist: "Sam Cooke", genre: "R&B", year: 1964, album: "Ain't That Good News" },
  { id: 6076, rank: 76, title: "(Your Love Keeps Lifting Me) Higher and Higher", artist: "Jackie Wilson", genre: "R&B", year: 1967, album: "Higher and Higher" },
  { id: 6077, rank: 77, title: "Reet Petite", artist: "Jackie Wilson", genre: "R&B", year: 1957, album: "He's So Fine" },
  { id: 6078, rank: 78, title: "Lonely Teardrops", artist: "Jackie Wilson", genre: "R&B", year: 1958, album: "Lonely Teardrops" },
  { id: 6079, rank: 79, title: "To Be Loved", artist: "Jackie Wilson", genre: "R&B", year: 1958, album: "He's So Fine" },
  { id: 6080, rank: 80, title: "Baby Workout", artist: "Jackie Wilson", genre: "R&B", year: 1963, album: "Baby Workout" },
  { id: 6081, rank: 81, title: "Let's Stay Together", artist: "Al Green", genre: "R&B", year: 1971, album: "Let's Stay Together" },
  { id: 6082, rank: 82, title: "Tired of Being Alone", artist: "Al Green", genre: "R&B", year: 1971, album: "Al Green Gets Next to You" },
  { id: 6083, rank: 83, title: "I'm Still in Love with You", artist: "Al Green", genre: "R&B", year: 1972, album: "I'm Still in Love with You" },
  { id: 6084, rank: 84, title: "Love and Happiness", artist: "Al Green", genre: "R&B", year: 1972, album: "I'm Still in Love with You" },
  { id: 6085, rank: 85, title: "Here I Am (Come and Take Me)", artist: "Al Green", genre: "R&B", year: 1973, album: "Call Me" },
  { id: 6086, rank: 86, title: "Call Me (Come Back Home)", artist: "Al Green", genre: "R&B", year: 1973, album: "Call Me" },
  { id: 6087, rank: 87, title: "Look What You Done for Me", artist: "Al Green", genre: "R&B", year: 1972, album: "I'm Still in Love with You" },
  { id: 6088, rank: 88, title: "How Can You Mend a Broken Heart", artist: "Al Green", genre: "R&B", year: 1972, album: "Let's Stay Together" },
  { id: 6089, rank: 89, title: "Move On Up", artist: "Curtis Mayfield", genre: "R&B", year: 1970, album: "Curtis" },
  { id: 6090, rank: 90, title: "Superfly", artist: "Curtis Mayfield", genre: "R&B", year: 1972, album: "Superfly" },
  { id: 6091, rank: 91, title: "Freddie's Dead", artist: "Curtis Mayfield", genre: "R&B", year: 1972, album: "Superfly" },
  { id: 6092, rank: 92, title: "People Get Ready", artist: "The Impressions", genre: "R&B", year: 1965, album: "People Get Ready" },
  { id: 6093, rank: 93, title: "Give Me Your Love", artist: "Curtis Mayfield", genre: "R&B", year: 1972, album: "Superfly" },
  { id: 6094, rank: 94, title: "Pusherman", artist: "Curtis Mayfield", genre: "R&B", year: 1972, album: "Superfly" },
  { id: 6095, rank: 95, title: "Tracks of My Tears", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1965, album: "Going to a Go-Go" },
  { id: 6096, rank: 96, title: "Tears of a Clown", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1967, album: "Make It Happen" },
  { id: 6097, rank: 97, title: "Cruisin'", artist: "Smokey Robinson", genre: "R&B", year: 1979, album: "Where There's Smoke..." },
  { id: 6098, rank: 98, title: "Being with You", artist: "Smokey Robinson", genre: "R&B", year: 1981, album: "Being with You" },
  { id: 6099, rank: 99, title: "I Second That Emotion", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1967, album: "Make It Happen" },
  { id: 6100, rank: 100, title: "Ooo Baby Baby", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1965, album: "Going to a Go-Go" },
  { id: 6101, rank: 101, title: "Shop Around", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1960, album: "Hi, We're the Miracles" },
  { id: 6102, rank: 102, title: "You've Really Got a Hold on Me", artist: "Smokey Robinson & The Miracles", genre: "R&B", year: 1962, album: "You've Really Got a Hold on Me" },
  { id: 6103, rank: 103, title: "Stop! In the Name of Love", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1965, album: "More Hits by The Supremes" },
  { id: 6104, rank: 104, title: "You Can't Hurry Love", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1966, album: "The Supremes A' Go-Go" },
  { id: 6105, rank: 105, title: "Baby Love", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1964, album: "Where Did Our Love Go" },
  { id: 6106, rank: 106, title: "Where Did Our Love Go", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1964, album: "Where Did Our Love Go" },
  { id: 6107, rank: 107, title: "Ain't No Mountain High Enough", artist: "Diana Ross", genre: "R&B", year: 1970, album: "Everything Is Everything" },
  { id: 6108, rank: 108, title: "I'm Coming Out", artist: "Diana Ross", genre: "R&B", year: 1980, album: "diana" },
  { id: 6109, rank: 109, title: "Upside Down", artist: "Diana Ross", genre: "R&B", year: 1980, album: "diana" },
  { id: 6110, rank: 110, title: "Love Hangover", artist: "Diana Ross", genre: "R&B", year: 1976, album: "Diana Ross" },
  { id: 6111, rank: 111, title: "Come See About Me", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1964, album: "Where Did Our Love Go" },
  { id: 6112, rank: 112, title: "Reflections", artist: "Diana Ross & The Supremes", genre: "R&B", year: 1967, album: "Reflections" },
  { id: 6113, rank: 113, title: "My Girl", artist: "The Temptations", genre: "R&B", year: 1964, album: "The Temptin' Temptations" },
  { id: 6114, rank: 114, title: "Papa Was a Rollin' Stone", artist: "The Temptations", genre: "R&B", year: 1972, album: "All Directions" },
  { id: 6115, rank: 115, title: "Ain't Too Proud to Beg", artist: "The Temptations", genre: "R&B", year: 1966, album: "Gettin' Ready" },
  { id: 6116, rank: 116, title: "Just My Imagination", artist: "The Temptations", genre: "R&B", year: 1971, album: "Sky's the Limit" },
  { id: 6117, rank: 117, title: "I Can't Get Next to You", artist: "The Temptations", genre: "R&B", year: 1969, album: "Puzzle People" },
  { id: 6118, rank: 118, title: "Ball of Confusion", artist: "The Temptations", genre: "R&B", year: 1970, album: "Psychedelic Shack" },
  { id: 6119, rank: 119, title: "Psychedelic Shack", artist: "The Temptations", genre: "R&B", year: 1970, album: "Psychedelic Shack" },
  { id: 6120, rank: 120, title: "Get Ready", artist: "The Temptations", genre: "R&B", year: 1966, album: "Gettin' Ready" },
  { id: 6121, rank: 121, title: "Cloud Nine", artist: "The Temptations", genre: "R&B", year: 1968, album: "Cloud Nine" },
  { id: 6122, rank: 122, title: "I Can't Help Myself (Sugar Pie Honey Bunch)", artist: "Four Tops", genre: "R&B", year: 1965, album: "Four Tops" },
  { id: 6123, rank: 123, title: "Reach Out I'll Be There", artist: "Four Tops", genre: "R&B", year: 1966, album: "Four Tops on Top" },
  { id: 6124, rank: 124, title: "Bernadette", artist: "Four Tops", genre: "R&B", year: 1967, album: "Four Tops on Top" },
  { id: 6125, rank: 125, title: "Standing in the Shadows of Love", artist: "Four Tops", genre: "R&B", year: 1966, album: "Four Tops on Top" },
  { id: 6126, rank: 126, title: "Ain't No Woman (Like the One I've Got)", artist: "Four Tops", genre: "R&B", year: 1973, album: "Keeper of the Castle" },
  { id: 6127, rank: 127, title: "Midnight Train to Georgia", artist: "Gladys Knight & The Pips", genre: "R&B", year: 1973, album: "Imagination" },
  { id: 6128, rank: 128, title: "I Heard It Through the Grapevine", artist: "Gladys Knight & The Pips", genre: "R&B", year: 1967, album: "Everybody Needs Love" },
  { id: 6129, rank: 129, title: "Neither One of Us", artist: "Gladys Knight & The Pips", genre: "R&B", year: 1972, album: "Neither One of Us" },
  { id: 6130, rank: 130, title: "Best Thing That Ever Happened to Me", artist: "Gladys Knight & The Pips", genre: "R&B", year: 1974, album: "I Feel a Song" },
  { id: 6131, rank: 131, title: "You're the Best Thing That Ever Happened to Me", artist: "Gladys Knight & The Pips", genre: "R&B", year: 1973, album: "Imagination" },
  { id: 6132, rank: 132, title: "Dancing in the Street", artist: "Martha Reeves & The Vandellas", genre: "R&B", year: 1964, album: "Dance Party" },
  { id: 6133, rank: 133, title: "Heat Wave", artist: "Martha Reeves & The Vandellas", genre: "R&B", year: 1963, album: "Come and Get These Memories" },
  { id: 6134, rank: 134, title: "Nowhere to Run", artist: "Martha Reeves & The Vandellas", genre: "R&B", year: 1965, album: "Dance Party" },
  { id: 6135, rank: 135, title: "Jimmy Mack", artist: "Martha Reeves & The Vandellas", genre: "R&B", year: 1967, album: "Watch Out!" },
  { id: 6136, rank: 136, title: "Shotgun", artist: "Junior Walker & The All Stars", genre: "R&B", year: 1965, album: "Shotgun" },
  { id: 6137, rank: 137, title: "What Does It Take (To Win Your Love)", artist: "Junior Walker & The All Stars", genre: "R&B", year: 1969, album: "What Does It Take" },
  { id: 6138, rank: 138, title: "How Sweet It Is (To Be Loved by You)", artist: "Junior Walker & The All Stars", genre: "R&B", year: 1966, album: "Soul Session" },
  { id: 6139, rank: 139, title: "All Night Long (All Night)", artist: "Lionel Richie", genre: "R&B", year: 1983, album: "Can't Slow Down" },
  { id: 6140, rank: 140, title: "Hello", artist: "Lionel Richie", genre: "R&B", year: 1984, album: "Can't Slow Down" },
  { id: 6141, rank: 141, title: "Say You, Say Me", artist: "Lionel Richie", genre: "R&B", year: 1985, album: "Say You, Say Me" },
  { id: 6142, rank: 142, title: "Endless Love", artist: "Lionel Richie", genre: "R&B", year: 1981, album: "Endless Love" },
  { id: 6143, rank: 143, title: "Dancing on the Ceiling", artist: "Lionel Richie", genre: "R&B", year: 1986, album: "Dancing on the Ceiling" },
  { id: 6144, rank: 144, title: "Truly", artist: "Lionel Richie", genre: "R&B", year: 1982, album: "Can't Slow Down" },
  { id: 6145, rank: 145, title: "Stuck on You", artist: "Lionel Richie", genre: "R&B", year: 1984, album: "Can't Slow Down" },
  { id: 6146, rank: 146, title: "Three Times a Lady", artist: "Commodores", genre: "R&B", year: 1978, album: "Natural High" },
  { id: 6147, rank: 147, title: "A House Is Not a Home", artist: "Luther Vandross", genre: "R&B", year: 1981, album: "Never Too Much" },
  { id: 6148, rank: 148, title: "Never Too Much", artist: "Luther Vandross", genre: "R&B", year: 1981, album: "Never Too Much" },
  { id: 6149, rank: 149, title: "Here and Now", artist: "Luther Vandross", genre: "R&B", year: 1989, album: "The Night I Fell in Love" },
  { id: 6150, rank: 150, title: "Dance with My Father", artist: "Luther Vandross", genre: "R&B", year: 2003, album: "Dance with My Father" },
  { id: 6151, rank: 151, title: "So Amazing", artist: "Luther Vandross", genre: "R&B", year: 1983, album: "Busy Body" },
  { id: 6152, rank: 152, title: "Give Me the Reason", artist: "Luther Vandross", genre: "R&B", year: 1986, album: "Give Me the Reason" },
  { id: 6153, rank: 153, title: "Any Love", artist: "Luther Vandross", genre: "R&B", year: 1988, album: "Any Love" },
  { id: 6154, rank: 154, title: "Stop to Love", artist: "Luther Vandross", genre: "R&B", year: 1986, album: "Give Me the Reason" },
  { id: 6155, rank: 155, title: "Don't Want to Be a Fool", artist: "Luther Vandross", genre: "R&B", year: 1991, album: "Power of Love" },
  { id: 6156, rank: 156, title: "I Will Always Love You", artist: "Whitney Houston", genre: "R&B", year: 1992, album: "The Bodyguard" },
  { id: 6157, rank: 157, title: "Greatest Love of All", artist: "Whitney Houston", genre: "R&B", year: 1985, album: "Whitney Houston" },
  { id: 6158, rank: 158, title: "Saving All My Love for You", artist: "Whitney Houston", genre: "R&B", year: 1985, album: "Whitney Houston" },
  { id: 6159, rank: 159, title: "I Wanna Dance with Somebody", artist: "Whitney Houston", genre: "R&B", year: 1987, album: "Whitney" },
  { id: 6160, rank: 160, title: "Didn't We Almost Have It All", artist: "Whitney Houston", genre: "R&B", year: 1987, album: "Whitney" },
  { id: 6161, rank: 161, title: "So Emotional", artist: "Whitney Houston", genre: "R&B", year: 1987, album: "Whitney" },
  { id: 6162, rank: 162, title: "Where Do Broken Hearts Go", artist: "Whitney Houston", genre: "R&B", year: 1988, album: "Whitney" },
  { id: 6163, rank: 163, title: "One Moment in Time", artist: "Whitney Houston", genre: "R&B", year: 1988, album: "One Moment in Time" },
  { id: 6164, rank: 164, title: "I'm Your Baby Tonight", artist: "Whitney Houston", genre: "R&B", year: 1990, album: "I'm Your Baby Tonight" },
  { id: 6165, rank: 165, title: "Exhale (Shoop Shoop)", artist: "Whitney Houston", genre: "R&B", year: 1995, album: "Waiting to Exhale" },
  { id: 6166, rank: 166, title: "My Love Is Your Love", artist: "Whitney Houston", genre: "R&B", year: 1998, album: "My Love Is Your Love" },
  { id: 6167, rank: 167, title: "Rapture", artist: "Anita Baker", genre: "R&B", year: 1986, album: "Rapture" },
  { id: 6168, rank: 168, title: "Sweet Love", artist: "Anita Baker", genre: "R&B", year: 1986, album: "Rapture" },
  { id: 6169, rank: 169, title: "Caught Up in the Rapture", artist: "Anita Baker", genre: "R&B", year: 1986, album: "Rapture" },
  { id: 6170, rank: 170, title: "Giving You the Best That I Got", artist: "Anita Baker", genre: "R&B", year: 1988, album: "Giving You the Best That I Got" },
  { id: 6171, rank: 171, title: "Just Because", artist: "Anita Baker", genre: "R&B", year: 1988, album: "Giving You the Best That I Got" },
  { id: 6172, rank: 172, title: "You Bring Me Joy", artist: "Anita Baker", genre: "R&B", year: 1986, album: "Rapture" },
  { id: 6173, rank: 173, title: "Smooth Operator", artist: "Sade", genre: "R&B", year: 1984, album: "Diamond Life" },
  { id: 6174, rank: 174, title: "The Sweetest Taboo", artist: "Sade", genre: "R&B", year: 1985, album: "Promise" },
  { id: 6175, rank: 175, title: "No Ordinary Love", artist: "Sade", genre: "R&B", year: 1992, album: "Love Deluxe" },
  { id: 6176, rank: 176, title: "By Your Side", artist: "Sade", genre: "R&B", year: 2000, album: "Lovers Rock" },
  { id: 6177, rank: 177, title: "Is It a Crime", artist: "Sade", genre: "R&B", year: 1985, album: "Promise" },
  { id: 6178, rank: 178, title: "Your Love Is King", artist: "Sade", genre: "R&B", year: 1984, album: "Diamond Life" },
  { id: 6179, rank: 179, title: "Never as Good as the First Time", artist: "Sade", genre: "R&B", year: 1985, album: "Promise" },
  { id: 6180, rank: 180, title: "Brown Sugar", artist: "D'Angelo", genre: "R&B", year: 1995, album: "Brown Sugar" },
  { id: 6181, rank: 181, title: "Untitled (How Does It Feel)", artist: "D'Angelo", genre: "R&B", year: 2000, album: "Voodoo" },
  { id: 6182, rank: 182, title: "Lady", artist: "D'Angelo", genre: "R&B", year: 1995, album: "Brown Sugar" },
  { id: 6183, rank: 183, title: "Cruisin'", artist: "D'Angelo", genre: "R&B", year: 1995, album: "Brown Sugar" },
  { id: 6184, rank: 184, title: "Devil's Pie", artist: "D'Angelo", genre: "R&B", year: 2000, album: "Voodoo" },
  { id: 6185, rank: 185, title: "Left & Right", artist: "D'Angelo", genre: "R&B", year: 2000, album: "Voodoo" },
  { id: 6186, rank: 186, title: "Send It On", artist: "D'Angelo", genre: "R&B", year: 1995, album: "Brown Sugar" },
  { id: 6187, rank: 187, title: "On & On", artist: "Erykah Badu", genre: "R&B", year: 1997, album: "Baduizm" },
  { id: 6188, rank: 188, title: "Next Lifetime", artist: "Erykah Badu", genre: "R&B", year: 1997, album: "Baduizm" },
  { id: 6189, rank: 189, title: "Tyrone", artist: "Erykah Badu", genre: "R&B", year: 1997, album: "Live" },
  { id: 6190, rank: 190, title: "Bag Lady", artist: "Erykah Badu", genre: "R&B", year: 2000, album: "Mama's Gun" },
  { id: 6191, rank: 191, title: "Didn't Cha Know", artist: "Erykah Badu", genre: "R&B", year: 2000, album: "Mama's Gun" },
  { id: 6192, rank: 192, title: "Window Seat", artist: "Erykah Badu", genre: "R&B", year: 2010, album: "New Amerykah Part Two" },
  { id: 6193, rank: 193, title: "Honey", artist: "Erykah Badu", genre: "R&B", year: 2008, album: "New Amerykah Part One" },
  { id: 6194, rank: 194, title: "Doo Wop (That Thing)", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6195, rank: 195, title: "Ex-Factor", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6196, rank: 196, title: "Everything Is Everything", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6197, rank: 197, title: "To Zion", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6198, rank: 198, title: "Nothing Even Matters", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6199, rank: 199, title: "Lost Ones", artist: "Lauryn Hill", genre: "R&B", year: 1998, album: "The Miseducation of Lauryn Hill" },
  { id: 6200, rank: 200, title: "Ascension (Don't Ever Wonder)", artist: "Maxwell", genre: "R&B", year: 1996, album: "Maxwell's Urban Hang Suite" },
  { id: 6201, rank: 201, title: "Sumthin' Sumthin'", artist: "Maxwell", genre: "R&B", year: 1996, album: "Maxwell's Urban Hang Suite" },
  { id: 6202, rank: 202, title: "Fortunate", artist: "Maxwell", genre: "R&B", year: 1999, album: "Embrya" },
  { id: 6203, rank: 203, title: "This Woman's Work", artist: "Maxwell", genre: "R&B", year: 1997, album: "Maxwell's Urban Hang Suite" },
  { id: 6204, rank: 204, title: "Pretty Wings", artist: "Maxwell", genre: "R&B", year: 2009, album: "BLACKsummers'night" },
  { id: 6205, rank: 205, title: "Bad Habits", artist: "Maxwell", genre: "R&B", year: 2009, album: "BLACKsummers'night" },
  { id: 6206, rank: 206, title: "Charlene", artist: "Anthony Hamilton", genre: "R&B", year: 2003, album: "Comin' From Where I'm From" },
  { id: 6207, rank: 207, title: "Comin' From Where I'm From", artist: "Anthony Hamilton", genre: "R&B", year: 2003, album: "Comin' From Where I'm From" },
  { id: 6208, rank: 208, title: "I'm a Mess", artist: "Anthony Hamilton", genre: "R&B", year: 2005, album: "Ain't Nobody Worryin'" },
  { id: 6209, rank: 209, title: "Pass Me Over", artist: "Anthony Hamilton", genre: "R&B", year: 2003, album: "Comin' From Where I'm From" },
  { id: 6210, rank: 210, title: "Best of Me", artist: "Anthony Hamilton", genre: "R&B", year: 2005, album: "Ain't Nobody Worryin'" },
  { id: 6211, rank: 211, title: "A Long Walk", artist: "Jill Scott", genre: "R&B", year: 2000, album: "Who Is Jill Scott?" },
  { id: 6212, rank: 212, title: "Gettin' in the Way", artist: "Jill Scott", genre: "R&B", year: 2000, album: "Who Is Jill Scott?" },
  { id: 6213, rank: 213, title: "He Loves Me (Lyzel in E Flat)", artist: "Jill Scott", genre: "R&B", year: 2000, album: "Who Is Jill Scott?" },
  { id: 6214, rank: 214, title: "Golden", artist: "Jill Scott", genre: "R&B", year: 2004, album: "Beautifully Human" },
  { id: 6215, rank: 215, title: "Cross My Mind", artist: "Jill Scott", genre: "R&B", year: 2004, album: "Beautifully Human" },
  { id: 6216, rank: 216, title: "Just Friends (Sunny)", artist: "Musiq Soulchild", genre: "R&B", year: 2000, album: "Aijuswanaseing" },
  { id: 6217, rank: 217, title: "Halfcrazy", artist: "Musiq Soulchild", genre: "R&B", year: 2002, album: "Juslisen" },
  { id: 6218, rank: 218, title: "Dontchange", artist: "Musiq Soulchild", genre: "R&B", year: 2000, album: "Aijuswanaseing" },
  { id: 6219, rank: 219, title: "Love", artist: "Musiq Soulchild", genre: "R&B", year: 2000, album: "Aijuswanaseing" },
  { id: 6220, rank: 220, title: "Teach Me", artist: "Musiq Soulchild", genre: "R&B", year: 2002, album: "Juslisen" },
  { id: 6221, rank: 221, title: "Fallin'", artist: "Alicia Keys", genre: "R&B", year: 2001, album: "Songs in A Minor" },
  { id: 6222, rank: 222, title: "If I Ain't Got You", artist: "Alicia Keys", genre: "R&B", year: 2003, album: "The Diary of Alicia Keys" },
  { id: 6223, rank: 223, title: "No One", artist: "Alicia Keys", genre: "R&B", year: 2007, album: "As I Am" },
  { id: 6224, rank: 224, title: "Girl on Fire", artist: "Alicia Keys", genre: "R&B", year: 2012, album: "Girl on Fire" },
  { id: 6225, rank: 225, title: "Unbreakable", artist: "Alicia Keys", genre: "R&B", year: 2001, album: "Songs in A Minor" },
  { id: 6226, rank: 226, title: "You Don't Know My Name", artist: "Alicia Keys", genre: "R&B", year: 2003, album: "The Diary of Alicia Keys" },
  { id: 6227, rank: 227, title: "Empire State of Mind (Part II)", artist: "Alicia Keys", genre: "R&B", year: 2009, album: "The Element of Freedom" },
  { id: 6228, rank: 228, title: "Superwoman", artist: "Alicia Keys", genre: "R&B", year: 2007, album: "As I Am" },
  { id: 6229, rank: 229, title: "Crazy in Love", artist: "Beyoncé", genre: "R&B", year: 2003, album: "Dangerously in Love" },
  { id: 6230, rank: 230, title: "Halo", artist: "Beyoncé", genre: "R&B", year: 2008, album: "I Am... Sasha Fierce" },
  { id: 6231, rank: 231, title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé", genre: "R&B", year: 2008, album: "I Am... Sasha Fierce" },
  { id: 6232, rank: 232, title: "Irreplaceable", artist: "Beyoncé", genre: "R&B", year: 2006, album: "B'Day" },
  { id: 6233, rank: 233, title: "Lemonade", artist: "Beyoncé", genre: "R&B", year: 2016, album: "Lemonade" },
  { id: 6234, rank: 234, title: "Love On Top", artist: "Beyoncé", genre: "R&B", year: 2011, album: "4" },
  { id: 6235, rank: 235, title: "Drunk in Love", artist: "Beyoncé", genre: "R&B", year: 2013, album: "Beyoncé" },
  { id: 6236, rank: 236, title: "Formation", artist: "Beyoncé", genre: "R&B", year: 2016, album: "Lemonade" },
  { id: 6237, rank: 237, title: "Flawless", artist: "Beyoncé", genre: "R&B", year: 2013, album: "Beyoncé" },
  { id: 6238, rank: 238, title: "Partition", artist: "Beyoncé", genre: "R&B", year: 2013, album: "Beyoncé" },
  { id: 6239, rank: 239, title: "Hold Up", artist: "Beyoncé", genre: "R&B", year: 2016, album: "Lemonade" },
  { id: 6240, rank: 240, title: "Freedom", artist: "Beyoncé", genre: "R&B", year: 2016, album: "Lemonade" },
  { id: 6241, rank: 241, title: "Real Love", artist: "Mary J. Blige", genre: "R&B", year: 1992, album: "What's the 411?" },
  { id: 6242, rank: 242, title: "Not Gon' Cry", artist: "Mary J. Blige", genre: "R&B", year: 1995, album: "Waiting to Exhale" },
  { id: 6243, rank: 243, title: "Family Affair", artist: "Mary J. Blige", genre: "R&B", year: 2001, album: "No More Drama" },
  { id: 6244, rank: 244, title: "Be Without You", artist: "Mary J. Blige", genre: "R&B", year: 2005, album: "The Breakthrough" },
  { id: 6245, rank: 245, title: "Just Fine", artist: "Mary J. Blige", genre: "R&B", year: 2007, album: "Growing Pains" },
  { id: 6246, rank: 246, title: "No More Drama", artist: "Mary J. Blige", genre: "R&B", year: 2001, album: "No More Drama" },
  { id: 6247, rank: 247, title: "You Remind Me", artist: "Mary J. Blige", genre: "R&B", year: 1992, album: "What's the 411?" },
  { id: 6248, rank: 248, title: "I'm Goin' Down", artist: "Mary J. Blige", genre: "R&B", year: 1994, album: "My Life" },
  { id: 6249, rank: 249, title: "I Believe I Can Fly", artist: "R. Kelly", genre: "R&B", year: 1996, album: "Space Jam Soundtrack" },
  { id: 6250, rank: 250, title: "Bump N' Grind", artist: "R. Kelly", genre: "R&B", year: 1993, album: "12 Play" },
  { id: 6251, rank: 251, title: "Your Body's Callin'", artist: "R. Kelly", genre: "R&B", year: 1994, album: "12 Play" },
  { id: 6252, rank: 252, title: "I'm Your Angel", artist: "R. Kelly", genre: "R&B", year: 1998, album: "R." },
  { id: 6253, rank: 253, title: "Ignition (Remix)", artist: "R. Kelly", genre: "R&B", year: 2003, album: "Chocolate Factory" },
  { id: 6254, rank: 254, title: "Yeah!", artist: "Usher", genre: "R&B", year: 2004, album: "Confessions" },
  { id: 6255, rank: 255, title: "Burn", artist: "Usher", genre: "R&B", year: 2004, album: "Confessions" },
  { id: 6256, rank: 256, title: "Confessions Part II", artist: "Usher", genre: "R&B", year: 2004, album: "Confessions" },
  { id: 6257, rank: 257, title: "U Remind Me", artist: "Usher", genre: "R&B", year: 2001, album: "8701" },
  { id: 6258, rank: 258, title: "My Boo", artist: "Usher", genre: "R&B", year: 2004, album: "Confessions" },
  { id: 6259, rank: 259, title: "Nice & Slow", artist: "Usher", genre: "R&B", year: 1997, album: "My Way" },
  { id: 6260, rank: 260, title: "U Got It Bad", artist: "Usher", genre: "R&B", year: 2001, album: "8701" },
  { id: 6261, rank: 261, title: "OMG", artist: "Usher", genre: "R&B", year: 2010, album: "Raymond v. Raymond" },
  { id: 6262, rank: 262, title: "Climax", artist: "Usher", genre: "R&B", year: 2012, album: "Looking 4 Myself" },
  { id: 6263, rank: 263, title: "So Sick", artist: "Ne-Yo", genre: "R&B", year: 2006, album: "In My Own Words" },
  { id: 6264, rank: 264, title: "Because of You", artist: "Ne-Yo", genre: "R&B", year: 2007, album: "Because of You" },
  { id: 6265, rank: 265, title: "Miss Independent", artist: "Ne-Yo", genre: "R&B", year: 2008, album: "Year of the Gentleman" },
  { id: 6266, rank: 266, title: "Closer", artist: "Ne-Yo", genre: "R&B", year: 2008, album: "Year of the Gentleman" },
  { id: 6267, rank: 267, title: "Mad", artist: "Ne-Yo", genre: "R&B", year: 2008, album: "Year of the Gentleman" },
  { id: 6268, rank: 268, title: "With You", artist: "Chris Brown", genre: "R&B", year: 2007, album: "Exclusive" },
  { id: 6269, rank: 269, title: "No Air", artist: "Chris Brown", genre: "R&B", year: 2007, album: "Exclusive" },
  { id: 6270, rank: 270, title: "Forever", artist: "Chris Brown", genre: "R&B", year: 2008, album: "Exclusive" },
  { id: 6271, rank: 271, title: "Beautiful People", artist: "Chris Brown", genre: "R&B", year: 2011, album: "F.A.M.E." },
  { id: 6272, rank: 272, title: "Loyal", artist: "Chris Brown", genre: "R&B", year: 2014, album: "X" },
  { id: 6273, rank: 273, title: "Fine China", artist: "Chris Brown", genre: "R&B", year: 2013, album: "Fortune" },
  { id: 6274, rank: 274, title: "Adorn", artist: "Miguel", genre: "R&B", year: 2012, album: "Kaleidoscope Dream" },
  { id: 6275, rank: 275, title: "Sure Thing", artist: "Miguel", genre: "R&B", year: 2010, album: "All I Want Is You" },
  { id: 6276, rank: 276, title: "How Many Drinks?", artist: "Miguel", genre: "R&B", year: 2012, album: "Kaleidoscope Dream" },
  { id: 6277, rank: 277, title: "Do You Like Drugs", artist: "Miguel", genre: "R&B", year: 2012, album: "Kaleidoscope Dream" },
  { id: 6278, rank: 278, title: "Coffee", artist: "Miguel", genre: "R&B", year: 2015, album: "Wildheart" },
  { id: 6279, rank: 279, title: "Thinkin Bout You", artist: "Frank Ocean", genre: "R&B", year: 2012, album: "channel ORANGE" },
  { id: 6280, rank: 280, title: "Pyramids", artist: "Frank Ocean", genre: "R&B", year: 2012, album: "channel ORANGE" },
  { id: 6281, rank: 281, title: "Lost", artist: "Frank Ocean", genre: "R&B", year: 2012, album: "channel ORANGE" },
  { id: 6282, rank: 282, title: "Nights", artist: "Frank Ocean", genre: "R&B", year: 2016, album: "Blonde" },
  { id: 6283, rank: 283, title: "Self Control", artist: "Frank Ocean", genre: "R&B", year: 2016, album: "Blonde" },
  { id: 6284, rank: 284, title: "Godspeed", artist: "Frank Ocean", genre: "R&B", year: 2016, album: "Blonde" },
  { id: 6285, rank: 285, title: "Pink + White", artist: "Frank Ocean", genre: "R&B", year: 2016, album: "Blonde" },
  { id: 6286, rank: 286, title: "Chanel", artist: "Frank Ocean", genre: "R&B", year: 2017, album: "Singles" },
  { id: 6287, rank: 287, title: "Blinding Lights", artist: "The Weeknd", genre: "R&B", year: 2019, album: "After Hours" },
  { id: 6288, rank: 288, title: "Can't Feel My Face", artist: "The Weeknd", genre: "R&B", year: 2015, album: "Beauty Behind the Madness" },
  { id: 6289, rank: 289, title: "The Hills", artist: "The Weeknd", genre: "R&B", year: 2015, album: "Beauty Behind the Madness" },
  { id: 6290, rank: 290, title: "Starboy", artist: "The Weeknd", genre: "R&B", year: 2016, album: "Starboy" },
  { id: 6291, rank: 291, title: "Save Your Tears", artist: "The Weeknd", genre: "R&B", year: 2020, album: "After Hours" },
  { id: 6292, rank: 292, title: "Call Out My Name", artist: "The Weeknd", genre: "R&B", year: 2018, album: "My Dear Melancholy" },
  { id: 6293, rank: 293, title: "Often", artist: "The Weeknd", genre: "R&B", year: 2014, album: "Beauty Behind the Madness" },
  { id: 6294, rank: 294, title: "I Feel It Coming", artist: "The Weeknd", genre: "R&B", year: 2016, album: "Starboy" },
  { id: 6295, rank: 295, title: "Earned It", artist: "The Weeknd", genre: "R&B", year: 2015, album: "Fifty Shades of Grey" },
  { id: 6296, rank: 296, title: "Uptown Funk", artist: "Bruno Mars", genre: "R&B", year: 2014, album: "Uptown Special" },
  { id: 6297, rank: 297, title: "Treasure", artist: "Bruno Mars", genre: "R&B", year: 2012, album: "Unorthodox Jukebox" },
  { id: 6298, rank: 298, title: "Just the Way You Are", artist: "Bruno Mars", genre: "R&B", year: 2010, album: "Doo-Wops & Hooligans" },
  { id: 6299, rank: 299, title: "Grenade", artist: "Bruno Mars", genre: "R&B", year: 2010, album: "Doo-Wops & Hooligans" },
  { id: 6300, rank: 300, title: "When I Was Your Man", artist: "Bruno Mars", genre: "R&B", year: 2012, album: "Unorthodox Jukebox" },
  { id: 6301, rank: 301, title: "That's What I Like", artist: "Bruno Mars", genre: "R&B", year: 2016, album: "24K Magic" },
  { id: 6302, rank: 302, title: "24K Magic", artist: "Bruno Mars", genre: "R&B", year: 2016, album: "24K Magic" },
  { id: 6303, rank: 303, title: "Versace on the Floor", artist: "Bruno Mars", genre: "R&B", year: 2016, album: "24K Magic" },
  { id: 6304, rank: 304, title: "Locked Out of Heaven", artist: "Bruno Mars", genre: "R&B", year: 2012, album: "Unorthodox Jukebox" },
  { id: 6305, rank: 305, title: "Come Down", artist: "Anderson .Paak", genre: "R&B", year: 2016, album: "Malibu" },
  { id: 6306, rank: 306, title: "Am I Wrong", artist: "Anderson .Paak", genre: "R&B", year: 2016, album: "Malibu" },
  { id: 6307, rank: 307, title: "Lazaretto", artist: "Anderson .Paak", genre: "R&B", year: 2016, album: "Malibu" },
  { id: 6308, rank: 308, title: "Suede", artist: "Anderson .Paak", genre: "R&B", year: 2019, album: "Ventura" },
  { id: 6309, rank: 309, title: "Make It Better", artist: "Anderson .Paak", genre: "R&B", year: 2019, album: "Ventura" },
  { id: 6310, rank: 310, title: "Tints", artist: "Anderson .Paak", genre: "R&B", year: 2018, album: "Oxnard" },
  { id: 6311, rank: 311, title: "Best Part", artist: "H.E.R.", genre: "R&B", year: 2017, album: "H.E.R." },
  { id: 6312, rank: 312, title: "Focus", artist: "H.E.R.", genre: "R&B", year: 2016, album: "H.E.R." },
  { id: 6313, rank: 313, title: "I Used to Know Her", artist: "H.E.R.", genre: "R&B", year: 2019, album: "I Used to Know Her" },
  { id: 6314, rank: 314, title: "Sometimes", artist: "H.E.R.", genre: "R&B", year: 2017, album: "H.E.R." },
  { id: 6315, rank: 315, title: "Damage", artist: "H.E.R.", genre: "R&B", year: 2021, album: "Back of My Mind" },
  { id: 6316, rank: 316, title: "Love Galore", artist: "SZA", genre: "R&B", year: 2017, album: "Ctrl" },
  { id: 6317, rank: 317, title: "Drew Barrymore", artist: "SZA", genre: "R&B", year: 2017, album: "Ctrl" },
  { id: 6318, rank: 318, title: "The Weekend", artist: "SZA", genre: "R&B", year: 2017, album: "Ctrl" },
  { id: 6319, rank: 319, title: "Kill Bill", artist: "SZA", genre: "R&B", year: 2022, album: "SOS" },
  { id: 6320, rank: 320, title: "Snooze", artist: "SZA", genre: "R&B", year: 2022, album: "SOS" },
  { id: 6321, rank: 321, title: "Good Days", artist: "SZA", genre: "R&B", year: 2020, album: "SOS" },
  { id: 6322, rank: 322, title: "Broken Clocks", artist: "SZA", genre: "R&B", year: 2017, album: "Ctrl" },
  { id: 6323, rank: 323, title: "Location", artist: "Khalid", genre: "R&B", year: 2017, album: "American Teen" },
  { id: 6324, rank: 324, title: "Young Dumb & Broke", artist: "Khalid", genre: "R&B", year: 2017, album: "American Teen" },
  { id: 6325, rank: 325, title: "Better", artist: "Khalid", genre: "R&B", year: 2018, album: "Free Spirit" },
  { id: 6326, rank: 326, title: "Talk", artist: "Khalid", genre: "R&B", year: 2019, album: "Free Spirit" },
  { id: 6327, rank: 327, title: "OTW", artist: "Khalid", genre: "R&B", year: 2018, album: "Free Spirit" },
  { id: 6328, rank: 328, title: "Heartbreak Anniversary", artist: "Giveon", genre: "R&B", year: 2020, album: "Take Time" },
  { id: 6329, rank: 329, title: "Like I Want You", artist: "Giveon", genre: "R&B", year: 2019, album: "Take Time" },
  { id: 6330, rank: 330, title: "Still Your Best", artist: "Giveon", genre: "R&B", year: 2020, album: "Take Time" },
  { id: 6331, rank: 331, title: "Coming Home", artist: "Giveon", genre: "R&B", year: 2021, album: "Give or Take" },
  { id: 6332, rank: 332, title: "Purple Rain", artist: "Prince", genre: "R&B", year: 1984, album: "Purple Rain" },
  { id: 6333, rank: 333, title: "Kiss", artist: "Prince", genre: "R&B", year: 1986, album: "Parade" },
  { id: 6334, rank: 334, title: "When Doves Cry", artist: "Prince", genre: "R&B", year: 1984, album: "Purple Rain" },
  { id: 6335, rank: 335, title: "Sign 'O' the Times", artist: "Prince", genre: "R&B", year: 1987, album: "Sign 'O' the Times" },
  { id: 6336, rank: 336, title: "Little Red Corvette", artist: "Prince", genre: "R&B", year: 1982, album: "1999" },
  { id: 6337, rank: 337, title: "Raspberry Beret", artist: "Prince", genre: "R&B", year: 1985, album: "Around the World in a Day" },
  { id: 6338, rank: 338, title: "I Would Die 4 U", artist: "Prince", genre: "R&B", year: 1984, album: "Purple Rain" },
  { id: 6339, rank: 339, title: "Let's Go Crazy", artist: "Prince", genre: "R&B", year: 1984, album: "Purple Rain" },
  { id: 6340, rank: 340, title: "1999", artist: "Prince", genre: "R&B", year: 1982, album: "1999" },
  { id: 6341, rank: 341, title: "Cream", artist: "Prince", genre: "R&B", year: 1991, album: "Diamonds and Pearls" },
  { id: 6342, rank: 342, title: "Diamonds and Pearls", artist: "Prince", genre: "R&B", year: 1991, album: "Diamonds and Pearls" },
  { id: 6343, rank: 343, title: "Super Freak", artist: "Rick James", genre: "R&B", year: 1981, album: "Street Songs" },
  { id: 6344, rank: 344, title: "Give It to Me Baby", artist: "Rick James", genre: "R&B", year: 1981, album: "Street Songs" },
  { id: 6345, rank: 345, title: "Mary Jane (All Night Long)", artist: "Rick James", genre: "R&B", year: 1978, album: "Come Get It!" },
  { id: 6346, rank: 346, title: "Ebony Eyes", artist: "Rick James", genre: "R&B", year: 1983, album: "Cold Blooded" },
  { id: 6347, rank: 347, title: "Cold Blooded", artist: "Rick James", genre: "R&B", year: 1983, album: "Cold Blooded" },
  { id: 6348, rank: 348, title: "I'm Every Woman", artist: "Chaka Khan", genre: "R&B", year: 1978, album: "Chaka" },
  { id: 6349, rank: 349, title: "Tell Me Something Good", artist: "Rufus", genre: "R&B", year: 1974, album: "Rags to Rufus" },
  { id: 6350, rank: 350, title: "Ain't Nobody", artist: "Chaka Khan", genre: "R&B", year: 1983, album: "I Feel for You" },
  { id: 6351, rank: 351, title: "I Feel for You", artist: "Chaka Khan", genre: "R&B", year: 1984, album: "I Feel for You" },
  { id: 6352, rank: 352, title: "Through the Fire", artist: "Chaka Khan", genre: "R&B", year: 1984, album: "I Feel for You" },
  { id: 6353, rank: 353, title: "September", artist: "Earth, Wind & Fire", genre: "R&B", year: 1978, album: "The Best of Earth, Wind & Fire, Vol. 1" },
  { id: 6354, rank: 354, title: "Shining Star", artist: "Earth, Wind & Fire", genre: "R&B", year: 1975, album: "That's the Way of the World" },
  { id: 6355, rank: 355, title: "Boogie Wonderland", artist: "Earth, Wind & Fire", genre: "R&B", year: 1979, album: "I Am" },
  { id: 6356, rank: 356, title: "Fantasy", artist: "Earth, Wind & Fire", genre: "R&B", year: 1977, album: "All 'N All" },
  { id: 6357, rank: 357, title: "Let's Groove", artist: "Earth, Wind & Fire", genre: "R&B", year: 1981, album: "Raise!" },
  { id: 6358, rank: 358, title: "After the Love Has Gone", artist: "Earth, Wind & Fire", genre: "R&B", year: 1979, album: "I Am" },
  { id: 6359, rank: 359, title: "Got to Get You into My Life", artist: "Earth, Wind & Fire", genre: "R&B", year: 1978, album: "The Best of Earth, Wind & Fire, Vol. 1" },
  { id: 6360, rank: 360, title: "Sing a Song", artist: "Earth, Wind & Fire", genre: "R&B", year: 1975, album: "Gratitude" },
  { id: 6361, rank: 361, title: "Flash Light", artist: "Parliament", genre: "R&B", year: 1977, album: "Funkentelechy Vs. the Placebo Syndrome" },
  { id: 6362, rank: 362, title: "Give Up the Funk (Tear the Roof off the Sucker)", artist: "Parliament", genre: "R&B", year: 1976, album: "Mothership Connection" },
  { id: 6363, rank: 363, title: "One Nation Under a Groove", artist: "Funkadelic", genre: "R&B", year: 1978, album: "One Nation Under a Groove" },
  { id: 6364, rank: 364, title: "Atomic Dog", artist: "George Clinton", genre: "R&B", year: 1982, album: "Computer Games" },
  { id: 6365, rank: 365, title: "Knee Deep", artist: "Funkadelic", genre: "R&B", year: 1979, album: "Uncle Jam Wants You" },
  { id: 6366, rank: 366, title: "(Not Just) Knee Deep", artist: "Funkadelic", genre: "R&B", year: 1979, album: "Uncle Jam Wants You" },
  { id: 6367, rank: 367, title: "Celebration", artist: "Kool & the Gang", genre: "R&B", year: 1980, album: "Celebrate!" },
  { id: 6368, rank: 368, title: "Get Down on It", artist: "Kool & the Gang", genre: "R&B", year: 1981, album: "Something Special" },
  { id: 6369, rank: 369, title: "Joanna", artist: "Kool & the Gang", genre: "R&B", year: 1983, album: "In the Heart" },
  { id: 6370, rank: 370, title: "Cherish", artist: "Kool & the Gang", genre: "R&B", year: 1985, album: "Emergency" },
  { id: 6371, rank: 371, title: "Fresh", artist: "Kool & the Gang", genre: "R&B", year: 1984, album: "Emergency" },
  { id: 6372, rank: 372, title: "Ladies' Night", artist: "Kool & the Gang", genre: "R&B", year: 1979, album: "Ladies' Night" },
  { id: 6373, rank: 373, title: "Too Hot", artist: "Kool & the Gang", genre: "R&B", year: 1980, album: "Ladies' Night" },
  { id: 6374, rank: 374, title: "Easy", artist: "Commodores", genre: "R&B", year: 1977, album: "Commodores" },
  { id: 6375, rank: 375, title: "Brick House", artist: "Commodores", genre: "R&B", year: 1977, album: "Commodores" },
  { id: 6376, rank: 376, title: "Nightshift", artist: "Commodores", genre: "R&B", year: 1985, album: "Nightshift" },
  { id: 6377, rank: 377, title: "Sail On", artist: "Commodores", genre: "R&B", year: 1979, album: "Midnight Magic" },
  { id: 6378, rank: 378, title: "Still", artist: "Commodores", genre: "R&B", year: 1979, album: "Midnight Magic" },
  { id: 6379, rank: 379, title: "Just to Be Close to You", artist: "Commodores", genre: "R&B", year: 1976, album: "Hot on the Tracks" },
  { id: 6380, rank: 380, title: "Back at One", artist: "Brian McKnight", genre: "R&B", year: 1999, album: "Back at One" },
  { id: 6381, rank: 381, title: "One Last Cry", artist: "Brian McKnight", genre: "R&B", year: 1993, album: "Brian McKnight" },
  { id: 6382, rank: 382, title: "Anytime", artist: "Brian McKnight", genre: "R&B", year: 1997, album: "Anytime" },
  { id: 6383, rank: 383, title: "On Bended Knee", artist: "Boyz II Men", genre: "R&B", year: 1994, album: "II" },
  { id: 6384, rank: 384, title: "End of the Road", artist: "Boyz II Men", genre: "R&B", year: 1992, album: "Cooleyhighharmony" },
  { id: 6385, rank: 385, title: "I'll Make Love to You", artist: "Boyz II Men", genre: "R&B", year: 1994, album: "II" },
  { id: 6386, rank: 386, title: "Water Runs Dry", artist: "Boyz II Men", genre: "R&B", year: 1994, album: "II" },
  { id: 6387, rank: 387, title: "Motownphilly", artist: "Boyz II Men", genre: "R&B", year: 1991, album: "Cooleyhighharmony" },
  { id: 6388, rank: 388, title: "4 Seasons of Loneliness", artist: "Boyz II Men", genre: "R&B", year: 1997, album: "Evolution" },
  { id: 6389, rank: 389, title: "A Song for Mama", artist: "Boyz II Men", genre: "R&B", year: 1997, album: "Evolution" },
  { id: 6390, rank: 390, title: "Exhale (Shoop Shoop)", artist: "Boyz II Men", genre: "R&B", year: 1995, album: "Waiting to Exhale" },
  { id: 6391, rank: 391, title: "It's So Hard to Say Goodbye to Yesterday", artist: "Boyz II Men", genre: "R&B", year: 1991, album: "Cooleyhighharmony" },
  { id: 6392, rank: 392, title: "Can You Stand the Rain", artist: "New Edition", genre: "R&B", year: 1988, album: "Heart Break" },
  { id: 6393, rank: 393, title: "If It Isn't Love", artist: "New Edition", genre: "R&B", year: 1988, album: "Heart Break" },
  { id: 6394, rank: 394, title: "Mr. Telephone Man", artist: "New Edition", genre: "R&B", year: 1984, album: "New Edition" },
  { id: 6395, rank: 395, title: "Candy Girl", artist: "New Edition", genre: "R&B", year: 1983, album: "Candy Girl" },
  { id: 6396, rank: 396, title: "Cool It Now", artist: "New Edition", genre: "R&B", year: 1984, album: "New Edition" },
  { id: 6397, rank: 397, title: "You Don't Have to Worry", artist: "New Edition", genre: "R&B", year: 1996, album: "Home Again" },
  { id: 6398, rank: 398, title: "With You I'm Born Again", artist: "Billy Preston", genre: "R&B", year: 1979, album: "With You I'm Born Again" },
  { id: 6399, rank: 399, title: "Nothing from Nothing", artist: "Billy Preston", genre: "R&B", year: 1974, album: "The Kids & Me" },
  { id: 6400, rank: 400, title: "Outta Space", artist: "Billy Preston", genre: "R&B", year: 1971, album: "I Wrote a Simple Song" },
  { id: 6401, rank: 401, title: "Will It Go Round in Circles", artist: "Billy Preston", genre: "R&B", year: 1972, album: "Music Is My Life" },
  { id: 6402, rank: 402, title: "I'm in Love", artist: "Wilson Pickett", genre: "R&B", year: 1967, album: "The Exciting Wilson Pickett" },
  { id: 6403, rank: 403, title: "In the Midnight Hour", artist: "Wilson Pickett", genre: "R&B", year: 1965, album: "In the Midnight Hour" },
  { id: 6404, rank: 404, title: "Land of 1000 Dances", artist: "Wilson Pickett", genre: "R&B", year: 1966, album: "The Exciting Wilson Pickett" },
  { id: 6405, rank: 405, title: "Mustang Sally", artist: "Wilson Pickett", genre: "R&B", year: 1966, album: "The Exciting Wilson Pickett" },
  { id: 6406, rank: 406, title: "Funky Broadway", artist: "Wilson Pickett", genre: "R&B", year: 1967, album: "The Exciting Wilson Pickett" },
  { id: 6407, rank: 407, title: "634-5789 (Soulsville, U.S.A.)", artist: "Wilson Pickett", genre: "R&B", year: 1966, album: "The Exciting Wilson Pickett" },
  { id: 6408, rank: 408, title: "The Midnight Special", artist: "Creedence Clearwater Revival", genre: "R&B", year: 1969, album: "Willy and the Poor Boys" },
  { id: 6409, rank: 409, title: "It Takes Two", artist: "Marvin Gaye", genre: "R&B", year: 1967, album: "United" },
  { id: 6410, rank: 410, title: "Your Precious Love", artist: "Marvin Gaye", genre: "R&B", year: 1967, album: "United" },
  { id: 6411, rank: 411, title: "Ain't Nothing Like the Real Thing", artist: "Marvin Gaye", genre: "R&B", year: 1968, album: "You're All I Need" },
  { id: 6412, rank: 412, title: "You're All I Need to Get By", artist: "Marvin Gaye", genre: "R&B", year: 1968, album: "You're All I Need" },
  { id: 6413, rank: 413, title: "Good Lovin' Ain't Easy to Come By", artist: "Marvin Gaye", genre: "R&B", year: 1969, album: "That's the Way Love Is" },
  { id: 6414, rank: 414, title: "Keep on Lovin' Me Honey", artist: "Marvin Gaye", genre: "R&B", year: 1968, album: "You're All I Need" },
  { id: 6415, rank: 415, title: "If This World Were Mine", artist: "Marvin Gaye", genre: "R&B", year: 1967, album: "United" },
  { id: 6416, rank: 416, title: "Let's Get It On (Extended)", artist: "Marvin Gaye", genre: "R&B", year: 1973, album: "Let's Get It On" },
  { id: 6417, rank: 417, title: "Come Get to This", artist: "Marvin Gaye", genre: "R&B", year: 1973, album: "Let's Get It On" },
  { id: 6418, rank: 418, title: "I Want You", artist: "Marvin Gaye", genre: "R&B", year: 1976, album: "I Want You" },
  { id: 6419, rank: 419, title: "After the Dance", artist: "Marvin Gaye", genre: "R&B", year: 1976, album: "I Want You" },
  { id: 6420, rank: 420, title: "Tomorrow Never Knows", artist: "Marvin Gaye", genre: "R&B", year: 1985, album: "Dream of a Lifetime" },
  { id: 6421, rank: 421, title: "Freak Me", artist: "Silk", genre: "R&B", year: 1993, album: "Lose Control" },
  { id: 6422, rank: 422, title: "Spend My Life with You", artist: "Eric Benet", genre: "R&B", year: 1999, album: "A Day in the Life" },
  { id: 6423, rank: 423, title: "In Those Jeans", artist: "Ginuwine", genre: "R&B", year: 2003, album: "The Life" },
  { id: 6424, rank: 424, title: "Pony", artist: "Ginuwine", genre: "R&B", year: 1996, album: "Ginuwine...the Bachelor" },
  { id: 6425, rank: 425, title: "Differences", artist: "Ginuwine", genre: "R&B", year: 2001, album: "The Life" },
  { id: 6426, rank: 426, title: "Tell Me", artist: "Dru Hill", genre: "R&B", year: 1996, album: "Dru Hill" },
  { id: 6427, rank: 427, title: "In My Bed", artist: "Dru Hill", genre: "R&B", year: 1996, album: "Dru Hill" },
  { id: 6428, rank: 428, title: "Beauty", artist: "Dru Hill", genre: "R&B", year: 1997, album: "Enter the Dru" },
  { id: 6429, rank: 429, title: "How Deep Is Your Love", artist: "Dru Hill", genre: "R&B", year: 1998, album: "Enter the Dru" },
  { id: 6430, rank: 430, title: "Let Me Love You", artist: "Mario", genre: "R&B", year: 2004, album: "Turning Point" },
  { id: 6431, rank: 431, title: "Just a Friend 2002", artist: "Mario", genre: "R&B", year: 2002, album: "Mario" },
  { id: 6432, rank: 432, title: "Whoa", artist: "Mario", genre: "R&B", year: 2009, album: "D.N.A." },
  { id: 6433, rank: 433, title: "I Just Wanna Love U", artist: "Jay-Z", genre: "R&B", year: 2000, album: "The Dynasty: Roc la Familia" },
  { id: 6434, rank: 434, title: "Always on Time", artist: "Ja Rule", genre: "R&B", year: 2001, album: "Pain Is Love" },
  { id: 6435, rank: 435, title: "Mesmerize", artist: "Ja Rule", genre: "R&B", year: 2002, album: "The Last Temptation" },
  { id: 6436, rank: 436, title: "Put It on Me", artist: "Ja Rule", genre: "R&B", year: 2000, album: "Rule 3:36" },
  { id: 6437, rank: 437, title: "Where the Party At", artist: "Jagged Edge", genre: "R&B", year: 2001, album: "Jagged Little Thrill" },
  { id: 6438, rank: 438, title: "Let's Get Married", artist: "Jagged Edge", genre: "R&B", year: 2000, album: "Jagged Little Thrill" },
  { id: 6439, rank: 439, title: "He Can't Love U", artist: "Jagged Edge", genre: "R&B", year: 2000, album: "Jagged Little Thrill" },
  { id: 6440, rank: 440, title: "Promise", artist: "Ciara", genre: "R&B", year: 2006, album: "Ciara: The Evolution" },
  { id: 6441, rank: 441, title: "Goodies", artist: "Ciara", genre: "R&B", year: 2004, album: "Goodies" },
  { id: 6442, rank: 442, title: "1, 2 Step", artist: "Ciara", genre: "R&B", year: 2004, album: "Goodies" },
  { id: 6443, rank: 443, title: "Oh", artist: "Ciara", genre: "R&B", year: 2005, album: "Ciara: The Evolution" },
  { id: 6444, rank: 444, title: "Like a Boy", artist: "Ciara", genre: "R&B", year: 2006, album: "Ciara: The Evolution" },
  { id: 6445, rank: 445, title: "Body Party", artist: "Ciara", genre: "R&B", year: 2013, album: "One Woman Army" },
  { id: 6446, rank: 446, title: "Love Sex Magic", artist: "Ciara", genre: "R&B", year: 2009, album: "Fantasy Ride" },
  { id: 6447, rank: 447, title: "Rule the World", artist: "Talib Kweli", genre: "R&B", year: 2006, album: "Eardrum" },
  { id: 6448, rank: 448, title: "Caught Up", artist: "Usher", genre: "R&B", year: 2004, album: "Confessions" },
  { id: 6449, rank: 449, title: "DJ Got Us Fallin' in Love", artist: "Usher", genre: "R&B", year: 2010, album: "Raymond v. Raymond" },
  { id: 6450, rank: 450, title: "There Goes My Baby", artist: "Usher", genre: "R&B", year: 2010, album: "Raymond v. Raymond" },
  { id: 6451, rank: 451, title: "More", artist: "Usher", genre: "R&B", year: 2010, album: "Raymond v. Raymond" },
  { id: 6452, rank: 452, title: "Hey Daddy (Daddy's Home)", artist: "Usher", genre: "R&B", year: 2010, album: "Raymond v. Raymond" },
  { id: 6453, rank: 453, title: "Fantasy", artist: "Mariah Carey", genre: "R&B", year: 1995, album: "Daydream" },
  { id: 6454, rank: 454, title: "We Belong Together", artist: "Mariah Carey", genre: "R&B", year: 2005, album: "The Emancipation of Mimi" },
  { id: 6455, rank: 455, title: "Always Be My Baby", artist: "Mariah Carey", genre: "R&B", year: 1995, album: "Daydream" },
  { id: 6456, rank: 456, title: "Emotions", artist: "Mariah Carey", genre: "R&B", year: 1991, album: "Emotions" },
  { id: 6457, rank: 457, title: "Dreamlover", artist: "Mariah Carey", genre: "R&B", year: 1993, album: "Music Box" },
  { id: 6458, rank: 458, title: "Hero", artist: "Mariah Carey", genre: "R&B", year: 1993, album: "Music Box" },
  { id: 6459, rank: 459, title: "Heartbreaker", artist: "Mariah Carey", genre: "R&B", year: 1999, album: "Rainbow" },
  { id: 6460, rank: 460, title: "Obsessed", artist: "Mariah Carey", genre: "R&B", year: 2009, album: "Memoirs of an Imperfect Angel" },
  { id: 6461, rank: 461, title: "Shake It Off", artist: "Mariah Carey", genre: "R&B", year: 2005, album: "The Emancipation of Mimi" },
  { id: 6462, rank: 462, title: "Vision of Love", artist: "Mariah Carey", genre: "R&B", year: 1990, album: "Mariah Carey" },
  { id: 6463, rank: 463, title: "All for You", artist: "Janet Jackson", genre: "R&B", year: 2001, album: "All for You" },
  { id: 6464, rank: 464, title: "Together Again", artist: "Janet Jackson", genre: "R&B", year: 1997, album: "The Velvet Rope" },
  { id: 6465, rank: 465, title: "Nasty", artist: "Janet Jackson", genre: "R&B", year: 1986, album: "Control" },
  { id: 6466, rank: 466, title: "Control", artist: "Janet Jackson", genre: "R&B", year: 1986, album: "Control" },
  { id: 6467, rank: 467, title: "When I Think of You", artist: "Janet Jackson", genre: "R&B", year: 1986, album: "Control" },
  { id: 6468, rank: 468, title: "Miss You Much", artist: "Janet Jackson", genre: "R&B", year: 1989, album: "Rhythm Nation 1814" },
  { id: 6469, rank: 469, title: "Rhythm Nation", artist: "Janet Jackson", genre: "R&B", year: 1989, album: "Rhythm Nation 1814" },
  { id: 6470, rank: 470, title: "Escapade", artist: "Janet Jackson", genre: "R&B", year: 1989, album: "Rhythm Nation 1814" },
  { id: 6471, rank: 471, title: "That's the Way Love Goes", artist: "Janet Jackson", genre: "R&B", year: 1993, album: "janet." },
  { id: 6472, rank: 472, title: "Any Time, Any Place", artist: "Janet Jackson", genre: "R&B", year: 1993, album: "janet." },
  { id: 6473, rank: 473, title: "Again", artist: "Janet Jackson", genre: "R&B", year: 1993, album: "janet." },
  { id: 6474, rank: 474, title: "Waterfalls", artist: "TLC", genre: "R&B", year: 1994, album: "CrazySexyCool" },
  { id: 6475, rank: 475, title: "No Scrubs", artist: "TLC", genre: "R&B", year: 1999, album: "FanMail" },
  { id: 6476, rank: 476, title: "Creep", artist: "TLC", genre: "R&B", year: 1994, album: "CrazySexyCool" },
  { id: 6477, rank: 477, title: "Red Light Special", artist: "TLC", genre: "R&B", year: 1994, album: "CrazySexyCool" },
  { id: 6478, rank: 478, title: "Diggin' on You", artist: "TLC", genre: "R&B", year: 1994, album: "CrazySexyCool" },
  { id: 6479, rank: 479, title: "Unpretty", artist: "TLC", genre: "R&B", year: 1999, album: "FanMail" },
  { id: 6480, rank: 480, title: "Crazy Sexy Cool", artist: "TLC", genre: "R&B", year: 1994, album: "CrazySexyCool" },
  { id: 6481, rank: 481, title: "Say My Name", artist: "Destiny's Child", genre: "R&B", year: 1999, album: "The Writing's on the Wall" },
  { id: 6482, rank: 482, title: "Survivor", artist: "Destiny's Child", genre: "R&B", year: 2001, album: "Survivor" },
  { id: 6483, rank: 483, title: "Bootylicious", artist: "Destiny's Child", genre: "R&B", year: 2001, album: "Survivor" },
  { id: 6484, rank: 484, title: "Independent Women Part I", artist: "Destiny's Child", genre: "R&B", year: 2000, album: "Survivor" },
  { id: 6485, rank: 485, title: "Bills, Bills, Bills", artist: "Destiny's Child", genre: "R&B", year: 1999, album: "The Writing's on the Wall" },
  { id: 6486, rank: 486, title: "Jumpin' Jumpin'", artist: "Destiny's Child", genre: "R&B", year: 1999, album: "The Writing's on the Wall" },
  { id: 6487, rank: 487, title: "Hot Stuff", artist: "Donna Summer", genre: "R&B", year: 1979, album: "Bad Girls" },
  { id: 6488, rank: 488, title: "Bad Girls", artist: "Donna Summer", genre: "R&B", year: 1979, album: "Bad Girls" },
  { id: 6489, rank: 489, title: "Love to Love You Baby", artist: "Donna Summer", genre: "R&B", year: 1975, album: "Love to Love You Baby" },
  { id: 6490, rank: 490, title: "Last Dance", artist: "Donna Summer", genre: "R&B", year: 1978, album: "Thank God It's Friday" },
  { id: 6491, rank: 491, title: "This Time I Know It's for Real", artist: "Donna Summer", genre: "R&B", year: 1989, album: "Another Place and Time" },
  { id: 6492, rank: 492, title: "She Works Hard for the Money", artist: "Donna Summer", genre: "R&B", year: 1983, album: "She Works Hard for the Money" },
  { id: 6493, rank: 493, title: "On the Radio", artist: "Donna Summer", genre: "R&B", year: 1979, album: "On the Radio" },
  { id: 6494, rank: 494, title: "MacArthur Park", artist: "Donna Summer", genre: "R&B", year: 1978, album: "Live and More" },
  { id: 6495, rank: 495, title: "Heaven Knows", artist: "Donna Summer", genre: "R&B", year: 1979, album: "Bad Girls" },
  { id: 6496, rank: 496, title: "I Will Survive", artist: "Gloria Gaynor", genre: "R&B", year: 1978, album: "Love Tracks" },
  { id: 6497, rank: 497, title: "Never Can Say Goodbye", artist: "Gloria Gaynor", genre: "R&B", year: 1974, album: "Never Can Say Goodbye" },
  { id: 6498, rank: 498, title: "Le Freak", artist: "Chic", genre: "R&B", year: 1978, album: "C'est Chic" },
  { id: 6499, rank: 499, title: "Good Times", artist: "Chic", genre: "R&B", year: 1979, album: "Risqué" },
  { id: 6500, rank: 500, title: "Dance, Dance, Dance (Yowsah, Yowsah, Yowsah)", artist: "Chic", genre: "R&B", year: 1977, album: "Chic" }
];

