const SONGS_BLUES = [
  { id: 5001, rank: 1, title: "Cross Road Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5002, rank: 2, title: "Sweet Home Chicago", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5003, rank: 3, title: "Love in Vain Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5004, rank: 4, title: "I Believe I'll Dust My Broom", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5005, rank: 5, title: "Terraplane Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5006, rank: 6, title: "Come On in My Kitchen", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5007, rank: 7, title: "Hellhound on My Trail", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5008, rank: 8, title: "Me and the Devil Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5009, rank: 9, title: "Stop Breakin' Down Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5010, rank: 10, title: "Walking Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5011, rank: 11, title: "Ramblin' on My Mind", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5012, rank: 12, title: "32-20 Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5013, rank: 13, title: "Kind Hearted Woman Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5014, rank: 14, title: "Phonograph Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5015, rank: 15, title: "Dead Shrimp Blues", artist: "Robert Johnson", genre: "Blues", year: 1937, album: "The Complete Recordings" },
  { id: 5016, rank: 16, title: "Hoochie Coochie Man", artist: "Muddy Waters", genre: "Blues", year: 1954, album: "The Best of Muddy Waters" },
  { id: 5017, rank: 17, title: "Mannish Boy", artist: "Muddy Waters", genre: "Blues", year: 1955, album: "The Best of Muddy Waters" },
  { id: 5018, rank: 18, title: "Rolling Stone", artist: "Muddy Waters", genre: "Blues", year: 1950, album: "The Best of Muddy Waters" },
  { id: 5019, rank: 19, title: "Got My Mojo Working", artist: "Muddy Waters", genre: "Blues", year: 1957, album: "At Newport 1960" },
  { id: 5020, rank: 20, title: "I'm Your Hoochie Coochie Man", artist: "Muddy Waters", genre: "Blues", year: 1954, album: "The Best of Muddy Waters" },
  { id: 5021, rank: 21, title: "Feel Like Going Home", artist: "Muddy Waters", genre: "Blues", year: 1948, album: "The Best of Muddy Waters" },
  { id: 5022, rank: 22, title: "I Just Want to Make Love to You", artist: "Muddy Waters", genre: "Blues", year: 1954, album: "The Best of Muddy Waters" },
  { id: 5023, rank: 23, title: "Trouble No More", artist: "Muddy Waters", genre: "Blues", year: 1955, album: "The Best of Muddy Waters" },
  { id: 5024, rank: 24, title: "Muddy Water Blues", artist: "Muddy Waters", genre: "Blues", year: 1951, album: "The Chess Box" },
  { id: 5025, rank: 25, title: "Long Distance Call", artist: "Muddy Waters", genre: "Blues", year: 1951, album: "The Best of Muddy Waters" },
  { id: 5026, rank: 26, title: "Honey Bee", artist: "Muddy Waters", genre: "Blues", year: 1951, album: "The Best of Muddy Waters" },
  { id: 5027, rank: 27, title: "Standing Around Crying", artist: "Muddy Waters", genre: "Blues", year: 1952, album: "The Chess Box" },
  { id: 5028, rank: 28, title: "Still a Fool", artist: "Muddy Waters", genre: "Blues", year: 1951, album: "The Chess Box" },
  { id: 5029, rank: 29, title: "She Moves Me", artist: "Muddy Waters", genre: "Blues", year: 1952, album: "The Chess Box" },
  { id: 5030, rank: 30, title: "Screamin' and Cryin'", artist: "Muddy Waters", genre: "Blues", year: 1954, album: "The Chess Box" },
  { id: 5031, rank: 31, title: "The Thrill Is Gone", artist: "B.B. King", genre: "Blues", year: 1969, album: "Completely Well" },
  { id: 5032, rank: 32, title: "Every Day I Have the Blues", artist: "B.B. King", genre: "Blues", year: 1955, album: "B.B. King Sings Spirituals" },
  { id: 5033, rank: 33, title: "How Blue Can You Get", artist: "B.B. King", genre: "Blues", year: 1964, album: "Live at the Regal" },
  { id: 5034, rank: 34, title: "Sweet Little Angel", artist: "B.B. King", genre: "Blues", year: 1956, album: "Singin' the Blues" },
  { id: 5035, rank: 35, title: "Rock Me Baby", artist: "B.B. King", genre: "Blues", year: 1964, album: "Live at the Regal" },
  { id: 5036, rank: 36, title: "Paying the Cost to Be the Boss", artist: "B.B. King", genre: "Blues", year: 1968, album: "Lucille" },
  { id: 5037, rank: 37, title: "Three O'Clock Blues", artist: "B.B. King", genre: "Blues", year: 1951, album: "Singin' the Blues" },
  { id: 5038, rank: 38, title: "When Love Comes to Town", artist: "B.B. King", genre: "Blues", year: 1988, album: "Rattle and Hum" },
  { id: 5039, rank: 39, title: "Why I Sing the Blues", artist: "B.B. King", genre: "Blues", year: 1969, album: "Completely Well" },
  { id: 5040, rank: 40, title: "Guess Who", artist: "B.B. King", genre: "Blues", year: 1972, album: "L.A. Midnight" },
  { id: 5041, rank: 41, title: "Let the Good Times Roll", artist: "B.B. King", genre: "Blues", year: 1976, album: "Bobby Bland and B.B. King Together Again" },
  { id: 5042, rank: 42, title: "Chains and Things", artist: "B.B. King", genre: "Blues", year: 1970, album: "Indianola Mississippi Seeds" },
  { id: 5043, rank: 43, title: "Please Accept My Love", artist: "B.B. King", genre: "Blues", year: 1958, album: "Singin' the Blues" },
  { id: 5044, rank: 44, title: "You Upset Me Baby", artist: "B.B. King", genre: "Blues", year: 1954, album: "Singin' the Blues" },
  { id: 5045, rank: 45, title: "Riding with the King", artist: "B.B. King", genre: "Blues", year: 2000, album: "Riding with the King" },
  { id: 5046, rank: 46, title: "Smokestack Lightning", artist: "Howlin' Wolf", genre: "Blues", year: 1956, album: "Moanin' in the Moonshine" },
  { id: 5047, rank: 47, title: "Spoonful", artist: "Howlin' Wolf", genre: "Blues", year: 1960, album: "Howlin' Wolf" },
  { id: 5048, rank: 48, title: "Back Door Man", artist: "Howlin' Wolf", genre: "Blues", year: 1961, album: "Howlin' Wolf" },
  { id: 5049, rank: 49, title: "Killing Floor", artist: "Howlin' Wolf", genre: "Blues", year: 1965, album: "The Real Folk Blues" },
  { id: 5050, rank: 50, title: "Wang Dang Doodle", artist: "Howlin' Wolf", genre: "Blues", year: 1960, album: "Howlin' Wolf" },
  { id: 5051, rank: 51, title: "Sittin' on Top of the World", artist: "Howlin' Wolf", genre: "Blues", year: 1957, album: "Moanin' in the Moonshine" },
  { id: 5052, rank: 52, title: "Evil", artist: "Howlin' Wolf", genre: "Blues", year: 1954, album: "Moanin' in the Moonshine" },
  { id: 5053, rank: 53, title: "Little Red Rooster", artist: "Howlin' Wolf", genre: "Blues", year: 1961, album: "Howlin' Wolf" },
  { id: 5054, rank: 54, title: "How Many More Years", artist: "Howlin' Wolf", genre: "Blues", year: 1951, album: "Moanin' in the Moonshine" },
  { id: 5055, rank: 55, title: "The Red Rooster", artist: "Howlin' Wolf", genre: "Blues", year: 1961, album: "Howlin' Wolf" },
  { id: 5056, rank: 56, title: "Hidden Charms", artist: "Howlin' Wolf", genre: "Blues", year: 1964, album: "The Real Folk Blues" },
  { id: 5057, rank: 57, title: "Commit a Crime", artist: "Howlin' Wolf", genre: "Blues", year: 1966, album: "The Real Folk Blues" },
  { id: 5058, rank: 58, title: "Highway 49", artist: "Howlin' Wolf", genre: "Blues", year: 1951, album: "Moanin' in the Moonshine" },
  { id: 5059, rank: 59, title: "Who's Been Talkin'", artist: "Howlin' Wolf", genre: "Blues", year: 1959, album: "Moanin' in the Moonshine" },
  { id: 5060, rank: 60, title: "Tail Dragger", artist: "Howlin' Wolf", genre: "Blues", year: 1962, album: "Howlin' Wolf" },
  { id: 5061, rank: 61, title: "Boom Boom", artist: "John Lee Hooker", genre: "Blues", year: 1962, album: "Boom Boom" },
  { id: 5062, rank: 62, title: "Boogie Chillen", artist: "John Lee Hooker", genre: "Blues", year: 1948, album: "The Best of John Lee Hooker" },
  { id: 5063, rank: 63, title: "I'm in the Mood", artist: "John Lee Hooker", genre: "Blues", year: 1951, album: "The Best of John Lee Hooker" },
  { id: 5064, rank: 64, title: "Dimples", artist: "John Lee Hooker", genre: "Blues", year: 1956, album: "The Best of John Lee Hooker" },
  { id: 5065, rank: 65, title: "Crawling King Snake", artist: "John Lee Hooker", genre: "Blues", year: 1949, album: "The Best of John Lee Hooker" },
  { id: 5066, rank: 66, title: "One Bourbon, One Scotch, One Beer", artist: "John Lee Hooker", genre: "Blues", year: 1966, album: "It Serve You Right to Suffer" },
  { id: 5067, rank: 67, title: "Tupelo Blues", artist: "John Lee Hooker", genre: "Blues", year: 1960, album: "The Real Folk Blues" },
  { id: 5068, rank: 68, title: "Burnin' Hell", artist: "John Lee Hooker", genre: "Blues", year: 1949, album: "The Best of John Lee Hooker" },
  { id: 5069, rank: 69, title: "It Serves You Right to Suffer", artist: "John Lee Hooker", genre: "Blues", year: 1966, album: "It Serve You Right to Suffer" },
  { id: 5070, rank: 70, title: "Shake It Baby", artist: "John Lee Hooker", genre: "Blues", year: 1962, album: "Boom Boom" },
  { id: 5071, rank: 71, title: "The Healer", artist: "John Lee Hooker", genre: "Blues", year: 1989, album: "The Healer" },
  { id: 5072, rank: 72, title: "I Cover the Waterfront", artist: "John Lee Hooker", genre: "Blues", year: 1970, album: "Hooker 'n Heat" },
  { id: 5073, rank: 73, title: "Whiskey and Wimmen", artist: "John Lee Hooker", genre: "Blues", year: 1966, album: "It Serve You Right to Suffer" },
  { id: 5074, rank: 74, title: "I'm Mad Again", artist: "John Lee Hooker", genre: "Blues", year: 1962, album: "Boom Boom" },
  { id: 5075, rank: 75, title: "Mr. Lucky", artist: "John Lee Hooker", genre: "Blues", year: 1991, album: "Mr. Lucky" },
  { id: 5076, rank: 76, title: "Dust My Broom", artist: "Elmore James", genre: "Blues", year: 1951, album: "The Sky Is Crying" },
  { id: 5077, rank: 77, title: "The Sky Is Crying", artist: "Elmore James", genre: "Blues", year: 1959, album: "The Sky Is Crying" },
  { id: 5078, rank: 78, title: "Shake Your Moneymaker", artist: "Elmore James", genre: "Blues", year: 1961, album: "The Sky Is Crying" },
  { id: 5079, rank: 79, title: "Something Inside Me", artist: "Elmore James", genre: "Blues", year: 1961, album: "The Sky Is Crying" },
  { id: 5080, rank: 80, title: "Bleeding Heart", artist: "Elmore James", genre: "Blues", year: 1960, album: "The Sky Is Crying" },
  { id: 5081, rank: 81, title: "Rollin' and Tumblin'", artist: "Elmore James", genre: "Blues", year: 1953, album: "The Best of Elmore James" },
  { id: 5082, rank: 82, title: "It Hurts Me Too", artist: "Elmore James", genre: "Blues", year: 1957, album: "The Sky Is Crying" },
  { id: 5083, rank: 83, title: "Done Somebody Wrong", artist: "Elmore James", genre: "Blues", year: 1960, album: "The Sky Is Crying" },
  { id: 5084, rank: 84, title: "Stranger Blues", artist: "Elmore James", genre: "Blues", year: 1953, album: "The Best of Elmore James" },
  { id: 5085, rank: 85, title: "Person to Person", artist: "Elmore James", genre: "Blues", year: 1963, album: "The Sky Is Crying" },
  { id: 5086, rank: 86, title: "Help Me", artist: "Sonny Boy Williamson", genre: "Blues", year: 1963, album: "Down and Out Blues" },
  { id: 5087, rank: 87, title: "Bring It on Home", artist: "Sonny Boy Williamson", genre: "Blues", year: 1963, album: "Down and Out Blues" },
  { id: 5088, rank: 88, title: "Don't Start Me to Talkin'", artist: "Sonny Boy Williamson", genre: "Blues", year: 1955, album: "Down and Out Blues" },
  { id: 5089, rank: 89, title: "Fattening Frogs for Snakes", artist: "Sonny Boy Williamson", genre: "Blues", year: 1957, album: "Down and Out Blues" },
  { id: 5090, rank: 90, title: "Nine Below Zero", artist: "Sonny Boy Williamson", genre: "Blues", year: 1961, album: "Down and Out Blues" },
  { id: 5091, rank: 91, title: "Keep It to Yourself", artist: "Sonny Boy Williamson", genre: "Blues", year: 1963, album: "Down and Out Blues" },
  { id: 5092, rank: 92, title: "One Way Out", artist: "Sonny Boy Williamson", genre: "Blues", year: 1961, album: "Down and Out Blues" },
  { id: 5093, rank: 93, title: "Eyesight to the Blind", artist: "Sonny Boy Williamson", genre: "Blues", year: 1951, album: "Down and Out Blues" },
  { id: 5094, rank: 94, title: "Checkin' Up on My Baby", artist: "Sonny Boy Williamson", genre: "Blues", year: 1963, album: "Down and Out Blues" },
  { id: 5095, rank: 95, title: "Your Funeral and My Trial", artist: "Sonny Boy Williamson", genre: "Blues", year: 1958, album: "Down and Out Blues" },
  { id: 5096, rank: 96, title: "Juke", artist: "Little Walter", genre: "Blues", year: 1952, album: "The Best of Little Walter" },
  { id: 5097, rank: 97, title: "My Babe", artist: "Little Walter", genre: "Blues", year: 1955, album: "The Best of Little Walter" },
  { id: 5098, rank: 98, title: "Sad Hours", artist: "Little Walter", genre: "Blues", year: 1952, album: "The Best of Little Walter" },
  { id: 5099, rank: 99, title: "Mean Old World", artist: "Little Walter", genre: "Blues", year: 1952, album: "The Best of Little Walter" },
  { id: 5100, rank: 100, title: "Last Night", artist: "Little Walter", genre: "Blues", year: 1954, album: "The Best of Little Walter" },
  { id: 5101, rank: 101, title: "Blues with a Feeling", artist: "Little Walter", genre: "Blues", year: 1953, album: "The Best of Little Walter" },
  { id: 5102, rank: 102, title: "Off the Wall", artist: "Little Walter", genre: "Blues", year: 1953, album: "The Best of Little Walter" },
  { id: 5103, rank: 103, title: "You're So Fine", artist: "Little Walter", genre: "Blues", year: 1954, album: "The Best of Little Walter" },
  { id: 5104, rank: 104, title: "Roller Coaster", artist: "Little Walter", genre: "Blues", year: 1955, album: "The Best of Little Walter" },
  { id: 5105, rank: 105, title: "Mellow Down Easy", artist: "Little Walter", genre: "Blues", year: 1954, album: "The Best of Little Walter" },
  { id: 5106, rank: 106, title: "Messin' with the Kid", artist: "Junior Wells", genre: "Blues", year: 1960, album: "Hoodoo Man Blues" },
  { id: 5107, rank: 107, title: "Hoodoo Man Blues", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5108, rank: 108, title: "Little by Little", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5109, rank: 109, title: "Snatch It Back and Hold It", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5110, rank: 110, title: "Early in the Morning", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5111, rank: 111, title: "We're Ready", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5112, rank: 112, title: "In the Wee Wee Hours", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5113, rank: 113, title: "Good Morning Little Schoolgirl", artist: "Junior Wells", genre: "Blues", year: 1965, album: "Hoodoo Man Blues" },
  { id: 5114, rank: 114, title: "You Don't Love Me Baby", artist: "Junior Wells", genre: "Blues", year: 1966, album: "It's My Life Baby!" },
  { id: 5115, rank: 115, title: "Vietcong Blues", artist: "Junior Wells", genre: "Blues", year: 1966, album: "It's My Life Baby!" },
  { id: 5116, rank: 116, title: "Stone Crazy", artist: "Buddy Guy", genre: "Blues", year: 1962, album: "Stone Crazy!" },
  { id: 5117, rank: 117, title: "First Time I Met the Blues", artist: "Buddy Guy", genre: "Blues", year: 1960, album: "I Left My Blues in San Francisco" },
  { id: 5118, rank: 118, title: "Damn Right, I've Got the Blues", artist: "Buddy Guy", genre: "Blues", year: 1991, album: "Damn Right, I've Got the Blues" },
  { id: 5119, rank: 119, title: "Feels Like Rain", artist: "Buddy Guy", genre: "Blues", year: 1993, album: "Feels Like Rain" },
  { id: 5120, rank: 120, title: "Mustang Sally", artist: "Buddy Guy", genre: "Blues", year: 1993, album: "Feels Like Rain" },
  { id: 5121, rank: 121, title: "Five Long Years", artist: "Buddy Guy", genre: "Blues", year: 1991, album: "Damn Right, I've Got the Blues" },
  { id: 5122, rank: 122, title: "Slippin' In", artist: "Buddy Guy", genre: "Blues", year: 1994, album: "Slippin' In" },
  { id: 5123, rank: 123, title: "Baby Please Don't Leave Me", artist: "Buddy Guy", genre: "Blues", year: 1962, album: "Stone Crazy!" },
  { id: 5124, rank: 124, title: "My Time After Awhile", artist: "Buddy Guy", genre: "Blues", year: 1965, album: "Left My Blues in San Francisco" },
  { id: 5125, rank: 125, title: "Mary Had a Little Lamb", artist: "Buddy Guy", genre: "Blues", year: 1991, album: "Damn Right, I've Got the Blues" },
  { id: 5126, rank: 126, title: "Born Under a Bad Sign", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5127, rank: 127, title: "Crosscut Saw", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5128, rank: 128, title: "Oh, Pretty Woman", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5129, rank: 129, title: "As the Years Go Passing By", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5130, rank: 130, title: "The Hunter", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5131, rank: 131, title: "I'll Play the Blues for You", artist: "Albert King", genre: "Blues", year: 1972, album: "I'll Play the Blues for You" },
  { id: 5132, rank: 132, title: "Kansas City", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5133, rank: 133, title: "Laundromat Blues", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5134, rank: 134, title: "Personal Manager", artist: "Albert King", genre: "Blues", year: 1967, album: "Born Under a Bad Sign" },
  { id: 5135, rank: 135, title: "Angel of Mercy", artist: "Albert King", genre: "Blues", year: 1972, album: "I'll Play the Blues for You" },
  { id: 5136, rank: 136, title: "Have You Ever Loved a Woman", artist: "Freddie King", genre: "Blues", year: 1961, album: "Freddie King Sings" },
  { id: 5137, rank: 137, title: "Hide Away", artist: "Freddie King", genre: "Blues", year: 1961, album: "Let's Hide Away and Dance Away" },
  { id: 5138, rank: 138, title: "The Stumble", artist: "Freddie King", genre: "Blues", year: 1961, album: "Let's Hide Away and Dance Away" },
  { id: 5139, rank: 139, title: "I'm Tore Down", artist: "Freddie King", genre: "Blues", year: 1961, album: "Freddie King Sings" },
  { id: 5140, rank: 140, title: "Going Down", artist: "Freddie King", genre: "Blues", year: 1971, album: "Getting Ready" },
  { id: 5141, rank: 141, title: "Tuxedo Junction", artist: "Freddie King", genre: "Blues", year: 1961, album: "Let's Hide Away and Dance Away" },
  { id: 5142, rank: 142, title: "San-Ho-Zay", artist: "Freddie King", genre: "Blues", year: 1961, album: "Let's Hide Away and Dance Away" },
  { id: 5143, rank: 143, title: "Just Pickin'", artist: "Freddie King", genre: "Blues", year: 1961, album: "Let's Hide Away and Dance Away" },
  { id: 5144, rank: 144, title: "Palace of the King", artist: "Freddie King", genre: "Blues", year: 1973, album: "Woman Across the River" },
  { id: 5145, rank: 145, title: "Same Old Blues", artist: "Freddie King", genre: "Blues", year: 1974, album: "Burglar" },
  { id: 5146, rank: 146, title: "Call It Stormy Monday", artist: "T-Bone Walker", genre: "Blues", year: 1947, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5147, rank: 147, title: "T-Bone Shuffle", artist: "T-Bone Walker", genre: "Blues", year: 1947, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5148, rank: 148, title: "Bobby Sox Baby", artist: "T-Bone Walker", genre: "Blues", year: 1946, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5149, rank: 149, title: "Mean Old World", artist: "T-Bone Walker", genre: "Blues", year: 1942, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5150, rank: 150, title: "I Got a Break Baby", artist: "T-Bone Walker", genre: "Blues", year: 1940, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5151, rank: 151, title: "Glamour Girl", artist: "T-Bone Walker", genre: "Blues", year: 1950, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5152, rank: 152, title: "Play On Little Girl", artist: "T-Bone Walker", genre: "Blues", year: 1950, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5153, rank: 153, title: "Long Skirt Baby Blues", artist: "T-Bone Walker", genre: "Blues", year: 1950, album: "The Complete Recordings of T-Bone Walker" },
  { id: 5154, rank: 154, title: "I Know Your Wig Is Gone", artist: "T-Bone Walker", genre: "Blues", year: 1955, album: "T-Bone Blues" },
  { id: 5155, rank: 155, title: "Blues Is a Woman", artist: "T-Bone Walker", genre: "Blues", year: 1956, album: "T-Bone Blues" },
  { id: 5156, rank: 156, title: "All Your Love", artist: "Magic Sam", genre: "Blues", year: 1957, album: "West Side Soul" },
  { id: 5157, rank: 157, title: "Easy Baby", artist: "Magic Sam", genre: "Blues", year: 1957, album: "West Side Soul" },
  { id: 5158, rank: 158, title: "West Side Soul", artist: "Magic Sam", genre: "Blues", year: 1967, album: "West Side Soul" },
  { id: 5159, rank: 159, title: "Magic Rocker", artist: "Magic Sam", genre: "Blues", year: 1967, album: "West Side Soul" },
  { id: 5160, rank: 160, title: "Sweet Home Chicago", artist: "Magic Sam", genre: "Blues", year: 1968, album: "Black Magic" },
  { id: 5161, rank: 161, title: "I Feel So Good", artist: "Magic Sam", genre: "Blues", year: 1967, album: "West Side Soul" },
  { id: 5162, rank: 162, title: "That's All I Need", artist: "Magic Sam", genre: "Blues", year: 1968, album: "Black Magic" },
  { id: 5163, rank: 163, title: "My Love Is Your Love", artist: "Magic Sam", genre: "Blues", year: 1969, album: "Black Magic" },
  { id: 5164, rank: 164, title: "I Need You So Bad", artist: "Magic Sam", genre: "Blues", year: 1968, album: "Black Magic" },
  { id: 5165, rank: 165, title: "Hard Times", artist: "Magic Sam", genre: "Blues", year: 1967, album: "West Side Soul" },
  { id: 5166, rank: 166, title: "All Your Love (I Miss Loving)", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5167, rank: 167, title: "Groaning the Blues", artist: "Otis Rush", genre: "Blues", year: 1956, album: "Groaning the Blues" },
  { id: 5168, rank: 168, title: "I Can't Quit You Baby", artist: "Otis Rush", genre: "Blues", year: 1956, album: "Groaning the Blues" },
  { id: 5169, rank: 169, title: "Homework", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5170, rank: 170, title: "Three Times a Fool", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5171, rank: 171, title: "Double Trouble", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5172, rank: 172, title: "Sit Down Baby", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5173, rank: 173, title: "My Love Will Never Die", artist: "Otis Rush", genre: "Blues", year: 1959, album: "Groaning the Blues" },
  { id: 5174, rank: 174, title: "Checking on My Baby", artist: "Otis Rush", genre: "Blues", year: 1965, album: "This One's a Good Un" },
  { id: 5175, rank: 175, title: "Cobra Blues", artist: "Otis Rush", genre: "Blues", year: 1958, album: "Groaning the Blues" },
  { id: 5176, rank: 176, title: "Death Letter Blues", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5177, rank: 177, title: "Preachin' Blues", artist: "Son House", genre: "Blues", year: 1930, album: "Father of the Delta Blues" },
  { id: 5178, rank: 178, title: "My Black Mama", artist: "Son House", genre: "Blues", year: 1930, album: "Father of the Delta Blues" },
  { id: 5179, rank: 179, title: "Grinnin' in Your Face", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5180, rank: 180, title: "Levee Camp Moan", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5181, rank: 181, title: "Empire State Express", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5182, rank: 182, title: "John the Revelator", artist: "Son House", genre: "Blues", year: 1930, album: "Father of the Delta Blues" },
  { id: 5183, rank: 183, title: "Louise McGhee", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5184, rank: 184, title: "County Farm Blues", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5185, rank: 185, title: "Walking Blues", artist: "Son House", genre: "Blues", year: 1965, album: "Father of the Delta Blues" },
  { id: 5186, rank: 186, title: "Pony Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5187, rank: 187, title: "High Water Everywhere", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5188, rank: 188, title: "Down the Dirt Road Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5189, rank: 189, title: "Screamin' and Hollerin' the Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5190, rank: 190, title: "Rattlesnake Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5191, rank: 191, title: "Tom Rushen Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5192, rank: 192, title: "Spoonful Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5193, rank: 193, title: "A Spoonful Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5194, rank: 194, title: "Mississippi Bo Weavil Blues", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5195, rank: 195, title: "Bird Nest Bound", artist: "Charley Patton", genre: "Blues", year: 1929, album: "Founder of the Delta Blues" },
  { id: 5196, rank: 196, title: "Devil Got My Woman", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5197, rank: 197, title: "Hard Time Killing Floor Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5198, rank: 198, title: "I'm So Glad", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5199, rank: 199, title: "Special Rider Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5200, rank: 200, title: "22-20 Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5201, rank: 201, title: "Cherry Ball Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5202, rank: 202, title: "Illinois Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5203, rank: 203, title: "Be Ready When He Comes", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5204, rank: 204, title: "Four O'Clock Blues", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5205, rank: 205, title: "How Long Buck", artist: "Skip James", genre: "Blues", year: 1931, album: "The Complete Early Recordings" },
  { id: 5206, rank: 206, title: "Candy Man Blues", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5207, rank: 207, title: "Frankie", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5208, rank: 208, title: "Blessed Be the Name", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5209, rank: 209, title: "Stack O' Lee Blues", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5210, rank: 210, title: "Louis Collins", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5211, rank: 211, title: "Spike Driver Blues", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5212, rank: 212, title: "Got the Blues Can't Be Satisfied", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5213, rank: 213, title: "Ain't No Tellin'", artist: "Mississippi John Hurt", genre: "Blues", year: 1928, album: "1928 Sessions" },
  { id: 5214, rank: 214, title: "Pay Day", artist: "Mississippi John Hurt", genre: "Blues", year: 1963, album: "Today!" },
  { id: 5215, rank: 215, title: "Make Me a Pallet on Your Floor", artist: "Mississippi John Hurt", genre: "Blues", year: 1963, album: "Today!" },
  { id: 5216, rank: 216, title: "Key to the Highway", artist: "Big Bill Broonzy", genre: "Blues", year: 1941, album: "The Young Big Bill Broonzy" },
  { id: 5217, rank: 217, title: "Just a Dream", artist: "Big Bill Broonzy", genre: "Blues", year: 1939, album: "The Young Big Bill Broonzy" },
  { id: 5218, rank: 218, title: "Somebody's Got to Go", artist: "Big Bill Broonzy", genre: "Blues", year: 1952, album: "Big Bill's Blues" },
  { id: 5219, rank: 219, title: "Truckin' Little Woman", artist: "Big Bill Broonzy", genre: "Blues", year: 1940, album: "The Young Big Bill Broonzy" },
  { id: 5220, rank: 220, title: "Too Too Train Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1934, album: "The Young Big Bill Broonzy" },
  { id: 5221, rank: 221, title: "When I Been Drinking", artist: "Big Bill Broonzy", genre: "Blues", year: 1938, album: "The Young Big Bill Broonzy" },
  { id: 5222, rank: 222, title: "Night Watchman Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1940, album: "The Young Big Bill Broonzy" },
  { id: 5223, rank: 223, title: "I Feel So Good", artist: "Big Bill Broonzy", genre: "Blues", year: 1951, album: "Big Bill's Blues" },
  { id: 5224, rank: 224, title: "Bull Cow Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1932, album: "The Young Big Bill Broonzy" },
  { id: 5225, rank: 225, title: "Plough Hand Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1927, album: "The Young Big Bill Broonzy" },
  { id: 5226, rank: 226, title: "It's Tight Like That", artist: "Tampa Red", genre: "Blues", year: 1928, album: "The Guitar Wizard" },
  { id: 5227, rank: 227, title: "Tight Like That", artist: "Tampa Red", genre: "Blues", year: 1929, album: "The Guitar Wizard" },
  { id: 5228, rank: 228, title: "Anna Lou Blues", artist: "Tampa Red", genre: "Blues", year: 1934, album: "The Guitar Wizard" },
  { id: 5229, rank: 229, title: "Black Angel Blues", artist: "Tampa Red", genre: "Blues", year: 1938, album: "The Guitar Wizard" },
  { id: 5230, rank: 230, title: "Denver Blues", artist: "Tampa Red", genre: "Blues", year: 1929, album: "The Guitar Wizard" },
  { id: 5231, rank: 231, title: "Love Her with a Feeling", artist: "Tampa Red", genre: "Blues", year: 1939, album: "The Guitar Wizard" },
  { id: 5232, rank: 232, title: "She Want to Sell My Monkey", artist: "Tampa Red", genre: "Blues", year: 1929, album: "The Guitar Wizard" },
  { id: 5233, rank: 233, title: "Let Me Play with Your Poodle", artist: "Tampa Red", genre: "Blues", year: 1942, album: "The Guitar Wizard" },
  { id: 5234, rank: 234, title: "Winter Time Blues", artist: "Tampa Red", genre: "Blues", year: 1940, album: "The Guitar Wizard" },
  { id: 5235, rank: 235, title: "Mistreated Man Blues", artist: "Tampa Red", genre: "Blues", year: 1940, album: "The Guitar Wizard" },
  { id: 5236, rank: 236, title: "Mojo Hand", artist: "Lightnin' Hopkins", genre: "Blues", year: 1962, album: "Mojo Hand" },
  { id: 5237, rank: 237, title: "Bring Me My Shotgun", artist: "Lightnin' Hopkins", genre: "Blues", year: 1948, album: "Mojo Hand" },
  { id: 5238, rank: 238, title: "Darling Do You Remember Me", artist: "Lightnin' Hopkins", genre: "Blues", year: 1947, album: "Lightnin' Hopkins" },
  { id: 5239, rank: 239, title: "Airplane Blues", artist: "Lightnin' Hopkins", genre: "Blues", year: 1961, album: "Lightnin' Hopkins" },
  { id: 5240, rank: 240, title: "Baby Please Don't Go", artist: "Lightnin' Hopkins", genre: "Blues", year: 1953, album: "Lightnin' Hopkins" },
  { id: 5241, rank: 241, title: "Automobile Blues", artist: "Lightnin' Hopkins", genre: "Blues", year: 1960, album: "Lightnin' Hopkins" },
  { id: 5242, rank: 242, title: "Penitentiary Blues", artist: "Lightnin' Hopkins", genre: "Blues", year: 1948, album: "Lightnin' Hopkins" },
  { id: 5243, rank: 243, title: "Lightnin's Boogie", artist: "Lightnin' Hopkins", genre: "Blues", year: 1947, album: "Mojo Hand" },
  { id: 5244, rank: 244, title: "Black Cadillac", artist: "Lightnin' Hopkins", genre: "Blues", year: 1962, album: "Mojo Hand" },
  { id: 5245, rank: 245, title: "Wonder What Is Wrong with Me", artist: "Lightnin' Hopkins", genre: "Blues", year: 1947, album: "Lightnin' Hopkins" },
  { id: 5246, rank: 246, title: "Frosty", artist: "Albert Collins", genre: "Blues", year: 1962, album: "Ice Pickin'" },
  { id: 5247, rank: 247, title: "Ice Pick", artist: "Albert Collins", genre: "Blues", year: 1978, album: "Ice Pickin'" },
  { id: 5248, rank: 248, title: "Cold Snap", artist: "Albert Collins", genre: "Blues", year: 1986, album: "Cold Snap" },
  { id: 5249, rank: 249, title: "Brick", artist: "Albert Collins", genre: "Blues", year: 1978, album: "Ice Pickin'" },
  { id: 5250, rank: 250, title: "Master Charge", artist: "Albert Collins", genre: "Blues", year: 1978, album: "Ice Pickin'" },
  { id: 5251, rank: 251, title: "Icy Blue", artist: "Albert Collins", genre: "Blues", year: 1986, album: "Cold Snap" },
  { id: 5252, rank: 252, title: "Avalanche", artist: "Albert Collins", genre: "Blues", year: 1986, album: "Cold Snap" },
  { id: 5253, rank: 253, title: "Put the Shoe on the Other Foot", artist: "Albert Collins", genre: "Blues", year: 1983, album: "Don't Lose Your Cool" },
  { id: 5254, rank: 254, title: "Honey Hush", artist: "Albert Collins", genre: "Blues", year: 1983, album: "Don't Lose Your Cool" },
  { id: 5255, rank: 255, title: "Fools Gold", artist: "Albert Collins", genre: "Blues", year: 1990, album: "Iceman" },
  { id: 5256, rank: 256, title: "Pride and Joy", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1983, album: "Texas Flood" },
  { id: 5257, rank: 257, title: "Texas Flood", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1983, album: "Texas Flood" },
  { id: 5258, rank: 258, title: "The Sky Is Crying", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1991, album: "The Sky Is Crying" },
  { id: 5259, rank: 259, title: "Couldn't Stand the Weather", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1984, album: "Couldn't Stand the Weather" },
  { id: 5260, rank: 260, title: "Cold Shot", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1985, album: "Soul to Soul" },
  { id: 5261, rank: 261, title: "Change It", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1985, album: "Soul to Soul" },
  { id: 5262, rank: 262, title: "Mary Had a Little Lamb", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1984, album: "Couldn't Stand the Weather" },
  { id: 5263, rank: 263, title: "Tin Pan Alley", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1984, album: "Couldn't Stand the Weather" },
  { id: 5264, rank: 264, title: "Lenny", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1983, album: "Texas Flood" },
  { id: 5265, rank: 265, title: "Life Without You", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1985, album: "Soul to Soul" },
  { id: 5266, rank: 266, title: "Tightrope", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1989, album: "In Step" },
  { id: 5267, rank: 267, title: "The House Is Rockin'", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1989, album: "In Step" },
  { id: 5268, rank: 268, title: "Crossfire", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1989, album: "In Step" },
  { id: 5269, rank: 269, title: "Riviera Paradise", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1989, album: "In Step" },
  { id: 5270, rank: 270, title: "Love Struck Baby", artist: "Stevie Ray Vaughan", genre: "Blues", year: 1983, album: "Texas Flood" },
  { id: 5271, rank: 271, title: "Still Got the Blues", artist: "Gary Moore", genre: "Blues", year: 1990, album: "Still Got the Blues" },
  { id: 5272, rank: 272, title: "The Loner", artist: "Gary Moore", genre: "Blues", year: 1987, album: "Wild Frontier" },
  { id: 5273, rank: 273, title: "Oh Well", artist: "Gary Moore", genre: "Blues", year: 1990, album: "Still Got the Blues" },
  { id: 5274, rank: 274, title: "Parisienne Walkways", artist: "Gary Moore", genre: "Blues", year: 1979, album: "Back on the Streets" },
  { id: 5275, rank: 275, title: "Walking by Myself", artist: "Gary Moore", genre: "Blues", year: 1990, album: "Still Got the Blues" },
  { id: 5276, rank: 276, title: "Too Tired", artist: "Gary Moore", genre: "Blues", year: 1990, album: "Still Got the Blues" },
  { id: 5277, rank: 277, title: "Texas Strut", artist: "Gary Moore", genre: "Blues", year: 1990, album: "Still Got the Blues" },
  { id: 5278, rank: 278, title: "King of the Blues", artist: "Gary Moore", genre: "Blues", year: 1992, album: "After Hours" },
  { id: 5279, rank: 279, title: "Story of the Blues", artist: "Gary Moore", genre: "Blues", year: 1992, album: "After Hours" },
  { id: 5280, rank: 280, title: "Separate Ways", artist: "Gary Moore", genre: "Blues", year: 1994, album: "Blues for Greeny" },
  { id: 5281, rank: 281, title: "Before You Accuse Me", artist: "Eric Clapton", genre: "Blues", year: 1989, album: "Journeyman" },
  { id: 5282, rank: 282, title: "Layla", artist: "Eric Clapton", genre: "Blues", year: 1970, album: "Layla and Other Assorted Love Songs" },
  { id: 5283, rank: 283, title: "Crossroads", artist: "Eric Clapton", genre: "Blues", year: 1969, album: "Goodbye" },
  { id: 5284, rank: 284, title: "Cocaine", artist: "Eric Clapton", genre: "Blues", year: 1977, album: "Slowhand" },
  { id: 5285, rank: 285, title: "Badge", artist: "Eric Clapton", genre: "Blues", year: 1969, album: "Goodbye" },
  { id: 5286, rank: 286, title: "I Shot the Sheriff", artist: "Eric Clapton", genre: "Blues", year: 1974, album: "461 Ocean Boulevard" },
  { id: 5287, rank: 287, title: "Lay Down Sally", artist: "Eric Clapton", genre: "Blues", year: 1977, album: "Slowhand" },
  { id: 5288, rank: 288, title: "Wonderful Tonight", artist: "Eric Clapton", genre: "Blues", year: 1977, album: "Slowhand" },
  { id: 5289, rank: 289, title: "Running on Faith", artist: "Eric Clapton", genre: "Blues", year: 1989, album: "Journeyman" },
  { id: 5290, rank: 290, title: "Tears in Heaven", artist: "Eric Clapton", genre: "Blues", year: 1992, album: "Rush Soundtrack" },
  { id: 5291, rank: 291, title: "Change the World", artist: "Eric Clapton", genre: "Blues", year: 1996, album: "Phenomenon Soundtrack" },
  { id: 5292, rank: 292, title: "Old Love", artist: "Eric Clapton", genre: "Blues", year: 1989, album: "Journeyman" },
  { id: 5293, rank: 293, title: "Five Long Years", artist: "Eric Clapton", genre: "Blues", year: 1994, album: "From the Cradle" },
  { id: 5294, rank: 294, title: "Malted Milk", artist: "Eric Clapton", genre: "Blues", year: 1994, album: "From the Cradle" },
  { id: 5295, rank: 295, title: "How Long Blues", artist: "Eric Clapton", genre: "Blues", year: 1994, album: "From the Cradle" },
  { id: 5296, rank: 296, title: "Big Boss Man", artist: "Jimmy Reed", genre: "Blues", year: 1961, album: "Just Jimmy Reed" },
  { id: 5297, rank: 297, title: "Baby What You Want Me to Do", artist: "Jimmy Reed", genre: "Blues", year: 1960, album: "Found Love" },
  { id: 5298, rank: 298, title: "Bright Lights Big City", artist: "Jimmy Reed", genre: "Blues", year: 1961, album: "Just Jimmy Reed" },
  { id: 5299, rank: 299, title: "Going to New York", artist: "Jimmy Reed", genre: "Blues", year: 1956, album: "I'm Jimmy Reed" },
  { id: 5300, rank: 300, title: "Ain't That Lovin' You Baby", artist: "Jimmy Reed", genre: "Blues", year: 1956, album: "I'm Jimmy Reed" },
  { id: 5301, rank: 301, title: "Hush-Hush", artist: "Jimmy Reed", genre: "Blues", year: 1960, album: "Found Love" },
  { id: 5302, rank: 302, title: "Take Out Some Insurance", artist: "Jimmy Reed", genre: "Blues", year: 1959, album: "Rockin' with Reed" },
  { id: 5303, rank: 303, title: "The Sun Is Shining", artist: "Jimmy Reed", genre: "Blues", year: 1959, album: "Rockin' with Reed" },
  { id: 5304, rank: 304, title: "You Don't Have to Go", artist: "Jimmy Reed", genre: "Blues", year: 1955, album: "I'm Jimmy Reed" },
  { id: 5305, rank: 305, title: "Down in Virginia", artist: "Jimmy Reed", genre: "Blues", year: 1958, album: "Rockin' with Reed" },
  { id: 5306, rank: 306, title: "I'm a King Bee", artist: "Slim Harpo", genre: "Blues", year: 1957, album: "Raining in My Heart" },
  { id: 5307, rank: 307, title: "Raining in My Heart", artist: "Slim Harpo", genre: "Blues", year: 1961, album: "Raining in My Heart" },
  { id: 5308, rank: 308, title: "Baby Scratch My Back", artist: "Slim Harpo", genre: "Blues", year: 1966, album: "Baby Scratch My Back" },
  { id: 5309, rank: 309, title: "Shake Your Hips", artist: "Slim Harpo", genre: "Blues", year: 1966, album: "Baby Scratch My Back" },
  { id: 5310, rank: 310, title: "Tip on In", artist: "Slim Harpo", genre: "Blues", year: 1968, album: "Tip On In" },
  { id: 5311, rank: 311, title: "Got Love If You Want It", artist: "Slim Harpo", genre: "Blues", year: 1957, album: "Raining in My Heart" },
  { id: 5312, rank: 312, title: "Blues Hang Over Me", artist: "Slim Harpo", genre: "Blues", year: 1961, album: "Raining in My Heart" },
  { id: 5313, rank: 313, title: "Buzz Me Babe", artist: "Slim Harpo", genre: "Blues", year: 1963, album: "Baby Scratch My Back" },
  { id: 5314, rank: 314, title: "Lobster", artist: "Slim Harpo", genre: "Blues", year: 1968, album: "Tip On In" },
  { id: 5315, rank: 315, title: "Midnight Blues", artist: "Slim Harpo", genre: "Blues", year: 1963, album: "Raining in My Heart" },
  { id: 5316, rank: 316, title: "Rocket 88", artist: "Ike Turner", genre: "Blues", year: 1951, album: "Rocket 88" },
  { id: 5317, rank: 317, title: "I'm Lonesome Baby", artist: "Ike Turner", genre: "Blues", year: 1951, album: "Rocket 88" },
  { id: 5318, rank: 318, title: "Hearts in My Shoes", artist: "Ike Turner", genre: "Blues", year: 1955, album: "I Like Ike!" },
  { id: 5319, rank: 319, title: "You've Got Too Many Irons in the Fire", artist: "Ike Turner", genre: "Blues", year: 1956, album: "I Like Ike!" },
  { id: 5320, rank: 320, title: "Down and Out", artist: "Ike Turner", genre: "Blues", year: 1958, album: "I Like Ike!" },
  { id: 5321, rank: 321, title: "Boxtop", artist: "Ike Turner", genre: "Blues", year: 1955, album: "I Like Ike!" },
  { id: 5322, rank: 322, title: "Come Back Baby", artist: "Ike Turner", genre: "Blues", year: 1960, album: "I Like Ike!" },
  { id: 5323, rank: 323, title: "Prancin'", artist: "Ike Turner", genre: "Blues", year: 1961, album: "I Like Ike!" },
  { id: 5324, rank: 324, title: "She Loves Me So", artist: "Ike Turner", genre: "Blues", year: 1956, album: "I Like Ike!" },
  { id: 5325, rank: 325, title: "A Fool in Love", artist: "Ike Turner", genre: "Blues", year: 1960, album: "I Like Ike!" },
  { id: 5326, rank: 326, title: "Turn on Your Love Light", artist: "Bobby Bland", genre: "Blues", year: 1961, album: "Two Steps from the Blues" },
  { id: 5327, rank: 327, title: "Stormy Monday Blues", artist: "Bobby Bland", genre: "Blues", year: 1962, album: "Here's the Man!!!" },
  { id: 5328, rank: 328, title: "I Pity the Fool", artist: "Bobby Bland", genre: "Blues", year: 1961, album: "Two Steps from the Blues" },
  { id: 5329, rank: 329, title: "That's the Way Love Is", artist: "Bobby Bland", genre: "Blues", year: 1963, album: "Call on Me" },
  { id: 5330, rank: 330, title: "Ain't Nothing You Can Do", artist: "Bobby Bland", genre: "Blues", year: 1964, album: "Ain't Nothing You Can Do" },
  { id: 5331, rank: 331, title: "Further on Up the Road", artist: "Bobby Bland", genre: "Blues", year: 1957, album: "Two Steps from the Blues" },
  { id: 5332, rank: 332, title: "Lead Me On", artist: "Bobby Bland", genre: "Blues", year: 1960, album: "Two Steps from the Blues" },
  { id: 5333, rank: 333, title: "Members Only", artist: "Bobby Bland", genre: "Blues", year: 1985, album: "Members Only" },
  { id: 5334, rank: 334, title: "Good Time Charlie", artist: "Bobby Bland", genre: "Blues", year: 1966, album: "The Soul of the Man" },
  { id: 5335, rank: 335, title: "Yield Not to Temptation", artist: "Bobby Bland", genre: "Blues", year: 1962, album: "Two Steps from the Blues" },
  { id: 5336, rank: 336, title: "We're Gonna Make It", artist: "Little Milton", genre: "Blues", year: 1965, album: "We're Gonna Make It" },
  { id: 5337, rank: 337, title: "Grits Ain't Groceries", artist: "Little Milton", genre: "Blues", year: 1969, album: "Grits Ain't Groceries" },
  { id: 5338, rank: 338, title: "Baby I Love You", artist: "Little Milton", genre: "Blues", year: 1966, album: "We're Gonna Make It" },
  { id: 5339, rank: 339, title: "If Walls Could Talk", artist: "Little Milton", genre: "Blues", year: 1968, album: "Sings Big Blues" },
  { id: 5340, rank: 340, title: "Let's Get Together", artist: "Little Milton", genre: "Blues", year: 1965, album: "We're Gonna Make It" },
  { id: 5341, rank: 341, title: "Annie Mae's Cafe", artist: "Little Milton", genre: "Blues", year: 1967, album: "Sings Big Blues" },
  { id: 5342, rank: 342, title: "Feel So Bad", artist: "Little Milton", genre: "Blues", year: 1967, album: "Sings Big Blues" },
  { id: 5343, rank: 343, title: "Blind Man", artist: "Little Milton", genre: "Blues", year: 1971, album: "If Walls Could Talk" },
  { id: 5344, rank: 344, title: "The Price You Have to Pay", artist: "Little Milton", genre: "Blues", year: 1966, album: "We're Gonna Make It" },
  { id: 5345, rank: 345, title: "That's What Love Will Do", artist: "Little Milton", genre: "Blues", year: 1968, album: "Sings Big Blues" },
  { id: 5346, rank: 346, title: "Eight Men, Four Women", artist: "O.V. Wright", genre: "Blues", year: 1965, album: "If It's Only for Tonight" },
  { id: 5347, rank: 347, title: "That's How Strong My Love Is", artist: "O.V. Wright", genre: "Blues", year: 1964, album: "If It's Only for Tonight" },
  { id: 5348, rank: 348, title: "Ace of Spades", artist: "O.V. Wright", genre: "Blues", year: 1970, album: "A Nickel and a Nail and Ace of Spades" },
  { id: 5349, rank: 349, title: "Nickel and a Nail", artist: "O.V. Wright", genre: "Blues", year: 1971, album: "A Nickel and a Nail and Ace of Spades" },
  { id: 5350, rank: 350, title: "You're Gonna Make Me Cry", artist: "O.V. Wright", genre: "Blues", year: 1965, album: "If It's Only for Tonight" },
  { id: 5351, rank: 351, title: "I'd Rather Be Blind Cripple and Crazy", artist: "O.V. Wright", genre: "Blues", year: 1971, album: "A Nickel and a Nail and Ace of Spades" },
  { id: 5352, rank: 352, title: "Into Something I Can't Shake Loose", artist: "O.V. Wright", genre: "Blues", year: 1968, album: "Nucleus of Soul" },
  { id: 5353, rank: 353, title: "He's My Son", artist: "O.V. Wright", genre: "Blues", year: 1969, album: "Nucleus of Soul" },
  { id: 5354, rank: 354, title: "Mother's Love", artist: "O.V. Wright", genre: "Blues", year: 1975, album: "Memphis Unlimited" },
  { id: 5355, rank: 355, title: "What About You", artist: "O.V. Wright", genre: "Blues", year: 1975, album: "Memphis Unlimited" },
  { id: 5356, rank: 356, title: "Mystery Train", artist: "Junior Parker", genre: "Blues", year: 1953, album: "Mystery Train" },
  { id: 5357, rank: 357, title: "Next Time You See Me", artist: "Junior Parker", genre: "Blues", year: 1957, album: "Driving Wheel" },
  { id: 5358, rank: 358, title: "Driving Wheel", artist: "Junior Parker", genre: "Blues", year: 1961, album: "Driving Wheel" },
  { id: 5359, rank: 359, title: "Annie Get Your Yo-Yo", artist: "Junior Parker", genre: "Blues", year: 1962, album: "Driving Wheel" },
  { id: 5360, rank: 360, title: "Sweet Home Chicago", artist: "Junior Parker", genre: "Blues", year: 1961, album: "Driving Wheel" },
  { id: 5361, rank: 361, title: "Feelin' Good", artist: "Junior Parker", genre: "Blues", year: 1953, album: "Mystery Train" },
  { id: 5362, rank: 362, title: "Stand by Me", artist: "Junior Parker", genre: "Blues", year: 1961, album: "Driving Wheel" },
  { id: 5363, rank: 363, title: "That's All Right", artist: "Junior Parker", genre: "Blues", year: 1953, album: "Mystery Train" },
  { id: 5364, rank: 364, title: "In the Dark", artist: "Junior Parker", genre: "Blues", year: 1961, album: "Driving Wheel" },
  { id: 5365, rank: 365, title: "Member's Only", artist: "Junior Parker", genre: "Blues", year: 1966, album: "Like It Is" },
  { id: 5366, rank: 366, title: "I Wish You Would", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5367, rank: 367, title: "I Ain't Got You", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5368, rank: 368, title: "Don't Stay Out All Night", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5369, rank: 369, title: "Kissing at Midnight", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5370, rank: 370, title: "I Was Fooled", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5371, rank: 371, title: "Here's My Picture", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5372, rank: 372, title: "Prisoner's Plea", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5373, rank: 373, title: "Rockinitis", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5374, rank: 374, title: "She's Fine", artist: "Billy Boy Arnold", genre: "Blues", year: 1955, album: "Back Where I Belong" },
  { id: 5375, rank: 375, title: "My Heart Is Cryin'", artist: "Billy Boy Arnold", genre: "Blues", year: 1963, album: "Blow the Back Off It" },
  { id: 5376, rank: 376, title: "Wang Dang Doodle", artist: "Koko Taylor", genre: "Blues", year: 1965, album: "I Got What It Takes" },
  { id: 5377, rank: 377, title: "I Got What It Takes", artist: "Koko Taylor", genre: "Blues", year: 1975, album: "I Got What It Takes" },
  { id: 5378, rank: 378, title: "Blues Heaven", artist: "Koko Taylor", genre: "Blues", year: 1987, album: "Live from Chicago!" },
  { id: 5379, rank: 379, title: "Cut You Loose", artist: "Koko Taylor", genre: "Blues", year: 1975, album: "I Got What It Takes" },
  { id: 5380, rank: 380, title: "What Kind of Man Is This?", artist: "Koko Taylor", genre: "Blues", year: 1975, album: "I Got What It Takes" },
  { id: 5381, rank: 381, title: "Queen Bee", artist: "Koko Taylor", genre: "Blues", year: 1985, album: "Queen of the Blues" },
  { id: 5382, rank: 382, title: "Hey Bartender", artist: "Koko Taylor", genre: "Blues", year: 1976, album: "The Earthshaker" },
  { id: 5383, rank: 383, title: "I'm a Woman", artist: "Koko Taylor", genre: "Blues", year: 1978, album: "The Earthshaker" },
  { id: 5384, rank: 384, title: "Telephone Blues", artist: "Koko Taylor", genre: "Blues", year: 1985, album: "Queen of the Blues" },
  { id: 5385, rank: 385, title: "Lip Service", artist: "Koko Taylor", genre: "Blues", year: 1987, album: "Live from Chicago!" },
  { id: 5386, rank: 386, title: "Tell Mama", artist: "Etta James", genre: "Blues", year: 1968, album: "Tell Mama" },
  { id: 5387, rank: 387, title: "At Last", artist: "Etta James", genre: "Blues", year: 1961, album: "At Last!" },
  { id: 5388, rank: 388, title: "I'd Rather Go Blind", artist: "Etta James", genre: "Blues", year: 1968, album: "Tell Mama" },
  { id: 5389, rank: 389, title: "Something's Got a Hold on Me", artist: "Etta James", genre: "Blues", year: 1962, album: "Etta James Sings for Lovers" },
  { id: 5390, rank: 390, title: "The Wallflower", artist: "Etta James", genre: "Blues", year: 1955, album: "Tell Mama" },
  { id: 5391, rank: 391, title: "Roll with Me Henry", artist: "Etta James", genre: "Blues", year: 1955, album: "Tell Mama" },
  { id: 5392, rank: 392, title: "A Sunday Kind of Love", artist: "Etta James", genre: "Blues", year: 1960, album: "At Last!" },
  { id: 5393, rank: 393, title: "All I Could Do Was Cry", artist: "Etta James", genre: "Blues", year: 1960, album: "At Last!" },
  { id: 5394, rank: 394, title: "W-O-M-A-N", artist: "Etta James", genre: "Blues", year: 1955, album: "Tell Mama" },
  { id: 5395, rank: 395, title: "My Dearest Darling", artist: "Etta James", genre: "Blues", year: 1960, album: "At Last!" },
  { id: 5396, rank: 396, title: "Hound Dog", artist: "Big Mama Thornton", genre: "Blues", year: 1952, album: "Hound Dog: The Peacock Recordings" },
  { id: 5397, rank: 397, title: "Ball and Chain", artist: "Big Mama Thornton", genre: "Blues", year: 1968, album: "Ball 'n' Chain" },
  { id: 5398, rank: 398, title: "They Call Me Big Mama", artist: "Big Mama Thornton", genre: "Blues", year: 1965, album: "In Europe" },
  { id: 5399, rank: 399, title: "Big Mama's Bumble Bee Blues", artist: "Big Mama Thornton", genre: "Blues", year: 1961, album: "In Europe" },
  { id: 5400, rank: 400, title: "Everything Gonna Be Alright", artist: "Big Mama Thornton", genre: "Blues", year: 1965, album: "In Europe" },
  { id: 5401, rank: 401, title: "Little Red Rooster", artist: "Big Mama Thornton", genre: "Blues", year: 1966, album: "Big Mama Thornton with Muddy Waters Blues Band" },
  { id: 5402, rank: 402, title: "Watergate Blues", artist: "Big Mama Thornton", genre: "Blues", year: 1973, album: "Jail" },
  { id: 5403, rank: 403, title: "Maybe My Last Ride", artist: "Big Mama Thornton", genre: "Blues", year: 1975, album: "Sassy Mama!" },
  { id: 5404, rank: 404, title: "Looking the World Over", artist: "Big Mama Thornton", genre: "Blues", year: 1975, album: "Sassy Mama!" },
  { id: 5405, rank: 405, title: "Swing It on Home", artist: "Big Mama Thornton", genre: "Blues", year: 1975, album: "Sassy Mama!" },
  { id: 5406, rank: 406, title: "Spoonful", artist: "Willie Dixon", genre: "Blues", year: 1960, album: "Willie's Blues" },
  { id: 5407, rank: 407, title: "Hoochie Coochie Man", artist: "Willie Dixon", genre: "Blues", year: 1954, album: "Willie's Blues" },
  { id: 5408, rank: 408, title: "Back Door Man", artist: "Willie Dixon", genre: "Blues", year: 1960, album: "Willie's Blues" },
  { id: 5409, rank: 409, title: "You Can't Judge a Book by the Cover", artist: "Willie Dixon", genre: "Blues", year: 1962, album: "Willie's Blues" },
  { id: 5410, rank: 410, title: "Little Red Rooster", artist: "Willie Dixon", genre: "Blues", year: 1961, album: "Willie's Blues" },
  { id: 5411, rank: 411, title: "Bring It on Home", artist: "Willie Dixon", genre: "Blues", year: 1963, album: "Willie's Blues" },
  { id: 5412, rank: 412, title: "I Just Want to Make Love to You", artist: "Willie Dixon", genre: "Blues", year: 1954, album: "Willie's Blues" },
  { id: 5413, rank: 413, title: "Evil", artist: "Willie Dixon", genre: "Blues", year: 1954, album: "Willie's Blues" },
  { id: 5414, rank: 414, title: "Seventh Son", artist: "Willie Dixon", genre: "Blues", year: 1955, album: "Willie's Blues" },
  { id: 5415, rank: 415, title: "Wang Dang Doodle", artist: "Willie Dixon", genre: "Blues", year: 1960, album: "Willie's Blues" },
  { id: 5416, rank: 416, title: "That's All Right", artist: "Jimmy Rogers", genre: "Blues", year: 1950, album: "Chicago Bound" },
  { id: 5417, rank: 417, title: "Walking by Myself", artist: "Jimmy Rogers", genre: "Blues", year: 1956, album: "Chicago Bound" },
  { id: 5418, rank: 418, title: "Chicago Bound", artist: "Jimmy Rogers", genre: "Blues", year: 1954, album: "Chicago Bound" },
  { id: 5419, rank: 419, title: "Rock This House", artist: "Jimmy Rogers", genre: "Blues", year: 1953, album: "Chicago Bound" },
  { id: 5420, rank: 420, title: "Out on the Road", artist: "Jimmy Rogers", genre: "Blues", year: 1957, album: "Chicago Bound" },
  { id: 5421, rank: 421, title: "Money Marbles and Chalk", artist: "Jimmy Rogers", genre: "Blues", year: 1954, album: "Chicago Bound" },
  { id: 5422, rank: 422, title: "Left Me with a Broken Heart", artist: "Jimmy Rogers", genre: "Blues", year: 1956, album: "Chicago Bound" },
  { id: 5423, rank: 423, title: "Back Door Friend", artist: "Jimmy Rogers", genre: "Blues", year: 1951, album: "Chicago Bound" },
  { id: 5424, rank: 424, title: "Blues All Day Long", artist: "Jimmy Rogers", genre: "Blues", year: 1972, album: "Gold Tailed Bird" },
  { id: 5425, rank: 425, title: "Sloppy Drunk", artist: "Jimmy Rogers", genre: "Blues", year: 1950, album: "Chicago Bound" },
  { id: 5426, rank: 426, title: "Reconsider Baby", artist: "Lowell Fulson", genre: "Blues", year: 1954, album: "Reconsider Baby" },
  { id: 5427, rank: 427, title: "Tramp", artist: "Lowell Fulson", genre: "Blues", year: 1967, album: "Tramp" },
  { id: 5428, rank: 428, title: "Trouble, Trouble", artist: "Lowell Fulson", genre: "Blues", year: 1956, album: "Reconsider Baby" },
  { id: 5429, rank: 429, title: "Black Nights", artist: "Lowell Fulson", genre: "Blues", year: 1965, album: "Tramp" },
  { id: 5430, rank: 430, title: "Make a Little Love", artist: "Lowell Fulson", genre: "Blues", year: 1950, album: "Reconsider Baby" },
  { id: 5431, rank: 431, title: "Three O'Clock Blues", artist: "Lowell Fulson", genre: "Blues", year: 1948, album: "Reconsider Baby" },
  { id: 5432, rank: 432, title: "Hung Down Head", artist: "Lowell Fulson", genre: "Blues", year: 1950, album: "Reconsider Baby" },
  { id: 5433, rank: 433, title: "Every Day I Have the Blues", artist: "Lowell Fulson", genre: "Blues", year: 1950, album: "Reconsider Baby" },
  { id: 5434, rank: 434, title: "Guitar Shuffle", artist: "Lowell Fulson", genre: "Blues", year: 1954, album: "Reconsider Baby" },
  { id: 5435, rank: 435, title: "Do Me Right", artist: "Lowell Fulson", genre: "Blues", year: 1965, album: "Tramp" },
  { id: 5436, rank: 436, title: "The Things That I Used to Do", artist: "Guitar Slim", genre: "Blues", year: 1953, album: "The Things That I Used to Do" },
  { id: 5437, rank: 437, title: "Well I Done Got Over It", artist: "Guitar Slim", genre: "Blues", year: 1954, album: "The Things That I Used to Do" },
  { id: 5438, rank: 438, title: "Our Only Child", artist: "Guitar Slim", genre: "Blues", year: 1954, album: "The Things That I Used to Do" },
  { id: 5439, rank: 439, title: "You Give Me Nothing but the Blues", artist: "Guitar Slim", genre: "Blues", year: 1955, album: "The Things That I Used to Do" },
  { id: 5440, rank: 440, title: "Sufferin' Mind", artist: "Guitar Slim", genre: "Blues", year: 1954, album: "The Things That I Used to Do" },
  { id: 5441, rank: 441, title: "Later for You Baby", artist: "Guitar Slim", genre: "Blues", year: 1956, album: "The Things That I Used to Do" },
  { id: 5442, rank: 442, title: "Trouble Don't Last", artist: "Guitar Slim", genre: "Blues", year: 1955, album: "The Things That I Used to Do" },
  { id: 5443, rank: 443, title: "Think It Over", artist: "Guitar Slim", genre: "Blues", year: 1956, album: "The Things That I Used to Do" },
  { id: 5444, rank: 444, title: "Cryin' in the Morning", artist: "Guitar Slim", genre: "Blues", year: 1957, album: "The Things That I Used to Do" },
  { id: 5445, rank: 445, title: "Something to Remember You By", artist: "Guitar Slim", genre: "Blues", year: 1955, album: "The Things That I Used to Do" },
  { id: 5446, rank: 446, title: "Motherless Children", artist: "Blind Willie McTell", genre: "Blues", year: 1927, album: "Atlanta Twelve String" },
  { id: 5447, rank: 447, title: "Statesboro Blues", artist: "Blind Willie McTell", genre: "Blues", year: 1928, album: "Atlanta Twelve String" },
  { id: 5448, rank: 448, title: "Death Cell Blues", artist: "Blind Willie McTell", genre: "Blues", year: 1933, album: "Atlanta Twelve String" },
  { id: 5449, rank: 449, title: "Georgia Rag", artist: "Blind Willie McTell", genre: "Blues", year: 1927, album: "Atlanta Twelve String" },
  { id: 5450, rank: 450, title: "Bell Street Lightnin'", artist: "Blind Willie McTell", genre: "Blues", year: 1949, album: "Last Session" },
  { id: 5451, rank: 451, title: "Broke Down Engine Blues", artist: "Blind Willie McTell", genre: "Blues", year: 1931, album: "Atlanta Twelve String" },
  { id: 5452, rank: 452, title: "You Were Born to Die", artist: "Blind Willie McTell", genre: "Blues", year: 1933, album: "Atlanta Twelve String" },
  { id: 5453, rank: 453, title: "Drive Away Blues", artist: "Blind Willie McTell", genre: "Blues", year: 1928, album: "Atlanta Twelve String" },
  { id: 5454, rank: 454, title: "Travelin' Blues", artist: "Blind Willie McTell", genre: "Blues", year: 1929, album: "Atlanta Twelve String" },
  { id: 5455, rank: 455, title: "Cold Winter Day", artist: "Blind Willie McTell", genre: "Blues", year: 1949, album: "Last Session" },
  { id: 5456, rank: 456, title: "Talking Casey", artist: "Reverend Gary Davis", genre: "Blues", year: 1935, album: "Pure Religion & Bad Company" },
  { id: 5457, rank: 457, title: "Death Don't Have No Mercy", artist: "Reverend Gary Davis", genre: "Blues", year: 1960, album: "Pure Religion & Bad Company" },
  { id: 5458, rank: 458, title: "Samson and Delilah", artist: "Reverend Gary Davis", genre: "Blues", year: 1956, album: "Pure Religion & Bad Company" },
  { id: 5459, rank: 459, title: "I Am the Light of This World", artist: "Reverend Gary Davis", genre: "Blues", year: 1956, album: "Pure Religion & Bad Company" },
  { id: 5460, rank: 460, title: "Keep Your Lamp Trimmed and Burning", artist: "Reverend Gary Davis", genre: "Blues", year: 1956, album: "Pure Religion & Bad Company" },
  { id: 5461, rank: 461, title: "Slow Blues", artist: "Reverend Gary Davis", genre: "Blues", year: 1954, album: "Pure Religion & Bad Company" },
  { id: 5462, rank: 462, title: "Say No to the Devil", artist: "Reverend Gary Davis", genre: "Blues", year: 1958, album: "Pure Religion & Bad Company" },
  { id: 5463, rank: 463, title: "Twelve Gates to the City", artist: "Reverend Gary Davis", genre: "Blues", year: 1963, album: "Pure Religion & Bad Company" },
  { id: 5464, rank: 464, title: "Candyman", artist: "Reverend Gary Davis", genre: "Blues", year: 1965, album: "Blues & Ragtime" },
  { id: 5465, rank: 465, title: "Hot Cha", artist: "Reverend Gary Davis", genre: "Blues", year: 1965, album: "Blues & Ragtime" },
  { id: 5466, rank: 466, title: "Ragged and Dirty", artist: "Sleepy John Estes", genre: "Blues", year: 1929, album: "I Ain't Gonna Be Worried No More" },
  { id: 5467, rank: 467, title: "Drop Down Mama", artist: "Sleepy John Estes", genre: "Blues", year: 1935, album: "I Ain't Gonna Be Worried No More" },
  { id: 5468, rank: 468, title: "Someday Baby Blues", artist: "Sleepy John Estes", genre: "Blues", year: 1935, album: "I Ain't Gonna Be Worried No More" },
  { id: 5469, rank: 469, title: "Working Man Blues", artist: "Sleepy John Estes", genre: "Blues", year: 1929, album: "I Ain't Gonna Be Worried No More" },
  { id: 5470, rank: 470, title: "Street Car Blues", artist: "Sleepy John Estes", genre: "Blues", year: 1929, album: "I Ain't Gonna Be Worried No More" },
  { id: 5471, rank: 471, title: "The Girl I Love, She Got Long Curly Hair", artist: "Sleepy John Estes", genre: "Blues", year: 1929, album: "I Ain't Gonna Be Worried No More" },
  { id: 5472, rank: 472, title: "Floating Bridge", artist: "Sleepy John Estes", genre: "Blues", year: 1941, album: "I Ain't Gonna Be Worried No More" },
  { id: 5473, rank: 473, title: "Lawyer Clark Blues", artist: "Sleepy John Estes", genre: "Blues", year: 1929, album: "I Ain't Gonna Be Worried No More" },
  { id: 5474, rank: 474, title: "Easin' Back to Tennessee", artist: "Sleepy John Estes", genre: "Blues", year: 1962, album: "The Legend of Sleepy John Estes" },
  { id: 5475, rank: 475, title: "Little Laura Blues", artist: "Sleepy John Estes", genre: "Blues", year: 1962, album: "The Legend of Sleepy John Estes" },
  { id: 5476, rank: 476, title: "Don't You Lie to Me", artist: "Tampa Red", genre: "Blues", year: 1940, album: "The Guitar Wizard" },
  { id: 5477, rank: 477, title: "Sweet Black Angel", artist: "Tampa Red", genre: "Blues", year: 1938, album: "The Guitar Wizard" },
  { id: 5478, rank: 478, title: "Black Angel Blues", artist: "Tampa Red", genre: "Blues", year: 1937, album: "The Guitar Wizard" },
  { id: 5479, rank: 479, title: "It Hurts Me Too", artist: "Tampa Red", genre: "Blues", year: 1940, album: "The Guitar Wizard" },
  { id: 5480, rank: 480, title: "Crying Won't Help You", artist: "Tampa Red", genre: "Blues", year: 1944, album: "The Guitar Wizard" },
  { id: 5481, rank: 481, title: "Love Her with a Feeling", artist: "Tampa Red", genre: "Blues", year: 1946, album: "The Guitar Wizard" },
  { id: 5482, rank: 482, title: "I'm Gonna Play It Slow", artist: "Tampa Red", genre: "Blues", year: 1937, album: "The Guitar Wizard" },
  { id: 5483, rank: 483, title: "Don't You Lie to Me", artist: "Big Bill Broonzy", genre: "Blues", year: 1940, album: "The Young Big Bill Broonzy" },
  { id: 5484, rank: 484, title: "When Did You Leave Heaven", artist: "Big Bill Broonzy", genre: "Blues", year: 1936, album: "The Young Big Bill Broonzy" },
  { id: 5485, rank: 485, title: "Willie Mae Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1952, album: "Big Bill's Blues" },
  { id: 5486, rank: 486, title: "All by Myself", artist: "Big Bill Broonzy", genre: "Blues", year: 1955, album: "Big Bill's Blues" },
  { id: 5487, rank: 487, title: "In the Evening", artist: "Big Bill Broonzy", genre: "Blues", year: 1952, album: "Big Bill's Blues" },
  { id: 5488, rank: 488, title: "Keep Your Hands Off Her", artist: "Big Bill Broonzy", genre: "Blues", year: 1940, album: "The Young Big Bill Broonzy" },
  { id: 5489, rank: 489, title: "Mississippi River Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1932, album: "The Young Big Bill Broonzy" },
  { id: 5490, rank: 490, title: "Lonesome Road Blues", artist: "Big Bill Broonzy", genre: "Blues", year: 1940, album: "The Young Big Bill Broonzy" },
  { id: 5491, rank: 491, title: "See See Rider", artist: "Ma Rainey", genre: "Blues", year: 1924, album: "Ma Rainey's Black Bottom" },
  { id: 5492, rank: 492, title: "Ma Rainey's Black Bottom", artist: "Ma Rainey", genre: "Blues", year: 1927, album: "Ma Rainey's Black Bottom" },
  { id: 5493, rank: 493, title: "Prove It on Me Blues", artist: "Ma Rainey", genre: "Blues", year: 1928, album: "Ma Rainey's Black Bottom" },
  { id: 5494, rank: 494, title: "Bo-Weavil Blues", artist: "Ma Rainey", genre: "Blues", year: 1923, album: "Ma Rainey's Black Bottom" },
  { id: 5495, rank: 495, title: "Barrel House Blues", artist: "Ma Rainey", genre: "Blues", year: 1923, album: "Ma Rainey's Black Bottom" },
  { id: 5496, rank: 496, title: "Jealous Hearted Blues", artist: "Ma Rainey", genre: "Blues", year: 1924, album: "Ma Rainey's Black Bottom" },
  { id: 5497, rank: 497, title: "Moonshine Blues", artist: "Ma Rainey", genre: "Blues", year: 1923, album: "Ma Rainey's Black Bottom" },
  { id: 5498, rank: 498, title: "Bessemer Bound Blues", artist: "Ma Rainey", genre: "Blues", year: 1925, album: "Ma Rainey's Black Bottom" },
  { id: 5499, rank: 499, title: "Oh My Babe Blues", artist: "Ma Rainey", genre: "Blues", year: 1923, album: "Ma Rainey's Black Bottom" },
  { id: 5500, rank: 500, title: "Southern Blues", artist: "Ma Rainey", genre: "Blues", year: 1923, album: "Ma Rainey's Black Bottom" }
];