const SONGS_LATIN = [
  { id: 7001, rank: 1, title: "Dakiti", artist: "Bad Bunny", genre: "Latin", year: 2020, album: "El Último Tour Del Mundo" },
  { id: 7002, rank: 2, title: "Tití Me Preguntó", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7003, rank: 3, title: "Me Porto Bonito", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7004, rank: 4, title: "Un Verano Sin Ti", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7005, rank: 5, title: "Yonaguni", artist: "Bad Bunny", genre: "Latin", year: 2021, album: "El Último Tour Del Mundo" },
  { id: 7006, rank: 6, title: "La Canción", artist: "Bad Bunny", genre: "Latin", year: 2019, album: "OASR" },
  { id: 7007, rank: 7, title: "Callaíta", artist: "Bad Bunny", genre: "Latin", year: 2019, album: "Single" },
  { id: 7008, rank: 8, title: "MIA", artist: "Bad Bunny", genre: "Latin", year: 2018, album: "X 100pre" },
  { id: 7009, rank: 9, title: "Safaera", artist: "Bad Bunny", genre: "Latin", year: 2020, album: "YHLQMDLG" },
  { id: 7010, rank: 10, title: "Yo Perreo Sola", artist: "Bad Bunny", genre: "Latin", year: 2020, album: "YHLQMDLG" },
  { id: 7011, rank: 11, title: "Mi Gente", artist: "J Balvin", genre: "Latin", year: 2017, album: "Vibras" },
  { id: 7012, rank: 12, title: "Reggaetón", artist: "J Balvin", genre: "Latin", year: 2017, album: "Vibras" },
  { id: 7013, rank: 13, title: "Ginza", artist: "J Balvin", genre: "Latin", year: 2015, album: "La Familia" },
  { id: 7014, rank: 14, title: "Safari", artist: "J Balvin", genre: "Latin", year: 2016, album: "Single" },
  { id: 7015, rank: 15, title: "Ambiente", artist: "J Balvin", genre: "Latin", year: 2019, album: "Oasis" },
  { id: 7016, rank: 16, title: "Con el Corazón", artist: "J Balvin", genre: "Latin", year: 2018, album: "Vibras" },
  { id: 7017, rank: 17, title: "Bonita", artist: "J Balvin", genre: "Latin", year: 2017, album: "Vibras" },
  { id: 7018, rank: 18, title: "Que Pena", artist: "J Balvin", genre: "Latin", year: 2019, album: "Oasis" },
  { id: 7019, rank: 19, title: "Gasolina", artist: "Daddy Yankee", genre: "Latin", year: 2004, album: "Barrio Fino" },
  { id: 7020, rank: 20, title: "Despacito", artist: "Daddy Yankee", genre: "Latin", year: 2017, album: "Single" },
  { id: 7021, rank: 21, title: "Limbo", artist: "Daddy Yankee", genre: "Latin", year: 2012, album: "Prestige" },
  { id: 7022, rank: 22, title: "Rompe", artist: "Daddy Yankee", genre: "Latin", year: 2005, album: "Barrio Fino en Directo" },
  { id: 7023, rank: 23, title: "Con Calma", artist: "Daddy Yankee", genre: "Latin", year: 2019, album: "Single" },
  { id: 7024, rank: 24, title: "Shaky Shaky", artist: "Daddy Yankee", genre: "Latin", year: 2016, album: "El Disco Duro" },
  { id: 7025, rank: 25, title: "Dura", artist: "Daddy Yankee", genre: "Latin", year: 2018, album: "Single" },
  { id: 7026, rank: 26, title: "Sigueme y Te Sigo", artist: "Daddy Yankee", genre: "Latin", year: 2016, album: "El Disco Duro" },
  { id: 7027, rank: 27, title: "Taki Taki", artist: "Ozuna", genre: "Latin", year: 2018, album: "Single" },
  { id: 7028, rank: 28, title: "Te Robaré", artist: "Ozuna", genre: "Latin", year: 2019, album: "Nibiru" },
  { id: 7029, rank: 29, title: "Caramelo", artist: "Ozuna", genre: "Latin", year: 2020, album: "ENOC" },
  { id: 7030, rank: 30, title: "Baila Baila Baila", artist: "Ozuna", genre: "Latin", year: 2019, album: "Nibiru" },
  { id: 7031, rank: 31, title: "La Modelo", artist: "Ozuna", genre: "Latin", year: 2017, album: "Odisea" },
  { id: 7032, rank: 32, title: "Ahora", artist: "Ozuna", genre: "Latin", year: 2017, album: "Odisea" },
  { id: 7033, rank: 33, title: "Criminal", artist: "Ozuna", genre: "Latin", year: 2017, album: "Single" },
  { id: 7034, rank: 34, title: "Una Flor", artist: "Ozuna", genre: "Latin", year: 2019, album: "Nibiru" },
  { id: 7035, rank: 35, title: "China", artist: "Anuel AA", genre: "Latin", year: 2019, album: "Single" },
  { id: 7036, rank: 36, title: "Ella Quiere Beber", artist: "Anuel AA", genre: "Latin", year: 2017, album: "Real Hasta La Muerte" },
  { id: 7037, rank: 37, title: "Hipócrita", artist: "Anuel AA", genre: "Latin", year: 2018, album: "Real Hasta La Muerte" },
  { id: 7038, rank: 38, title: "Bichota (Remix)", artist: "Anuel AA", genre: "Latin", year: 2021, album: "Single" },
  { id: 7039, rank: 39, title: "Mayor Que Yo", artist: "Anuel AA", genre: "Latin", year: 2017, album: "Single" },
  { id: 7040, rank: 40, title: "Hawái", artist: "Maluma", genre: "Latin", year: 2020, album: "Papi Juancho" },
  { id: 7041, rank: 41, title: "Felices los 4", artist: "Maluma", genre: "Latin", year: 2017, album: "F.A.M.E." },
  { id: 7042, rank: 42, title: "Corazón", artist: "Maluma", genre: "Latin", year: 2017, album: "F.A.M.E." },
  { id: 7043, rank: 43, title: "Cuatro Babys", artist: "Maluma", genre: "Latin", year: 2016, album: "Single" },
  { id: 7044, rank: 44, title: "El Préstamo", artist: "Maluma", genre: "Latin", year: 2017, album: "F.A.M.E." },
  { id: 7045, rank: 45, title: "Borró Cassette", artist: "Maluma", genre: "Latin", year: 2015, album: "Pretty Boy Dirty Boy" },
  { id: 7046, rank: 46, title: "El Perdón", artist: "Nicky Jam", genre: "Latin", year: 2015, album: "Fénix" },
  { id: 7047, rank: 47, title: "X", artist: "Nicky Jam", genre: "Latin", year: 2017, album: "Single" },
  { id: 7048, rank: 48, title: "Hasta el Amanecer", artist: "Nicky Jam", genre: "Latin", year: 2016, album: "Fénix" },
  { id: 7049, rank: 49, title: "Whine Up", artist: "Nicky Jam", genre: "Latin", year: 2007, album: "El Prodigy" },
  { id: 7050, rank: 50, title: "Travesuras", artist: "Nicky Jam", genre: "Latin", year: 2014, album: "Fénix" },
  { id: 7051, rank: 51, title: "Despacito", artist: "Luis Fonsi", genre: "Latin", year: 2017, album: "Vida" },
  { id: 7052, rank: 52, title: "Échame La Culpa", artist: "Luis Fonsi", genre: "Latin", year: 2017, album: "Vida" },
  { id: 7053, rank: 53, title: "Imposible", artist: "Luis Fonsi", genre: "Latin", year: 2003, album: "Amor Secreto" },
  { id: 7054, rank: 54, title: "Nada Es Para Siempre", artist: "Luis Fonsi", genre: "Latin", year: 2002, album: "Amor Secreto" },
  { id: 7055, rank: 55, title: "Aquí Estoy Yo", artist: "Luis Fonsi", genre: "Latin", year: 2009, album: "Nuestro Amor Eterno" },
  { id: 7056, rank: 56, title: "Hips Don't Lie", artist: "Shakira", genre: "Latin", year: 2005, album: "Oral Fixation Vol. 2" },
  { id: 7057, rank: 57, title: "Waka Waka", artist: "Shakira", genre: "Latin", year: 2010, album: "She Wolf" },
  { id: 7058, rank: 58, title: "La Tortura", artist: "Shakira", genre: "Latin", year: 2005, album: "Fijación Oral Vol. 1" },
  { id: 7059, rank: 59, title: "Whenever Wherever", artist: "Shakira", genre: "Latin", year: 2001, album: "Laundry Service" },
  { id: 7060, rank: 60, title: "She Wolf", artist: "Shakira", genre: "Latin", year: 2009, album: "She Wolf" },
  { id: 7061, rank: 61, title: "Loca", artist: "Shakira", genre: "Latin", year: 2010, album: "Sale El Sol" },
  { id: 7062, rank: 62, title: "Can't Remember to Forget You", artist: "Shakira", genre: "Latin", year: 2014, album: "Single" },
  { id: 7063, rank: 63, title: "Bzrp Music Sessions #53", artist: "Shakira", genre: "Latin", year: 2023, album: "Single" },
  { id: 7064, rank: 64, title: "Suerte", artist: "Shakira", genre: "Latin", year: 2001, album: "Laundry Service" },
  { id: 7065, rank: 65, title: "Antología", artist: "Shakira", genre: "Latin", year: 1995, album: "Pies Descalzos" },
  { id: 7066, rank: 66, title: "On the Floor", artist: "Jennifer Lopez", genre: "Latin", year: 2011, album: "Love?" },
  { id: 7067, rank: 67, title: "Jenny from the Block", artist: "Jennifer Lopez", genre: "Latin", year: 2002, album: "This Is Me...Then" },
  { id: 7068, rank: 68, title: "Waiting for Tonight", artist: "Jennifer Lopez", genre: "Latin", year: 1999, album: "On the 6" },
  { id: 7069, rank: 69, title: "If You Had My Love", artist: "Jennifer Lopez", genre: "Latin", year: 1999, album: "On the 6" },
  { id: 7070, rank: 70, title: "Let's Get Loud", artist: "Jennifer Lopez", genre: "Latin", year: 1999, album: "On the 6" },
  { id: 7071, rank: 71, title: "Ain't It Funny", artist: "Jennifer Lopez", genre: "Latin", year: 2001, album: "J.Lo" },
  { id: 7072, rank: 72, title: "Get Right", artist: "Jennifer Lopez", genre: "Latin", year: 2005, album: "Rebirth" },
  { id: 7073, rank: 73, title: "Vivir Mi Vida", artist: "Marc Anthony", genre: "Latin", year: 2013, album: "3.0" },
  { id: 7074, rank: 74, title: "Valió la Pena", artist: "Marc Anthony", genre: "Latin", year: 2009, album: "Iconos" },
  { id: 7075, rank: 75, title: "Tu Amor Me Hace Bien", artist: "Marc Anthony", genre: "Latin", year: 2006, album: "Valió la Pena" },
  { id: 7076, rank: 76, title: "Flor Pálida", artist: "Marc Anthony", genre: "Latin", year: 2013, album: "3.0" },
  { id: 7077, rank: 77, title: "Y Hubo Alguien", artist: "Marc Anthony", genre: "Latin", year: 1999, album: "Todo a Su Tiempo" },
  { id: 7078, rank: 78, title: "Que Precio Tiene el Cielo", artist: "Marc Anthony", genre: "Latin", year: 1993, album: "Otra Nota" },
  { id: 7079, rank: 79, title: "Hasta Que Te Conocí", artist: "Marc Anthony", genre: "Latin", year: 1993, album: "Otra Nota" },
  { id: 7080, rank: 80, title: "Se Esfumó", artist: "Marc Anthony", genre: "Latin", year: 2000, album: "Libre" },
  { id: 7081, rank: 81, title: "Para Siempre", artist: "Marc Anthony", genre: "Latin", year: 2008, album: "El Cantante" },
  { id: 7082, rank: 82, title: "La Vida Es Un Carnaval", artist: "Celia Cruz", genre: "Latin", year: 1998, album: "Mi Vida Es Cantar" },
  { id: 7083, rank: 83, title: "Quimbara", artist: "Celia Cruz", genre: "Latin", year: 1974, album: "Celia & Johnny" },
  { id: 7084, rank: 84, title: "Bemba Colorá", artist: "Celia Cruz", genre: "Latin", year: 1966, album: "Cuba's Foremost Rhythm Singer" },
  { id: 7085, rank: 85, title: "Oye Como Va", artist: "Celia Cruz", genre: "Latin", year: 1975, album: "Tremendo Caché" },
  { id: 7086, rank: 86, title: "Azúcar Negra", artist: "Celia Cruz", genre: "Latin", year: 1993, album: "Azúcar Negra" },
  { id: 7087, rank: 87, title: "Guantanamera", artist: "Celia Cruz", genre: "Latin", year: 1966, album: "Single" },
  { id: 7088, rank: 88, title: "El Malo", artist: "Willie Colón", genre: "Latin", year: 1967, album: "El Malo" },
  { id: 7089, rank: 89, title: "Cosa Nuestra", artist: "Willie Colón", genre: "Latin", year: 1970, album: "Cosa Nuestra" },
  { id: 7090, rank: 90, title: "El Gran Varón", artist: "Willie Colón", genre: "Latin", year: 1989, album: "Single" },
  { id: 7091, rank: 91, title: "Idilio", artist: "Willie Colón", genre: "Latin", year: 1978, album: "Solo" },
  { id: 7092, rank: 92, title: "La Murga", artist: "Willie Colón", genre: "Latin", year: 1975, album: "The Good, the Bad, the Ugly" },
  { id: 7093, rank: 93, title: "El Cantante", artist: "Hector Lavoe", genre: "Latin", year: 1975, album: "La Voz" },
  { id: 7094, rank: 94, title: "Periódico de Ayer", artist: "Hector Lavoe", genre: "Latin", year: 1975, album: "La Voz" },
  { id: 7095, rank: 95, title: "Todo Tiene Su Final", artist: "Hector Lavoe", genre: "Latin", year: 1974, album: "Caminando" },
  { id: 7096, rank: 96, title: "Aguanile", artist: "Hector Lavoe", genre: "Latin", year: 1969, album: "Cosa Nuestra" },
  { id: 7097, rank: 97, title: "Mi Gente", artist: "Hector Lavoe", genre: "Latin", year: 1975, album: "La Voz" },
  { id: 7098, rank: 98, title: "Pedro Navaja", artist: "Rubén Blades", genre: "Latin", year: 1978, album: "Siembra" },
  { id: 7099, rank: 99, title: "Plástico", artist: "Rubén Blades", genre: "Latin", year: 1978, album: "Siembra" },
  { id: 7100, rank: 100, title: "Pablo Pueblo", artist: "Rubén Blades", genre: "Latin", year: 1978, album: "Siembra" },
  { id: 7101, rank: 101, title: "Buscando América", artist: "Rubén Blades", genre: "Latin", year: 1984, album: "Buscando América" },
  { id: 7102, rank: 102, title: "Decisiones", artist: "Rubén Blades", genre: "Latin", year: 1984, album: "Buscando América" },
  { id: 7103, rank: 103, title: "Oye Como Va", artist: "Tito Puente", genre: "Latin", year: 1962, album: "El Rey Bravo" },
  { id: 7104, rank: 104, title: "Ran Kan Kan", artist: "Tito Puente", genre: "Latin", year: 1949, album: "Tito Puente and His Concert Orchestra" },
  { id: 7105, rank: 105, title: "Para Los Rumberos", artist: "Tito Puente", genre: "Latin", year: 1955, album: "Single" },
  { id: 7106, rank: 106, title: "Mambo Inn", artist: "Tito Puente", genre: "Latin", year: 1958, album: "Top Percussion" },
  { id: 7107, rank: 107, title: "El Cayuco", artist: "Tito Puente", genre: "Latin", year: 1956, album: "Single" },
  { id: 7108, rank: 108, title: "Cali Ají", artist: "Grupo Niche", genre: "Latin", year: 1990, album: "Sin Problemas" },
  { id: 7109, rank: 109, title: "Sin Saliva", artist: "Grupo Niche", genre: "Latin", year: 1985, album: "Nueva Ola" },
  { id: 7110, rank: 110, title: "Buenaventura y Caney", artist: "Grupo Niche", genre: "Latin", year: 1989, album: "Cielo de Tambores" },
  { id: 7111, rank: 111, title: "Una Aventura", artist: "Grupo Niche", genre: "Latin", year: 1982, album: "Al Pasito" },
  { id: 7112, rank: 112, title: "Que Manera de Quererte", artist: "Gilberto Santa Rosa", genre: "Latin", year: 1993, album: "Solo" },
  { id: 7113, rank: 113, title: "Conciencia", artist: "Gilberto Santa Rosa", genre: "Latin", year: 1992, album: "Perspectiva" },
  { id: 7114, rank: 114, title: "Perdoname", artist: "Gilberto Santa Rosa", genre: "Latin", year: 1997, album: "Auténtico" },
  { id: 7115, rank: 115, title: "La Cura", artist: "Frankie Ruiz", genre: "Latin", year: 1987, album: "La Cura" },
  { id: 7116, rank: 116, title: "Quiero Llenarte", artist: "Frankie Ruiz", genre: "Latin", year: 1986, album: "Voy Pa'lla" },
  { id: 7117, rank: 117, title: "Bailando", artist: "Frankie Ruiz", genre: "Latin", year: 1986, album: "Voy Pa'lla" },
  { id: 7118, rank: 118, title: "Danza Kuduro", artist: "Don Omar", genre: "Latin", year: 2011, album: "Single" },
  { id: 7119, rank: 119, title: "Virtual Diva", artist: "Don Omar", genre: "Latin", year: 2009, album: "iDon" },
  { id: 7120, rank: 120, title: "Taboo", artist: "Don Omar", genre: "Latin", year: 2003, album: "The Last Don" },
  { id: 7121, rank: 121, title: "Pobre Diabla", artist: "Don Omar", genre: "Latin", year: 2003, album: "The Last Don" },
  { id: 7122, rank: 122, title: "Conteo", artist: "Don Omar", genre: "Latin", year: 2015, album: "Single" },
  { id: 7123, rank: 123, title: "Al Natural", artist: "Tego Calderón", genre: "Latin", year: 2002, album: "El Abayarde" },
  { id: 7124, rank: 124, title: "Métele Sazón", artist: "Tego Calderón", genre: "Latin", year: 2002, album: "El Abayarde" },
  { id: 7125, rank: 125, title: "Nadie Como Tú", artist: "Wisin & Yandel", genre: "Latin", year: 2008, album: "Los Extraterrestres" },
  { id: 7126, rank: 126, title: "Rakata", artist: "Wisin & Yandel", genre: "Latin", year: 2005, album: "Pa'l Mundo" },
  { id: 7127, rank: 127, title: "Sexy Movimiento", artist: "Wisin & Yandel", genre: "Latin", year: 2005, album: "Pa'l Mundo" },
  { id: 7128, rank: 128, title: "Propuesta Indecente", artist: "Romeo Santos", genre: "Latin", year: 2013, album: "Fórmula Vol. 2" },
  { id: 7129, rank: 129, title: "Odio", artist: "Romeo Santos", genre: "Latin", year: 2014, album: "Fórmula Vol. 2" },
  { id: 7130, rank: 130, title: "La Diabla", artist: "Romeo Santos", genre: "Latin", year: 2011, album: "Fórmula Vol. 1" },
  { id: 7131, rank: 131, title: "Eres Mía", artist: "Romeo Santos", genre: "Latin", year: 2014, album: "Fórmula Vol. 2" },
  { id: 7132, rank: 132, title: "Héroe Favorito", artist: "Romeo Santos", genre: "Latin", year: 2017, album: "Golden" },
  { id: 7133, rank: 133, title: "Aléjate", artist: "Romeo Santos", genre: "Latin", year: 2011, album: "Fórmula Vol. 1" },
  { id: 7134, rank: 134, title: "Cancioncita de Amor", artist: "Romeo Santos", genre: "Latin", year: 2017, album: "Golden" },
  { id: 7135, rank: 135, title: "Stand by Me", artist: "Prince Royce", genre: "Latin", year: 2010, album: "Prince Royce" },
  { id: 7136, rank: 136, title: "Darte un Beso", artist: "Prince Royce", genre: "Latin", year: 2012, album: "Phase II" },
  { id: 7137, rank: 137, title: "Corazón Sin Cara", artist: "Prince Royce", genre: "Latin", year: 2010, album: "Prince Royce" },
  { id: 7138, rank: 138, title: "Te Robaré", artist: "Prince Royce", genre: "Latin", year: 2019, album: "Single" },
  { id: 7139, rank: 139, title: "Incondicional", artist: "Prince Royce", genre: "Latin", year: 2013, album: "Phase II" },
  { id: 7140, rank: 140, title: "La Bicicleta", artist: "Carlos Vives", genre: "Latin", year: 2016, album: "Vives" },
  { id: 7141, rank: 141, title: "Volví a Nacer", artist: "Carlos Vives", genre: "Latin", year: 2012, album: "Corazón Profundo" },
  { id: 7142, rank: 142, title: "Carito", artist: "Carlos Vives", genre: "Latin", year: 1993, album: "Clásicos de la Provincia" },
  { id: 7143, rank: 143, title: "La Chaqueta", artist: "Carlos Vives", genre: "Latin", year: 1993, album: "Clásicos de la Provincia" },
  { id: 7144, rank: 144, title: "Fruta Fresca", artist: "Carlos Vives", genre: "Latin", year: 2015, album: "Más + Corazón Profundo" },
  { id: 7145, rank: 145, title: "Ojalá Que Llueva Café", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Ojalá Que Llueva Café" },
  { id: 7146, rank: 146, title: "La Bilirrubina", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Bachata Rosa" },
  { id: 7147, rank: 147, title: "Bachata Rosa", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Bachata Rosa" },
  { id: 7148, rank: 148, title: "El Niágara en Bicicleta", artist: "Juan Luis Guerra", genre: "Latin", year: 1994, album: "Fogaraté" },
  { id: 7149, rank: 149, title: "Burbujas de Amor", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Bachata Rosa" },
  { id: 7150, rank: 150, title: "Visa para un Sueño", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Ojalá Que Llueva Café" },
  { id: 7151, rank: 151, title: "Give Me Everything", artist: "Pitbull", genre: "Latin", year: 2011, album: "Planet Pit" },
  { id: 7152, rank: 152, title: "International Love", artist: "Pitbull", genre: "Latin", year: 2012, album: "Global Warming" },
  { id: 7153, rank: 153, title: "Feel This Moment", artist: "Pitbull", genre: "Latin", year: 2013, album: "Global Warming: Meltdown" },
  { id: 7154, rank: 154, title: "Timber", artist: "Pitbull", genre: "Latin", year: 2013, album: "Globalization" },
  { id: 7155, rank: 155, title: "Don't Stop the Party", artist: "Pitbull", genre: "Latin", year: 2012, album: "Global Warming" },
  { id: 7156, rank: 156, title: "Rain Over Me", artist: "Pitbull", genre: "Latin", year: 2011, album: "Planet Pit" },
  { id: 7157, rank: 157, title: "Smooth", artist: "Carlos Santana", genre: "Latin", year: 1999, album: "Supernatural" },
  { id: 7158, rank: 158, title: "Oye Como Va", artist: "Carlos Santana", genre: "Latin", year: 1970, album: "Abraxas" },
  { id: 7159, rank: 159, title: "Black Magic Woman", artist: "Carlos Santana", genre: "Latin", year: 1970, album: "Abraxas" },
  { id: 7160, rank: 160, title: "Maria Maria", artist: "Carlos Santana", genre: "Latin", year: 1999, album: "Supernatural" },
  { id: 7161, rank: 161, title: "Evil Ways", artist: "Carlos Santana", genre: "Latin", year: 1969, album: "Santana" },
  { id: 7162, rank: 162, title: "Europa", artist: "Carlos Santana", genre: "Latin", year: 1976, album: "Amigos" },
  { id: 7163, rank: 163, title: "Samba Pa Ti", artist: "Carlos Santana", genre: "Latin", year: 1970, album: "Abraxas" },
  { id: 7164, rank: 164, title: "Game of Love", artist: "Carlos Santana", genre: "Latin", year: 2002, album: "Shaman" },
  { id: 7165, rank: 165, title: "Oye Mi Amor", artist: "Maná", genre: "Latin", year: 1992, album: "¿Dónde Jugarán los Niños?" },
  { id: 7166, rank: 166, title: "Labios Compartidos", artist: "Maná", genre: "Latin", year: 2003, album: "Revolución de Amor" },
  { id: 7167, rank: 167, title: "En el Muelle de San Blás", artist: "Maná", genre: "Latin", year: 1994, album: "Cuando los Ángeles Lloran" },
  { id: 7168, rank: 168, title: "Rayando el Sol", artist: "Maná", genre: "Latin", year: 1990, album: "Falta Amor" },
  { id: 7169, rank: 169, title: "De Pies a Cabeza", artist: "Maná", genre: "Latin", year: 1994, album: "Cuando los Ángeles Lloran" },
  { id: 7170, rank: 170, title: "Clavado en un Bar", artist: "Maná", genre: "Latin", year: 1994, album: "Cuando los Ángeles Lloran" },
  { id: 7171, rank: 171, title: "Amor Clandestino", artist: "Maná", genre: "Latin", year: 1997, album: "Sueños Líquidos" },
  { id: 7172, rank: 172, title: "La Ingrata", artist: "Café Tacvba", genre: "Latin", year: 1994, album: "Re" },
  { id: 7173, rank: 173, title: "Eres", artist: "Café Tacvba", genre: "Latin", year: 1994, album: "Re" },
  { id: 7174, rank: 174, title: "Las Flores", artist: "Café Tacvba", genre: "Latin", year: 1999, album: "Revés / Yo Soy" },
  { id: 7175, rank: 175, title: "Cómo Te Extraño Mi Amor", artist: "Café Tacvba", genre: "Latin", year: 2003, album: "Cuatro Caminos" },
  { id: 7176, rank: 176, title: "Quiero Ver", artist: "Café Tacvba", genre: "Latin", year: 2007, album: "Sino" },
  { id: 7177, rank: 177, title: "De Música Ligera", artist: "Soda Stereo", genre: "Latin", year: 1990, album: "Canción Animal" },
  { id: 7178, rank: 178, title: "Persiana Americana", artist: "Soda Stereo", genre: "Latin", year: 1987, album: "Ruido Blanco" },
  { id: 7179, rank: 179, title: "Cuando Pase el Temblor", artist: "Soda Stereo", genre: "Latin", year: 1985, album: "Nada Personal" },
  { id: 7180, rank: 180, title: "En la Ciudad de la Furia", artist: "Soda Stereo", genre: "Latin", year: 1990, album: "Canción Animal" },
  { id: 7181, rank: 181, title: "Fue", artist: "Soda Stereo", genre: "Latin", year: 1994, album: "Dynamo" },
  { id: 7182, rank: 182, title: "Trátame Suavemente", artist: "Soda Stereo", genre: "Latin", year: 1984, album: "Soda Stereo" },
  { id: 7183, rank: 183, title: "Matador", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1994, album: "El León" },
  { id: 7184, rank: 184, title: "Mal Bicho", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1994, album: "El León" },
  { id: 7185, rank: 185, title: "Siguiendo la Luna", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1992, album: "Rey Azúcar" },
  { id: 7186, rank: 186, title: "La Camisa Negra", artist: "Juanes", genre: "Latin", year: 2004, album: "Mi Sangre" },
  { id: 7187, rank: 187, title: "A Dios le Pido", artist: "Juanes", genre: "Latin", year: 2002, album: "Un Día Normal" },
  { id: 7188, rank: 188, title: "Me Enamora", artist: "Juanes", genre: "Latin", year: 2006, album: "La Vida... Es un Ratico" },
  { id: 7189, rank: 189, title: "Para Tu Amor", artist: "Juanes", genre: "Latin", year: 2000, album: "Fíjate Bien" },
  { id: 7190, rank: 190, title: "Nada Valgo Sin Tu Amor", artist: "Juanes", genre: "Latin", year: 2002, album: "Un Día Normal" },
  { id: 7191, rank: 191, title: "Livin' la Vida Loca", artist: "Ricky Martin", genre: "Latin", year: 1999, album: "Ricky Martin" },
  { id: 7192, rank: 192, title: "La Copa de la Vida", artist: "Ricky Martin", genre: "Latin", year: 1998, album: "Vuelve" },
  { id: 7193, rank: 193, title: "She Bangs", artist: "Ricky Martin", genre: "Latin", year: 2000, album: "Sound Loaded" },
  { id: 7194, rank: 194, title: "María", artist: "Ricky Martin", genre: "Latin", year: 1995, album: "A Medio Vivir" },
  { id: 7195, rank: 195, title: "Shake Your Bon-Bon", artist: "Ricky Martin", genre: "Latin", year: 1999, album: "Ricky Martin" },
  { id: 7196, rank: 196, title: "Amor", artist: "Ricky Martin", genre: "Latin", year: 2006, album: "Life" },
  { id: 7197, rank: 197, title: "Pégate", artist: "Ricky Martin", genre: "Latin", year: 2005, album: "Life" },
  { id: 7198, rank: 198, title: "Hero", artist: "Enrique Iglesias", genre: "Latin", year: 2001, album: "Escape" },
  { id: 7199, rank: 199, title: "Bailamos", artist: "Enrique Iglesias", genre: "Latin", year: 1999, album: "Enrique" },
  { id: 7200, rank: 200, title: "Be with You", artist: "Enrique Iglesias", genre: "Latin", year: 1999, album: "Enrique" },
  { id: 7201, rank: 201, title: "Escapar", artist: "Enrique Iglesias", genre: "Latin", year: 2002, album: "Quizás" },
  { id: 7202, rank: 202, title: "Rhythm Divine", artist: "Enrique Iglesias", genre: "Latin", year: 1999, album: "Enrique" },
  { id: 7203, rank: 203, title: "I Like It", artist: "Enrique Iglesias", genre: "Latin", year: 2010, album: "Euphoria" },
  { id: 7204, rank: 204, title: "Tonight (I'm Lovin' You)", artist: "Enrique Iglesias", genre: "Latin", year: 2010, album: "Euphoria" },
  { id: 7205, rank: 205, title: "Subeme la Radio", artist: "Enrique Iglesias", genre: "Latin", year: 2017, album: "Single" },
  { id: 7206, rank: 206, title: "Conga", artist: "Gloria Estefan", genre: "Latin", year: 1985, album: "Primitive Love" },
  { id: 7207, rank: 207, title: "Get On Your Feet", artist: "Gloria Estefan", genre: "Latin", year: 1989, album: "Cuts Both Ways" },
  { id: 7208, rank: 208, title: "Don't Want to Lose You", artist: "Gloria Estefan", genre: "Latin", year: 1989, album: "Cuts Both Ways" },
  { id: 7209, rank: 209, title: "Rhythm Is Gonna Get You", artist: "Gloria Estefan", genre: "Latin", year: 1987, album: "Let It Loose" },
  { id: 7210, rank: 210, title: "Coming Out of the Dark", artist: "Gloria Estefan", genre: "Latin", year: 1991, album: "Into the Light" },
  { id: 7211, rank: 211, title: "Mi Tierra", artist: "Gloria Estefan", genre: "Latin", year: 1993, album: "Mi Tierra" },
  { id: 7212, rank: 212, title: "Amor Eterno", artist: "Juan Gabriel", genre: "Latin", year: 1984, album: "Recuerdos Vol. II" },
  { id: 7213, rank: 213, title: "Querida", artist: "Juan Gabriel", genre: "Latin", year: 1984, album: "Recuerdos Vol. II" },
  { id: 7214, rank: 214, title: "Te Sigo Amando", artist: "Juan Gabriel", genre: "Latin", year: 1994, album: "Gracias por Esperar" },
  { id: 7215, rank: 215, title: "Así Fue", artist: "Juan Gabriel", genre: "Latin", year: 1987, album: "México Siempre en mi Corazón" },
  { id: 7216, rank: 216, title: "Hasta Que Te Conocí", artist: "Juan Gabriel", genre: "Latin", year: 1987, album: "México Siempre en mi Corazón" },
  { id: 7217, rank: 217, title: "Volver Volver", artist: "Vicente Fernández", genre: "Latin", year: 1972, album: "Volver Volver" },
  { id: 7218, rank: 218, title: "El Rey", artist: "Vicente Fernández", genre: "Latin", year: 1971, album: "El Rey" },
  { id: 7219, rank: 219, title: "Acá Entre Nos", artist: "Vicente Fernández", genre: "Latin", year: 1987, album: "Acá Entre Nos" },
  { id: 7220, rank: 220, title: "Lástima Que Seas Ajena", artist: "Vicente Fernández", genre: "Latin", year: 1977, album: "Para Siempre" },
  { id: 7221, rank: 221, title: "Mujeres Divinas", artist: "Vicente Fernández", genre: "Latin", year: 1984, album: "Mujeres Divinas" },
  { id: 7222, rank: 222, title: "El Triste", artist: "José José", genre: "Latin", year: 1970, album: "El Triste" },
  { id: 7223, rank: 223, title: "Gavilán o Paloma", artist: "José José", genre: "Latin", year: 1982, album: "Reflexiones" },
  { id: 7224, rank: 224, title: "Lo Que No Fue No Será", artist: "José José", genre: "Latin", year: 1979, album: "Romántico" },
  { id: 7225, rank: 225, title: "Almohada", artist: "José José", genre: "Latin", year: 1976, album: "Almohada" },
  { id: 7226, rank: 226, title: "Llorando Me Dormí", artist: "Alejandro Fernández", genre: "Latin", year: 1992, album: "Alejandro Fernández" },
  { id: 7227, rank: 227, title: "Mátenme Porque Me Muero", artist: "Alejandro Fernández", genre: "Latin", year: 1995, album: "Me Estoy Enamorando" },
  { id: 7228, rank: 228, title: "Sé Que Te Duele", artist: "Alejandro Fernández", genre: "Latin", year: 2010, album: "Dos Mundos" },
  { id: 7229, rank: 229, title: "Bichota", artist: "Karol G", genre: "Latin", year: 2020, album: "KG0516" },
  { id: 7230, rank: 230, title: "PROVENZA", artist: "Karol G", genre: "Latin", year: 2022, album: "Mañana Será Bonito" },
  { id: 7231, rank: 231, title: "Mamiii", artist: "Karol G", genre: "Latin", year: 2022, album: "Single" },
  { id: 7232, rank: 232, title: "Tusa", artist: "Karol G", genre: "Latin", year: 2019, album: "KG0516" },
  { id: 7233, rank: 233, title: "El Makinon", artist: "Karol G", genre: "Latin", year: 2022, album: "KG0516" },
  { id: 7234, rank: 234, title: "Mi Cama", artist: "Karol G", genre: "Latin", year: 2018, album: "Single" },
  { id: 7235, rank: 235, title: "Location", artist: "Karol G", genre: "Latin", year: 2018, album: "Unstoppable" },
  { id: 7236, rank: 236, title: "Mientras Me Curo del Cora", artist: "Karol G", genre: "Latin", year: 2022, album: "Mañana Será Bonito" },
  { id: 7237, rank: 237, title: "Con Altura", artist: "Rosalía", genre: "Latin", year: 2019, album: "Single" },
  { id: 7238, rank: 238, title: "Malamente", artist: "Rosalía", genre: "Latin", year: 2017, album: "Los Ángeles" },
  { id: 7239, rank: 239, title: "Pienso en Tu Mirá", artist: "Rosalía", genre: "Latin", year: 2018, album: "El Mal Querer" },
  { id: 7240, rank: 240, title: "Di Mi Nombre", artist: "Rosalía", genre: "Latin", year: 2018, album: "El Mal Querer" },
  { id: 7241, rank: 241, title: "SAOKO", artist: "Rosalía", genre: "Latin", year: 2022, album: "MOTOMAMI" },
  { id: 7242, rank: 242, title: "BIZCOCHITO", artist: "Rosalía", genre: "Latin", year: 2021, album: "MOTOMAMI" },
  { id: 7243, rank: 243, title: "Chicken Teriyaki", artist: "Rosalía", genre: "Latin", year: 2021, album: "MOTOMAMI" },
  { id: 7244, rank: 244, title: "Hentai", artist: "Rosalía", genre: "Latin", year: 2021, album: "MOTOMAMI" },
  { id: 7245, rank: 245, title: "Vida de Rico", artist: "Camilo", genre: "Latin", year: 2020, album: "Por Primera Vez" },
  { id: 7246, rank: 246, title: "Tutu", artist: "Camilo", genre: "Latin", year: 2019, album: "Single" },
  { id: 7247, rank: 247, title: "Por Primera Vez", artist: "Camilo", genre: "Latin", year: 2020, album: "Por Primera Vez" },
  { id: 7248, rank: 248, title: "Ropa Cara", artist: "Camilo", genre: "Latin", year: 2019, album: "Por Primera Vez" },
  { id: 7249, rank: 249, title: "NASA", artist: "Camilo", genre: "Latin", year: 2020, album: "Por Primera Vez" },
  { id: 7250, rank: 250, title: "Garota de Ipanema", artist: "João Gilberto", genre: "Latin", year: 1962, album: "Getz/Gilberto" },
  { id: 7251, rank: 251, title: "Chega de Saudade", artist: "João Gilberto", genre: "Latin", year: 1959, album: "Chega de Saudade" },
  { id: 7252, rank: 252, title: "Desafinado", artist: "João Gilberto", genre: "Latin", year: 1958, album: "Chega de Saudade" },
  { id: 7253, rank: 253, title: "Águas de Março", artist: "João Gilberto", genre: "Latin", year: 1972, album: "Single" },
  { id: 7254, rank: 254, title: "Bim Bom", artist: "João Gilberto", genre: "Latin", year: 1958, album: "Chega de Saudade" },
  { id: 7255, rank: 255, title: "The Girl from Ipanema", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1964, album: "Getz/Gilberto" },
  { id: 7256, rank: 256, title: "Corcovado", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1960, album: "The Composer of Desafinado Plays" },
  { id: 7257, rank: 257, title: "Wave", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1967, album: "Wave" },
  { id: 7258, rank: 258, title: "Insensatez", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1961, album: "Love, Strings and Jobim" },
  { id: 7259, rank: 259, title: "Triste", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1968, album: "Wave" },
  { id: 7260, rank: 260, title: "Meditation (Meditação)", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1960, album: "Wave" },
  { id: 7261, rank: 261, title: "The Girl from Ipanema", artist: "Astrud Gilberto", genre: "Latin", year: 1964, album: "Getz/Gilberto" },
  { id: 7262, rank: 262, title: "Corcovado (Quiet Nights)", artist: "Astrud Gilberto", genre: "Latin", year: 1964, album: "Getz/Gilberto" },
  { id: 7263, rank: 263, title: "So Danco Samba", artist: "Astrud Gilberto", genre: "Latin", year: 1964, album: "Getz/Gilberto" },
  { id: 7264, rank: 264, title: "Desafinado", artist: "Stan Getz", genre: "Latin", year: 1962, album: "Jazz Samba" },
  { id: 7265, rank: 265, title: "Aquarela do Brasil", artist: "Elis Regina", genre: "Latin", year: 1970, album: "Elis & Tom" },
  { id: 7266, rank: 266, title: "Como Nossos Pais", artist: "Elis Regina", genre: "Latin", year: 1976, album: "Falso Brilhante" },
  { id: 7267, rank: 267, title: "Cucurrucucú Paloma", artist: "Caetano Veloso", genre: "Latin", year: 1965, album: "Caetano Veloso" },
  { id: 7268, rank: 268, title: "Terra", artist: "Caetano Veloso", genre: "Latin", year: 1978, album: "Muito" },
  { id: 7269, rank: 269, title: "Sozinho", artist: "Caetano Veloso", genre: "Latin", year: 1998, album: "Livro" },
  { id: 7270, rank: 270, title: "Aquele Abraço", artist: "Gilberto Gil", genre: "Latin", year: 1969, album: "Gilberto Gil" },
  { id: 7271, rank: 271, title: "Toda Menina Baiana", artist: "Gilberto Gil", genre: "Latin", year: 1979, album: "Realce" },
  { id: 7272, rank: 272, title: "La Incondicional", artist: "Luis Miguel", genre: "Latin", year: 1989, album: "20 Años" },
  { id: 7273, rank: 273, title: "Sabor a Mí", artist: "Luis Miguel", genre: "Latin", year: 1994, album: "Segundo Romance" },
  { id: 7274, rank: 274, title: "Que el Ritmo No Pare", artist: "Luis Miguel", genre: "Latin", year: 1991, album: "Romance" },
  { id: 7275, rank: 275, title: "Romance", artist: "Luis Miguel", genre: "Latin", year: 1991, album: "Romance" },
  { id: 7276, rank: 276, title: "Besame Mucho", artist: "Luis Miguel", genre: "Latin", year: 1994, album: "Segundo Romance" },
  { id: 7277, rank: 277, title: "Solamente una Vez", artist: "Luis Miguel", genre: "Latin", year: 1991, album: "Romance" },
  { id: 7278, rank: 278, title: "Perfidia", artist: "Luis Miguel", genre: "Latin", year: 1994, album: "Segundo Romance" },
  { id: 7279, rank: 279, title: "No Sé Tú", artist: "Luis Miguel", genre: "Latin", year: 1989, album: "20 Años" },
  { id: 7280, rank: 280, title: "Bésame Mucho", artist: "Trio Los Panchos", genre: "Latin", year: 1944, album: "Single" },
  { id: 7281, rank: 281, title: "Sabor a Mí", artist: "Trio Los Panchos", genre: "Latin", year: 1959, album: "Single" },
  { id: 7282, rank: 282, title: "Sin Ti", artist: "Trio Los Panchos", genre: "Latin", year: 1949, album: "Single" },
  { id: 7283, rank: 283, title: "Quizás Quizás Quizás", artist: "Trio Los Panchos", genre: "Latin", year: 1947, album: "Single" },
  { id: 7284, rank: 284, title: "Esta Tarde Vi Llover", artist: "Armando Manzanero", genre: "Latin", year: 1967, album: "Vivo" },
  { id: 7285, rank: 285, title: "Somos Novios", artist: "Armando Manzanero", genre: "Latin", year: 1968, album: "Vivo" },
  { id: 7286, rank: 286, title: "No Sé Tú", artist: "Armando Manzanero", genre: "Latin", year: 1989, album: "Single" },
  { id: 7287, rank: 287, title: "La Llorona", artist: "Chavela Vargas", genre: "Latin", year: 1961, album: "Noche de Bodas" },
  { id: 7288, rank: 288, title: "Macorina", artist: "Chavela Vargas", genre: "Latin", year: 1961, album: "Noche de Bodas" },
  { id: 7289, rank: 289, title: "Entre Dos Aguas", artist: "Paco de Lucía", genre: "Latin", year: 1973, album: "Fuente y Caudal" },
  { id: 7290, rank: 290, title: "Almoraima", artist: "Paco de Lucía", genre: "Latin", year: 1976, album: "Almoraima" },
  { id: 7291, rank: 291, title: "Zyryab", artist: "Paco de Lucía", genre: "Latin", year: 1990, album: "Zyryab" },
  { id: 7292, rank: 292, title: "Solo Quiero Caminar", artist: "Paco de Lucía", genre: "Latin", year: 1981, album: "Solo Quiero Caminar" },
  { id: 7293, rank: 293, title: "La Leyenda del Tiempo", artist: "Camarón de la Isla", genre: "Latin", year: 1979, album: "La Leyenda del Tiempo" },
  { id: 7294, rank: 294, title: "Como el Agua", artist: "Camarón de la Isla", genre: "Latin", year: 1981, album: "Como el Agua" },
  { id: 7295, rank: 295, title: "Soy Gitano", artist: "Camarón de la Isla", genre: "Latin", year: 1989, album: "Soy Gitano" },
  { id: 7296, rank: 296, title: "Nana del Caballo Grande", artist: "Camarón de la Isla", genre: "Latin", year: 1979, album: "La Leyenda del Tiempo" },
  { id: 7297, rank: 297, title: "La Zarzamora", artist: "Lola Flores", genre: "Latin", year: 1945, album: "Single" },
  { id: 7298, rank: 298, title: "Ay Pena Penita Pena", artist: "Lola Flores", genre: "Latin", year: 1953, album: "Single" },
  { id: 7299, rank: 299, title: "Volver", artist: "Estrella Morente", genre: "Latin", year: 2006, album: "Single" },
  { id: 7300, rank: 300, title: "Lágrimas Negras", artist: "Diego El Cigala", genre: "Latin", year: 2003, album: "Lágrimas Negras" },
  { id: 7301, rank: 301, title: "Omega", artist: "Enrique Morente", genre: "Latin", year: 1996, album: "Omega" },
  { id: 7302, rank: 302, title: "Illegal", artist: "Shakira", genre: "Latin", year: 2005, album: "Fijación Oral Vol. 1" },
  { id: 7303, rank: 303, title: "Te Aviso, Te Anuncio (Tango)", artist: "Shakira", genre: "Latin", year: 2005, album: "Fijación Oral Vol. 1" },
  { id: 7304, rank: 304, title: "All I Have", artist: "Jennifer Lopez", genre: "Latin", year: 2002, album: "This Is Me...Then" },
  { id: 7305, rank: 305, title: "I'm Real", artist: "Jennifer Lopez", genre: "Latin", year: 2001, album: "J.Lo" },
  { id: 7306, rank: 306, title: "Heartbeat", artist: "Enrique Iglesias", genre: "Latin", year: 2011, album: "Euphoria" },
  { id: 7307, rank: 307, title: "Duele el Corazón", artist: "Enrique Iglesias", genre: "Latin", year: 2015, album: "Sex and Love" },
  { id: 7308, rank: 308, title: "Bailando", artist: "Enrique Iglesias", genre: "Latin", year: 2014, album: "Sex and Love" },
  { id: 7309, rank: 309, title: "El Perdedor", artist: "Enrique Iglesias", genre: "Latin", year: 2014, album: "Sex and Love" },
  { id: 7310, rank: 310, title: "Gotas de Agua Dulce", artist: "Juanes", genre: "Latin", year: 2002, album: "Un Día Normal" },
  { id: 7311, rank: 311, title: "Volverte a Ver", artist: "Juanes", genre: "Latin", year: 2003, album: "Mi Sangre" },
  { id: 7312, rank: 312, title: "Fotografía", artist: "Juanes", genre: "Latin", year: 2002, album: "Un Día Normal" },
  { id: 7313, rank: 313, title: "Si No Te Hubieras Ido", artist: "Maná", genre: "Latin", year: 2001, album: "Revolución de Amor" },
  { id: 7314, rank: 314, title: "Ángel de Amor", artist: "Maná", genre: "Latin", year: 1997, album: "Sueños Líquidos" },
  { id: 7315, rank: 315, title: "Mariposa Traicionera", artist: "Maná", genre: "Latin", year: 2002, album: "Revolución de Amor" },
  { id: 7316, rank: 316, title: "Chilanga Banda", artist: "Café Tacvba", genre: "Latin", year: 1994, album: "Re" },
  { id: 7317, rank: 317, title: "Olita del Altamar", artist: "Café Tacvba", genre: "Latin", year: 2003, album: "Cuatro Caminos" },
  { id: 7318, rank: 318, title: "Vasos Vacíos", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1994, album: "El León" },
  { id: 7319, rank: 319, title: "El Satánico Dr. Cadillac", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1997, album: "Fabulosos Calavera" },
  { id: 7320, rank: 320, title: "Cucala", artist: "Celia Cruz", genre: "Latin", year: 1992, album: "La Ceiba" },
  { id: 7321, rank: 321, title: "Che Che Colé", artist: "Willie Colón", genre: "Latin", year: 1969, album: "The Hustler" },
  { id: 7322, rank: 322, title: "Picadillo", artist: "Tito Puente", genre: "Latin", year: 1956, album: "Single" },
  { id: 7323, rank: 323, title: "Siembra", artist: "Rubén Blades", genre: "Latin", year: 1978, album: "Siembra" },
  { id: 7324, rank: 324, title: "Amor y Control", artist: "Rubén Blades", genre: "Latin", year: 1992, album: "Amor y Control" },
  { id: 7325, rank: 325, title: "Tu Con El", artist: "Frankie Ruiz", genre: "Latin", year: 1986, album: "Voy Pa'lla" },
  { id: 7326, rank: 326, title: "Tú Me Quemas", artist: "Gilberto Santa Rosa", genre: "Latin", year: 2002, album: "Un Caballero" },
  { id: 7327, rank: 327, title: "No Me Conozco", artist: "Marc Anthony", genre: "Latin", year: 2013, album: "3.0" },
  { id: 7328, rank: 328, title: "Preciosa", artist: "Marc Anthony", genre: "Latin", year: 1999, album: "Todo a Su Tiempo" },
  { id: 7329, rank: 329, title: "Querer Es Poder", artist: "Grupo Niche", genre: "Latin", year: 1996, album: "¿Por Qué Dios?" },
  { id: 7330, rank: 330, title: "Necio", artist: "Romeo Santos", genre: "Latin", year: 2007, album: "The Last" },
  { id: 7331, rank: 331, title: "You", artist: "Romeo Santos", genre: "Latin", year: 2011, album: "Fórmula Vol. 1" },
  { id: 7332, rank: 332, title: "Memorias", artist: "Prince Royce", genre: "Latin", year: 2014, album: "Soy el Mismo" },
  { id: 7333, rank: 333, title: "El Amor Que Perdimos", artist: "Prince Royce", genre: "Latin", year: 2010, album: "Prince Royce" },
  { id: 7334, rank: 334, title: "Obsesión", artist: "Aventura", genre: "Latin", year: 2002, album: "We Broke the Rules" },
  { id: 7335, rank: 335, title: "Por Un Segundo", artist: "Aventura", genre: "Latin", year: 2005, album: "God's Project" },
  { id: 7336, rank: 336, title: "Su Veneno", artist: "Aventura", genre: "Latin", year: 2009, album: "The Last" },
  { id: 7337, rank: 337, title: "Ella y Yo", artist: "Aventura", genre: "Latin", year: 2005, album: "God's Project" },
  { id: 7338, rank: 338, title: "Romeo Santos", artist: "Aventura", genre: "Latin", year: 2002, album: "We Broke the Rules" },
  { id: 7339, rank: 339, title: "Déjame Entrar", artist: "Carlos Vives", genre: "Latin", year: 2001, album: "Déjame Entrar" },
  { id: 7340, rank: 340, title: "El Mar de Sus Ojos", artist: "Carlos Vives", genre: "Latin", year: 1993, album: "Clásicos de la Provincia" },
  { id: 7341, rank: 341, title: "Como la Flor", artist: "Selena", genre: "Latin", year: 1992, album: "Entre a Mi Mundo" },
  { id: 7342, rank: 342, title: "Amor Prohibido", artist: "Selena", genre: "Latin", year: 1994, album: "Amor Prohibido" },
  { id: 7343, rank: 343, title: "Dreaming of You", artist: "Selena", genre: "Latin", year: 1995, album: "Dreaming of You" },
  { id: 7344, rank: 344, title: "Bidi Bidi Bom Bom", artist: "Selena", genre: "Latin", year: 1994, album: "Amor Prohibido" },
  { id: 7345, rank: 345, title: "Baila Esta Cumbia", artist: "Selena", genre: "Latin", year: 1990, album: "Ven Conmigo" },
  { id: 7346, rank: 346, title: "No Me Queda Más", artist: "Selena", genre: "Latin", year: 1995, album: "Amor Prohibido" },
  { id: 7347, rank: 347, title: "La Carcacha", artist: "Selena", genre: "Latin", year: 1992, album: "Entre a Mi Mundo" },
  { id: 7348, rank: 348, title: "Vaina Loca", artist: "Ozuna", genre: "Latin", year: 2018, album: "Nibiru" },
  { id: 7349, rank: 349, title: "Quiero Más", artist: "Ozuna", genre: "Latin", year: 2018, album: "Nibiru" },
  { id: 7350, rank: 350, title: "La Difícil", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7351, rank: 351, title: "Andrea", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7352, rank: 352, title: "Moscow Mule", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7353, rank: 353, title: "Rojo", artist: "J Balvin", genre: "Latin", year: 2020, album: "Colores" },
  { id: 7354, rank: 354, title: "Verde", artist: "J Balvin", genre: "Latin", year: 2020, album: "Colores" },
  { id: 7355, rank: 355, title: "Azul", artist: "J Balvin", genre: "Latin", year: 2020, album: "Colores" },
  { id: 7356, rank: 356, title: "Amarillo", artist: "J Balvin", genre: "Latin", year: 2020, album: "Colores" },
  { id: 7357, rank: 357, title: "Chantaje", artist: "Maluma", genre: "Latin", year: 2016, album: "Single" },
  { id: 7358, rank: 358, title: "GPS", artist: "Maluma", genre: "Latin", year: 2018, album: "13Black" },
  { id: 7359, rank: 359, title: "Mala Mía", artist: "Maluma", genre: "Latin", year: 2018, album: "13Black" },
  { id: 7360, rank: 360, title: "200 Copas", artist: "Karol G", genre: "Latin", year: 2022, album: "Mañana Será Bonito" },
  { id: 7361, rank: 361, title: "Gatúbela", artist: "Karol G", genre: "Latin", year: 2019, album: "KG0516" },
  { id: 7362, rank: 362, title: "KESI", artist: "Camilo", genre: "Latin", year: 2021, album: "Single" },
  { id: 7363, rank: 363, title: "Favorito", artist: "Camilo", genre: "Latin", year: 2020, album: "Por Primera Vez" },
  { id: 7364, rank: 364, title: "TKN", artist: "Rosalía", genre: "Latin", year: 2020, album: "Single" },
  { id: 7365, rank: 365, title: "Lo Vas a Olvidar", artist: "Rosalía", genre: "Latin", year: 2021, album: "Single" },
  { id: 7366, rank: 366, title: "Ella Me Levantó", artist: "Daddy Yankee", genre: "Latin", year: 2008, album: "Talento de Barrio" },
  { id: 7367, rank: 367, title: "Que Tengo que Hacer", artist: "Daddy Yankee", genre: "Latin", year: 2006, album: "Barrio Fino en Directo" },
  { id: 7368, rank: 368, title: "King Daddy", artist: "Daddy Yankee", genre: "Latin", year: 2012, album: "Prestige" },
  { id: 7369, rank: 369, title: "Ella y Yo", artist: "Don Omar", genre: "Latin", year: 2005, album: "The Last Don" },
  { id: 7370, rank: 370, title: "Hasta Abajo", artist: "Don Omar", genre: "Latin", year: 2009, album: "iDon" },
  { id: 7371, rank: 371, title: "Noche de Sexo", artist: "Wisin & Yandel", genre: "Latin", year: 2008, album: "Los Extraterrestres" },
  { id: 7372, rank: 372, title: "Algo Me Gusta de Ti", artist: "Wisin & Yandel", genre: "Latin", year: 2011, album: "Los Líderes" },
  { id: 7373, rank: 373, title: "Secreto", artist: "Anuel AA", genre: "Latin", year: 2019, album: "Emmanuel" },
  { id: 7374, rank: 374, title: "Sola", artist: "Anuel AA", genre: "Latin", year: 2018, album: "Real Hasta La Muerte" },
  { id: 7375, rank: 375, title: "Fenomenal", artist: "Nicky Jam", genre: "Latin", year: 2017, album: "Fenomenal" },
  { id: 7376, rank: 376, title: "Si Tu No Estas", artist: "Nicky Jam", genre: "Latin", year: 2004, album: "El Prodigy" },
  { id: 7377, rank: 377, title: "No Me Doy por Vencido", artist: "Luis Fonsi", genre: "Latin", year: 2008, album: "Nuestro Amor Eterno" },
  { id: 7378, rank: 378, title: "Llegaste Tú", artist: "Luis Fonsi", genre: "Latin", year: 2011, album: "Tierra Firme" },
  { id: 7379, rank: 379, title: "Words Get in the Way", artist: "Gloria Estefan", genre: "Latin", year: 1986, album: "Primitive Love" },
  { id: 7380, rank: 380, title: "1-2-3", artist: "Gloria Estefan", genre: "Latin", year: 1988, album: "Let It Loose" },
  { id: 7381, rank: 381, title: "Tradicion", artist: "Gloria Estefan", genre: "Latin", year: 1993, album: "Mi Tierra" },
  { id: 7382, rank: 382, title: "Rosalía", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Bachata Rosa" },
  { id: 7383, rank: 383, title: "El Costo de la Vida", artist: "Juan Luis Guerra", genre: "Latin", year: 1992, album: "Areíto" },
  { id: 7384, rank: 384, title: "Para Ti", artist: "Juan Luis Guerra", genre: "Latin", year: 2010, album: "A Son de Guerra" },
  { id: 7385, rank: 385, title: "Amor de los Dos", artist: "Vicente Fernández", genre: "Latin", year: 1972, album: "Volver Volver" },
  { id: 7386, rank: 386, title: "Por Tu Maldito Amor", artist: "Vicente Fernández", genre: "Latin", year: 1988, album: "Mujeres Divinas" },
  { id: 7387, rank: 387, title: "Siempre en Mi Mente", artist: "Juan Gabriel", genre: "Latin", year: 1982, album: "Recuerdos" },
  { id: 7388, rank: 388, title: "No Tengo Dinero", artist: "Juan Gabriel", genre: "Latin", year: 1971, album: "El Alma Joven" },
  { id: 7389, rank: 389, title: "Te lo Pido Por Favor", artist: "Juan Gabriel", genre: "Latin", year: 1992, album: "Pensamientos" },
  { id: 7390, rank: 390, title: "Payaso", artist: "José José", genre: "Latin", year: 1979, album: "Romántico" },
  { id: 7391, rank: 391, title: "Si Me Dejas Ahora", artist: "José José", genre: "Latin", year: 1977, album: "Secretos" },
  { id: 7392, rank: 392, title: "Como Quien Pierde una Estrella", artist: "Alejandro Fernández", genre: "Latin", year: 2003, album: "Dos Mundos" },
  { id: 7393, rank: 393, title: "Si Tú Supieras", artist: "Alejandro Fernández", genre: "Latin", year: 1993, album: "Alejandro Fernández" },
  { id: 7394, rank: 394, title: "Mátenme Porque Me Muero", artist: "Alejandro Fernández", genre: "Latin", year: 1995, album: "Me Estoy Enamorando" },
  { id: 7395, rank: 395, title: "Bon, Bon", artist: "Pitbull", genre: "Latin", year: 2011, album: "Planet Pit" },
  { id: 7396, rank: 396, title: "Back in Time", artist: "Pitbull", genre: "Latin", year: 2012, album: "Men in Black: The Album" },
  { id: 7397, rank: 397, title: "Wild Wild Love", artist: "Pitbull", genre: "Latin", year: 2014, album: "Meltdown" },
  { id: 7398, rank: 398, title: "Culpa al Corazón", artist: "Prince Royce", genre: "Latin", year: 2015, album: "Double Vision" },
  { id: 7399, rank: 399, title: "Soy el Mismo", artist: "Prince Royce", genre: "Latin", year: 2013, album: "Soy el Mismo" },
  { id: 7400, rank: 400, title: "Hilito", artist: "Romeo Santos", genre: "Latin", year: 2007, album: "The Last" },
  { id: 7401, rank: 401, title: "Llevame Contigo", artist: "Romeo Santos", genre: "Latin", year: 2014, album: "Fórmula Vol. 2" },
  { id: 7402, rank: 402, title: "Dile al Amor", artist: "Aventura", genre: "Latin", year: 2009, album: "The Last" },
  { id: 7403, rank: 403, title: "Cuando Volverás", artist: "Aventura", genre: "Latin", year: 2005, album: "God's Project" },
  { id: 7404, rank: 404, title: "Missing My Baby", artist: "Selena", genre: "Latin", year: 1992, album: "Entre a Mi Mundo" },
  { id: 7405, rank: 405, title: "Cuando Nos Volvamos a Ver", artist: "Carlos Vives", genre: "Latin", year: 2010, album: "Corazón Profundo" },
  { id: 7406, rank: 406, title: "El Alegre", artist: "Grupo Niche", genre: "Latin", year: 1982, album: "Al Pasito" },
  { id: 7407, rank: 407, title: "Comedia", artist: "Hector Lavoe", genre: "Latin", year: 1975, album: "La Voz" },
  { id: 7408, rank: 408, title: "Río Ancho", artist: "Paco de Lucía", genre: "Latin", year: 1972, album: "Fuente y Caudal" },
  { id: 7409, rank: 409, title: "Volando Voy", artist: "Camarón de la Isla", genre: "Latin", year: 1979, album: "La Leyenda del Tiempo" },
  { id: 7410, rank: 410, title: "Vivir sin Ella", artist: "Gilberto Santa Rosa", genre: "Latin", year: 1990, album: "Solo" },
  { id: 7411, rank: 411, title: "Imposible Amor", artist: "Frankie Ruiz", genre: "Latin", year: 1987, album: "La Cura" },
  { id: 7412, rank: 412, title: "Winning", artist: "Carlos Santana", genre: "Latin", year: 1981, album: "Zebop!" },
  { id: 7413, rank: 413, title: "She's Not There", artist: "Carlos Santana", genre: "Latin", year: 1977, album: "Moonflower" },
  { id: 7414, rank: 414, title: "Zoom", artist: "Soda Stereo", genre: "Latin", year: 1992, album: "Dynamo" },
  { id: 7415, rank: 415, title: "Signos", artist: "Soda Stereo", genre: "Latin", year: 1986, album: "Signos" },
  { id: 7416, rank: 416, title: "Un Millón de Años Luz", artist: "Soda Stereo", genre: "Latin", year: 1982, album: "Soda Stereo" },
  { id: 7417, rank: 417, title: "Gitana", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 1987, album: "Bares y Fondas" },
  { id: 7418, rank: 418, title: "Amame", artist: "Juanes", genre: "Latin", year: 2003, album: "Mi Sangre" },
  { id: 7419, rank: 419, title: "Minas Piedras", artist: "Juanes", genre: "Latin", year: 2007, album: "La Vida... Es un Ratico" },
  { id: 7420, rank: 420, title: "Volver a Comenzar", artist: "Café Tacvba", genre: "Latin", year: 2003, album: "Cuatro Caminos" },
  { id: 7421, rank: 421, title: "Huele a Traición", artist: "Maná", genre: "Latin", year: 2015, album: "Cama Incendiada" },
  { id: 7422, rank: 422, title: "Amor es Combate", artist: "Maná", genre: "Latin", year: 2006, album: "Amar es Combatir" },
  { id: 7423, rank: 423, title: "Manda una Señal", artist: "Maná", genre: "Latin", year: 2010, album: "Drama y Luz" },
  { id: 7424, rank: 424, title: "Do You Know? (The Ping Pong Song)", artist: "Enrique Iglesias", genre: "Latin", year: 2007, album: "Insomniac" },
  { id: 7425, rank: 425, title: "Tal Vez", artist: "Ricky Martin", genre: "Latin", year: 2003, album: "Almas del Silencio" },
  { id: 7426, rank: 426, title: "Tu Recuerdo", artist: "Ricky Martin", genre: "Latin", year: 2003, album: "Almas del Silencio" },
  { id: 7427, rank: 427, title: "Jaleo", artist: "Ricky Martin", genre: "Latin", year: 1994, album: "A Medio Vivir" },
  { id: 7428, rank: 428, title: "Fuego de Noche Nieve de Día", artist: "Ricky Martin", genre: "Latin", year: 2003, album: "Almas del Silencio" },
  { id: 7429, rank: 429, title: "El Apagón", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7430, rank: 430, title: "Un Verano Sin Ti", artist: "Bad Bunny", genre: "Latin", year: 2022, album: "Un Verano Sin Ti" },
  { id: 7431, rank: 431, title: "Party", artist: "Bad Bunny", genre: "Latin", year: 2021, album: "El Último Tour Del Mundo" },
  { id: 7432, rank: 432, title: "La Noche de Anoche", artist: "Bad Bunny", genre: "Latin", year: 2021, album: "El Último Tour Del Mundo" },
  { id: 7433, rank: 433, title: "Tranquila", artist: "J Balvin", genre: "Latin", year: 2014, album: "La Familia" },
  { id: 7434, rank: 434, title: "6 AM", artist: "J Balvin", genre: "Latin", year: 2014, album: "La Familia" },
  { id: 7435, rank: 435, title: "Ay Vamos", artist: "J Balvin", genre: "Latin", year: 2014, album: "La Familia" },
  { id: 7436, rank: 436, title: "Síguelo Bailando", artist: "Ozuna", genre: "Latin", year: 2016, album: "Odisea" },
  { id: 7437, rank: 437, title: "No Quiero Amor", artist: "Ozuna", genre: "Latin", year: 2018, album: "Nibiru" },
  { id: 7438, rank: 438, title: "Pose", artist: "Daddy Yankee", genre: "Latin", year: 2012, album: "Prestige" },
  { id: 7439, rank: 439, title: "Lovumba", artist: "Daddy Yankee", genre: "Latin", year: 2012, album: "Prestige" },
  { id: 7440, rank: 440, title: "Reí Lo Suficiente", artist: "Don Omar", genre: "Latin", year: 2007, album: "King of Kings" },
  { id: 7441, rank: 441, title: "Sin Contrato", artist: "Maluma", genre: "Latin", year: 2015, album: "Pretty Boy Dirty Boy" },
  { id: 7442, rank: 442, title: "Bésame", artist: "Maluma", genre: "Latin", year: 2016, album: "Pretty Boy Dirty Boy" },
  { id: 7443, rank: 443, title: "Punto G", artist: "Karol G", genre: "Latin", year: 2019, album: "KG0516" },
  { id: 7444, rank: 444, title: "Ocean", artist: "Karol G", genre: "Latin", year: 2019, album: "Ocean" },
  { id: 7445, rank: 445, title: "Millones", artist: "Camilo", genre: "Latin", year: 2021, album: "De Adentro Pa Afuera" },
  { id: 7446, rank: 446, title: "Índigo", artist: "Camilo", genre: "Latin", year: 2021, album: "De Adentro Pa Afuera" },
  { id: 7447, rank: 447, title: "Juro Que", artist: "Rosalía", genre: "Latin", year: 2017, album: "Los Ángeles" },
  { id: 7448, rank: 448, title: "La Noche de Anoche", artist: "Rosalía", genre: "Latin", year: 2021, album: "Single" },
  { id: 7449, rank: 449, title: "Garota de Ipanema", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1963, album: "Getz/Gilberto" },
  { id: 7450, rank: 450, title: "Água de Beber", artist: "Antônio Carlos Jobim", genre: "Latin", year: 1961, album: "The Composer Plays" },
  { id: 7451, rank: 451, title: "Você É Linda", artist: "Caetano Veloso", genre: "Latin", year: 1997, album: "Livro" },
  { id: 7452, rank: 452, title: "Expresso 2222", artist: "Gilberto Gil", genre: "Latin", year: 1972, album: "Expresso 2222" },
  { id: 7453, rank: 453, title: "Meditação", artist: "João Gilberto", genre: "Latin", year: 1963, album: "Getz/Gilberto" },
  { id: 7454, rank: 454, title: "Cai Dentro", artist: "Elis Regina", genre: "Latin", year: 1965, album: "Dois na Bossa" },
  { id: 7455, rank: 455, title: "Entregate", artist: "Luis Miguel", genre: "Latin", year: 1993, album: "Aries" },
  { id: 7456, rank: 456, title: "El Reloj", artist: "Luis Miguel", genre: "Latin", year: 1994, album: "Segundo Romance" },
  { id: 7457, rank: 457, title: "Amor", artist: "Trio Los Panchos", genre: "Latin", year: 1950, album: "Single" },
  { id: 7458, rank: 458, title: "Contigo Aprendí", artist: "Armando Manzanero", genre: "Latin", year: 1969, album: "Single" },
  { id: 7459, rank: 459, title: "El Último Trago", artist: "Chavela Vargas", genre: "Latin", year: 1975, album: "Single" },
  { id: 7460, rank: 460, title: "Entre Vareta y Canastero", artist: "Diego El Cigala", genre: "Latin", year: 2003, album: "Lágrimas Negras" },
  { id: 7461, rank: 461, title: "Lamentaciones de Semana Santa", artist: "Enrique Morente", genre: "Latin", year: 1971, album: "Cante Flamenco" },
  { id: 7462, rank: 462, title: "Se Me Enamora el Alma", artist: "Lola Flores", genre: "Latin", year: 1963, album: "Single" },
  { id: 7463, rank: 463, title: "Convite", artist: "Paco de Lucía", genre: "Latin", year: 1976, album: "Almoraima" },
  { id: 7464, rank: 464, title: "Tangos de Triana", artist: "Camarón de la Isla", genre: "Latin", year: 1969, album: "Al Verte las Flores Lloran" },
  { id: 7465, rank: 465, title: "El Africano", artist: "Wilfrido Vargas", genre: "Latin", year: 1984, album: "Single" },
  { id: 7466, rank: 466, title: "Abusadora", artist: "Wilfrido Vargas", genre: "Latin", year: 1984, album: "Single" },
  { id: 7467, rank: 467, title: "La Muchacha", artist: "Johnny Ventura", genre: "Latin", year: 1966, album: "Single" },
  { id: 7468, rank: 468, title: "Patacon Pisao", artist: "Johnny Ventura", genre: "Latin", year: 1967, album: "Single" },
  { id: 7469, rank: 469, title: "El Padre Antonio y el Monaguillo Andrés", artist: "Rubén Blades", genre: "Latin", year: 1984, album: "Buscando América" },
  { id: 7470, rank: 470, title: "Timbalero", artist: "Willie Colón", genre: "Latin", year: 1971, album: "La Gran Fuga" },
  { id: 7471, rank: 471, title: "Babarabatiri", artist: "Tito Puente", genre: "Latin", year: 1963, album: "El Rey Bravo" },
  { id: 7472, rank: 472, title: "Quiero Ser", artist: "Frankie Ruiz", genre: "Latin", year: 1989, album: "Mas Grande Que Nunca" },
  { id: 7473, rank: 473, title: "Si Te Vas a Ir", artist: "Gilberto Santa Rosa", genre: "Latin", year: 1995, album: "Expresión" },
  { id: 7474, rank: 474, title: "Mi Negra No Quiere Na", artist: "Grupo Niche", genre: "Latin", year: 1985, album: "Nueva Ola" },
  { id: 7475, rank: 475, title: "Calle Luna Calle Sol", artist: "Hector Lavoe", genre: "Latin", year: 1975, album: "La Voz" },
  { id: 7476, rank: 476, title: "Yo Viviré", artist: "Celia Cruz", genre: "Latin", year: 2000, album: "Siempre Viviré" },
  { id: 7477, rank: 477, title: "Amar Sin Mentiras", artist: "Marc Anthony", genre: "Latin", year: 2004, album: "Amar Sin Mentiras" },
  { id: 7478, rank: 478, title: "I Want to Spend My Lifetime Loving You", artist: "Marc Anthony", genre: "Latin", year: 1998, album: "The Mask of Zorro" },
  { id: 7479, rank: 479, title: "Por un Segundo", artist: "Aventura", genre: "Latin", year: 2006, album: "God's Project" },
  { id: 7480, rank: 480, title: "All Aboard", artist: "Romeo Santos", genre: "Latin", year: 2017, album: "Golden" },
  { id: 7481, rank: 481, title: "Ganas Locas", artist: "Prince Royce", genre: "Latin", year: 2016, album: "Double Vision" },
  { id: 7482, rank: 482, title: "Guavaberry", artist: "Juan Luis Guerra", genre: "Latin", year: 1990, album: "Ojala Que Llueva Café" },
  { id: 7483, rank: 483, title: "La Llave de Mi Corazón", artist: "Juan Luis Guerra", genre: "Latin", year: 2007, album: "La Llave de Mi Corazón" },
  { id: 7484, rank: 484, title: "Tengo Fe", artist: "Carlos Vives", genre: "Latin", year: 2015, album: "Más + Corazón Profundo" },
  { id: 7485, rank: 485, title: "Fotos y Recuerdos", artist: "Selena", genre: "Latin", year: 1995, album: "Dreaming of You" },
  { id: 7486, rank: 486, title: "Corazón Espinado", artist: "Carlos Santana", genre: "Latin", year: 1999, album: "Supernatural" },
  { id: 7487, rank: 487, title: "Put Your Lights On", artist: "Carlos Santana", genre: "Latin", year: 1999, album: "Supernatural" },
  { id: 7488, rank: 488, title: "Hola", artist: "Los Fabulosos Cadillacs", genre: "Latin", year: 2008, album: "La Luz del Ritmo" },
  { id: 7489, rank: 489, title: "Es por Ti", artist: "Juanes", genre: "Latin", year: 2006, album: "La Vida... Es un Ratico" },
  { id: 7490, rank: 490, title: "Fuego", artist: "Juanes", genre: "Latin", year: 2000, album: "Fíjate Bien" },
  { id: 7491, rank: 491, title: "7/8", artist: "Soda Stereo", genre: "Latin", year: 1992, album: "Dynamo" },
  { id: 7492, rank: 492, title: "Texturas", artist: "Soda Stereo", genre: "Latin", year: 1990, album: "Canción Animal" },
  { id: 7493, rank: 493, title: "La Muerte Chiquita", artist: "Café Tacvba", genre: "Latin", year: 1994, album: "Re" },
  { id: 7494, rank: 494, title: "Eres Mi Religión", artist: "Maná", genre: "Latin", year: 2015, album: "Cama Incendiada" },
  { id: 7495, rank: 495, title: "Tocarte Tequila", artist: "Maná", genre: "Latin", year: 2006, album: "Amar es Combatir" },
  { id: 7496, rank: 496, title: "I Like How It Feels", artist: "Enrique Iglesias", genre: "Latin", year: 2011, album: "Euphoria" },
  { id: 7497, rank: 497, title: "Nada es Imposible", artist: "Ricky Martin", genre: "Latin", year: 2003, album: "Almas del Silencio" },
  { id: 7498, rank: 498, title: "Oye", artist: "Gloria Estefan", genre: "Latin", year: 1998, album: "gloria!" },
  { id: 7499, rank: 499, title: "I Know You Want Me", artist: "Pitbull", genre: "Latin", year: 2009, album: "Rebelution" },
  { id: 7500, rank: 500, title: "Hotel Room Service", artist: "Pitbull", genre: "Latin", year: 2009, album: "Rebelution" }
];
