const SONGS_ROCK = [
  { id: 1, rank: 1, title: "Bohemian Rhapsody", artist: "Queen", genre: "Rock", year: 1975, album: "A Night at the Opera" },
  { id: 2, rank: 2, title: "Stairway to Heaven", artist: "Led Zeppelin", genre: "Rock", year: 1971, album: "Led Zeppelin IV" },
  { id: 3, rank: 3, title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 4, rank: 4, title: "Hotel California", artist: "Eagles", genre: "Rock", year: 1977, album: "Hotel California" },
  { id: 5, rank: 5, title: "Back in Black", artist: "AC/DC", genre: "Rock", year: 1980, album: "Back in Black" },
  { id: 6, rank: 6, title: "Whole Lotta Love", artist: "Led Zeppelin", genre: "Rock", year: 1969, album: "Led Zeppelin II" },
  { id: 7, rank: 7, title: "Purple Haze", artist: "Jimi Hendrix", genre: "Rock", year: 1967, album: "Are You Experienced" },
  { id: 8, rank: 8, title: "Comfortably Numb", artist: "Pink Floyd", genre: "Rock", year: 1979, album: "The Wall" },
  { id: 9, rank: 9, title: "Welcome to the Jungle", artist: "Guns N' Roses", genre: "Rock", year: 1987, album: "Appetite for Destruction" },
  { id: 10, rank: 10, title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "Rock", year: 1987, album: "Appetite for Destruction" },
  { id: 11, rank: 11, title: "Satisfaction (I Can't Get No)", artist: "The Rolling Stones", genre: "Rock", year: 1965, album: "Out of Our Heads" },
  { id: 12, rank: 12, title: "Johnny B. Goode", artist: "Chuck Berry", genre: "Rock", year: 1958, album: "Single" },
  { id: 13, rank: 13, title: "Hey Jude", artist: "The Beatles", genre: "Rock", year: 1968, album: "Single" },
  { id: 14, rank: 14, title: "Come as You Are", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 15, rank: 15, title: "Dream On", artist: "Aerosmith", genre: "Rock", year: 1973, album: "Aerosmith" },
  { id: 16, rank: 16, title: "Paranoid", artist: "Black Sabbath", genre: "Rock", year: 1970, album: "Paranoid" },
  { id: 17, rank: 17, title: "Wish You Were Here", artist: "Pink Floyd", genre: "Rock", year: 1975, album: "Wish You Were Here" },
  { id: 18, rank: 18, title: "Born to Run", artist: "Bruce Springsteen", genre: "Rock", year: 1975, album: "Born to Run" },
  { id: 19, rank: 19, title: "Highway to Hell", artist: "AC/DC", genre: "Rock", year: 1979, album: "Highway to Hell" },
  { id: 20, rank: 20, title: "Paint It Black", artist: "The Rolling Stones", genre: "Rock", year: 1966, album: "Aftermath" },
  { id: 21, rank: 21, title: "Smoke on the Water", artist: "Deep Purple", genre: "Rock", year: 1972, album: "Machine Head" },
  { id: 22, rank: 22, title: "Enter Sandman", artist: "Metallica", genre: "Rock", year: 1991, album: "Metallica" },
  { id: 23, rank: 23, title: "Under the Bridge", artist: "Red Hot Chili Peppers", genre: "Rock", year: 1992, album: "Blood Sugar Sex Magik" },
  { id: 24, rank: 24, title: "Everlong", artist: "Foo Fighters", genre: "Rock", year: 1997, album: "The Colour and the Shape" },
  { id: 25, rank: 25, title: "Black", artist: "Pearl Jam", genre: "Rock", year: 1991, album: "Ten" },
  { id: 26, rank: 26, title: "One", artist: "Metallica", genre: "Rock", year: 1988, album: "...And Justice for All" },
  { id: 27, rank: 27, title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "Rock", year: 1986, album: "Slippery When Wet" },
  { id: 28, rank: 28, title: "Roxanne", artist: "The Police", genre: "Rock", year: 1978, album: "Outlandos d'Amour" },
  { id: 29, rank: 29, title: "Mr. Brightside", artist: "The Killers", genre: "Rock", year: 2003, album: "Hot Fuss" },
  { id: 30, rank: 30, title: "Seven Nation Army", artist: "The White Stripes", genre: "Rock", year: 2003, album: "Elephant" },
  { id: 31, rank: 31, title: "In Bloom", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 32, rank: 32, title: "Creep", artist: "Radiohead", genre: "Rock", year: 1992, album: "Pablo Honey" },
  { id: 33, rank: 33, title: "Wonderwall", artist: "Oasis", genre: "Rock", year: 1995, album: "(What's the Story) Morning Glory?" },
  { id: 34, rank: 34, title: "Yellow", artist: "Coldplay", genre: "Rock", year: 2000, album: "Parachutes" },
  { id: 35, rank: 35, title: "Basket Case", artist: "Green Day", genre: "Rock", year: 1994, album: "Dookie" },
  { id: 36, rank: 36, title: "Killing Me Softly", artist: "The Who", genre: "Rock", year: 1973, album: "Quadrophenia" },
  { id: 37, rank: 37, title: "My Generation", artist: "The Who", genre: "Rock", year: 1965, album: "My Generation" },
  { id: 38, rank: 38, title: "Pinball Wizard", artist: "The Who", genre: "Rock", year: 1969, album: "Tommy" },
  { id: 39, rank: 39, title: "Baba O'Riley", artist: "The Who", genre: "Rock", year: 1971, album: "Who's Next" },
  { id: 40, rank: 40, title: "Won't Get Fooled Again", artist: "The Who", genre: "Rock", year: 1971, album: "Who's Next" },
  { id: 41, rank: 41, title: "Sultans of Swing", artist: "Dire Straits", genre: "Rock", year: 1978, album: "Dire Straits" },
  { id: 42, rank: 42, title: "Money for Nothing", artist: "Dire Straits", genre: "Rock", year: 1985, album: "Brothers in Arms" },
  { id: 43, rank: 43, title: "Layla", artist: "Derek and the Dominos", genre: "Rock", year: 1970, album: "Layla and Other Assorted Love Songs" },
  { id: 44, rank: 44, title: "Cocaine", artist: "Eric Clapton", genre: "Rock", year: 1977, album: "Slowhand" },
  { id: 45, rank: 45, title: "Sunshine of Your Love", artist: "Cream", genre: "Rock", year: 1967, album: "Disraeli Gears" },
  { id: 46, rank: 46, title: "White Room", artist: "Cream", genre: "Rock", year: 1968, album: "Wheels of Fire" },
  { id: 47, rank: 47, title: "All Along the Watchtower", artist: "Jimi Hendrix", genre: "Rock", year: 1968, album: "Electric Ladyland" },
  { id: 48, rank: 48, title: "Foxy Lady", artist: "Jimi Hendrix", genre: "Rock", year: 1967, album: "Are You Experienced" },
  { id: 49, rank: 49, title: "Black Dog", artist: "Led Zeppelin", genre: "Rock", year: 1971, album: "Led Zeppelin IV" },
  { id: 50, rank: 50, title: "Kashmir", artist: "Led Zeppelin", genre: "Rock", year: 1975, album: "Physical Graffiti" },
  { id: 51, rank: 51, title: "Rock and Roll", artist: "Led Zeppelin", genre: "Rock", year: 1971, album: "Led Zeppelin IV" },
  { id: 52, rank: 52, title: "Immigrant Song", artist: "Led Zeppelin", genre: "Rock", year: 1970, album: "Led Zeppelin III" },
  { id: 53, rank: 53, title: "Good Times Bad Times", artist: "Led Zeppelin", genre: "Rock", year: 1969, album: "Led Zeppelin" },
  { id: 54, rank: 54, title: "Ramble On", artist: "Led Zeppelin", genre: "Rock", year: 1969, album: "Led Zeppelin II" },
  { id: 55, rank: 55, title: "Since I've Been Loving You", artist: "Led Zeppelin", genre: "Rock", year: 1970, album: "Led Zeppelin III" },
  { id: 56, rank: 56, title: "The Ocean", artist: "Led Zeppelin", genre: "Rock", year: 1973, album: "Houses of the Holy" },
  { id: 57, rank: 57, title: "Heartbreaker", artist: "Led Zeppelin", genre: "Rock", year: 1969, album: "Led Zeppelin II" },
  { id: 58, rank: 58, title: "Communication Breakdown", artist: "Led Zeppelin", genre: "Rock", year: 1969, album: "Led Zeppelin" },
  { id: 59, rank: 59, title: "Rock You Like a Hurricane", artist: "Scorpions", genre: "Rock", year: 1984, album: "Love at First Sting" },
  { id: 60, rank: 60, title: "Wind of Change", artist: "Scorpions", genre: "Rock", year: 1990, album: "Crazy World" },
  { id: 61, rank: 61, title: "Don't Stop Believin'", artist: "Journey", genre: "Rock", year: 1981, album: "Escape" },
  { id: 62, rank: 62, title: "Separate Ways", artist: "Journey", genre: "Rock", year: 1983, album: "Frontiers" },
  { id: 63, rank: 63, title: "Open Arms", artist: "Journey", genre: "Rock", year: 1981, album: "Escape" },
  { id: 64, rank: 64, title: "More Than a Feeling", artist: "Boston", genre: "Rock", year: 1976, album: "Boston" },
  { id: 65, rank: 65, title: "Long Time", artist: "Boston", genre: "Rock", year: 1976, album: "Boston" },
  { id: 66, rank: 66, title: "Foreplay/Long Time", artist: "Boston", genre: "Rock", year: 1976, album: "Boston" },
  { id: 67, rank: 67, title: "Pour Some Sugar on Me", artist: "Def Leppard", genre: "Rock", year: 1987, album: "Hysteria" },
  { id: 68, rank: 68, title: "Love Bites", artist: "Def Leppard", genre: "Rock", year: 1987, album: "Hysteria" },
  { id: 69, rank: 69, title: "Rock of Ages", artist: "Def Leppard", genre: "Rock", year: 1983, album: "Pyromania" },
  { id: 70, rank: 70, title: "Photograph", artist: "Def Leppard", genre: "Rock", year: 1983, album: "Pyromania" },
  { id: 71, rank: 71, title: "Jump", artist: "Van Halen", genre: "Rock", year: 1984, album: "1984" },
  { id: 72, rank: 72, title: "Eruption", artist: "Van Halen", genre: "Rock", year: 1978, album: "Van Halen" },
  { id: 73, rank: 73, title: "Hot for Teacher", artist: "Van Halen", genre: "Rock", year: 1984, album: "1984" },
  { id: 74, rank: 74, title: "Panama", artist: "Van Halen", genre: "Rock", year: 1984, album: "1984" },
  { id: 75, rank: 75, title: "Runnin' with the Devil", artist: "Van Halen", genre: "Rock", year: 1978, album: "Van Halen" },
  { id: 76, rank: 76, title: "Rock and Roll All Nite", artist: "Kiss", genre: "Rock", year: 1975, album: "Dressed to Kill" },
  { id: 77, rank: 77, title: "Detroit Rock City", artist: "Kiss", genre: "Rock", year: 1976, album: "Destroyer" },
  { id: 78, rank: 78, title: "I Was Made for Lovin' You", artist: "Kiss", genre: "Rock", year: 1979, album: "Dynasty" },
  { id: 79, rank: 79, title: "Shout at the Devil", artist: "Mötley Crüe", genre: "Rock", year: 1983, album: "Shout at the Devil" },
  { id: 80, rank: 80, title: "Girls, Girls, Girls", artist: "Mötley Crüe", genre: "Rock", year: 1987, album: "Girls, Girls, Girls" },
  { id: 81, rank: 81, title: "Dr. Feelgood", artist: "Mötley Crüe", genre: "Rock", year: 1989, album: "Dr. Feelgood" },
  { id: 82, rank: 82, title: "Kickstart My Heart", artist: "Mötley Crüe", genre: "Rock", year: 1989, album: "Dr. Feelgood" },
  { id: 83, rank: 83, title: "You Give Love a Bad Name", artist: "Bon Jovi", genre: "Rock", year: 1986, album: "Slippery When Wet" },
  { id: 84, rank: 84, title: "Bad Medicine", artist: "Bon Jovi", genre: "Rock", year: 1988, album: "New Jersey" },
  { id: 85, rank: 85, title: "Wanted Dead or Alive", artist: "Bon Jovi", genre: "Rock", year: 1986, album: "Slippery When Wet" },
  { id: 86, rank: 86, title: "It's My Life", artist: "Bon Jovi", genre: "Rock", year: 2000, album: "Crush" },
  { id: 87, rank: 87, title: "November Rain", artist: "Guns N' Roses", genre: "Rock", year: 1991, album: "Use Your Illusion I" },
  { id: 88, rank: 88, title: "Paradise City", artist: "Guns N' Roses", genre: "Rock", year: 1987, album: "Appetite for Destruction" },
  { id: 89, rank: 89, title: "Night Train", artist: "Guns N' Roses", genre: "Rock", year: 1987, album: "Appetite for Destruction" },
  { id: 90, rank: 90, title: "Mr. Brownstone", artist: "Guns N' Roses", genre: "Rock", year: 1987, album: "Appetite for Destruction" },
  { id: 91, rank: 91, title: "Patience", artist: "Guns N' Roses", genre: "Rock", year: 1989, album: "G N' R Lies" },
  { id: 92, rank: 92, title: "Civil War", artist: "Guns N' Roses", genre: "Rock", year: 1991, album: "Use Your Illusion II" },
  { id: 93, rank: 93, title: "Black Hole Sun", artist: "Soundgarden", genre: "Rock", year: 1994, album: "Superunknown" },
  { id: 94, rank: 94, title: "Spoonman", artist: "Soundgarden", genre: "Rock", year: 1994, album: "Superunknown" },
  { id: 95, rank: 95, title: "Burden in My Hand", artist: "Soundgarden", genre: "Rock", year: 1996, album: "Down on the Upside" },
  { id: 96, rank: 96, title: "Fell on Black Days", artist: "Soundgarden", genre: "Rock", year: 1994, album: "Superunknown" },
  { id: 97, rank: 97, title: "Jeremy", artist: "Pearl Jam", genre: "Rock", year: 1991, album: "Ten" },
  { id: 98, rank: 98, title: "Even Flow", artist: "Pearl Jam", genre: "Rock", year: 1991, album: "Ten" },
  { id: 99, rank: 99, title: "Alive", artist: "Pearl Jam", genre: "Rock", year: 1991, album: "Ten" },
  { id: 100, rank: 100, title: "Better Man", artist: "Pearl Jam", genre: "Rock", year: 1994, album: "Vitalogy" },
  { id: 101, rank: 101, title: "Last Kiss", artist: "Pearl Jam", genre: "Rock", year: 1999, album: "Single" },
  { id: 102, rank: 102, title: "Given to Fly", artist: "Pearl Jam", genre: "Rock", year: 1998, album: "Yield" },
  { id: 103, rank: 103, title: "Californication", artist: "Red Hot Chili Peppers", genre: "Rock", year: 1999, album: "Californication" },
  { id: 104, rank: 104, title: "Scar Tissue", artist: "Red Hot Chili Peppers", genre: "Rock", year: 1999, album: "Californication" },
  { id: 105, rank: 105, title: "Give It Away", artist: "Red Hot Chili Peppers", genre: "Rock", year: 1991, album: "Blood Sugar Sex Magik" },
  { id: 106, rank: 106, title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", genre: "Rock", year: 2006, album: "Stadium Arcadium" },
  { id: 107, rank: 107, title: "Dani California", artist: "Red Hot Chili Peppers", genre: "Rock", year: 2006, album: "Stadium Arcadium" },
  { id: 108, rank: 108, title: "By the Way", artist: "Red Hot Chili Peppers", genre: "Rock", year: 2002, album: "By the Way" },
  { id: 109, rank: 109, title: "The Best of You", artist: "Foo Fighters", genre: "Rock", year: 2005, album: "In Your Honor" },
  { id: 110, rank: 110, title: "Learn to Fly", artist: "Foo Fighters", genre: "Rock", year: 1999, album: "There Is Nothing Left to Lose" },
  { id: 111, rank: 111, title: "Best of You", artist: "Foo Fighters", genre: "Rock", year: 2005, album: "In Your Honor" },
  { id: 112, rank: 112, title: "All My Life", artist: "Foo Fighters", genre: "Rock", year: 2002, album: "One by One" },
  { id: 113, rank: 113, title: "Times Like These", artist: "Foo Fighters", genre: "Rock", year: 2003, album: "One by One" },
  { id: 114, rank: 114, title: "The Pretender", artist: "Foo Fighters", genre: "Rock", year: 2007, album: "Echoes, Silence, Patience & Grace" },
  { id: 115, rank: 115, title: "Walk", artist: "Foo Fighters", genre: "Rock", year: 2011, album: "Wasting Light" },
  { id: 116, rank: 116, title: "These Days", artist: "Foo Fighters", genre: "Rock", year: 2005, album: "In Your Honor" },
  { id: 117, rank: 117, title: "Sunday Bloody Sunday", artist: "U2", genre: "Rock", year: 1983, album: "War" },
  { id: 118, rank: 118, title: "With or Without You", artist: "U2", genre: "Rock", year: 1987, album: "The Joshua Tree" },
  { id: 119, rank: 119, title: "Where the Streets Have No Name", artist: "U2", genre: "Rock", year: 1987, album: "The Joshua Tree" },
  { id: 120, rank: 120, title: "One", artist: "U2", genre: "Rock", year: 1991, album: "Achtung Baby" },
  { id: 121, rank: 121, title: "I Still Haven't Found What I'm Looking For", artist: "U2", genre: "Rock", year: 1987, album: "The Joshua Tree" },
  { id: 122, rank: 122, title: "Beautiful Day", artist: "U2", genre: "Rock", year: 2000, album: "All That You Can't Leave Behind" },
  { id: 123, rank: 123, title: "Mysterious Ways", artist: "U2", genre: "Rock", year: 1991, album: "Achtung Baby" },
  { id: 124, rank: 124, title: "Vertigo", artist: "U2", genre: "Rock", year: 2004, album: "How to Dismantle an Atomic Bomb" },
  { id: 125, rank: 125, title: "Don't Look Back in Anger", artist: "Oasis", genre: "Rock", year: 1996, album: "(What's the Story) Morning Glory?" },
  { id: 126, rank: 126, title: "Champagne Supernova", artist: "Oasis", genre: "Rock", year: 1995, album: "(What's the Story) Morning Glory?" },
  { id: 127, rank: 127, title: "Live Forever", artist: "Oasis", genre: "Rock", year: 1994, album: "Definitely Maybe" },
  { id: 128, rank: 128, title: "Supersonic", artist: "Oasis", genre: "Rock", year: 1994, album: "Definitely Maybe" },
  { id: 129, rank: 129, title: "Cigarettes & Alcohol", artist: "Oasis", genre: "Rock", year: 1994, album: "Definitely Maybe" },
  { id: 130, rank: 130, title: "Some Might Say", artist: "Oasis", genre: "Rock", year: 1995, album: "(What's the Story) Morning Glory?" },
  { id: 131, rank: 131, title: "The Scientist", artist: "Coldplay", genre: "Rock", year: 2002, album: "A Rush of Blood to the Head" },
  { id: 132, rank: 132, title: "Clocks", artist: "Coldplay", genre: "Rock", year: 2002, album: "A Rush of Blood to the Head" },
  { id: 133, rank: 133, title: "Fix You", artist: "Coldplay", genre: "Rock", year: 2005, album: "X&Y" },
  { id: 134, rank: 134, title: "Speed of Sound", artist: "Coldplay", genre: "Rock", year: 2005, album: "X&Y" },
  { id: 135, rank: 135, title: "Viva la Vida", artist: "Coldplay", genre: "Rock", year: 2008, album: "Viva la Vida or Death and All His Friends" },
  { id: 136, rank: 136, title: "The Hardest Part", artist: "Coldplay", genre: "Rock", year: 2007, album: "X&Y" },
  { id: 137, rank: 137, title: "R U Mine?", artist: "Arctic Monkeys", genre: "Rock", year: 2013, album: "AM" },
  { id: 138, rank: 138, title: "Do I Wanna Know?", artist: "Arctic Monkeys", genre: "Rock", year: 2013, album: "AM" },
  { id: 139, rank: 139, title: "I Bet You Look Good on the Dancefloor", artist: "Arctic Monkeys", genre: "Rock", year: 2005, album: "Whatever People Say I Am, That's What I'm Not" },
  { id: 140, rank: 140, title: "Fluorescent Adolescent", artist: "Arctic Monkeys", genre: "Rock", year: 2011, album: "Suck It and See" },
  { id: 141, rank: 141, title: "505", artist: "Arctic Monkeys", genre: "Rock", year: 2006, album: "Whatever People Say I Am, That's What I'm Not" },
  { id: 142, rank: 142, title: "Why'd You Only Call Me When You're High?", artist: "Arctic Monkeys", genre: "Rock", year: 2013, album: "AM" },
  { id: 143, rank: 143, title: "Uprising", artist: "Muse", genre: "Rock", year: 2009, album: "The Resistance" },
  { id: 144, rank: 144, title: "Supermassive Black Hole", artist: "Muse", genre: "Rock", year: 2006, album: "Black Holes and Revelations" },
  { id: 145, rank: 145, title: "Knights of Cydonia", artist: "Muse", genre: "Rock", year: 2006, album: "Black Holes and Revelations" },
  { id: 146, rank: 146, title: "Starlight", artist: "Muse", genre: "Rock", year: 2006, album: "Black Holes and Revelations" },
  { id: 147, rank: 147, title: "Madness", artist: "Muse", genre: "Rock", year: 2012, album: "The 2nd Law" },
  { id: 148, rank: 148, title: "Resistance", artist: "Muse", genre: "Rock", year: 2009, album: "The Resistance" },
  { id: 149, rank: 149, title: "Time Is Running Out", artist: "Muse", genre: "Rock", year: 2003, album: "Absolution" },
  { id: 150, rank: 150, title: "In the Air Tonight", artist: "Phil Collins", genre: "Rock", year: 1981, album: "Face Value" },
  { id: 151, rank: 151, title: "The Show Must Go On", artist: "Queen", genre: "Rock", year: 1991, album: "Innuendo" },
  { id: 152, rank: 152, title: "We Will Rock You", artist: "Queen", genre: "Rock", year: 1977, album: "News of the World" },
  { id: 153, rank: 153, title: "We Are the Champions", artist: "Queen", genre: "Rock", year: 1977, album: "News of the World" },
  { id: 154, rank: 154, title: "Don't Stop Me Now", artist: "Queen", genre: "Rock", year: 1978, album: "Jazz" },
  { id: 155, rank: 155, title: "Somebody to Love", artist: "Queen", genre: "Rock", year: 1976, album: "A Day at the Races" },
  { id: 156, rank: 156, title: "Under Pressure", artist: "Queen", genre: "Rock", year: 1981, album: "Hot Space" },
  { id: 157, rank: 157, title: "Radio Ga Ga", artist: "Queen", genre: "Rock", year: 1984, album: "The Works" },
  { id: 158, rank: 158, title: "Killer Queen", artist: "Queen", genre: "Rock", year: 1974, album: "Sheer Heart Attack" },
  { id: 159, rank: 159, title: "Another One Bites the Dust", artist: "Queen", genre: "Rock", year: 1980, album: "The Game" },
  { id: 160, rank: 160, title: "Innuendo", artist: "Queen", genre: "Rock", year: 1991, album: "Innuendo" },
  { id: 161, rank: 161, title: "Crazy Little Thing Called Love", artist: "Queen", genre: "Rock", year: 1979, album: "The Game" },
  { id: 162, rank: 162, title: "Tie Your Mother Down", artist: "Queen", genre: "Rock", year: 1977, album: "A Day at the Races" },
  { id: 163, rank: 163, title: "Stone Cold Crazy", artist: "Queen", genre: "Rock", year: 1974, album: "Sheer Heart Attack" },
  { id: 164, rank: 164, title: "Let There Be Rock", artist: "AC/DC", genre: "Rock", year: 1977, album: "Let There Be Rock" },
  { id: 165, rank: 165, title: "Thunderstruck", artist: "AC/DC", genre: "Rock", year: 1990, album: "The Razors Edge" },
  { id: 166, rank: 166, title: "Shoot to Thrill", artist: "AC/DC", genre: "Rock", year: 1980, album: "Back in Black" },
  { id: 167, rank: 167, title: "You Shook Me All Night Long", artist: "AC/DC", genre: "Rock", year: 1980, album: "Back in Black" },
  { id: 168, rank: 168, title: "Hells Bells", artist: "AC/DC", genre: "Rock", year: 1980, album: "Back in Black" },
  { id: 169, rank: 169, title: "Whole Lotta Rosie", artist: "AC/DC", genre: "Rock", year: 1977, album: "Let There Be Rock" },
  { id: 170, rank: 170, title: "TNT", artist: "AC/DC", genre: "Rock", year: 1975, album: "T.N.T." },
  { id: 171, rank: 171, title: "Dirty Deeds Done Dirt Cheap", artist: "AC/DC", genre: "Rock", year: 1976, album: "Dirty Deeds Done Dirt Cheap" },
  { id: 172, rank: 172, title: "For Those About to Rock", artist: "AC/DC", genre: "Rock", year: 1981, album: "For Those About to Rock We Salute You" },
  { id: 173, rank: 173, title: "Highway Star", artist: "Deep Purple", genre: "Rock", year: 1972, album: "Machine Head" },
  { id: 174, rank: 174, title: "Child in Time", artist: "Deep Purple", genre: "Rock", year: 1970, album: "Deep Purple in Rock" },
  { id: 175, rank: 175, title: "Space Truckin'", artist: "Deep Purple", genre: "Rock", year: 1972, album: "Machine Head" },
  { id: 176, rank: 176, title: "Perfect Strangers", artist: "Deep Purple", genre: "Rock", year: 1984, album: "Perfect Strangers" },
  { id: 177, rank: 177, title: "Black Night", artist: "Deep Purple", genre: "Rock", year: 1970, album: "Single" },
  { id: 178, rank: 178, title: "Iron Man", artist: "Black Sabbath", genre: "Rock", year: 1970, album: "Paranoid" },
  { id: 179, rank: 179, title: "War Pigs", artist: "Black Sabbath", genre: "Rock", year: 1970, album: "Paranoid" },
  { id: 180, rank: 180, title: "Black Sabbath", artist: "Black Sabbath", genre: "Rock", year: 1970, album: "Black Sabbath" },
  { id: 181, rank: 181, title: "Sabbath Bloody Sabbath", artist: "Black Sabbath", genre: "Rock", year: 1973, album: "Sabbath Bloody Sabbath" },
  { id: 182, rank: 182, title: "Children of the Grave", artist: "Black Sabbath", genre: "Rock", year: 1971, album: "Master of Reality" },
  { id: 183, rank: 183, title: "Sweet Leaf", artist: "Black Sabbath", genre: "Rock", year: 1971, album: "Master of Reality" },
  { id: 184, rank: 184, title: "Numb", artist: "Linkin Park", genre: "Rock", year: 2003, album: "Meteora" },
  { id: 185, rank: 185, title: "In the End", artist: "Linkin Park", genre: "Rock", year: 2000, album: "Hybrid Theory" },
  { id: 186, rank: 186, title: "Crawling", artist: "Linkin Park", genre: "Rock", year: 2000, album: "Hybrid Theory" },
  { id: 187, rank: 187, title: "Breaking the Habit", artist: "Linkin Park", genre: "Rock", year: 2003, album: "Meteora" },
  { id: 188, rank: 188, title: "Faint", artist: "Linkin Park", genre: "Rock", year: 2003, album: "Meteora" },
  { id: 189, rank: 189, title: "Somewhere I Belong", artist: "Linkin Park", genre: "Rock", year: 2003, album: "Meteora" },
  { id: 190, rank: 190, title: "What I've Done", artist: "Linkin Park", genre: "Rock", year: 2007, album: "Minutes to Midnight" },
  { id: 191, rank: 191, title: "Losing My Religion", artist: "R.E.M.", genre: "Rock", year: 1991, album: "Out of Time" },
  { id: 192, rank: 192, title: "Everybody Hurts", artist: "R.E.M.", genre: "Rock", year: 1992, album: "Automatic for the People" },
  { id: 193, rank: 193, title: "Man on the Moon", artist: "R.E.M.", genre: "Rock", year: 1992, album: "Automatic for the People" },
  { id: 194, rank: 194, title: "The One I Love", artist: "R.E.M.", genre: "Rock", year: 1987, album: "Document" },
  { id: 195, rank: 195, title: "Shiny Happy People", artist: "R.E.M.", genre: "Rock", year: 1991, album: "Out of Time" },
  { id: 196, rank: 196, title: "Come Together", artist: "The Beatles", genre: "Rock", year: 1969, album: "Abbey Road" },
  { id: 197, rank: 197, title: "Let It Be", artist: "The Beatles", genre: "Rock", year: 1970, album: "Let It Be" },
  { id: 198, rank: 198, title: "A Day in the Life", artist: "The Beatles", genre: "Rock", year: 1967, album: "Sgt. Pepper's Lonely Hearts Club Band" },
  { id: 199, rank: 199, title: "Blackbird", artist: "The Beatles", genre: "Rock", year: 1968, album: "The White Album" },
  { id: 200, rank: 200, title: "Revolution", artist: "The Beatles", genre: "Rock", year: 1968, album: "The White Album" },
  { id: 201, rank: 201, title: "Something", artist: "The Beatles", genre: "Rock", year: 1969, album: "Abbey Road" },
  { id: 202, rank: 202, title: "Eleanor Rigby", artist: "The Beatles", genre: "Rock", year: 1966, album: "Revolver" },
  { id: 203, rank: 203, title: "Yesterday", artist: "The Beatles", genre: "Rock", year: 1965, album: "Help!" },
  { id: 204, rank: 204, title: "Help!", artist: "The Beatles", genre: "Rock", year: 1965, album: "Help!" },
  { id: 205, rank: 205, title: "Twist and Shout", artist: "The Beatles", genre: "Rock", year: 1963, album: "Please Please Me" },
  { id: 206, rank: 206, title: "Back in the USSR", artist: "The Beatles", genre: "Rock", year: 1968, album: "The White Album" },
  { id: 207, rank: 207, title: "Norwegian Wood", artist: "The Beatles", genre: "Rock", year: 1965, album: "Rubber Soul" },
  { id: 208, rank: 208, title: "Jumpin' Jack Flash", artist: "The Rolling Stones", genre: "Rock", year: 1968, album: "Single" },
  { id: 209, rank: 209, title: "Sympathy for the Devil", artist: "The Rolling Stones", genre: "Rock", year: 1968, album: "Beggars Banquet" },
  { id: 210, rank: 210, title: "Gimme Shelter", artist: "The Rolling Stones", genre: "Rock", year: 1969, album: "Let It Bleed" },
  { id: 211, rank: 211, title: "Wild Horses", artist: "The Rolling Stones", genre: "Rock", year: 1971, album: "Sticky Fingers" },
  { id: 212, rank: 212, title: "Start Me Up", artist: "The Rolling Stones", genre: "Rock", year: 1981, album: "Tattoo You" },
  { id: 213, rank: 213, title: "Honky Tonk Women", artist: "The Rolling Stones", genre: "Rock", year: 1969, album: "Single" },
  { id: 214, rank: 214, title: "Miss You", artist: "The Rolling Stones", genre: "Rock", year: 1978, album: "Some Girls" },
  { id: 215, rank: 215, title: "Brown Sugar", artist: "The Rolling Stones", genre: "Rock", year: 1971, album: "Sticky Fingers" },
  { id: 216, rank: 216, title: "Angie", artist: "The Rolling Stones", genre: "Rock", year: 1973, album: "Goats Head Soup" },
  { id: 217, rank: 217, title: "Rocks Off", artist: "The Rolling Stones", genre: "Rock", year: 1972, album: "Exile on Main St." },
  { id: 218, rank: 218, title: "Eye of the Tiger", artist: "Survivor", genre: "Rock", year: 1982, album: "Eye of the Tiger" },
  { id: 219, rank: 219, title: "The Final Countdown", artist: "Europe", genre: "Rock", year: 1986, album: "The Final Countdown" },
  { id: 220, rank: 220, title: "Shot Through the Heart", artist: "Bon Jovi", genre: "Rock", year: 1984, album: "Bon Jovi" },
  { id: 221, rank: 221, title: "Here I Go Again", artist: "Whitesnake", genre: "Rock", year: 1982, album: "Saints & Sinners" },
  { id: 222, rank: 222, title: "Still of the Night", artist: "Whitesnake", genre: "Rock", year: 1987, album: "Whitesnake" },
  { id: 223, rank: 223, title: "Is This Love", artist: "Whitesnake", genre: "Rock", year: 1987, album: "Whitesnake" },
  { id: 224, rank: 224, title: "Alone Again Naturally", artist: "Ozzy Osbourne", genre: "Rock", year: 1981, album: "Diary of a Madman" },
  { id: 225, rank: 225, title: "Crazy Train", artist: "Ozzy Osbourne", genre: "Rock", year: 1980, album: "Blizzard of Ozz" },
  { id: 226, rank: 226, title: "Mr. Crowley", artist: "Ozzy Osbourne", genre: "Rock", year: 1980, album: "Blizzard of Ozz" },
  { id: 227, rank: 227, title: "Mama, I'm Coming Home", artist: "Ozzy Osbourne", genre: "Rock", year: 1991, album: "No More Tears" },
  { id: 228, rank: 228, title: "No More Tears", artist: "Ozzy Osbourne", genre: "Rock", year: 1991, album: "No More Tears" },
  { id: 229, rank: 229, title: "Bullet with Butterfly Wings", artist: "Smashing Pumpkins", genre: "Rock", year: 1995, album: "Mellon Collie and the Infinite Sadness" },
  { id: 230, rank: 230, title: "Today", artist: "Smashing Pumpkins", genre: "Rock", year: 1993, album: "Siamese Dream" },
  { id: 231, rank: 231, title: "Zero", artist: "Smashing Pumpkins", genre: "Rock", year: 1995, album: "Mellon Collie and the Infinite Sadness" },
  { id: 232, rank: 232, title: "1979", artist: "Smashing Pumpkins", genre: "Rock", year: 1995, album: "Mellon Collie and the Infinite Sadness" },
  { id: 233, rank: 233, title: "Tonight, Tonight", artist: "Smashing Pumpkins", genre: "Rock", year: 1995, album: "Mellon Collie and the Infinite Sadness" },
  { id: 234, rank: 234, title: "Disarm", artist: "Smashing Pumpkins", genre: "Rock", year: 1993, album: "Siamese Dream" },
  { id: 235, rank: 235, title: "Cherub Rock", artist: "Smashing Pumpkins", genre: "Rock", year: 1993, album: "Siamese Dream" },
  { id: 236, rank: 236, title: "About a Girl", artist: "Nirvana", genre: "Rock", year: 1989, album: "Bleach" },
  { id: 237, rank: 237, title: "Heart-Shaped Box", artist: "Nirvana", genre: "Rock", year: 1993, album: "In Utero" },
  { id: 238, rank: 238, title: "All Apologies", artist: "Nirvana", genre: "Rock", year: 1993, album: "In Utero" },
  { id: 239, rank: 239, title: "Rape Me", artist: "Nirvana", genre: "Rock", year: 1993, album: "In Utero" },
  { id: 240, rank: 240, title: "Lithium", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 241, rank: 241, title: "Polly", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 242, rank: 242, title: "The Man Who Sold the World", artist: "Nirvana", genre: "Rock", year: 1993, album: "MTV Unplugged in New York" },
  { id: 243, rank: 243, title: "Territorial Pissings", artist: "Nirvana", genre: "Rock", year: 1991, album: "Nevermind" },
  { id: 244, rank: 244, title: "Teen Spirit (Acoustic)", artist: "Nirvana", genre: "Rock", year: 1993, album: "MTV Unplugged in New York" },
  { id: 245, rank: 245, title: "Jeremy (Live)", artist: "Pearl Jam", genre: "Rock", year: 1992, album: "MTV Unplugged" },
  { id: 246, rank: 246, title: "Daughter", artist: "Pearl Jam", genre: "Rock", year: 1993, album: "Vs." },
  { id: 247, rank: 247, title: "Dissident", artist: "Pearl Jam", genre: "Rock", year: 1994, album: "Vitalogy" },
  { id: 248, rank: 248, title: "Nothingman", artist: "Pearl Jam", genre: "Rock", year: 1994, album: "Vitalogy" },
  { id: 249, rank: 249, title: "Go", artist: "Pearl Jam", genre: "Rock", year: 1993, album: "Vs." },
  { id: 250, rank: 250, title: "Hunger Strike", artist: "Temple of the Dog", genre: "Rock", year: 1991, album: "Temple of the Dog" },
  { id: 251, rank: 251, title: "Say Hello 2 Heaven", artist: "Temple of the Dog", genre: "Rock", year: 1991, album: "Temple of the Dog" },
  { id: 252, rank: 252, title: "Man in the Box", artist: "Alice in Chains", genre: "Rock", year: 1990, album: "Facelift" },
  { id: 253, rank: 253, title: "Rooster", artist: "Alice in Chains", genre: "Rock", year: 1992, album: "Dirt" },
  { id: 254, rank: 254, title: "Would?", artist: "Alice in Chains", genre: "Rock", year: 1992, album: "Dirt" },
  { id: 255, rank: 255, title: "Down in a Hole", artist: "Alice in Chains", genre: "Rock", year: 1992, album: "Dirt" },
  { id: 256, rank: 256, title: "Them Bones", artist: "Alice in Chains", genre: "Rock", year: 1992, album: "Dirt" },
  { id: 257, rank: 257, title: "Angry Chair", artist: "Alice in Chains", genre: "Rock", year: 1992, album: "Dirt" },
  { id: 258, rank: 258, title: "No Excuses", artist: "Alice in Chains", genre: "Rock", year: 1994, album: "Jar of Flies" },
  { id: 259, rank: 259, title: "Nutshell", artist: "Alice in Chains", genre: "Rock", year: 1994, album: "Jar of Flies" },
  { id: 260, rank: 260, title: "Would (Unplugged)", artist: "Alice in Chains", genre: "Rock", year: 1996, album: "MTV Unplugged" },
  { id: 261, rank: 261, title: "Possum Kingdom", artist: "Toadies", genre: "Rock", year: 1994, album: "Rubberneck" },
  { id: 262, rank: 262, title: "Semi-Charmed Life", artist: "Third Eye Blind", genre: "Rock", year: 1997, album: "Third Eye Blind" },
  { id: 263, rank: 263, title: "Jumper", artist: "Third Eye Blind", genre: "Rock", year: 1997, album: "Third Eye Blind" },
  { id: 264, rank: 264, title: "Fly Away", artist: "Lenny Kravitz", genre: "Rock", year: 1998, album: "5" },
  { id: 265, rank: 265, title: "Are You Gonna Go My Way", artist: "Lenny Kravitz", genre: "Rock", year: 1993, album: "Are You Gonna Go My Way" },
  { id: 266, rank: 266, title: "Again", artist: "Lenny Kravitz", genre: "Rock", year: 2000, album: "Greatest Hits" },
  { id: 267, rank: 267, title: "Glycerine", artist: "Bush", genre: "Rock", year: 1994, album: "Sixteen Stone" },
  { id: 268, rank: 268, title: "Machinehead", artist: "Bush", genre: "Rock", year: 1994, album: "Sixteen Stone" },
  { id: 269, rank: 269, title: "Everything Zen", artist: "Bush", genre: "Rock", year: 1994, album: "Sixteen Stone" },
  { id: 270, rank: 270, title: "Vasoline", artist: "Stone Temple Pilots", genre: "Rock", year: 1994, album: "Purple" },
  { id: 271, rank: 271, title: "Plush", artist: "Stone Temple Pilots", genre: "Rock", year: 1992, album: "Core" },
  { id: 272, rank: 272, title: "Creep", artist: "Stone Temple Pilots", genre: "Rock", year: 1992, album: "Core" },
  { id: 273, rank: 273, title: "Wicked Garden", artist: "Stone Temple Pilots", genre: "Rock", year: 1992, album: "Core" },
  { id: 274, rank: 274, title: "Big Empty", artist: "Stone Temple Pilots", genre: "Rock", year: 1994, album: "Purple" },
  { id: 275, rank: 275, title: "Interstate Love Song", artist: "Stone Temple Pilots", genre: "Rock", year: 1994, album: "Purple" },
  { id: 276, rank: 276, title: "Running Down a Dream", artist: "Tom Petty", genre: "Rock", year: 1989, album: "Full Moon Fever" },
  { id: 277, rank: 277, title: "Free Fallin'", artist: "Tom Petty", genre: "Rock", year: 1989, album: "Full Moon Fever" },
  { id: 278, rank: 278, title: "American Girl", artist: "Tom Petty", genre: "Rock", year: 1976, album: "Tom Petty and the Heartbreakers" },
  { id: 279, rank: 279, title: "Refugee", artist: "Tom Petty", genre: "Rock", year: 1979, album: "Damn the Torpedoes" },
  { id: 280, rank: 280, title: "The Waiting", artist: "Tom Petty", genre: "Rock", year: 1981, album: "Hard Promises" },
  { id: 281, rank: 281, title: "Learning to Fly", artist: "Tom Petty", genre: "Rock", year: 1991, album: "Into the Great Wide Open" },
  { id: 282, rank: 282, title: "Boys of Summer", artist: "Don Henley", genre: "Rock", year: 1984, album: "Building the Perfect Beast" },
  { id: 283, rank: 283, title: "Hotel California (Live)", artist: "Eagles", genre: "Rock", year: 1994, album: "Hell Freezes Over" },
  { id: 284, rank: 284, title: "Life in the Fast Lane", artist: "Eagles", genre: "Rock", year: 1977, album: "Hotel California" },
  { id: 285, rank: 285, title: "Desperado", artist: "Eagles", genre: "Rock", year: 1973, album: "Desperado" },
  { id: 286, rank: 286, title: "One of These Nights", artist: "Eagles", genre: "Rock", year: 1975, album: "One of These Nights" },
  { id: 287, rank: 287, title: "Take It Easy", artist: "Eagles", genre: "Rock", year: 1972, album: "Eagles" },
  { id: 288, rank: 288, title: "Lyin' Eyes", artist: "Eagles", genre: "Rock", year: 1975, album: "One of These Nights" },
  { id: 289, rank: 289, title: "Already Gone", artist: "Eagles", genre: "Rock", year: 1974, album: "On the Border" },
  { id: 290, rank: 290, title: "The Long Run", artist: "Eagles", genre: "Rock", year: 1979, album: "The Long Run" },
  { id: 291, rank: 291, title: "Peaceful Easy Feeling", artist: "Eagles", genre: "Rock", year: 1972, album: "Eagles" },
  { id: 292, rank: 292, title: "Pink Floyd's Echoes", artist: "Pink Floyd", genre: "Rock", year: 1971, album: "Meddle" },
  { id: 293, rank: 293, title: "The Wall (Another Brick in the Wall Part 2)", artist: "Pink Floyd", genre: "Rock", year: 1979, album: "The Wall" },
  { id: 294, rank: 294, title: "Money", artist: "Pink Floyd", genre: "Rock", year: 1973, album: "The Dark Side of the Moon" },
  { id: 295, rank: 295, title: "Time", artist: "Pink Floyd", genre: "Rock", year: 1973, album: "The Dark Side of the Moon" },
  { id: 296, rank: 296, title: "Shine On You Crazy Diamond", artist: "Pink Floyd", genre: "Rock", year: 1975, album: "Wish You Were Here" },
  { id: 297, rank: 297, title: "Brain Damage", artist: "Pink Floyd", genre: "Rock", year: 1973, album: "The Dark Side of the Moon" },
  { id: 298, rank: 298, title: "Dogs", artist: "Pink Floyd", genre: "Rock", year: 1977, album: "Animals" },
  { id: 299, rank: 299, title: "Have a Cigar", artist: "Pink Floyd", genre: "Rock", year: 1975, album: "Wish You Were Here" },
  { id: 300, rank: 300, title: "Run Like Hell", artist: "Pink Floyd", genre: "Rock", year: 1979, album: "The Wall" },
  { id: 301, rank: 301, title: "Astronomy Domine", artist: "Pink Floyd", genre: "Rock", year: 1967, album: "The Piper at the Gates of Dawn" },
  { id: 302, rank: 302, title: "High Hopes", artist: "Pink Floyd", genre: "Rock", year: 1994, album: "The Division Bell" },
  { id: 303, rank: 303, title: "Learning to Fly", artist: "Pink Floyd", genre: "Rock", year: 1987, album: "A Momentary Lapse of Reason" },
  { id: 304, rank: 304, title: "Roundabout", artist: "Yes", genre: "Rock", year: 1971, album: "Fragile" },
  { id: 305, rank: 305, title: "Owner of a Lonely Heart", artist: "Yes", genre: "Rock", year: 1983, album: "90125" },
  { id: 306, rank: 306, title: "Heart of the Sunrise", artist: "Yes", genre: "Rock", year: 1971, album: "Fragile" },
  { id: 307, rank: 307, title: "Carry On Wayward Son", artist: "Kansas", genre: "Rock", year: 1976, album: "Leftoverture" },
  { id: 308, rank: 308, title: "Dust in the Wind", artist: "Kansas", genre: "Rock", year: 1977, album: "Point of Know Return" },
  { id: 309, rank: 309, title: "In the Court of the Crimson King", artist: "King Crimson", genre: "Rock", year: 1969, album: "In the Court of the Crimson King" },
  { id: 310, rank: 310, title: "21st Century Schizoid Man", artist: "King Crimson", genre: "Rock", year: 1969, album: "In the Court of the Crimson King" },
  { id: 311, rank: 311, title: "Anarchy in the U.K.", artist: "Sex Pistols", genre: "Rock", year: 1976, album: "Never Mind the Bollocks" },
  { id: 312, rank: 312, title: "God Save the Queen", artist: "Sex Pistols", genre: "Rock", year: 1977, album: "Never Mind the Bollocks" },
  { id: 313, rank: 313, title: "London Calling", artist: "The Clash", genre: "Rock", year: 1979, album: "London Calling" },
  { id: 314, rank: 314, title: "Should I Stay or Should I Go", artist: "The Clash", genre: "Rock", year: 1982, album: "Combat Rock" },
  { id: 315, rank: 315, title: "Rock the Casbah", artist: "The Clash", genre: "Rock", year: 1982, album: "Combat Rock" },
  { id: 316, rank: 316, title: "White Riot", artist: "The Clash", genre: "Rock", year: 1977, album: "The Clash" },
  { id: 317, rank: 317, title: "Train in Vain", artist: "The Clash", genre: "Rock", year: 1980, album: "London Calling" },
  { id: 318, rank: 318, title: "American Idiot", artist: "Green Day", genre: "Rock", year: 2004, album: "American Idiot" },
  { id: 319, rank: 319, title: "Boulevard of Broken Dreams", artist: "Green Day", genre: "Rock", year: 2004, album: "American Idiot" },
  { id: 320, rank: 320, title: "Good Riddance (Time of Your Life)", artist: "Green Day", genre: "Rock", year: 1997, album: "Nimrod" },
  { id: 321, rank: 321, title: "When I Come Around", artist: "Green Day", genre: "Rock", year: 1994, album: "Dookie" },
  { id: 322, rank: 322, title: "Longview", artist: "Green Day", genre: "Rock", year: 1994, album: "Dookie" },
  { id: 323, rank: 323, title: "Wake Me Up When September Ends", artist: "Green Day", genre: "Rock", year: 2004, album: "American Idiot" },
  { id: 324, rank: 324, title: "Holiday", artist: "Green Day", genre: "Rock", year: 2004, album: "American Idiot" },
  { id: 325, rank: 325, title: "All the Small Things", artist: "Blink-182", genre: "Rock", year: 1999, album: "Enema of the State" },
  { id: 326, rank: 326, title: "What's My Age Again?", artist: "Blink-182", genre: "Rock", year: 1999, album: "Enema of the State" },
  { id: 327, rank: 327, title: "I Miss You", artist: "Blink-182", genre: "Rock", year: 2003, album: "Blink-182" },
  { id: 328, rank: 328, title: "Dammit", artist: "Blink-182", genre: "Rock", year: 1997, album: "Dude Ranch" },
  { id: 329, rank: 329, title: "Adam's Song", artist: "Blink-182", genre: "Rock", year: 1999, album: "Enema of the State" },
  { id: 330, rank: 330, title: "Stacy's Mom", artist: "Fountains of Wayne", genre: "Rock", year: 2003, album: "Welcome Interstate Managers" },
  { id: 331, rank: 331, title: "Blister in the Sun", artist: "Violent Femmes", genre: "Rock", year: 1983, album: "Violent Femmes" },
  { id: 332, rank: 332, title: "Add It Up", artist: "Violent Femmes", genre: "Rock", year: 1983, album: "Violent Femmes" },
  { id: 333, rank: 333, title: "Girlfriend", artist: "Matthew Sweet", genre: "Rock", year: 1991, album: "Girlfriend" },
  { id: 334, rank: 334, title: "Lightning Crashes", artist: "Live", genre: "Rock", year: 1994, album: "Throwing Copper" },
  { id: 335, rank: 335, title: "I Alone", artist: "Live", genre: "Rock", year: 1994, album: "Throwing Copper" },
  { id: 336, rank: 336, title: "Selling the Drama", artist: "Live", genre: "Rock", year: 1994, album: "Throwing Copper" },
  { id: 337, rank: 337, title: "One Headlight", artist: "The Wallflowers", genre: "Rock", year: 1996, album: "Bringing Down the Horse" },
  { id: 338, rank: 338, title: "6th Avenue Heartache", artist: "The Wallflowers", genre: "Rock", year: 1996, album: "Bringing Down the Horse" },
  { id: 339, rank: 339, title: "Counting Blue Cars", artist: "Dishwalla", genre: "Rock", year: 1995, album: "Pet Your Friends" },
  { id: 340, rank: 340, title: "Pepper", artist: "Butthole Surfers", genre: "Rock", year: 1996, album: "Electriclarryland" },
  { id: 341, rank: 341, title: "Santeria", artist: "Sublime", genre: "Rock", year: 1996, album: "Sublime" },
  { id: 342, rank: 342, title: "What I Got", artist: "Sublime", genre: "Rock", year: 1996, album: "Sublime" },
  { id: 343, rank: 343, title: "40oz. to Freedom", artist: "Sublime", genre: "Rock", year: 1992, album: "40oz. to Freedom" },
  { id: 344, rank: 344, title: "Two Princes", artist: "Spin Doctors", genre: "Rock", year: 1991, album: "Pocket Full of Kryptonite" },
  { id: 345, rank: 345, title: "Little Miss Can't Be Wrong", artist: "Spin Doctors", genre: "Rock", year: 1991, album: "Pocket Full of Kryptonite" },
  { id: 346, rank: 346, title: "What's Up", artist: "4 Non Blondes", genre: "Rock", year: 1992, album: "Bigger, Better, Faster, More!" },
  { id: 347, rank: 347, title: "Unwell", artist: "Matchbox Twenty", genre: "Rock", year: 2002, album: "More Than You Think You Are" },
  { id: 348, rank: 348, title: "3 AM", artist: "Matchbox Twenty", genre: "Rock", year: 1996, album: "Yourself or Someone Like You" },
  { id: 349, rank: 349, title: "Push", artist: "Matchbox Twenty", genre: "Rock", year: 1996, album: "Yourself or Someone Like You" },
  { id: 350, rank: 350, title: "Bent", artist: "Matchbox Twenty", genre: "Rock", year: 2000, album: "Mad Season" },
  { id: 351, rank: 351, title: "Kryptonite", artist: "3 Doors Down", genre: "Rock", year: 2000, album: "The Better Life" },
  { id: 352, rank: 352, title: "Here Without You", artist: "3 Doors Down", genre: "Rock", year: 2002, album: "Away from the Sun" },
  { id: 353, rank: 353, title: "When I'm Gone", artist: "3 Doors Down", genre: "Rock", year: 2002, album: "Away from the Sun" },
  { id: 354, rank: 354, title: "Hemorrhage (In My Hands)", artist: "Fuel", genre: "Rock", year: 2000, album: "Something Like Human" },
  { id: 355, rank: 355, title: "Shimmer", artist: "Fuel", genre: "Rock", year: 1998, album: "Sunburn" },
  { id: 356, rank: 356, title: "Photograph", artist: "Nickelback", genre: "Rock", year: 2005, album: "All the Right Reasons" },
  { id: 357, rank: 357, title: "How You Remind Me", artist: "Nickelback", genre: "Rock", year: 2001, album: "Silver Side Up" },
  { id: 358, rank: 358, title: "Rockstar", artist: "Nickelback", genre: "Rock", year: 2005, album: "All the Right Reasons" },
  { id: 359, rank: 359, title: "Far Away", artist: "Nickelback", genre: "Rock", year: 2005, album: "All the Right Reasons" },
  { id: 360, rank: 360, title: "Someday", artist: "Nickelback", genre: "Rock", year: 2003, album: "The Long Road" },
  { id: 361, rank: 361, title: "Chop Suey!", artist: "System of a Down", genre: "Rock", year: 2001, album: "Toxicity" },
  { id: 362, rank: 362, title: "Toxicity", artist: "System of a Down", genre: "Rock", year: 2001, album: "Toxicity" },
  { id: 363, rank: 363, title: "B.Y.O.B.", artist: "System of a Down", genre: "Rock", year: 2005, album: "Mezmerize" },
  { id: 364, rank: 364, title: "Aerials", artist: "System of a Down", genre: "Rock", year: 2001, album: "Toxicity" },
  { id: 365, rank: 365, title: "Byob", artist: "System of a Down", genre: "Rock", year: 2005, album: "Mezmerize" },
  { id: 366, rank: 366, title: "Bat Country", artist: "Avenged Sevenfold", genre: "Rock", year: 2005, album: "City of Evil" },
  { id: 367, rank: 367, title: "Beast and the Harlot", artist: "Avenged Sevenfold", genre: "Rock", year: 2005, album: "City of Evil" },
  { id: 368, rank: 368, title: "Welcome to the Family", artist: "Avenged Sevenfold", genre: "Rock", year: 2010, album: "Nightmare" },
  { id: 369, rank: 369, title: "Nightmare", artist: "Avenged Sevenfold", genre: "Rock", year: 2010, album: "Nightmare" },
  { id: 370, rank: 370, title: "Hail to the King", artist: "Avenged Sevenfold", genre: "Rock", year: 2013, album: "Hail to the King" },
  { id: 371, rank: 371, title: "Beautiful", artist: "Joanna Newsom", genre: "Rock", year: 2004, album: "The Milk-Eyed Mender" },
  { id: 372, rank: 372, title: "Maps", artist: "Yeah Yeah Yeahs", genre: "Rock", year: 2003, album: "Fever to Tell" },
  { id: 373, rank: 373, title: "Heads Will Roll", artist: "Yeah Yeah Yeahs", genre: "Rock", year: 2009, album: "It's Blitz!" },
  { id: 374, rank: 374, title: "Last Nite", artist: "The Strokes", genre: "Rock", year: 2001, album: "Is This It" },
  { id: 375, rank: 375, title: "Someday", artist: "The Strokes", genre: "Rock", year: 2001, album: "Is This It" },
  { id: 376, rank: 376, title: "Reptilia", artist: "The Strokes", genre: "Rock", year: 2003, album: "Room on Fire" },
  { id: 377, rank: 377, title: "Hard to Explain", artist: "The Strokes", genre: "Rock", year: 2001, album: "Is This It" },
  { id: 378, rank: 378, title: "12:51", artist: "The Strokes", genre: "Rock", year: 2003, album: "Room on Fire" },
  { id: 379, rank: 379, title: "Elephant", artist: "Tame Impala", genre: "Rock", year: 2012, album: "Lonerism" },
  { id: 380, rank: 380, title: "Let It Happen", artist: "Tame Impala", genre: "Rock", year: 2015, album: "Currents" },
  { id: 381, rank: 381, title: "The Less I Know the Better", artist: "Tame Impala", genre: "Rock", year: 2015, album: "Currents" },
  { id: 382, rank: 382, title: "Feels Like We Only Go Backwards", artist: "Tame Impala", genre: "Rock", year: 2012, album: "Lonerism" },
  { id: 383, rank: 383, title: "New Person, Same Old Mistakes", artist: "Tame Impala", genre: "Rock", year: 2015, album: "Currents" },
  { id: 384, rank: 384, title: "Freak Scene", artist: "Dinosaur Jr.", genre: "Rock", year: 1988, album: "Bug" },
  { id: 385, rank: 385, title: "Just Like Heaven", artist: "The Cure", genre: "Rock", year: 1987, album: "Kiss Me, Kiss Me, Kiss Me" },
  { id: 386, rank: 386, title: "Boys Don't Cry", artist: "The Cure", genre: "Rock", year: 1979, album: "Three Imaginary Boys" },
  { id: 387, rank: 387, title: "Friday I'm in Love", artist: "The Cure", genre: "Rock", year: 1992, album: "Wish" },
  { id: 388, rank: 388, title: "Pictures of You", artist: "The Cure", genre: "Rock", year: 1990, album: "Disintegration" },
  { id: 389, rank: 389, title: "Lovesong", artist: "The Cure", genre: "Rock", year: 1989, album: "Disintegration" },
  { id: 390, rank: 390, title: "This Charming Man", artist: "The Smiths", genre: "Rock", year: 1983, album: "Single" },
  { id: 391, rank: 391, title: "There Is a Light That Never Goes Out", artist: "The Smiths", genre: "Rock", year: 1986, album: "The Queen Is Dead" },
  { id: 392, rank: 392, title: "How Soon Is Now?", artist: "The Smiths", genre: "Rock", year: 1985, album: "Meat Is Murder" },
  { id: 393, rank: 393, title: "The Boy with the Thorn in His Side", artist: "The Smiths", genre: "Rock", year: 1985, album: "The Queen Is Dead" },
  { id: 394, rank: 394, title: "Girlfriend in a Coma", artist: "The Smiths", genre: "Rock", year: 1987, album: "Strangeways, Here We Come" },
  { id: 395, rank: 395, title: "Is It Really So Strange?", artist: "The Smiths", genre: "Rock", year: 1987, album: "The World Won't Listen" },
  { id: 396, rank: 396, title: "Morning Glory", artist: "Oasis", genre: "Rock", year: 1995, album: "(What's the Story) Morning Glory?" },
  { id: 397, rank: 397, title: "Fake Plastic Trees", artist: "Radiohead", genre: "Rock", year: 1995, album: "The Bends" },
  { id: 398, rank: 398, title: "High and Dry", artist: "Radiohead", genre: "Rock", year: 1995, album: "The Bends" },
  { id: 399, rank: 399, title: "Street Spirit (Fade Out)", artist: "Radiohead", genre: "Rock", year: 1995, album: "The Bends" },
  { id: 400, rank: 400, title: "Just", artist: "Radiohead", genre: "Rock", year: 1995, album: "The Bends" },
  { id: 401, rank: 401, title: "Karma Police", artist: "Radiohead", genre: "Rock", year: 1997, album: "OK Computer" },
  { id: 402, rank: 402, title: "Paranoid Android", artist: "Radiohead", genre: "Rock", year: 1997, album: "OK Computer" },
  { id: 403, rank: 403, title: "No Surprises", artist: "Radiohead", genre: "Rock", year: 1997, album: "OK Computer" },
  { id: 404, rank: 404, title: "Lucky", artist: "Radiohead", genre: "Rock", year: 1997, album: "OK Computer" },
  { id: 405, rank: 405, title: "Knives Out", artist: "Radiohead", genre: "Rock", year: 2001, album: "Amnesiac" },
  { id: 406, rank: 406, title: "Man on the Moon", artist: "Counting Crows", genre: "Rock", year: 1993, album: "August and Everything After" },
  { id: 407, rank: 407, title: "Mr. Jones", artist: "Counting Crows", genre: "Rock", year: 1993, album: "August and Everything After" },
  { id: 408, rank: 408, title: "Round Here", artist: "Counting Crows", genre: "Rock", year: 1993, album: "August and Everything After" },
  { id: 409, rank: 409, title: "A Long December", artist: "Counting Crows", genre: "Rock", year: 1996, album: "Recovering the Satellites" },
  { id: 410, rank: 410, title: "Anna Begins", artist: "Counting Crows", genre: "Rock", year: 1993, album: "August and Everything After" },
  { id: 411, rank: 411, title: "Hunger Strike (Live)", artist: "Pearl Jam", genre: "Rock", year: 1992, album: "Single" },
  { id: 412, rank: 412, title: "Alive (MTV Unplugged)", artist: "Pearl Jam", genre: "Rock", year: 1992, album: "MTV Unplugged" },
  { id: 413, rank: 413, title: "Yellow Ledbetter", artist: "Pearl Jam", genre: "Rock", year: 1992, album: "Single" },
  { id: 414, rank: 414, title: "Porch", artist: "Pearl Jam", genre: "Rock", year: 1991, album: "Ten" },
  { id: 415, rank: 415, title: "State of Love and Trust", artist: "Pearl Jam", genre: "Rock", year: 1992, album: "Singles Soundtrack" },
  { id: 416, rank: 416, title: "Rooster (Live)", artist: "Alice in Chains", genre: "Rock", year: 1996, album: "MTV Unplugged" },
  { id: 417, rank: 417, title: "Heaven Beside You", artist: "Alice in Chains", genre: "Rock", year: 1995, album: "Alice in Chains" },
  { id: 418, rank: 418, title: "Grind", artist: "Alice in Chains", genre: "Rock", year: 1995, album: "Alice in Chains" },
  { id: 419, rank: 419, title: "Again", artist: "Alice in Chains", genre: "Rock", year: 1995, album: "Alice in Chains" },
  { id: 420, rank: 420, title: "Over Now", artist: "Alice in Chains", genre: "Rock", year: 1995, album: "Alice in Chains" },
  { id: 421, rank: 421, title: "All Within My Hands", artist: "Metallica", genre: "Rock", year: 2003, album: "St. Anger" },
  { id: 422, rank: 422, title: "The Unforgiven", artist: "Metallica", genre: "Rock", year: 1991, album: "Metallica" },
  { id: 423, rank: 423, title: "Nothing Else Matters", artist: "Metallica", genre: "Rock", year: 1991, album: "Metallica" },
  { id: 424, rank: 424, title: "Sad but True", artist: "Metallica", genre: "Rock", year: 1991, album: "Metallica" },
  { id: 425, rank: 425, title: "Wherever I May Roam", artist: "Metallica", genre: "Rock", year: 1991, album: "Metallica" },
  { id: 426, rank: 426, title: "Fuel", artist: "Metallica", genre: "Rock", year: 1997, album: "ReLoad" },
  { id: 427, rank: 427, title: "The Memory Remains", artist: "Metallica", genre: "Rock", year: 1997, album: "ReLoad" },
  { id: 428, rank: 428, title: "Turn the Page", artist: "Metallica", genre: "Rock", year: 1998, album: "Garage Inc." },
  { id: 429, rank: 429, title: "Master of Puppets", artist: "Metallica", genre: "Rock", year: 1986, album: "Master of Puppets" },
  { id: 430, rank: 430, title: "Battery", artist: "Metallica", genre: "Rock", year: 1986, album: "Master of Puppets" },
  { id: 431, rank: 431, title: "Ride the Lightning", artist: "Metallica", genre: "Rock", year: 1984, album: "Ride the Lightning" },
  { id: 432, rank: 432, title: "For Whom the Bell Tolls", artist: "Metallica", genre: "Rock", year: 1984, album: "Ride the Lightning" },
  { id: 433, rank: 433, title: "Fade to Black", artist: "Metallica", genre: "Rock", year: 1984, album: "Ride the Lightning" },
  { id: 434, rank: 434, title: "Seek and Destroy", artist: "Metallica", genre: "Rock", year: 1983, album: "Kill 'Em All" },
  { id: 435, rank: 435, title: "Hit the Lights", artist: "Metallica", genre: "Rock", year: 1983, album: "Kill 'Em All" },
  { id: 436, rank: 436, title: "Laid", artist: "James", genre: "Rock", year: 1993, album: "Laid" },
  { id: 437, rank: 437, title: "Come Out and Play", artist: "The Offspring", genre: "Rock", year: 1994, album: "Smash" },
  { id: 438, rank: 438, title: "Self Esteem", artist: "The Offspring", genre: "Rock", year: 1994, album: "Smash" },
  { id: 439, rank: 439, title: "Pretty Fly (for a White Guy)", artist: "The Offspring", genre: "Rock", year: 1998, album: "Americana" },
  { id: 440, rank: 440, title: "The Kids Aren't Alright", artist: "The Offspring", genre: "Rock", year: 1998, album: "Americana" },
  { id: 441, rank: 441, title: "Why Don't You Get a Job?", artist: "The Offspring", genre: "Rock", year: 1999, album: "Americana" },
  { id: 442, rank: 442, title: "Defy You", artist: "The Offspring", genre: "Rock", year: 2002, album: "Conspiracy of One" },
  { id: 443, rank: 443, title: "She", artist: "Green Day", genre: "Rock", year: 1994, album: "Dookie" },
  { id: 444, rank: 444, title: "Minority", artist: "Green Day", genre: "Rock", year: 2000, album: "Warning" },
  { id: 445, rank: 445, title: "21 Guns", artist: "Green Day", genre: "Rock", year: 2009, album: "21st Century Breakdown" },
  { id: 446, rank: 446, title: "Know Your Enemy", artist: "Green Day", genre: "Rock", year: 2009, album: "21st Century Breakdown" },
  { id: 447, rank: 447, title: "Jesus of Suburbia", artist: "Green Day", genre: "Rock", year: 2004, album: "American Idiot" },
  { id: 448, rank: 448, title: "Brain Stew", artist: "Green Day", genre: "Rock", year: 1996, album: "Insomniac" },
  { id: 449, rank: 449, title: "Geek Stink Breath", artist: "Green Day", genre: "Rock", year: 1995, album: "Insomniac" },
  { id: 450, rank: 450, title: "Helena", artist: "My Chemical Romance", genre: "Rock", year: 2004, album: "Three Cheers for Sweet Revenge" },
  { id: 451, rank: 451, title: "Welcome to the Black Parade", artist: "My Chemical Romance", genre: "Rock", year: 2006, album: "The Black Parade" },
  { id: 452, rank: 452, title: "Famous Last Words", artist: "My Chemical Romance", genre: "Rock", year: 2006, album: "The Black Parade" },
  { id: 453, rank: 453, title: "I'm Not Okay (I Promise)", artist: "My Chemical Romance", genre: "Rock", year: 2004, album: "Three Cheers for Sweet Revenge" },
  { id: 454, rank: 454, title: "Na Na Na", artist: "My Chemical Romance", genre: "Rock", year: 2010, album: "Danger Days: The True Lives of the Fabulous Killjoys" },
  { id: 455, rank: 455, title: "Teenagers", artist: "My Chemical Romance", genre: "Rock", year: 2006, album: "The Black Parade" },
  { id: 456, rank: 456, title: "The Ghost of You", artist: "My Chemical Romance", genre: "Rock", year: 2004, album: "Three Cheers for Sweet Revenge" },
  { id: 457, rank: 457, title: "Sugar We're Goin Down", artist: "Fall Out Boy", genre: "Rock", year: 2005, album: "From Under the Cork Tree" },
  { id: 458, rank: 458, title: "Dance, Dance", artist: "Fall Out Boy", genre: "Rock", year: 2005, album: "From Under the Cork Tree" },
  { id: 459, rank: 459, title: "Thnks fr th Mmrs", artist: "Fall Out Boy", genre: "Rock", year: 2007, album: "Infinity on High" },
  { id: 460, rank: 460, title: "This Ain't a Scene, It's an Arms Race", artist: "Fall Out Boy", genre: "Rock", year: 2007, album: "Infinity on High" },
  { id: 461, rank: 461, title: "Centuries", artist: "Fall Out Boy", genre: "Rock", year: 2014, album: "American Beauty/American Psycho" },
  { id: 462, rank: 462, title: "Pressure", artist: "Paramore", genre: "Rock", year: 2005, album: "All We Know Is Falling" },
  { id: 463, rank: 463, title: "Misery Business", artist: "Paramore", genre: "Rock", year: 2007, album: "Riot!" },
  { id: 464, rank: 464, title: "Decode", artist: "Paramore", genre: "Rock", year: 2008, album: "Twilight Soundtrack" },
  { id: 465, rank: 465, title: "The Only Exception", artist: "Paramore", genre: "Rock", year: 2009, album: "Brand New Eyes" },
  { id: 466, rank: 466, title: "Still Into You", artist: "Paramore", genre: "Rock", year: 2013, album: "Paramore" },
  { id: 467, rank: 467, title: "Hard Times", artist: "Paramore", genre: "Rock", year: 2017, album: "After Laughter" },
  { id: 468, rank: 468, title: "Feel Good Inc.", artist: "Gorillaz", genre: "Rock", year: 2005, album: "Demon Days" },
  { id: 469, rank: 469, title: "Clint Eastwood", artist: "Gorillaz", genre: "Rock", year: 2001, album: "Gorillaz" },
  { id: 470, rank: 470, title: "On Melancholy Hill", artist: "Gorillaz", genre: "Rock", year: 2010, album: "Plastic Beach" },
  { id: 471, rank: 471, title: "DARE", artist: "Gorillaz", genre: "Rock", year: 2005, album: "Demon Days" },
  { id: 472, rank: 472, title: "Empire Ants", artist: "Gorillaz", genre: "Rock", year: 2010, album: "Plastic Beach" },
  { id: 473, rank: 473, title: "Buddy Holly", artist: "Weezer", genre: "Rock", year: 1994, album: "Weezer (Blue Album)" },
  { id: 474, rank: 474, title: "Undone – The Sweater Song", artist: "Weezer", genre: "Rock", year: 1994, album: "Weezer (Blue Album)" },
  { id: 475, rank: 475, title: "Say It Ain't So", artist: "Weezer", genre: "Rock", year: 1994, album: "Weezer (Blue Album)" },
  { id: 476, rank: 476, title: "Hash Pipe", artist: "Weezer", genre: "Rock", year: 2001, album: "Weezer (Green Album)" },
  { id: 477, rank: 477, title: "Island in the Sun", artist: "Weezer", genre: "Rock", year: 2001, album: "Weezer (Green Album)" },
  { id: 478, rank: 478, title: "Beverly Hills", artist: "Weezer", genre: "Rock", year: 2005, album: "Make Believe" },
  { id: 479, rank: 479, title: "Pork and Beans", artist: "Weezer", genre: "Rock", year: 2008, album: "Weezer (Red Album)" },
  { id: 480, rank: 480, title: "Somebody That I Used to Know", artist: "Gotye", genre: "Rock", year: 2011, album: "Making Mirrors" },
  { id: 481, rank: 481, title: "Electric Feel", artist: "MGMT", genre: "Rock", year: 2007, album: "Oracular Spectacular" },
  { id: 482, rank: 482, title: "Kids", artist: "MGMT", genre: "Rock", year: 2007, album: "Oracular Spectacular" },
  { id: 483, rank: 483, title: "Time to Pretend", artist: "MGMT", genre: "Rock", year: 2007, album: "Oracular Spectacular" },
  { id: 484, rank: 484, title: "Two Door Cinema Club - What You Know", artist: "Two Door Cinema Club", genre: "Rock", year: 2010, album: "Tourist History" },
  { id: 485, rank: 485, title: "Changing of the Seasons", artist: "Two Door Cinema Club", genre: "Rock", year: 2012, album: "Beacon" },
  { id: 486, rank: 486, title: "Come Back Home", artist: "Two Door Cinema Club", genre: "Rock", year: 2010, album: "Tourist History" },
  { id: 487, rank: 487, title: "Take Me Out", artist: "Franz Ferdinand", genre: "Rock", year: 2004, album: "Franz Ferdinand" },
  { id: 488, rank: 488, title: "Do You Want To", artist: "Franz Ferdinand", genre: "Rock", year: 2004, album: "Franz Ferdinand" },
  { id: 489, rank: 489, title: "Michael", artist: "Franz Ferdinand", genre: "Rock", year: 2004, album: "Franz Ferdinand" },
  { id: 490, rank: 490, title: "Lazy Eye", artist: "Silversun Pickups", genre: "Rock", year: 2006, album: "Carnavas" },
  { id: 491, rank: 491, title: "Panic Switch", artist: "Silversun Pickups", genre: "Rock", year: 2009, album: "Swoon" },
  { id: 492, rank: 492, title: "Rebellion (Lies)", artist: "Arcade Fire", genre: "Rock", year: 2004, album: "Funeral" },
  { id: 493, rank: 493, title: "Wake Up", artist: "Arcade Fire", genre: "Rock", year: 2004, album: "Funeral" },
  { id: 494, rank: 494, title: "Ready to Start", artist: "Arcade Fire", genre: "Rock", year: 2010, album: "The Suburbs" },
  { id: 495, rank: 495, title: "The Suburbs", artist: "Arcade Fire", genre: "Rock", year: 2010, album: "The Suburbs" },
  { id: 496, rank: 496, title: "Keep the Car Running", artist: "Arcade Fire", genre: "Rock", year: 2007, album: "Neon Bible" },
  { id: 497, rank: 497, title: "Everything Now", artist: "Arcade Fire", genre: "Rock", year: 2017, album: "Everything Now" },
  { id: 498, rank: 498, title: "Psycho Killer", artist: "Talking Heads", genre: "Rock", year: 1977, album: "Talking Heads: 77" },
  { id: 499, rank: 499, title: "Once in a Lifetime", artist: "Talking Heads", genre: "Rock", year: 1980, album: "Remain in Light" },
  { id: 500, rank: 500, title: "Burning Down the House", artist: "Talking Heads", genre: "Rock", year: 1983, album: "Speaking in Tongues" },
];
