const SONGS_EDM = [
  { id: 2501, rank: 1, title: "Around the World", artist: "Daft Punk", genre: "EDM", year: 1997, album: "Homework" },
  { id: 2502, rank: 2, title: "One More Time", artist: "Daft Punk", genre: "EDM", year: 2000, album: "Discovery" },
  { id: 2503, rank: 3, title: "Levels", artist: "Avicii", genre: "EDM", year: 2011, album: "Levels" },
  { id: 2504, rank: 4, title: "Wake Me Up", artist: "Avicii", genre: "EDM", year: 2013, album: "True" },
  { id: 2505, rank: 5, title: "Animals", artist: "Martin Garrix", genre: "EDM", year: 2013, album: "Animals" },
  { id: 2506, rank: 6, title: "Sandstorm", artist: "Darude", genre: "EDM", year: 1999, album: "Before the Storm" },
  { id: 2507, rank: 7, title: "Summer", artist: "Calvin Harris", genre: "EDM", year: 2014, album: "Motion" },
  { id: 2508, rank: 8, title: "Titanium", artist: "David Guetta ft. Sia", genre: "EDM", year: 2011, album: "Nothing but the Beat" },
  { id: 2509, rank: 9, title: "Scary Monsters and Nice Sprites", artist: "Skrillex", genre: "EDM", year: 2010, album: "Scary Monsters and Nice Sprites" },
  { id: 2510, rank: 10, title: "Clarity", artist: "Zedd ft. Foxes", genre: "EDM", year: 2012, album: "Clarity" },
  { id: 2511, rank: 11, title: "Don't You Worry Child", artist: "Swedish House Mafia", genre: "EDM", year: 2012, album: "Until Now" },
  { id: 2512, rank: 12, title: "Save the World", artist: "Swedish House Mafia", genre: "EDM", year: 2011, album: "Until Now" },
  { id: 2513, rank: 13, title: "Adagio for Strings", artist: "Tiësto", genre: "EDM", year: 2004, album: "Just Be" },
  { id: 2514, rank: 14, title: "Red Lights", artist: "Tiësto", genre: "EDM", year: 2014, album: "A Town Called Paradise" },
  { id: 2515, rank: 15, title: "Strobe", artist: "Deadmau5", genre: "EDM", year: 2009, album: "For Lack of a Better Name" },
  { id: 2516, rank: 16, title: "Get Lucky", artist: "Daft Punk ft. Pharrell Williams", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2517, rank: 17, title: "Harder Better Faster Stronger", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2518, rank: 18, title: "Insomnia", artist: "Faithless", genre: "EDM", year: 1995, album: "Reverence" },
  { id: 2519, rank: 19, title: "Born Slippy .NUXX", artist: "Underworld", genre: "EDM", year: 1995, album: "Second Toughest in the Infants" },
  { id: 2520, rank: 20, title: "Firestarter", artist: "The Prodigy", genre: "EDM", year: 1996, album: "The Fat of the Land" },
  { id: 2521, rank: 21, title: "Breathe", artist: "The Prodigy", genre: "EDM", year: 1996, album: "The Fat of the Land" },
  { id: 2522, rank: 22, title: "Block Rockin' Beats", artist: "The Chemical Brothers", genre: "EDM", year: 1997, album: "Dig Your Own Hole" },
  { id: 2523, rank: 23, title: "Hey Boy Hey Girl", artist: "The Chemical Brothers", genre: "EDM", year: 1999, album: "Surrender" },
  { id: 2524, rank: 24, title: "Fade into Darkness", artist: "Avicii", genre: "EDM", year: 2011, album: "Fade into Darkness" },
  { id: 2525, rank: 25, title: "Le7els", artist: "Zedd", genre: "EDM", year: 2012, album: "Clarity" },
  { id: 2526, rank: 26, title: "We Found Love", artist: "Calvin Harris ft. Rihanna", genre: "EDM", year: 2011, album: "18 Months" },
  { id: 2527, rank: 27, title: "Feel So Close", artist: "Calvin Harris", genre: "EDM", year: 2011, album: "18 Months" },
  { id: 2528, rank: 28, title: "This Is What You Came For", artist: "Calvin Harris ft. Rihanna", genre: "EDM", year: 2016, album: "This Is What You Came For" },
  { id: 2529, rank: 29, title: "Gettin' Over You", artist: "David Guetta ft. Fergie & LMFAO", genre: "EDM", year: 2010, album: "One Love" },
  { id: 2530, rank: 30, title: "When Love Takes Over", artist: "David Guetta ft. Kelly Rowland", genre: "EDM", year: 2009, album: "One Love" },
  { id: 2531, rank: 31, title: "Memories", artist: "David Guetta ft. Kid Cudi", genre: "EDM", year: 2009, album: "One Love" },
  { id: 2532, rank: 32, title: "Without You", artist: "David Guetta ft. Usher", genre: "EDM", year: 2011, album: "Nothing but the Beat" },
  { id: 2533, rank: 33, title: "Lean On", artist: "Major Lazer & DJ Snake ft. MØ", genre: "EDM", year: 2015, album: "Peace Is the Mission" },
  { id: 2534, rank: 34, title: "Turn Down for What", artist: "DJ Snake & Lil Jon", genre: "EDM", year: 2013, album: "Turn Down for What" },
  { id: 2535, rank: 35, title: "Tuna Melt", artist: "DJ Snake", genre: "EDM", year: 2016, album: "Encore" },
  { id: 2536, rank: 36, title: "Stay the Night", artist: "Zedd ft. Hayley Williams", genre: "EDM", year: 2014, album: "True Colors" },
  { id: 2537, rank: 37, title: "Beautiful Now", artist: "Zedd ft. Jon Bellion", genre: "EDM", year: 2015, album: "True Colors" },
  { id: 2538, rank: 38, title: "Happier", artist: "Marshmello & Bastille", genre: "EDM", year: 2018, album: "Joytime III" },
  { id: 2539, rank: 39, title: "Alone", artist: "Marshmello", genre: "EDM", year: 2016, album: "Joytime" },
  { id: 2540, rank: 40, title: "Faded", artist: "Alan Walker", genre: "EDM", year: 2015, album: "Different World" },
  { id: 2541, rank: 41, title: "Spectre", artist: "Alan Walker", genre: "EDM", year: 2015, album: "Spectre" },
  { id: 2542, rank: 42, title: "Stay", artist: "Kygo ft. Maty Noyes", genre: "EDM", year: 2015, album: "Cloud Nine" },
  { id: 2543, rank: 43, title: "Firestone", artist: "Kygo ft. Conrad Sewell", genre: "EDM", year: 2014, album: "Cloud Nine" },
  { id: 2544, rank: 44, title: "Here for You", artist: "Kygo ft. Ella Henderson", genre: "EDM", year: 2015, album: "Cloud Nine" },
  { id: 2545, rank: 45, title: "Roses", artist: "The Chainsmokers ft. ROZES", genre: "EDM", year: 2015, album: "Collage" },
  { id: 2546, rank: 46, title: "Don't Let Me Down", artist: "The Chainsmokers ft. Daya", genre: "EDM", year: 2016, album: "Collage" },
  { id: 2547, rank: 47, title: "Closer", artist: "The Chainsmokers ft. Halsey", genre: "EDM", year: 2016, album: "Collage" },
  { id: 2548, rank: 48, title: "Something Just Like This", artist: "The Chainsmokers & Coldplay", genre: "EDM", year: 2017, album: "Memories...Do Not Open" },
  { id: 2549, rank: 49, title: "Seek Bromance", artist: "Avicii", genre: "EDM", year: 2010, album: "Seek Bromance" },
  { id: 2550, rank: 50, title: "The Days", artist: "Avicii", genre: "EDM", year: 2014, album: "The Days / Nights" },
  { id: 2551, rank: 51, title: "Waiting for Love", artist: "Avicii", genre: "EDM", year: 2015, album: "Stories" },
  { id: 2552, rank: 52, title: "Hey Brother", artist: "Avicii", genre: "EDM", year: 2013, album: "True" },
  { id: 2553, rank: 53, title: "Lay Me Down", artist: "Avicii", genre: "EDM", year: 2013, album: "True" },
  { id: 2554, rank: 54, title: "What Would I Change It To", artist: "Avicii", genre: "EDM", year: 2017, album: "AVĪCI (01)" },
  { id: 2555, rank: 55, title: "Silhouettes", artist: "Avicii", genre: "EDM", year: 2012, album: "Silhouettes" },
  { id: 2556, rank: 56, title: "Antidote", artist: "Swedish House Mafia", genre: "EDM", year: 2022, album: "Paradise Again" },
  { id: 2557, rank: 57, title: "One (Your Name)", artist: "Swedish House Mafia ft. Pharrell Williams", genre: "EDM", year: 2010, album: "Until Now" },
  { id: 2558, rank: 58, title: "Miami 2 Ibiza", artist: "Swedish House Mafia ft. Tinie Tempah", genre: "EDM", year: 2011, album: "Until Now" },
  { id: 2559, rank: 59, title: "Greyhound", artist: "Swedish House Mafia", genre: "EDM", year: 2012, album: "Until Now" },
  { id: 2560, rank: 60, title: "In My Arms", artist: "Tiësto ft. Christian Burns", genre: "EDM", year: 2007, album: "Elements of Life" },
  { id: 2561, rank: 61, title: "Chasing Summers", artist: "Tiësto", genre: "EDM", year: 2010, album: "Kaleidoscope" },
  { id: 2562, rank: 62, title: "You Are the Music in Me", artist: "Tiësto", genre: "EDM", year: 2007, album: "Elements of Life" },
  { id: 2563, rank: 63, title: "Speed Rail", artist: "Tiësto", genre: "EDM", year: 2003, album: "Just Be" },
  { id: 2564, rank: 64, title: "Traffic", artist: "Tiësto", genre: "EDM", year: 2003, album: "Just Be" },
  { id: 2565, rank: 65, title: "Numb", artist: "Avicii", genre: "EDM", year: 2013, album: "True" },
  { id: 2566, rank: 66, title: "Reload", artist: "Sebastian Ingrosso & Tommy Trash ft. John Martin", genre: "EDM", year: 2012, album: "Reload" },
  { id: 2567, rank: 67, title: "This Is Goodbye", artist: "Deadmau5", genre: "EDM", year: 2012, album: "Album Title Goes Here" },
  { id: 2568, rank: 68, title: "Raise Your Weapon", artist: "Deadmau5", genre: "EDM", year: 2010, album: "4x4=12" },
  { id: 2569, rank: 69, title: "Some Chords", artist: "Deadmau5", genre: "EDM", year: 2011, album: "4x4=12" },
  { id: 2570, rank: 70, title: "Ghosts 'n' Stuff", artist: "Deadmau5 ft. Rob Swire", genre: "EDM", year: 2009, album: "For Lack of a Better Name" },
  { id: 2571, rank: 71, title: "I Remember", artist: "Deadmau5 & Kaskade", genre: "EDM", year: 2008, album: "Random Album Title" },
  { id: 2572, rank: 72, title: "Move for Me", artist: "Deadmau5 & Kaskade", genre: "EDM", year: 2008, album: "Random Album Title" },
  { id: 2573, rank: 73, title: "Beautiful Liar", artist: "Deadmau5", genre: "EDM", year: 2012, album: "Album Title Goes Here" },
  { id: 2574, rank: 74, title: "Tremors", artist: "Deadmau5", genre: "EDM", year: 2014, album: "while(1<2)" },
  { id: 2575, rank: 75, title: "Night Owl", artist: "Deadmau5", genre: "EDM", year: 2009, album: "For Lack of a Better Name" },
  { id: 2576, rank: 76, title: "Neon Future", artist: "Steve Aoki ft. Luke Steele", genre: "EDM", year: 2014, album: "Neon Future I" },
  { id: 2577, rank: 77, title: "Pursuit of Happiness", artist: "Steve Aoki ft. Kid Cudi", genre: "EDM", year: 2009, album: "Wonderland" },
  { id: 2578, rank: 78, title: "Cudi Zone", artist: "Steve Aoki", genre: "EDM", year: 2010, album: "Cudi Zone" },
  { id: 2579, rank: 79, title: "Turbulence", artist: "Steve Aoki ft. Lil Jon", genre: "EDM", year: 2012, album: "Wonderland" },
  { id: 2580, rank: 80, title: "Alive", artist: "Daft Punk", genre: "EDM", year: 2007, album: "Alive 2007" },
  { id: 2581, rank: 81, title: "Technologic", artist: "Daft Punk", genre: "EDM", year: 2005, album: "Human After All" },
  { id: 2582, rank: 82, title: "Da Funk", artist: "Daft Punk", genre: "EDM", year: 1995, album: "Homework" },
  { id: 2583, rank: 83, title: "Digital Love", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2584, rank: 84, title: "Instant Crush", artist: "Daft Punk ft. Julian Casablancas", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2585, rank: 85, title: "Lose Yourself to Dance", artist: "Daft Punk ft. Pharrell Williams", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2586, rank: 86, title: "Within", artist: "Daft Punk", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2587, rank: 87, title: "Contact", artist: "Daft Punk", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2588, rank: 88, title: "Robot Rock", artist: "Daft Punk", genre: "EDM", year: 2005, album: "Human After All" },
  { id: 2589, rank: 89, title: "Superheroes", artist: "Daft Punk", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2590, rank: 90, title: "Spaceship", artist: "Armin van Buuren", genre: "EDM", year: 2017, album: "Shivers" },
  { id: 2591, rank: 91, title: "This Is What It Feels Like", artist: "Armin van Buuren ft. Trevor Guthrie", genre: "EDM", year: 2013, album: "Intense" },
  { id: 2592, rank: 92, title: "Ping Pong", artist: "Armin van Buuren", genre: "EDM", year: 2013, album: "Intense" },
  { id: 2593, rank: 93, title: "Blah Blah Blah", artist: "Armin van Buuren", genre: "EDM", year: 2019, album: "Balance" },
  { id: 2594, rank: 94, title: "In and Out of Love", artist: "Armin van Buuren ft. Sharon den Adel", genre: "EDM", year: 2008, album: "Imagine" },
  { id: 2595, rank: 95, title: "Communication", artist: "Armin van Buuren", genre: "EDM", year: 2000, album: "Communication" },
  { id: 2596, rank: 96, title: "Shivers", artist: "Armin van Buuren ft. Susana", genre: "EDM", year: 2005, album: "Shivers" },
  { id: 2597, rank: 97, title: "Blue Fear", artist: "Armin van Buuren", genre: "EDM", year: 1997, album: "Blue Fear" },
  { id: 2598, rank: 98, title: "A State of Trance (Festival Mix)", artist: "Armin van Buuren", genre: "EDM", year: 2008, album: "Imagine" },
  { id: 2599, rank: 99, title: "Sometimes They Return (For More)", artist: "Armin van Buuren", genre: "EDM", year: 2004, album: "Shivers" },
  { id: 2600, rank: 100, title: "Safe Within", artist: "Armin van Buuren ft. Alika", genre: "EDM", year: 2014, album: "Intense" },
  { id: 2601, rank: 101, title: "We Are", artist: "Paul van Dyk ft. Johnny McDaid", genre: "EDM", year: 2012, album: "Evolution" },
  { id: 2602, rank: 102, title: "For an Angel", artist: "Paul van Dyk", genre: "EDM", year: 1994, album: "45 RPM" },
  { id: 2603, rank: 103, title: "Words", artist: "Paul van Dyk ft. Vega 4", genre: "EDM", year: 2005, album: "The Politics of Dancing 2" },
  { id: 2604, rank: 104, title: "Time of Our Lives", artist: "Paul van Dyk ft. Vega 4", genre: "EDM", year: 2004, album: "Reflections" },
  { id: 2605, rank: 105, title: "Another Way", artist: "Paul van Dyk", genre: "EDM", year: 1994, album: "45 RPM" },
  { id: 2606, rank: 106, title: "Let Go", artist: "Ferry Corsten", genre: "EDM", year: 2000, album: "Right of Way" },
  { id: 2607, rank: 107, title: "Punk", artist: "Ferry Corsten", genre: "EDM", year: 2002, album: "Rock Your Body Rock" },
  { id: 2608, rank: 108, title: "Holding On", artist: "Ferry Corsten ft. Guru Josh", genre: "EDM", year: 2012, album: "Holding On" },
  { id: 2609, rank: 109, title: "Resurrection", artist: "PPK", genre: "EDM", year: 2001, album: "Resurrection" },
  { id: 2610, rank: 110, title: "The Sound of Goodbye", artist: "Rank 1", genre: "EDM", year: 2005, album: "The Sound of Goodbye" },
  { id: 2611, rank: 111, title: "Airwave", artist: "Rank 1", genre: "EDM", year: 1999, album: "Airwave" },
  { id: 2612, rank: 112, title: "Age of Love", artist: "Age of Love", genre: "EDM", year: 1990, album: "Age of Love" },
  { id: 2613, rank: 113, title: "Offshore", artist: "Chicane", genre: "EDM", year: 1996, album: "Far from the Maddening Crowds" },
  { id: 2614, rank: 114, title: "Don't Give Up", artist: "Chicane ft. Bryan Adams", genre: "EDM", year: 2000, album: "Behind the Sun" },
  { id: 2615, rank: 115, title: "Saltwater", artist: "Chicane", genre: "EDM", year: 1999, album: "Far from the Maddening Crowds" },
  { id: 2616, rank: 116, title: "No Ordinary Morning / Halcyon", artist: "Chicane", genre: "EDM", year: 1999, album: "Far from the Maddening Crowds" },
  { id: 2617, rank: 117, title: "Inner Universe", artist: "Yoko Kanno & Origa", genre: "EDM", year: 2002, album: "Ghost in the Shell: Stand Alone Complex" },
  { id: 2618, rank: 118, title: "Spitfire", artist: "The Prodigy", genre: "EDM", year: 2004, album: "Always Outnumbered, Never Outgunned" },
  { id: 2619, rank: 119, title: "Omen", artist: "The Prodigy", genre: "EDM", year: 2009, album: "Invaders Must Die" },
  { id: 2620, rank: 120, title: "Invaders Must Die", artist: "The Prodigy", genre: "EDM", year: 2009, album: "Invaders Must Die" },
  { id: 2621, rank: 121, title: "Voodoo People", artist: "The Prodigy", genre: "EDM", year: 1994, album: "Music for the Jilted Generation" },
  { id: 2622, rank: 122, title: "Music: Response", artist: "The Chemical Brothers", genre: "EDM", year: 1999, album: "Surrender" },
  { id: 2623, rank: 123, title: "Galvanize", artist: "The Chemical Brothers", genre: "EDM", year: 2005, album: "Push the Button" },
  { id: 2624, rank: 124, title: "Believe", artist: "The Chemical Brothers", genre: "EDM", year: 2005, album: "Push the Button" },
  { id: 2625, rank: 125, title: "Got Glint?", artist: "The Chemical Brothers", genre: "EDM", year: 2007, album: "We Are the Night" },
  { id: 2626, rank: 126, title: "Star Guitar", artist: "The Chemical Brothers", genre: "EDM", year: 2002, album: "Come with Us" },
  { id: 2627, rank: 127, title: "Swoon", artist: "The Chemical Brothers", genre: "EDM", year: 2010, album: "Further" },
  { id: 2628, rank: 128, title: "Escape Velocity", artist: "The Chemical Brothers", genre: "EDM", year: 2010, album: "Further" },
  { id: 2629, rank: 129, title: "Setting Sun", artist: "The Chemical Brothers ft. Noel Gallagher", genre: "EDM", year: 1996, album: "Dig Your Own Hole" },
  { id: 2630, rank: 130, title: "Elektrobank", artist: "The Chemical Brothers", genre: "EDM", year: 1997, album: "Dig Your Own Hole" },
  { id: 2631, rank: 131, title: "Windowlicker", artist: "Aphex Twin", genre: "EDM", year: 1999, album: "Windowlicker" },
  { id: 2632, rank: 132, title: "Come to Daddy", artist: "Aphex Twin", genre: "EDM", year: 1997, album: "Come to Daddy" },
  { id: 2633, rank: 133, title: "Flim", artist: "Aphex Twin", genre: "EDM", year: 1997, album: "Come to Daddy" },
  { id: 2634, rank: 134, title: "Alberto Balsalm", artist: "Aphex Twin", genre: "EDM", year: 1994, album: "I Care Because You Do" },
  { id: 2635, rank: 135, title: "Xtal", artist: "Aphex Twin", genre: "EDM", year: 1992, album: "Selected Ambient Works 85–92" },
  { id: 2636, rank: 136, title: "Ageispolis", artist: "Aphex Twin", genre: "EDM", year: 1992, album: "Selected Ambient Works 85–92" },
  { id: 2637, rank: 137, title: "Strange Days", artist: "Portishead", genre: "EDM", year: 1994, album: "Dummy" },
  { id: 2638, rank: 138, title: "Buku", artist: "Buku", genre: "EDM", year: 2015, album: "Buku" },
  { id: 2639, rank: 139, title: "Ghosts", artist: "Porter Robinson", genre: "EDM", year: 2016, album: "Worlds" },
  { id: 2640, rank: 140, title: "Language", artist: "Porter Robinson", genre: "EDM", year: 2012, album: "Language" },
  { id: 2641, rank: 141, title: "Sad Machine", artist: "Porter Robinson", genre: "EDM", year: 2014, album: "Worlds" },
  { id: 2642, rank: 142, title: "Flicker", artist: "Porter Robinson", genre: "EDM", year: 2014, album: "Worlds" },
  { id: 2643, rank: 143, title: "Sea of Voices", artist: "Porter Robinson", genre: "EDM", year: 2014, album: "Worlds" },
  { id: 2644, rank: 144, title: "Shelter", artist: "Porter Robinson & Madeon", genre: "EDM", year: 2016, album: "Shelter" },
  { id: 2645, rank: 145, title: "Pop Culture", artist: "Madeon", genre: "EDM", year: 2011, album: "Pop Culture" },
  { id: 2646, rank: 146, title: "Finale", artist: "Madeon", genre: "EDM", year: 2015, album: "Adventure" },
  { id: 2647, rank: 147, title: "Pay No Mind", artist: "Madeon ft. Passion Pit", genre: "EDM", year: 2015, album: "Adventure" },
  { id: 2648, rank: 148, title: "Icarus", artist: "Madeon", genre: "EDM", year: 2012, album: "Icarus" },
  { id: 2649, rank: 149, title: "You're On", artist: "Madeon ft. Kucka", genre: "EDM", year: 2015, album: "Adventure" },
  { id: 2650, rank: 150, title: "Rushed to the Altar", artist: "Flume", genre: "EDM", year: 2016, album: "Skin" },
  { id: 2651, rank: 151, title: "Say It", artist: "Flume ft. Tove Lo", genre: "EDM", year: 2016, album: "Skin" },
  { id: 2652, rank: 152, title: "Never Be Like You", artist: "Flume ft. Kai", genre: "EDM", year: 2016, album: "Skin" },
  { id: 2653, rank: 153, title: "Holdin On", artist: "Flume", genre: "EDM", year: 2012, album: "Flume" },
  { id: 2654, rank: 154, title: "Over You", artist: "Flume ft. Chet Faker", genre: "EDM", year: 2012, album: "Flume" },
  { id: 2655, rank: 155, title: "Tennis Courts", artist: "Flume", genre: "EDM", year: 2012, album: "Flume" },
  { id: 2656, rank: 156, title: "Insane", artist: "Flume ft. Moon Holiday", genre: "EDM", year: 2016, album: "Skin" },
  { id: 2657, rank: 157, title: "The Difference", artist: "Flume ft. Toro y Moi", genre: "EDM", year: 2019, album: "Hi This Is Flume" },
  { id: 2658, rank: 158, title: "Ghosts n Stuff", artist: "Deadmau5 ft. Rob Swire", genre: "EDM", year: 2009, album: "For Lack of a Better Name" },
  { id: 2659, rank: 159, title: "Clarity (Radio Edit)", artist: "Zedd", genre: "EDM", year: 2013, album: "Clarity" },
  { id: 2660, rank: 160, title: "Find You", artist: "Zedd ft. Matthew Koma & Miriam Bryant", genre: "EDM", year: 2014, album: "True Colors" },
  { id: 2661, rank: 161, title: "Lost at Sea", artist: "Zedd ft. Ryan Tedder", genre: "EDM", year: 2015, album: "True Colors" },
  { id: 2662, rank: 162, title: "Inside Out", artist: "Zedd ft. Griff", genre: "EDM", year: 2021, album: "Inside Out" },
  { id: 2663, rank: 163, title: "Illusion", artist: "Zedd ft. Echosmith", genre: "EDM", year: 2015, album: "True Colors" },
  { id: 2664, rank: 164, title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics (Tiësto Remix)", genre: "EDM", year: 2002, album: "Sweet Dreams Remix" },
  { id: 2665, rank: 165, title: "Numb / Encore", artist: "Jay-Z & Linkin Park", genre: "EDM", year: 2004, album: "Collision Course" },
  { id: 2666, rank: 166, title: "Midnight City", artist: "M83", genre: "EDM", year: 2011, album: "Hurry Up, We're Dreaming" },
  { id: 2667, rank: 167, title: "Reunion", artist: "M83", genre: "EDM", year: 2011, album: "Hurry Up, We're Dreaming" },
  { id: 2668, rank: 168, title: "Intro", artist: "M83", genre: "EDM", year: 2011, album: "Hurry Up, We're Dreaming" },
  { id: 2669, rank: 169, title: "Youth", artist: "Daughter", genre: "EDM", year: 2013, album: "If You Leave" },
  { id: 2670, rank: 170, title: "Blue (Da Ba Dee)", artist: "Eiffel 65", genre: "EDM", year: 1998, album: "Europop" },
  { id: 2671, rank: 171, title: "Move Your Body", artist: "Eiffel 65", genre: "EDM", year: 1999, album: "Europop" },
  { id: 2672, rank: 172, title: "Kernkraft 400", artist: "Zombie Nation", genre: "EDM", year: 1999, album: "Kernkraft 400" },
  { id: 2673, rank: 173, title: "Better Off Alone", artist: "Alice Deejay", genre: "EDM", year: 1998, album: "Who Needs Guitars Anyway?" },
  { id: 2674, rank: 174, title: "We Speak No Americano", artist: "Yolanda Be Cool & DCUP", genre: "EDM", year: 2010, album: "We Speak No Americano" },
  { id: 2675, rank: 175, title: "Rockin' on the Dancefloor", artist: "Junior Jack", genre: "EDM", year: 2004, album: "Thrill Me" },
  { id: 2676, rank: 176, title: "Right Here, Right Now", artist: "Fatboy Slim", genre: "EDM", year: 1999, album: "You've Come a Long Way, Baby" },
  { id: 2677, rank: 177, title: "Praise You", artist: "Fatboy Slim", genre: "EDM", year: 1999, album: "You've Come a Long Way, Baby" },
  { id: 2678, rank: 178, title: "The Rockafeller Skank", artist: "Fatboy Slim", genre: "EDM", year: 1998, album: "You've Come a Long Way, Baby" },
  { id: 2679, rank: 179, title: "Weapon of Choice", artist: "Fatboy Slim", genre: "EDM", year: 2000, album: "Halfway Between the Gutter and the Stars" },
  { id: 2680, rank: 180, title: "Push the Feeling On", artist: "Nightcrawlers", genre: "EDM", year: 1992, album: "Push the Feeling On" },
  { id: 2681, rank: 181, title: "Where Love Lives", artist: "Alison Limerick", genre: "EDM", year: 1990, album: "And Still I Rise" },
  { id: 2682, rank: 182, title: "Energy Flash", artist: "Joey Beltram", genre: "EDM", year: 1990, album: "Energy Flash" },
  { id: 2683, rank: 183, title: "Stakker Humanoid", artist: "Humanoid", genre: "EDM", year: 1988, album: "Stakker Humanoid" },
  { id: 2684, rank: 184, title: "Pacific State", artist: "808 State", genre: "EDM", year: 1989, album: "Newbuild" },
  { id: 2685, rank: 185, title: "The Theme", artist: "808 State", genre: "EDM", year: 1993, album: "Gorgeous" },
  { id: 2686, rank: 186, title: "French Kiss", artist: "Lil Louis", genre: "EDM", year: 1989, album: "French Kiss" },
  { id: 2687, rank: 187, title: "Strings of Life", artist: "Derrick May", genre: "EDM", year: 1987, album: "Strings of Life" },
  { id: 2688, rank: 188, title: "Big Fun", artist: "Inner City", genre: "EDM", year: 1988, album: "Paradise" },
  { id: 2689, rank: 189, title: "Good Life", artist: "Inner City", genre: "EDM", year: 1988, album: "Paradise" },
  { id: 2690, rank: 190, title: "Music Sounds Better with You", artist: "Stardust", genre: "EDM", year: 1998, album: "Music Sounds Better with You" },
  { id: 2691, rank: 191, title: "Needin' U", artist: "David Morales", genre: "EDM", year: 1998, album: "Needin' U" },
  { id: 2692, rank: 192, title: "Show Me Love", artist: "Robin S.", genre: "EDM", year: 1990, album: "Show Me Love" },
  { id: 2693, rank: 193, title: "Finally", artist: "CeCe Peniston", genre: "EDM", year: 1991, album: "Finally" },
  { id: 2694, rank: 194, title: "What Is Love", artist: "Haddaway", genre: "EDM", year: 1993, album: "The Album" },
  { id: 2695, rank: 195, title: "The Power", artist: "Snap!", genre: "EDM", year: 1990, album: "World Power" },
  { id: 2696, rank: 196, title: "Rhythm Is a Dancer", artist: "Snap!", genre: "EDM", year: 1992, album: "The Madman's Return" },
  { id: 2697, rank: 197, title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory", genre: "EDM", year: 1990, album: "Gonna Make You Sweat" },
  { id: 2698, rank: 198, title: "Together", artist: "Solu Music ft. Kimblee", genre: "EDM", year: 2001, album: "Solu Music" },
  { id: 2699, rank: 199, title: "Crave You", artist: "Flight Facilities ft. Giselle", genre: "EDM", year: 2010, album: "Crave You" },
  { id: 2700, rank: 200, title: "Trembling", artist: "Duke Dumont", genre: "EDM", year: 2015, album: "Duality" },
  { id: 2701, rank: 201, title: "I Got U", artist: "Duke Dumont ft. Jax Jones", genre: "EDM", year: 2014, album: "I Got U" },
  { id: 2702, rank: 202, title: "Need U (100%)", artist: "Duke Dumont ft. A*M*E", genre: "EDM", year: 2013, album: "Need U (100%)" },
  { id: 2703, rank: 203, title: "Ocean Drive", artist: "Duke Dumont", genre: "EDM", year: 2015, album: "Duality" },
  { id: 2704, rank: 204, title: "Spectrum", artist: "Zedd ft. Matthew Koma", genre: "EDM", year: 2012, album: "Clarity" },
  { id: 2705, rank: 205, title: "Keep Your Head Up", artist: "Martin Garrix & Matisse & Sadko", genre: "EDM", year: 2020, album: "Keep Your Head Up" },
  { id: 2706, rank: 206, title: "In the Name of Love", artist: "Martin Garrix & Bebe Rexha", genre: "EDM", year: 2016, album: "In the Name of Love" },
  { id: 2707, rank: 207, title: "Scared to Be Lonely", artist: "Martin Garrix & Dua Lipa", genre: "EDM", year: 2017, album: "Scared to Be Lonely" },
  { id: 2708, rank: 208, title: "Tremor", artist: "Martin Garrix & Dimitri Vegas & Like Mike", genre: "EDM", year: 2014, album: "Tremor" },
  { id: 2709, rank: 209, title: "BYOB", artist: "Martin Garrix", genre: "EDM", year: 2015, album: "BYOB" },
  { id: 2710, rank: 210, title: "Forbidden Voices", artist: "Martin Garrix", genre: "EDM", year: 2014, album: "Forbidden Voices" },
  { id: 2711, rank: 211, title: "Waiting for Tomorrow", artist: "Martin Garrix ft. Pierce Fulton & Mike Shinoda", genre: "EDM", year: 2019, album: "Waiting for Tomorrow" },
  { id: 2712, rank: 212, title: "Pizza", artist: "Martin Garrix", genre: "EDM", year: 2013, album: "Pizza" },
  { id: 2713, rank: 213, title: "Break Through the Silence", artist: "Martin Garrix", genre: "EDM", year: 2016, album: "Break Through the Silence" },
  { id: 2714, rank: 214, title: "Won't Let You Go", artist: "Martin Garrix ft. Julian Jordan", genre: "EDM", year: 2016, album: "Won't Let You Go" },
  { id: 2715, rank: 215, title: "The Only Way Is Up", artist: "Martin Garrix ft. Tiësto", genre: "EDM", year: 2015, album: "The Only Way Is Up" },
  { id: 2716, rank: 216, title: "Dusk Till Dawn", artist: "ZAYN ft. Sia", genre: "EDM", year: 2017, album: "Icarus Falls" },
  { id: 2717, rank: 217, title: "Cold Water", artist: "Major Lazer ft. Justin Bieber & MØ", genre: "EDM", year: 2016, album: "Music Is the Weapon" },
  { id: 2718, rank: 218, title: "Powerful", artist: "Major Lazer ft. Ellie Goulding & Tarrus Riley", genre: "EDM", year: 2015, album: "Peace Is the Mission" },
  { id: 2719, rank: 219, title: "Run the World (Girls)", artist: "Beyoncé", genre: "EDM", year: 2011, album: "4" },
  { id: 2720, rank: 220, title: "Promises", artist: "Calvin Harris & Sam Smith", genre: "EDM", year: 2018, album: "Funk Wav Bounces Vol. 1" },
  { id: 2721, rank: 221, title: "Slide", artist: "Calvin Harris ft. Frank Ocean & Migos", genre: "EDM", year: 2017, album: "Funk Wav Bounces Vol. 1" },
  { id: 2722, rank: 222, title: "Rollin", artist: "Calvin Harris ft. Future & Khalid", genre: "EDM", year: 2017, album: "Funk Wav Bounces Vol. 1" },
  { id: 2723, rank: 223, title: "How Deep Is Your Love", artist: "Calvin Harris & Disciples", genre: "EDM", year: 2015, album: "How Deep Is Your Love" },
  { id: 2724, rank: 224, title: "Outside", artist: "Calvin Harris ft. Ellie Goulding", genre: "EDM", year: 2014, album: "Motion" },
  { id: 2725, rank: 225, title: "Acceptable in the 80s", artist: "Calvin Harris", genre: "EDM", year: 2007, album: "I Created Disco" },
  { id: 2726, rank: 226, title: "Bounce", artist: "Calvin Harris ft. Kelis", genre: "EDM", year: 2011, album: "18 Months" },
  { id: 2727, rank: 227, title: "Thinking About You", artist: "Calvin Harris ft. Ayah Marar", genre: "EDM", year: 2012, album: "18 Months" },
  { id: 2728, rank: 228, title: "Sweet Nothing", artist: "Calvin Harris ft. Florence Welch", genre: "EDM", year: 2012, album: "18 Months" },
  { id: 2729, rank: 229, title: "Drinking from the Bottle", artist: "Calvin Harris ft. Tinie Tempah", genre: "EDM", year: 2012, album: "18 Months" },
  { id: 2730, rank: 230, title: "Flashback", artist: "Calvin Harris", genre: "EDM", year: 2009, album: "Ready for the Weekend" },
  { id: 2731, rank: 231, title: "Reason (I Need You)", artist: "Nervo ft. Ollie James", genre: "EDM", year: 2011, album: "Reason" },
  { id: 2732, rank: 232, title: "Tomorrow Can Wait", artist: "Nervo ft. Hook N Sling & Devin Hoff", genre: "EDM", year: 2013, album: "Collateral" },
  { id: 2733, rank: 233, title: "Calling (Lose My Mind)", artist: "Sebastian Ingrosso & Alesso ft. Ryan Tedder", genre: "EDM", year: 2012, album: "Calling" },
  { id: 2734, rank: 234, title: "Tear the Roof Up", artist: "Alesso", genre: "EDM", year: 2015, album: "Forever" },
  { id: 2735, rank: 235, title: "Years", artist: "Alesso ft. Matthew Koma", genre: "EDM", year: 2013, album: "Years" },
  { id: 2736, rank: 236, title: "Heroes (We Could Be)", artist: "Alesso ft. Tove Lo", genre: "EDM", year: 2014, album: "Forever" },
  { id: 2737, rank: 237, title: "Cool", artist: "Alesso ft. Roy English", genre: "EDM", year: 2015, album: "Forever" },
  { id: 2738, rank: 238, title: "I Wanna Know", artist: "Alesso ft. Nico & Vinz", genre: "EDM", year: 2019, album: "I Wanna Know" },
  { id: 2739, rank: 239, title: "If I Lose Myself", artist: "OneRepublic", genre: "EDM", year: 2012, album: "Native" },
  { id: 2740, rank: 240, title: "Closer", artist: "Lemaitre", genre: "EDM", year: 2013, album: "Relativity" },
  { id: 2741, rank: 241, title: "Take Me to Church", artist: "Hozier", genre: "EDM", year: 2013, album: "Hozier" },
  { id: 2742, rank: 242, title: "Echo", artist: "Tiësto & Jacqueline", genre: "EDM", year: 2014, album: "A Town Called Paradise" },
  { id: 2743, rank: 243, title: "The Business", artist: "Tiësto", genre: "EDM", year: 2020, album: "The Business" },
  { id: 2744, rank: 244, title: "Don't Be Shy", artist: "Tiësto & Karol G", genre: "EDM", year: 2021, album: "Don't Be Shy" },
  { id: 2745, rank: 245, title: "Boom", artist: "Tiësto & Sevenn", genre: "EDM", year: 2017, album: "Boom" },
  { id: 2746, rank: 246, title: "Wasted", artist: "Tiësto ft. Matthew Koma", genre: "EDM", year: 2014, album: "A Town Called Paradise" },
  { id: 2747, rank: 247, title: "Maximal Crazy", artist: "Tiësto ft. Kirsty Hawkshaw", genre: "EDM", year: 2007, album: "Elements of Life" },
  { id: 2748, rank: 248, title: "Lethal Industry", artist: "Tiësto", genre: "EDM", year: 2002, album: "In My Memory" },
  { id: 2749, rank: 249, title: "In My Memory", artist: "Tiësto ft. Susana", genre: "EDM", year: 2001, album: "In My Memory" },
  { id: 2750, rank: 250, title: "Flight 643", artist: "Tiësto", genre: "EDM", year: 2001, album: "In My Memory" },
  { id: 2751, rank: 251, title: "Escape Me", artist: "Tiësto ft. CC Sheffield", genre: "EDM", year: 2009, album: "Kaleidoscope" },
  { id: 2752, rank: 252, title: "I Will Be Here", artist: "Tiësto ft. Kele", genre: "EDM", year: 2011, album: "Club Life Vol. 2" },
  { id: 2753, rank: 253, title: "Under My Skin", artist: "Sander van Doorn", genre: "EDM", year: 2009, album: "Supernova" },
  { id: 2754, rank: 254, title: "Nothing Inside", artist: "Sander van Doorn", genre: "EDM", year: 2010, album: "Supernova" },
  { id: 2755, rank: 255, title: "Spooky (Original Mix)", artist: "Sander van Doorn", genre: "EDM", year: 2007, album: "Purple Box" },
  { id: 2756, rank: 256, title: "Gold Skies", artist: "Sander van Doorn, Martin Garrix & DVBBS ft. Aleesia", genre: "EDM", year: 2014, album: "Gold Skies" },
  { id: 2757, rank: 257, title: "Raven", artist: "DVBBS & Borgeous", genre: "EDM", year: 2013, album: "Raven" },
  { id: 2758, rank: 258, title: "Tsunami", artist: "DVBBS & Borgeous", genre: "EDM", year: 2013, album: "Tsunami" },
  { id: 2759, rank: 259, title: "Stampede", artist: "Hardwell & Maddix", genre: "EDM", year: 2018, album: "Stampede" },
  { id: 2760, rank: 260, title: "Dare You", artist: "Hardwell ft. Matthew Koma", genre: "EDM", year: 2013, album: "Dare You" },
  { id: 2761, rank: 261, title: "Three Triangles", artist: "Hardwell", genre: "EDM", year: 2012, album: "Three Triangles" },
  { id: 2762, rank: 262, title: "Spaceman", artist: "Hardwell & Dannic", genre: "EDM", year: 2013, album: "Spaceman" },
  { id: 2763, rank: 263, title: "United We Are", artist: "Hardwell ft. Amba Shepherd", genre: "EDM", year: 2014, album: "United We Are" },
  { id: 2764, rank: 264, title: "Camelot", artist: "Hardwell", genre: "EDM", year: 2011, album: "Camelot" },
  { id: 2765, rank: 265, title: "Encoded", artist: "Hardwell", genre: "EDM", year: 2012, album: "Encoded" },
  { id: 2766, rank: 266, title: "Frequency", artist: "Hardwell", genre: "EDM", year: 2012, album: "Frequency" },
  { id: 2767, rank: 267, title: "Apollo", artist: "Hardwell ft. Amba Shepherd", genre: "EDM", year: 2012, album: "Apollo" },
  { id: 2768, rank: 268, title: "Thinking About You", artist: "Nora En Pure", genre: "EDM", year: 2016, album: "Thinking About You" },
  { id: 2769, rank: 269, title: "Come with Me", artist: "Nora En Pure", genre: "EDM", year: 2015, album: "Come with Me" },
  { id: 2770, rank: 270, title: "Tryst", artist: "Nora En Pure", genre: "EDM", year: 2015, album: "Tryst" },
  { id: 2771, rank: 271, title: "Wetlands", artist: "Nora En Pure", genre: "EDM", year: 2017, album: "Wetlands" },
  { id: 2772, rank: 272, title: "Lost in You", artist: "Ilan Bluestone", genre: "EDM", year: 2016, album: "Lost in You" },
  { id: 2773, rank: 273, title: "Spheres", artist: "Ilan Bluestone", genre: "EDM", year: 2017, album: "Spheres" },
  { id: 2774, rank: 274, title: "No Good (Start the Dance)", artist: "The Prodigy", genre: "EDM", year: 1994, album: "Music for the Jilted Generation" },
  { id: 2775, rank: 275, title: "One Love", artist: "The Prodigy", genre: "EDM", year: 1993, album: "Experience" },
  { id: 2776, rank: 276, title: "Everybody in the Place", artist: "The Prodigy", genre: "EDM", year: 1991, album: "Experience" },
  { id: 2777, rank: 277, title: "Charly", artist: "The Prodigy", genre: "EDM", year: 1991, album: "Experience" },
  { id: 2778, rank: 278, title: "Out of Space", artist: "The Prodigy", genre: "EDM", year: 1992, album: "Experience" },
  { id: 2779, rank: 279, title: "Their Law", artist: "The Prodigy ft. Pop Will Eat Itself", genre: "EDM", year: 1994, album: "Music for the Jilted Generation" },
  { id: 2780, rank: 280, title: "Mindfields", artist: "The Prodigy", genre: "EDM", year: 1997, album: "The Fat of the Land" },
  { id: 2781, rank: 281, title: "Smack My Bitch Up", artist: "The Prodigy", genre: "EDM", year: 1997, album: "The Fat of the Land" },
  { id: 2782, rank: 282, title: "Stand Up", artist: "The Prodigy", genre: "EDM", year: 2004, album: "Always Outnumbered, Never Outgunned" },
  { id: 2783, rank: 283, title: "Narayan", artist: "The Prodigy ft. Shahin Badar", genre: "EDM", year: 1997, album: "The Fat of the Land" },
  { id: 2784, rank: 284, title: "Poison", artist: "The Prodigy", genre: "EDM", year: 1995, album: "Music for the Jilted Generation" },
  { id: 2785, rank: 285, title: "Animals", artist: "The Prodigy", genre: "EDM", year: 2015, album: "The Day Is My Enemy" },
  { id: 2786, rank: 286, title: "Lullaby for a Sadist", artist: "The Prodigy", genre: "EDM", year: 2015, album: "The Day Is My Enemy" },
  { id: 2787, rank: 287, title: "Thunder", artist: "The Prodigy", genre: "EDM", year: 2018, album: "No Tourists" },
  { id: 2788, rank: 288, title: "Need Some1", artist: "The Prodigy", genre: "EDM", year: 2018, album: "No Tourists" },
  { id: 2789, rank: 289, title: "How I Play", artist: "Pleasurekraft", genre: "EDM", year: 2014, album: "How I Play" },
  { id: 2790, rank: 290, title: "Talamanca", artist: "Pleasurekraft", genre: "EDM", year: 2012, album: "Talamanca" },
  { id: 2791, rank: 291, title: "Stay", artist: "Diplo & Sidepiece", genre: "EDM", year: 2021, album: "Stay" },
  { id: 2792, rank: 292, title: "Boom", artist: "Diplo ft. Lil Pump, Juicy J & Damian Marley", genre: "EDM", year: 2019, album: "Thomas Wesley Chapter 1: Snake Oil" },
  { id: 2793, rank: 293, title: "Revolution", artist: "Diplo ft. Faustix & Imanos & Kai", genre: "EDM", year: 2015, album: "Revolution" },
  { id: 2794, rank: 294, title: "Express Yourself", artist: "Diplo ft. Nicky Da B", genre: "EDM", year: 2012, album: "Express Yourself" },
  { id: 2795, rank: 295, title: "Wave", artist: "Diplo ft. Trippie Redd", genre: "EDM", year: 2021, album: "Thomas Wesley Chapter 2: Swamp Savant" },
  { id: 2796, rank: 296, title: "Take Ü There", artist: "Jack Ü (Skrillex & Diplo) ft. Kiesza", genre: "EDM", year: 2014, album: "Skrillex and Diplo Present Jack Ü" },
  { id: 2797, rank: 297, title: "Where Are Ü Now", artist: "Jack Ü ft. Justin Bieber", genre: "EDM", year: 2015, album: "Skrillex and Diplo Present Jack Ü" },
  { id: 2798, rank: 298, title: "Breathe", artist: "Skrillex & J Balvin", genre: "EDM", year: 2021, album: "Breathe" },
  { id: 2799, rank: 299, title: "First of the Year (Equinox)", artist: "Skrillex", genre: "EDM", year: 2011, album: "Bangarang" },
  { id: 2800, rank: 300, title: "Bangarang", artist: "Skrillex ft. Sirah", genre: "EDM", year: 2011, album: "Bangarang" },
  { id: 2801, rank: 301, title: "Cinema", artist: "Skrillex ft. Benny Benassi", genre: "EDM", year: 2011, album: "Cinema" },
  { id: 2802, rank: 302, title: "Breakn' a Sweat", artist: "Skrillex & The Doors", genre: "EDM", year: 2011, album: "Breakn' a Sweat" },
  { id: 2803, rank: 303, title: "Summit", artist: "Skrillex ft. Ellie Goulding", genre: "EDM", year: 2011, album: "Summit" },
  { id: 2804, rank: 304, title: "Kill Everybody", artist: "Skrillex", genre: "EDM", year: 2010, album: "My Name Is Skrillex" },
  { id: 2805, rank: 305, title: "Rock n Roll (Will Take You to the Mountain)", artist: "Skrillex", genre: "EDM", year: 2010, album: "My Name Is Skrillex" },
  { id: 2806, rank: 306, title: "Kyoto", artist: "Skrillex & Sirah", genre: "EDM", year: 2015, album: "Recess" },
  { id: 2807, rank: 307, title: "Recess", artist: "Skrillex ft. Kill the Noise & Fatman Scoop", genre: "EDM", year: 2014, album: "Recess" },
  { id: 2808, rank: 308, title: "Ease My Mind", artist: "Ben Pearce", genre: "EDM", year: 2013, album: "Ease My Mind" },
  { id: 2809, rank: 309, title: "The Feels", artist: "Snakehips ft. Tinashe & Chance the Rapper", genre: "EDM", year: 2015, album: "The Feels" },
  { id: 2810, rank: 310, title: "All My Friends", artist: "Snakehips ft. Tinashe & Chance the Rapper", genre: "EDM", year: 2015, album: "All My Friends" },
  { id: 2811, rank: 311, title: "Revolution", artist: "Steve Aoki, Nervo & The Cataracs ft. NERVO", genre: "EDM", year: 2011, album: "Revolution" },
  { id: 2812, rank: 312, title: "Coming Home", artist: "Diddy ft. Skylar Grey", genre: "EDM", year: 2010, album: "Last Train to Paris" },
  { id: 2813, rank: 313, title: "Let Her Go", artist: "Passenger", genre: "EDM", year: 2012, album: "All the Little Lights" },
  { id: 2814, rank: 314, title: "Radioactive", artist: "Imagine Dragons", genre: "EDM", year: 2012, album: "Night Visions" },
  { id: 2815, rank: 315, title: "Spectrum (Say My Name)", artist: "Florence + The Machine", genre: "EDM", year: 2011, album: "Ceremonials" },
  { id: 2816, rank: 316, title: "Silhouette", artist: "Kiesza", genre: "EDM", year: 2014, album: "Sound of a Woman" },
  { id: 2817, rank: 317, title: "Hideaway", artist: "Kiesza", genre: "EDM", year: 2014, album: "Sound of a Woman" },
  { id: 2818, rank: 318, title: "Overdose", artist: "Zara Larsson ft. Wiz Khalifa", genre: "EDM", year: 2017, album: "So Good" },
  { id: 2819, rank: 319, title: "Latch", artist: "Disclosure ft. Sam Smith", genre: "EDM", year: 2012, album: "Settle" },
  { id: 2820, rank: 320, title: "White Noise", artist: "Disclosure ft. AlunaGeorge", genre: "EDM", year: 2012, album: "Settle" },
  { id: 2821, rank: 321, title: "You & Me", artist: "Disclosure ft. Eliza Doolittle", genre: "EDM", year: 2013, album: "Settle" },
  { id: 2822, rank: 322, title: "Help Me Lose My Mind", artist: "Disclosure ft. London Grammar", genre: "EDM", year: 2013, album: "Settle" },
  { id: 2823, rank: 323, title: "Magnets", artist: "Disclosure ft. Lorde", genre: "EDM", year: 2015, album: "Caracal" },
  { id: 2824, rank: 324, title: "Omen", artist: "Disclosure ft. Sam Smith", genre: "EDM", year: 2015, album: "Caracal" },
  { id: 2825, rank: 325, title: "Holding On", artist: "Disclosure ft. Gregory Porter", genre: "EDM", year: 2015, album: "Caracal" },
  { id: 2826, rank: 326, title: "Caracal", artist: "Disclosure", genre: "EDM", year: 2015, album: "Caracal" },
  { id: 2827, rank: 327, title: "Where Angels Fear", artist: "Rush", genre: "EDM", year: 2002, album: "Vapor Trails" },
  { id: 2828, rank: 328, title: "Touch", artist: "Daft Punk ft. Paul Williams", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2829, rank: 329, title: "Fragments of Time", artist: "Daft Punk ft. Todd Edwards", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2830, rank: 330, title: "Give Life Back to Music", artist: "Daft Punk", genre: "EDM", year: 2013, album: "Random Access Memories" },
  { id: 2831, rank: 331, title: "The Game of Love", artist: "Daft Punk ft. Romanthony", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2832, rank: 332, title: "Veridis Quo", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2833, rank: 333, title: "Something About Us", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2834, rank: 334, title: "Aerodynamic", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2835, rank: 335, title: "Face to Face", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2836, rank: 336, title: "Crescendolls", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2837, rank: 337, title: "High Life", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2838, rank: 338, title: "Short Circuit", artist: "Daft Punk", genre: "EDM", year: 2001, album: "Discovery" },
  { id: 2839, rank: 339, title: "Indo Silver Club", artist: "Daft Punk", genre: "EDM", year: 1997, album: "Homework" },
  { id: 2840, rank: 340, title: "Revolution 909", artist: "Daft Punk", genre: "EDM", year: 1997, album: "Homework" },
  { id: 2841, rank: 341, title: "Burnin'", artist: "Daft Punk", genre: "EDM", year: 1997, album: "Homework" },
  { id: 2842, rank: 342, title: "Phoenix", artist: "Fall Out Boy", genre: "EDM", year: 2013, album: "Save Rock and Roll" },
  { id: 2843, rank: 343, title: "Get Together", artist: "Madonna", genre: "EDM", year: 2005, album: "Confessions on a Dance Floor" },
  { id: 2844, rank: 344, title: "Hung Up", artist: "Madonna", genre: "EDM", year: 2005, album: "Confessions on a Dance Floor" },
  { id: 2845, rank: 345, title: "Jump", artist: "Madonna", genre: "EDM", year: 2005, album: "Confessions on a Dance Floor" },
  { id: 2846, rank: 346, title: "4 Minutes", artist: "Madonna ft. Justin Timberlake & Timbaland", genre: "EDM", year: 2008, album: "Hard Candy" },
  { id: 2847, rank: 347, title: "Girls Aloud", artist: "Girls Aloud", genre: "EDM", year: 2009, album: "Out of Control" },
  { id: 2848, rank: 348, title: "Give Me Everything", artist: "Pitbull ft. Ne-Yo, Afrojack & Nayer", genre: "EDM", year: 2011, album: "Planet Pit" },
  { id: 2849, rank: 349, title: "Can't Stop the Feeling!", artist: "Justin Timberlake", genre: "EDM", year: 2016, album: "Trolls Original Motion Picture Soundtrack" },
  { id: 2850, rank: 350, title: "Wild Ones", artist: "Flo Rida ft. Sia", genre: "EDM", year: 2011, album: "Wild Ones" },
  { id: 2851, rank: 351, title: "Show Me the Way", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2008, album: "Tri-State" },
  { id: 2852, rank: 352, title: "Can't Sleep", artist: "Above & Beyond ft. Richard Bedford", genre: "EDM", year: 2011, album: "Group Therapy" },
  { id: 2853, rank: 353, title: "Sun & Moon", artist: "Above & Beyond ft. Richard Bedford", genre: "EDM", year: 2011, album: "Group Therapy" },
  { id: 2854, rank: 354, title: "Alchemy", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2011, album: "Group Therapy" },
  { id: 2855, rank: 355, title: "Alone Tonight", artist: "Above & Beyond ft. Richard Bedford", genre: "EDM", year: 2016, album: "Common Ground" },
  { id: 2856, rank: 356, title: "Always", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2016, album: "Common Ground" },
  { id: 2857, rank: 357, title: "Northern Soul", artist: "Above & Beyond ft. Justine Suissa", genre: "EDM", year: 2004, album: "Tri-State" },
  { id: 2858, rank: 358, title: "Good for Me", artist: "Above & Beyond ft. Alex Vargas", genre: "EDM", year: 2016, album: "Common Ground" },
  { id: 2859, rank: 359, title: "Making of Me", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2016, album: "Common Ground" },
  { id: 2860, rank: 360, title: "Love Is Not Enough", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2016, album: "Common Ground" },
  { id: 2861, rank: 361, title: "Blue Sky Action", artist: "Above & Beyond ft. Alex Vargas", genre: "EDM", year: 2014, album: "We Are All We Need" },
  { id: 2862, rank: 362, title: "We're All We Need", artist: "Above & Beyond ft. Zoë Johnston", genre: "EDM", year: 2014, album: "We Are All We Need" },
  { id: 2863, rank: 363, title: "Thomas Straight", artist: "Ferry Corsten ft. Cass Fox", genre: "EDM", year: 2012, album: "Now & Then" },
  { id: 2864, rank: 364, title: "Zocalo", artist: "BT", genre: "EDM", year: 2002, album: "Emotional Technology" },
  { id: 2865, rank: 365, title: "Simply Being Loved", artist: "BT ft. Jan Johnston", genre: "EDM", year: 1999, album: "Movement in Still Life" },
  { id: 2866, rank: 366, title: "Flaming June", artist: "BT", genre: "EDM", year: 1997, album: "ESCM" },
  { id: 2867, rank: 367, title: "Remember", artist: "BT ft. Jan Johnston", genre: "EDM", year: 1997, album: "ESCM" },
  { id: 2868, rank: 368, title: "Dreaming", artist: "BT ft. Kirsty Hawkshaw", genre: "EDM", year: 2003, album: "Emotional Technology" },
  { id: 2869, rank: 369, title: "Seven Cities", artist: "Solar Stone", genre: "EDM", year: 1999, album: "Seven Cities" },
  { id: 2870, rank: 370, title: "Underwater", artist: "Delerium ft. Rani", genre: "EDM", year: 2001, album: "Poem" },
  { id: 2871, rank: 371, title: "Silence", artist: "Delerium ft. Sarah McLachlan", genre: "EDM", year: 1999, album: "Poem" },
  { id: 2872, rank: 372, title: "Heaven", artist: "Delerium ft. Jael", genre: "EDM", year: 2001, album: "Poem" },
  { id: 2873, rank: 373, title: "Fade to Grey", artist: "Visage", genre: "EDM", year: 1980, album: "Visage" },
  { id: 2874, rank: 374, title: "Unfinished Sympathy", artist: "Massive Attack", genre: "EDM", year: 1991, album: "Blue Lines" },
  { id: 2875, rank: 375, title: "Teardrop", artist: "Massive Attack", genre: "EDM", year: 1998, album: "Mezzanine" },
  { id: 2876, rank: 376, title: "Safe from Harm", artist: "Massive Attack", genre: "EDM", year: 1991, album: "Blue Lines" },
  { id: 2877, rank: 377, title: "Angel", artist: "Massive Attack", genre: "EDM", year: 1998, album: "Mezzanine" },
  { id: 2878, rank: 378, title: "Paradise Circus", artist: "Massive Attack", genre: "EDM", year: 2010, album: "Heligoland" },
  { id: 2879, rank: 379, title: "Atlas", artist: "Coldplay", genre: "EDM", year: 2013, album: "Atlas" },
  { id: 2880, rank: 380, title: "A Sky Full of Stars", artist: "Coldplay ft. Avicii", genre: "EDM", year: 2014, album: "Ghost Stories" },
  { id: 2881, rank: 381, title: "RITMO (Bad Boys for Life)", artist: "Black Eyed Peas & J Balvin", genre: "EDM", year: 2019, album: "Translation" },
  { id: 2882, rank: 382, title: "I Gotta Feeling", artist: "Black Eyed Peas", genre: "EDM", year: 2009, album: "The E.N.D." },
  { id: 2883, rank: 383, title: "Boom Boom", artist: "Black Eyed Peas ft. RedOne, Daddy Yankee & Dinah Jane", genre: "EDM", year: 2016, album: "Masters of the Sun Vol. 1" },
  { id: 2884, rank: 384, title: "Pump It", artist: "Black Eyed Peas", genre: "EDM", year: 2006, album: "Monkey Business" },
  { id: 2885, rank: 385, title: "Bailando", artist: "Enrique Iglesias ft. Descemer Bueno & Gente de Zona", genre: "EDM", year: 2014, album: "Sex and Love" },
  { id: 2886, rank: 386, title: "Drop the World", artist: "Lil Wayne ft. Eminem", genre: "EDM", year: 2009, album: "Rebirth" },
  { id: 2887, rank: 387, title: "Midnight", artist: "Coldplay", genre: "EDM", year: 2014, album: "Ghost Stories" },
  { id: 2888, rank: 388, title: "Hysteria", artist: "Def Leppard", genre: "EDM", year: 1987, album: "Hysteria" },
  { id: 2889, rank: 389, title: "Show Me Love", artist: "Sam Feldt ft. Kimberly Anne", genre: "EDM", year: 2015, album: "Show Me Love" },
  { id: 2890, rank: 390, title: "Post Malone", artist: "Sam Feldt ft. ROZES", genre: "EDM", year: 2015, album: "Post Malone" },
  { id: 2891, rank: 391, title: "Teardrops", artist: "Sam Feldt & Niles Mason", genre: "EDM", year: 2021, album: "Teardrops" },
  { id: 2892, rank: 392, title: "Gold", artist: "Kiiara", genre: "EDM", year: 2015, album: "Gold" },
  { id: 2893, rank: 393, title: "Flame", artist: "Tinlicker ft. Helsloot", genre: "EDM", year: 2020, album: "This Is Not Our Universe" },
  { id: 2894, rank: 394, title: "Save Me", artist: "Meduza & Becky Hill & Goodboys", genre: "EDM", year: 2021, album: "Save Me" },
  { id: 2895, rank: 395, title: "Piece of Your Heart", artist: "Meduza ft. Goodboys", genre: "EDM", year: 2019, album: "Piece of Your Heart" },
  { id: 2896, rank: 396, title: "Paradise", artist: "Meduza ft. Dermot Kennedy", genre: "EDM", year: 2021, album: "Paradise" },
  { id: 2897, rank: 397, title: "Lose Control", artist: "Meduza ft. Becky Hill & Goodboys", genre: "EDM", year: 2022, album: "Lose Control" },
  { id: 2898, rank: 398, title: "One Last Dance", artist: "Purple Disco Machine & Boss Doms ft. Eyelar", genre: "EDM", year: 2020, album: "Firefly" },
  { id: 2899, rank: 399, title: "Dished (Male Stripper)", artist: "Purple Disco Machine", genre: "EDM", year: 2020, album: "Firefly" },
  { id: 2900, rank: 400, title: "Fireworks", artist: "Purple Disco Machine & Burns", genre: "EDM", year: 2020, album: "Firefly" },
  { id: 2901, rank: 401, title: "Tinted Love", artist: "Purple Disco Machine ft. Sophie and the Giants", genre: "EDM", year: 2020, album: "Firefly" },
  { id: 2902, rank: 402, title: "Body Funk", artist: "Purple Disco Machine", genre: "EDM", year: 2018, album: "Soulmatic" },
  { id: 2903, rank: 403, title: "Hypnotized", artist: "Purple Disco Machine ft. Sophie and the Giants", genre: "EDM", year: 2020, album: "Firefly" },
  { id: 2904, rank: 404, title: "Feel the Heat", artist: "Purple Disco Machine & Bosq ft. Kaleta", genre: "EDM", year: 2021, album: "Exotica" },
  { id: 2905, rank: 405, title: "Playful Minds", artist: "Purple Disco Machine", genre: "EDM", year: 2023, album: "Exotica" },
  { id: 2906, rank: 406, title: "Teachers", artist: "Daft Punk", genre: "EDM", year: 1997, album: "Homework" },
  { id: 2907, rank: 407, title: "Waiting", artist: "Armin van Buuren ft. Sonja Aldén", genre: "EDM", year: 2013, album: "Intense" },
  { id: 2908, rank: 408, title: "Intense", artist: "Armin van Buuren ft. Miri Ben-Ari", genre: "EDM", year: 2012, album: "Intense" },
  { id: 2909, rank: 409, title: "These Silent Hearts", artist: "Armin van Buuren ft. Ana Criado", genre: "EDM", year: 2014, album: "Intense" },
  { id: 2910, rank: 410, title: "Music Is Life", artist: "Benny Benassi", genre: "EDM", year: 2013, album: "Electroman" },
  { id: 2911, rank: 411, title: "Satisfaction", artist: "Benny Benassi", genre: "EDM", year: 2002, album: "Hypnotica" },
  { id: 2912, rank: 412, title: "Who's Your Daddy", artist: "Benny Benassi ft. The Biz", genre: "EDM", year: 2003, album: "Hypnotica" },
  { id: 2913, rank: 413, title: "Illusion", artist: "Benny Benassi ft. Channing", genre: "EDM", year: 2010, album: "Electroman" },
  { id: 2914, rank: 414, title: "Love Is Gonna Save Us", artist: "Benny Benassi ft. Sandy", genre: "EDM", year: 2004, album: "Hypnotica" },
  { id: 2915, rank: 415, title: "Spaceship", artist: "Hardwell", genre: "EDM", year: 2016, album: "Spaceship" },
  { id: 2916, rank: 416, title: "Run Wild", artist: "DVBBS ft. Shaun Frank & Delaney Jane", genre: "EDM", year: 2015, album: "Run Wild" },
  { id: 2917, rank: 417, title: "Not Going Home", artist: "DVBBS & CMC$", genre: "EDM", year: 2015, album: "Not Going Home" },
  { id: 2918, rank: 418, title: "Die Another Night", artist: "DVBBS & CMC$", genre: "EDM", year: 2014, album: "Die Another Night" },
  { id: 2919, rank: 419, title: "Touch Me", artist: "Rui Da Silva ft. Cassandra", genre: "EDM", year: 2000, album: "Touch Me" },
  { id: 2920, rank: 420, title: "Cafe Del Mar", artist: "Energy 52", genre: "EDM", year: 1993, album: "Cafe Del Mar" },
  { id: 2921, rank: 421, title: "Be with You", artist: "ATB", genre: "EDM", year: 2005, album: "No Silence" },
  { id: 2922, rank: 422, title: "9 PM (Till I Come)", artist: "ATB", genre: "EDM", year: 1998, album: "Movin' Melodies" },
  { id: 2923, rank: 423, title: "Killer", artist: "ATB", genre: "EDM", year: 2000, album: "Two Worlds" },
  { id: 2924, rank: 424, title: "Ecstasy", artist: "ATB", genre: "EDM", year: 1999, album: "Movin' Melodies" },
  { id: 2925, rank: 425, title: "Let U Go", artist: "ATB", genre: "EDM", year: 2001, album: "Two Worlds" },
  { id: 2926, rank: 426, title: "Fine Day (2001 Mix)", artist: "Opus III", genre: "EDM", year: 2001, album: "Fine Day" },
  { id: 2927, rank: 427, title: "It's a Fine Day", artist: "Opus III", genre: "EDM", year: 1992, album: "Mind Fruit" },
  { id: 2928, rank: 428, title: "Roar", artist: "Katy Perry", genre: "EDM", year: 2013, album: "Prism" },
  { id: 2929, rank: 429, title: "Wasted on You", artist: "Tiësto ft. Madison Beer", genre: "EDM", year: 2020, album: "The London Sessions" },
  { id: 2930, rank: 430, title: "The Night Is Still Young", artist: "Nicki Minaj", genre: "EDM", year: 2015, album: "The Pinkprint" },
  { id: 2931, rank: 431, title: "Out of My Mind", artist: "Dimitri Vegas & Like Mike ft. Julian Perretta", genre: "EDM", year: 2014, album: "Out of My Mind" },
  { id: 2932, rank: 432, title: "Stay a While", artist: "Dimitri Vegas & Like Mike ft. Ain't Afraid", genre: "EDM", year: 2018, album: "Bringing the Madness" },
  { id: 2933, rank: 433, title: "Mammoth", artist: "Dimitri Vegas & Like Mike ft. Moguai", genre: "EDM", year: 2014, album: "Mammoth" },
  { id: 2934, rank: 434, title: "Higher Ground", artist: "Martin Garrix & John Martin", genre: "EDM", year: 2018, album: "Sentio" },
  { id: 2935, rank: 435, title: "Hold On", artist: "Martin Garrix ft. Bono & The Edge", genre: "EDM", year: 2018, album: "Hold On" },
  { id: 2936, rank: 436, title: "So Far Away", artist: "Martin Garrix & David Guetta ft. Jamie Scott & Romy Dya", genre: "EDM", year: 2016, album: "So Far Away" },
  { id: 2937, rank: 437, title: "Burning Bridges", artist: "OneRepublic ft. Tebey", genre: "EDM", year: 2018, album: "Human" },
  { id: 2938, rank: 438, title: "Stargate", artist: "Sygnum", genre: "EDM", year: 2017, album: "Stargate" },
  { id: 2939, rank: 439, title: "Exodus", artist: "Noisia & Foreign Beggars", genre: "EDM", year: 2010, album: "Split the Atom" },
  { id: 2940, rank: 440, title: "Split the Atom", artist: "Noisia ft. Foreign Beggars", genre: "EDM", year: 2010, album: "Split the Atom" },
  { id: 2941, rank: 441, title: "Machine Gun", artist: "Noisia", genre: "EDM", year: 2008, album: "Machine Gun" },
  { id: 2942, rank: 442, title: "Shellshock", artist: "Noisia", genre: "EDM", year: 2010, album: "Split the Atom" },
  { id: 2943, rank: 443, title: "Concussion", artist: "Noisia", genre: "EDM", year: 2010, album: "Split the Atom" },
  { id: 2944, rank: 444, title: "Sinkhole", artist: "Noisia", genre: "EDM", year: 2016, album: "Outer Edges" },
  { id: 2945, rank: 445, title: "Cold", artist: "Noisia", genre: "EDM", year: 2016, album: "Outer Edges" },
  { id: 2946, rank: 446, title: "Phace", artist: "Phace", genre: "EDM", year: 2012, album: "Phace" },
  { id: 2947, rank: 447, title: "Goldfinger", artist: "Chase & Status ft. Takura", genre: "EDM", year: 2011, album: "No More Idols" },
  { id: 2948, rank: 448, title: "Let You Go", artist: "Chase & Status ft. Mali", genre: "EDM", year: 2015, album: "Brand New Machine" },
  { id: 2949, rank: 449, title: "Count on Me", artist: "Chase & Status ft. Moko", genre: "EDM", year: 2013, album: "Brand New Machine" },
  { id: 2950, rank: 450, title: "Time", artist: "Chase & Status ft. Delilah", genre: "EDM", year: 2011, album: "No More Idols" },
  { id: 2951, rank: 451, title: "All Goes Wrong", artist: "Chase & Status ft. Tom Grennan", genre: "EDM", year: 2017, album: "indicative of Rage" },
  { id: 2952, rank: 452, title: "Flashing Lights", artist: "Sub Focus ft. Alpines", genre: "EDM", year: 2013, album: "Torus" },
  { id: 2953, rank: 453, title: "Turn It Around", artist: "Sub Focus ft. Kele", genre: "EDM", year: 2013, album: "Torus" },
  { id: 2954, rank: 454, title: "Rock It", artist: "Sub Focus", genre: "EDM", year: 2009, album: "Sub Focus" },
  { id: 2955, rank: 455, title: "Timewarp", artist: "Sub Focus", genre: "EDM", year: 2009, album: "Sub Focus" },
  { id: 2956, rank: 456, title: "Solar System", artist: "Sub Focus", genre: "EDM", year: 2015, album: "Evolve" },
  { id: 2957, rank: 457, title: "Evolve", artist: "Sub Focus ft. Damon Albarn", genre: "EDM", year: 2015, album: "Evolve" },
  { id: 2958, rank: 458, title: "Endorphins", artist: "Sub Focus & Alpines", genre: "EDM", year: 2015, album: "Evolve" },
  { id: 2959, rank: 459, title: "Natural High", artist: "Sub Focus ft. Alex Clare", genre: "EDM", year: 2015, album: "Evolve" },
  { id: 2960, rank: 460, title: "Torus", artist: "Sub Focus ft. Foxes", genre: "EDM", year: 2013, album: "Torus" },
  { id: 2961, rank: 461, title: "Changing", artist: "Sub Focus ft. Kele & Nina Nesbitt", genre: "EDM", year: 2015, album: "Evolve" },
  { id: 2962, rank: 462, title: "Cracks", artist: "Flux Pavilion ft. Steve Aoki", genre: "EDM", year: 2011, album: "Cracks" },
  { id: 2963, rank: 463, title: "I Can't Stop", artist: "Flux Pavilion", genre: "EDM", year: 2011, album: "I Can't Stop" },
  { id: 2964, rank: 464, title: "Bass Cannon", artist: "Flux Pavilion", genre: "EDM", year: 2010, album: "Bass Cannon" },
  { id: 2965, rank: 465, title: "Blow the Roof", artist: "Flux Pavilion ft. Chiddy Bang", genre: "EDM", year: 2011, album: "Blow the Roof" },
  { id: 2966, rank: 466, title: "Lines in Wax", artist: "Flux Pavilion", genre: "EDM", year: 2011, album: "Lines in Wax" },
  { id: 2967, rank: 467, title: "Blessings", artist: "Flux Pavilion ft. Angela Hunte", genre: "EDM", year: 2013, album: "Tesla" },
  { id: 2968, rank: 468, title: "Ready for War", artist: "Nero", genre: "EDM", year: 2011, album: "Welcome Reality" },
  { id: 2969, rank: 469, title: "Into the Night", artist: "Nero ft. Alana Watson", genre: "EDM", year: 2019, album: "Into the Night" },
  { id: 2970, rank: 470, title: "Me & You", artist: "Nero", genre: "EDM", year: 2010, album: "Me & You" },
  { id: 2971, rank: 471, title: "Must Be the Feeling", artist: "Nero", genre: "EDM", year: 2011, album: "Welcome Reality" },
  { id: 2972, rank: 472, title: "Guilt", artist: "Nero", genre: "EDM", year: 2011, album: "Welcome Reality" },
  { id: 2973, rank: 473, title: "Promises", artist: "Nero", genre: "EDM", year: 2011, album: "Welcome Reality" },
  { id: 2974, rank: 474, title: "Two Minds", artist: "Nero", genre: "EDM", year: 2011, album: "Welcome Reality" },
  { id: 2975, rank: 475, title: "Eternity", artist: "Modulate", genre: "EDM", year: 2003, album: "Eternity" },
  { id: 2976, rank: 476, title: "Never Fade Away", artist: "Deadmau5 & Kaskade", genre: "EDM", year: 2011, album: "4x4=12" },
  { id: 2977, rank: 477, title: "Movin' On", artist: "Deadmau5 & Tc", genre: "EDM", year: 2016, album: "stuff i used to do" },
  { id: 2978, rank: 478, title: "Saved", artist: "Nero ft. Tanya Lacey", genre: "EDM", year: 2019, album: "Saved" },
  { id: 2979, rank: 479, title: "Free the Animal", artist: "Sia", genre: "EDM", year: 2014, album: "1000 Forms of Fear" },
  { id: 2980, rank: 480, title: "Chandelier", artist: "Sia", genre: "EDM", year: 2014, album: "1000 Forms of Fear" },
  { id: 2981, rank: 481, title: "Unstoppable", artist: "Sia", genre: "EDM", year: 2016, album: "This Is Acting" },
  { id: 2982, rank: 482, title: "The Greatest", artist: "Sia ft. Kendrick Lamar", genre: "EDM", year: 2016, album: "This Is Acting" },
  { id: 2983, rank: 483, title: "Alive", artist: "Sia", genre: "EDM", year: 2015, album: "This Is Acting" },
  { id: 2984, rank: 484, title: "Elastic Heart", artist: "Sia ft. Shia LaBeouf & Maddie Ziegler", genre: "EDM", year: 2015, album: "1000 Forms of Fear" },
  { id: 2985, rank: 485, title: "Cheap Thrills", artist: "Sia ft. Sean Paul", genre: "EDM", year: 2016, album: "This Is Acting" },
  { id: 2986, rank: 486, title: "On the Floor", artist: "Jennifer Lopez ft. Pitbull", genre: "EDM", year: 2011, album: "Love?" },
  { id: 2987, rank: 487, title: "Mr. Brightside", artist: "The Killers", genre: "EDM", year: 2003, album: "Hot Fuss" },
  { id: 2988, rank: 488, title: "Human", artist: "The Killers", genre: "EDM", year: 2008, album: "Day & Age" },
  { id: 2989, rank: 489, title: "Mr. Brightside", artist: "The Killers (Soulwax Remix)", genre: "EDM", year: 2004, album: "Hot Fuss" },
  { id: 2990, rank: 490, title: "Echo Beach", artist: "Milk & Sugar", genre: "EDM", year: 2003, album: "Echo Beach" },
  { id: 2991, rank: 491, title: "Be There", artist: "Heller & Farley Project", genre: "EDM", year: 1997, album: "Be There" },
  { id: 2992, rank: 492, title: "Beautiful People", artist: "Ed Sheeran ft. Khalid", genre: "EDM", year: 2019, album: "No.6 Collaborations Project" },
  { id: 2993, rank: 493, title: "Don't Start Now", artist: "Dua Lipa", genre: "EDM", year: 2019, album: "Future Nostalgia" },
  { id: 2994, rank: 494, title: "Levitating", artist: "Dua Lipa ft. DaBaby", genre: "EDM", year: 2020, album: "Future Nostalgia" },
  { id: 2995, rank: 495, title: "Physical", artist: "Dua Lipa", genre: "EDM", year: 2020, album: "Future Nostalgia" },
  { id: 2996, rank: 496, title: "Break My Heart", artist: "Dua Lipa", genre: "EDM", year: 2020, album: "Future Nostalgia" },
  { id: 2997, rank: 497, title: "Electricity", artist: "Silk City & Dua Lipa ft. Diplo & Mark Ronson", genre: "EDM", year: 2018, album: "Electricity" },
  { id: 2998, rank: 498, title: "We're Good", artist: "Dua Lipa", genre: "EDM", year: 2021, album: "We're Good" },
  { id: 2999, rank: 499, title: "One Kiss", artist: "Calvin Harris & Dua Lipa", genre: "EDM", year: 2018, album: "One Kiss" },
  { id: 3000, rank: 500, title: "Infinity 2008", artist: "Guru Josh Project", genre: "EDM", year: 2008, album: "Infinity 2008" },
];
