const SONGS_HIPHOP = [
  { id: 1001, rank: 1, title: "Rapper's Delight", artist: "Sugarhill Gang", genre: "Hip-Hop", year: 1979, album: "Single" },
  { id: 1002, rank: 2, title: "The Message", artist: "Grandmaster Flash & The Furious Five", genre: "Hip-Hop", year: 1982, album: "The Message" },
  { id: 1003, rank: 3, title: "Fight the Power", artist: "Public Enemy", genre: "Hip-Hop", year: 1989, album: "Fear of a Black Planet" },
  { id: 1004, rank: 4, title: "Juicy", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1994, album: "Ready to Die" },
  { id: 1005, rank: 5, title: "Gin and Juice", artist: "Snoop Dogg", genre: "Hip-Hop", year: 1994, album: "Doggystyle" },
  { id: 1006, rank: 6, title: "California Love", artist: "2Pac", genre: "Hip-Hop", year: 1995, album: "All Eyez on Me" },
  { id: 1007, rank: 7, title: "Lose Yourself", artist: "Eminem", genre: "Hip-Hop", year: 2002, album: "8 Mile Soundtrack" },
  { id: 1008, rank: 8, title: "HUMBLE.", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2017, album: "DAMN." },
  { id: 1009, rank: 9, title: "God's Plan", artist: "Drake", genre: "Hip-Hop", year: 2018, album: "Scorpion" },
  { id: 1010, rank: 10, title: "N.Y. State of Mind", artist: "Nas", genre: "Hip-Hop", year: 1994, album: "Illmatic" },
  { id: 1011, rank: 11, title: "C.R.E.A.M.", artist: "Wu-Tang Clan", genre: "Hip-Hop", year: 1993, album: "Enter the Wu-Tang (36 Chambers)" },
  { id: 1012, rank: 12, title: "Nuthin' But a G Thang", artist: "Dr. Dre", genre: "Hip-Hop", year: 1992, album: "The Chronic" },
  { id: 1013, rank: 13, title: "Empire State of Mind", artist: "Jay-Z", genre: "Hip-Hop", year: 2009, album: "The Blueprint 3" },
  { id: 1014, rank: 14, title: "Ms. Jackson", artist: "Outkast", genre: "Hip-Hop", year: 2000, album: "Stankonia" },
  { id: 1015, rank: 15, title: "Gold Digger", artist: "Kanye West", genre: "Hip-Hop", year: 2005, album: "Late Registration" },
  { id: 1016, rank: 16, title: "Alright", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2015, album: "To Pimp a Butterfly" },
  { id: 1017, rank: 17, title: "99 Problems", artist: "Jay-Z", genre: "Hip-Hop", year: 2004, album: "The Black Album" },
  { id: 1018, rank: 18, title: "Sicko Mode", artist: "Travis Scott", genre: "Hip-Hop", year: 2018, album: "Astroworld" },
  { id: 1019, rank: 19, title: "Forgot About Dre", artist: "Dr. Dre", genre: "Hip-Hop", year: 1999, album: "2001" },
  { id: 1020, rank: 20, title: "Stan", artist: "Eminem", genre: "Hip-Hop", year: 2000, album: "The Marshall Mathers LP" },
  { id: 1021, rank: 21, title: "Hypnotize", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1997, album: "Life After Death" },
  { id: 1022, rank: 22, title: "The Real Slim Shady", artist: "Eminem", genre: "Hip-Hop", year: 2000, album: "The Marshall Mathers LP" },
  { id: 1023, rank: 23, title: "All Falls Down", artist: "Kanye West", genre: "Hip-Hop", year: 2004, album: "The College Dropout" },
  { id: 1024, rank: 24, title: "Killing Me Softly", artist: "Fugees", genre: "Hip-Hop", year: 1996, album: "The Score" },
  { id: 1025, rank: 25, title: "Dear Mama", artist: "2Pac", genre: "Hip-Hop", year: 1995, album: "Me Against the World" },
  { id: 1026, rank: 26, title: "Bonita Applebum", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1990, album: "People's Instinctive Travels" },
  { id: 1027, rank: 27, title: "Electric Relaxation", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1993, album: "Midnight Marauders" },
  { id: 1028, rank: 28, title: "Express Yourself", artist: "N.W.A", genre: "Hip-Hop", year: 1988, album: "Straight Outta Compton" },
  { id: 1029, rank: 29, title: "Straight Outta Compton", artist: "N.W.A", genre: "Hip-Hop", year: 1988, album: "Straight Outta Compton" },
  { id: 1030, rank: 30, title: "Gangsta's Paradise", artist: "Coolio", genre: "Hip-Hop", year: 1995, album: "Dangerous Minds Soundtrack" },
  { id: 1031, rank: 31, title: "Regulate", artist: "Warren G", genre: "Hip-Hop", year: 1994, album: "Regulate...G Funk Era" },
  { id: 1032, rank: 32, title: "Passin' Me By", artist: "The Pharcyde", genre: "Hip-Hop", year: 1992, album: "Bizarre Ride II the Pharcyde" },
  { id: 1033, rank: 33, title: "Shook Ones Pt. II", artist: "Mobb Deep", genre: "Hip-Hop", year: 1995, album: "The Infamous" },
  { id: 1034, rank: 34, title: "Big Pimpin'", artist: "Jay-Z", genre: "Hip-Hop", year: 2000, album: "Vol. 3... Life and Times of S. Carter" },
  { id: 1035, rank: 35, title: "Izzo (H.O.V.A.)", artist: "Jay-Z", genre: "Hip-Hop", year: 2001, album: "The Blueprint" },
  { id: 1036, rank: 36, title: "Mockingbird", artist: "Eminem", genre: "Hip-Hop", year: 2004, album: "Encore" },
  { id: 1037, rank: 37, title: "Stronger", artist: "Kanye West", genre: "Hip-Hop", year: 2007, album: "Graduation" },
  { id: 1038, rank: 38, title: "Power", artist: "Kanye West", genre: "Hip-Hop", year: 2010, album: "My Beautiful Dark Twisted Fantasy" },
  { id: 1039, rank: 39, title: "Backseat Freestyle", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1040, rank: 40, title: "Hotline Bling", artist: "Drake", genre: "Hip-Hop", year: 2015, album: "Views" },
  { id: 1041, rank: 41, title: "Started From the Bottom", artist: "Drake", genre: "Hip-Hop", year: 2013, album: "Nothing Was the Same" },
  { id: 1042, rank: 42, title: "Lucid Dreams", artist: "Juice WRLD", genre: "Hip-Hop", year: 2018, album: "Goodbye & Good Riddance" },
  { id: 1043, rank: 43, title: "Rockstar", artist: "Post Malone", genre: "Hip-Hop", year: 2017, album: "Beerbongs & Bentleys" },
  { id: 1044, rank: 44, title: "White Iverson", artist: "Post Malone", genre: "Hip-Hop", year: 2015, album: "Single" },
  { id: 1045, rank: 45, title: "SAD!", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1046, rank: 46, title: "Look at Me!", artist: "XXXTentacion", genre: "Hip-Hop", year: 2017, album: "17" },
  { id: 1047, rank: 47, title: "Mask Off", artist: "Future", genre: "Hip-Hop", year: 2017, album: "Future" },
  { id: 1048, rank: 48, title: "Bad and Boujee", artist: "Migos", genre: "Hip-Hop", year: 2016, album: "Culture" },
  { id: 1049, rank: 49, title: "Bodak Yellow", artist: "Cardi B", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1050, rank: 50, title: "Super Bass", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2011, album: "Pink Friday" },
  { id: 1051, rank: 51, title: "Lollipop", artist: "Lil Wayne", genre: "Hip-Hop", year: 2008, album: "Tha Carter III" },
  { id: 1052, rank: 52, title: "A Milli", artist: "Lil Wayne", genre: "Hip-Hop", year: 2008, album: "Tha Carter III" },
  { id: 1053, rank: 53, title: "Work It", artist: "Missy Elliott", genre: "Hip-Hop", year: 2002, album: "Under Construction" },
  { id: 1054, rank: 54, title: "Get Ur Freak On", artist: "Missy Elliott", genre: "Hip-Hop", year: 2001, album: "Miss E...So Addictive" },
  { id: 1055, rank: 55, title: "Drop It Like It's Hot", artist: "Snoop Dogg", genre: "Hip-Hop", year: 2004, album: "R&G (Rhythm & Gangsta)" },
  { id: 1056, rank: 56, title: "Beautiful", artist: "Snoop Dogg", genre: "Hip-Hop", year: 2003, album: "Paid tha Cost to Be da Bo$$" },
  { id: 1057, rank: 57, title: "Killing in the Name", artist: "Rage Against the Machine", genre: "Hip-Hop", year: 1992, album: "Rage Against the Machine" },
  { id: 1058, rank: 58, title: "Me Against the World", artist: "2Pac", genre: "Hip-Hop", year: 1995, album: "Me Against the World" },
  { id: 1059, rank: 59, title: "Changes", artist: "2Pac", genre: "Hip-Hop", year: 1998, album: "Greatest Hits" },
  { id: 1060, rank: 60, title: "Keep Ya Head Up", artist: "2Pac", genre: "Hip-Hop", year: 1993, album: "Strictly 4 My N.I.G.G.A.Z." },
  { id: 1061, rank: 61, title: "Hit 'Em Up", artist: "2Pac", genre: "Hip-Hop", year: 1996, album: "Single" },
  { id: 1062, rank: 62, title: "Ambitionz Az a Ridah", artist: "2Pac", genre: "Hip-Hop", year: 1996, album: "All Eyez on Me" },
  { id: 1063, rank: 63, title: "Big Poppa", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1994, album: "Ready to Die" },
  { id: 1064, rank: 64, title: "Mo Money Mo Problems", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1997, album: "Life After Death" },
  { id: 1065, rank: 65, title: "Ten Crack Commandments", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1997, album: "Life After Death" },
  { id: 1066, rank: 66, title: "One More Chance", artist: "The Notorious B.I.G.", genre: "Hip-Hop", year: 1995, album: "Ready to Die" },
  { id: 1067, rank: 67, title: "Triumph", artist: "Wu-Tang Clan", genre: "Hip-Hop", year: 1997, album: "Wu-Tang Forever" },
  { id: 1068, rank: 68, title: "Protect Ya Neck", artist: "Wu-Tang Clan", genre: "Hip-Hop", year: 1993, album: "Enter the Wu-Tang (36 Chambers)" },
  { id: 1069, rank: 69, title: "Tearz", artist: "Wu-Tang Clan", genre: "Hip-Hop", year: 1993, album: "Enter the Wu-Tang (36 Chambers)" },
  { id: 1070, rank: 70, title: "Liquid Swords", artist: "GZA", genre: "Hip-Hop", year: 1995, album: "Liquid Swords" },
  { id: 1071, rank: 71, title: "Incarcerated Scarfaces", artist: "Raekwon", genre: "Hip-Hop", year: 1995, album: "Only Built 4 Cuban Linx..." },
  { id: 1072, rank: 72, title: "Criminology", artist: "Raekwon", genre: "Hip-Hop", year: 1995, album: "Only Built 4 Cuban Linx..." },
  { id: 1073, rank: 73, title: "Shimmy Shimmy Ya", artist: "Ol' Dirty Bastard", genre: "Hip-Hop", year: 1995, album: "Return to the 36 Chambers" },
  { id: 1074, rank: 74, title: "Glaciers of Ice", artist: "Raekwon", genre: "Hip-Hop", year: 1995, album: "Only Built 4 Cuban Linx..." },
  { id: 1075, rank: 75, title: "It's Dark and Hell Is Hot", artist: "DMX", genre: "Hip-Hop", year: 1998, album: "It's Dark and Hell Is Hot" },
  { id: 1076, rank: 76, title: "Ruff Ryders' Anthem", artist: "DMX", genre: "Hip-Hop", year: 1998, album: "It's Dark and Hell Is Hot" },
  { id: 1077, rank: 77, title: "Party Up (Up in Here)", artist: "DMX", genre: "Hip-Hop", year: 1999, album: "...And Then There Was X" },
  { id: 1078, rank: 78, title: "Where the Hood At", artist: "DMX", genre: "Hip-Hop", year: 2003, album: "Grand Champ" },
  { id: 1079, rank: 79, title: "Hard Knock Life (Ghetto Anthem)", artist: "Jay-Z", genre: "Hip-Hop", year: 1998, album: "Vol. 2... Hard Knock Life" },
  { id: 1080, rank: 80, title: "Can I Get A...", artist: "Jay-Z", genre: "Hip-Hop", year: 1998, album: "Vol. 2... Hard Knock Life" },
  { id: 1081, rank: 81, title: "Dead Presidents II", artist: "Jay-Z", genre: "Hip-Hop", year: 1996, album: "Reasonable Doubt" },
  { id: 1082, rank: 82, title: "Takeover", artist: "Jay-Z", genre: "Hip-Hop", year: 2001, album: "The Blueprint" },
  { id: 1083, rank: 83, title: "Public Service Announcement", artist: "Jay-Z", genre: "Hip-Hop", year: 2003, album: "The Black Album" },
  { id: 1084, rank: 84, title: "Dirt Off Your Shoulder", artist: "Jay-Z", genre: "Hip-Hop", year: 2003, album: "The Black Album" },
  { id: 1085, rank: 85, title: "Clique", artist: "Kanye West", genre: "Hip-Hop", year: 2012, album: "Cruel Summer" },
  { id: 1086, rank: 86, title: "Heartless", artist: "Kanye West", genre: "Hip-Hop", year: 2008, album: "808s & Heartbreak" },
  { id: 1087, rank: 87, title: "Runaway", artist: "Kanye West", genre: "Hip-Hop", year: 2010, album: "My Beautiful Dark Twisted Fantasy" },
  { id: 1088, rank: 88, title: "All of the Lights", artist: "Kanye West", genre: "Hip-Hop", year: 2010, album: "My Beautiful Dark Twisted Fantasy" },
  { id: 1089, rank: 89, title: "Jesus Walks", artist: "Kanye West", genre: "Hip-Hop", year: 2004, album: "The College Dropout" },
  { id: 1090, rank: 90, title: "Through the Wire", artist: "Kanye West", genre: "Hip-Hop", year: 2003, album: "The College Dropout" },
  { id: 1091, rank: 91, title: "The New Workout Plan", artist: "Kanye West", genre: "Hip-Hop", year: 2004, album: "The College Dropout" },
  { id: 1092, rank: 92, title: "Touch the Sky", artist: "Kanye West", genre: "Hip-Hop", year: 2005, album: "Late Registration" },
  { id: 1093, rank: 93, title: "Flashing Lights", artist: "Kanye West", genre: "Hip-Hop", year: 2007, album: "Graduation" },
  { id: 1094, rank: 94, title: "Good Life", artist: "Kanye West", genre: "Hip-Hop", year: 2007, album: "Graduation" },
  { id: 1095, rank: 95, title: "Can't Tell Me Nothing", artist: "Kanye West", genre: "Hip-Hop", year: 2007, album: "Graduation" },
  { id: 1096, rank: 96, title: "Gorgeous", artist: "Kanye West", genre: "Hip-Hop", year: 2010, album: "My Beautiful Dark Twisted Fantasy" },
  { id: 1097, rank: 97, title: "New Slaves", artist: "Kanye West", genre: "Hip-Hop", year: 2013, album: "Yeezus" },
  { id: 1098, rank: 98, title: "Black Skinhead", artist: "Kanye West", genre: "Hip-Hop", year: 2013, album: "Yeezus" },
  { id: 1099, rank: 99, title: "Real Friends", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1100, rank: 100, title: "Ultralight Beam", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1101, rank: 101, title: "m.A.A.d city", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1102, rank: 102, title: "Swimming Pools (Drank)", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1103, rank: 103, title: "Poetic Justice", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1104, rank: 104, title: "i", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2014, album: "To Pimp a Butterfly" },
  { id: 1105, rank: 105, title: "King Kunta", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2015, album: "To Pimp a Butterfly" },
  { id: 1106, rank: 106, title: "DNA.", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2017, album: "DAMN." },
  { id: 1107, rank: 107, title: "LOYALTY.", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2017, album: "DAMN." },
  { id: 1108, rank: 108, title: "Money Trees", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1109, rank: 109, title: "Bitch, Don't Kill My Vibe", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1110, rank: 110, title: "The Heart Part 5", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2022, album: "Single" },
  { id: 1111, rank: 111, title: "Rich Spirit", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2022, album: "Mr. Morale & The Big Steppers" },
  { id: 1112, rank: 112, title: "Not Like Us", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2024, album: "Single" },
  { id: 1113, rank: 113, title: "One Dance", artist: "Drake", genre: "Hip-Hop", year: 2016, album: "Views" },
  { id: 1114, rank: 114, title: "In My Feelings", artist: "Drake", genre: "Hip-Hop", year: 2018, album: "Scorpion" },
  { id: 1115, rank: 115, title: "HYFR", artist: "Drake", genre: "Hip-Hop", year: 2011, album: "Take Care" },
  { id: 1116, rank: 116, title: "Marvin's Room", artist: "Drake", genre: "Hip-Hop", year: 2011, album: "Take Care" },
  { id: 1117, rank: 117, title: "Hold On, We're Going Home", artist: "Drake", genre: "Hip-Hop", year: 2013, album: "Nothing Was the Same" },
  { id: 1118, rank: 118, title: "0 to 100 / The Catch Up", artist: "Drake", genre: "Hip-Hop", year: 2014, album: "Single" },
  { id: 1119, rank: 119, title: "Energy", artist: "Drake", genre: "Hip-Hop", year: 2015, album: "If You're Reading This It's Too Late" },
  { id: 1120, rank: 120, title: "Jumpman", artist: "Drake", genre: "Hip-Hop", year: 2015, album: "What a Time to Be Alive" },
  { id: 1121, rank: 121, title: "Forever", artist: "Drake", genre: "Hip-Hop", year: 2009, album: "Single" },
  { id: 1122, rank: 122, title: "Best I Ever Had", artist: "Drake", genre: "Hip-Hop", year: 2009, album: "So Far Gone" },
  { id: 1123, rank: 123, title: "GODS PLAN", artist: "Drake", genre: "Hip-Hop", year: 2018, album: "Scorpion" },
  { id: 1124, rank: 124, title: "Controlla", artist: "Drake", genre: "Hip-Hop", year: 2016, album: "Views" },
  { id: 1125, rank: 125, title: "The Motto", artist: "Drake", genre: "Hip-Hop", year: 2011, album: "Take Care" },
  { id: 1126, rank: 126, title: "Panda", artist: "Desiigner", genre: "Hip-Hop", year: 2015, album: "Single" },
  { id: 1127, rank: 127, title: "Broccoli", artist: "DRAM", genre: "Hip-Hop", year: 2016, album: "Single" },
  { id: 1128, rank: 128, title: "Black Beatles", artist: "Rae Sremmurd", genre: "Hip-Hop", year: 2016, album: "SremmLife 2" },
  { id: 1129, rank: 129, title: "No Flex Zone", artist: "Rae Sremmurd", genre: "Hip-Hop", year: 2014, album: "SremmLife" },
  { id: 1130, rank: 130, title: "Antidote", artist: "Travis Scott", genre: "Hip-Hop", year: 2015, album: "Rodeo" },
  { id: 1131, rank: 131, title: "goosebumps", artist: "Travis Scott", genre: "Hip-Hop", year: 2016, album: "Birds in the Trap Sing McKnight" },
  { id: 1132, rank: 132, title: "Butterfly Effect", artist: "Travis Scott", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1133, rank: 133, title: "Franchise", artist: "Travis Scott", genre: "Hip-Hop", year: 2020, album: "Single" },
  { id: 1134, rank: 134, title: "STARGAZING", artist: "Travis Scott", genre: "Hip-Hop", year: 2018, album: "Astroworld" },
  { id: 1135, rank: 135, title: "WAKE UP", artist: "Travis Scott", genre: "Hip-Hop", year: 2018, album: "Astroworld" },
  { id: 1136, rank: 136, title: "SWEET SWEET", artist: "Travis Scott", genre: "Hip-Hop", year: 2018, album: "Astroworld" },
  { id: 1137, rank: 137, title: "Magnolia", artist: "Playboi Carti", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1138, rank: 138, title: "wokeuplikethis*", artist: "Playboi Carti", genre: "Hip-Hop", year: 2017, album: "Playboi Carti" },
  { id: 1139, rank: 139, title: "Congratulations", artist: "Post Malone", genre: "Hip-Hop", year: 2016, album: "Stoney" },
  { id: 1140, rank: 140, title: "Better Now", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1141, rank: 141, title: "Sunflower", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Spider-Man: Into the Spider-Verse" },
  { id: 1142, rank: 142, title: "Circles", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1143, rank: 143, title: "Saint-Tropez", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1144, rank: 144, title: "Wow.", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1145, rank: 145, title: "No Role Modelz", artist: "J. Cole", genre: "Hip-Hop", year: 2014, album: "2014 Forest Hills Drive" },
  { id: 1146, rank: 146, title: "Love Yourz", artist: "J. Cole", genre: "Hip-Hop", year: 2014, album: "2014 Forest Hills Drive" },
  { id: 1147, rank: 147, title: "Crooked Smile", artist: "J. Cole", genre: "Hip-Hop", year: 2013, album: "Born Sinner" },
  { id: 1148, rank: 148, title: "A Tale of 2 Citiez", artist: "J. Cole", genre: "Hip-Hop", year: 2014, album: "2014 Forest Hills Drive" },
  { id: 1149, rank: 149, title: "Power Trip", artist: "J. Cole", genre: "Hip-Hop", year: 2013, album: "Born Sinner" },
  { id: 1150, rank: 150, title: "Apparently", artist: "J. Cole", genre: "Hip-Hop", year: 2014, album: "2014 Forest Hills Drive" },
  { id: 1151, rank: 151, title: "KOD", artist: "J. Cole", genre: "Hip-Hop", year: 2018, album: "KOD" },
  { id: 1152, rank: 152, title: "ATM", artist: "J. Cole", genre: "Hip-Hop", year: 2018, album: "KOD" },
  { id: 1153, rank: 153, title: "1985", artist: "J. Cole", genre: "Hip-Hop", year: 2018, album: "KOD" },
  { id: 1154, rank: 154, title: "MIDDLE CHILD", artist: "J. Cole", genre: "Hip-Hop", year: 2019, album: "Single" },
  { id: 1155, rank: 155, title: "Work Out", artist: "J. Cole", genre: "Hip-Hop", year: 2011, album: "Cole World: The Sideline Story" },
  { id: 1156, rank: 156, title: "Lean and Dab", artist: "21 Savage", genre: "Hip-Hop", year: 2016, album: "Savage Mode" },
  { id: 1157, rank: 157, title: "Bank Account", artist: "21 Savage", genre: "Hip-Hop", year: 2017, album: "Issa Album" },
  { id: 1158, rank: 158, title: "X", artist: "21 Savage", genre: "Hip-Hop", year: 2018, album: "I Am > I Was" },
  { id: 1159, rank: 159, title: "A Lot", artist: "21 Savage", genre: "Hip-Hop", year: 2018, album: "I Am > I Was" },
  { id: 1160, rank: 160, title: "Savage Mode II (intro)", artist: "21 Savage", genre: "Hip-Hop", year: 2020, album: "Savage Mode II" },
  { id: 1161, rank: 161, title: "Codeine Crazy", artist: "Future", genre: "Hip-Hop", year: 2014, album: "Monster" },
  { id: 1162, rank: 162, title: "March Madness", artist: "Future", genre: "Hip-Hop", year: 2015, album: "Single" },
  { id: 1163, rank: 163, title: "Fuck Up Some Commas", artist: "Future", genre: "Hip-Hop", year: 2014, album: "Single" },
  { id: 1164, rank: 164, title: "Low Life", artist: "Future", genre: "Hip-Hop", year: 2016, album: "EVOL" },
  { id: 1165, rank: 165, title: "Used to This", artist: "Future", genre: "Hip-Hop", year: 2016, album: "EVOL" },
  { id: 1166, rank: 166, title: "Wicked", artist: "Future", genre: "Hip-Hop", year: 2017, album: "Future" },
  { id: 1167, rank: 167, title: "I'm So Groovy", artist: "Lil Uzi Vert", genre: "Hip-Hop", year: 2016, album: "Luv Is Rage" },
  { id: 1168, rank: 168, title: "XO Tour Llif3", artist: "Lil Uzi Vert", genre: "Hip-Hop", year: 2017, album: "Luv Is Rage 2" },
  { id: 1169, rank: 169, title: "Money Longer", artist: "Lil Uzi Vert", genre: "Hip-Hop", year: 2016, album: "Single" },
  { id: 1170, rank: 170, title: "The Way Life Goes", artist: "Lil Uzi Vert", genre: "Hip-Hop", year: 2017, album: "Luv Is Rage 2" },
  { id: 1171, rank: 171, title: "New Patek", artist: "Lil Uzi Vert", genre: "Hip-Hop", year: 2018, album: "Single" },
  { id: 1172, rank: 172, title: "Slippery", artist: "Migos", genre: "Hip-Hop", year: 2017, album: "Culture" },
  { id: 1173, rank: 173, title: "T-Shirt", artist: "Migos", genre: "Hip-Hop", year: 2017, album: "Culture" },
  { id: 1174, rank: 174, title: "MotorSport", artist: "Migos", genre: "Hip-Hop", year: 2017, album: "Culture II" },
  { id: 1175, rank: 175, title: "Versace", artist: "Migos", genre: "Hip-Hop", year: 2013, album: "Single" },
  { id: 1176, rank: 176, title: "Walk It Talk It", artist: "Migos", genre: "Hip-Hop", year: 2018, album: "Culture II" },
  { id: 1177, rank: 177, title: "Stir Fry", artist: "Migos", genre: "Hip-Hop", year: 2018, album: "Culture II" },
  { id: 1178, rank: 178, title: "Young Thug Rich Homie Quan Freestyle", artist: "Young Thug", genre: "Hip-Hop", year: 2014, album: "Single" },
  { id: 1179, rank: 179, title: "Digits", artist: "Young Thug", genre: "Hip-Hop", year: 2016, album: "Jeffery" },
  { id: 1180, rank: 180, title: "Wyclef Jean", artist: "Young Thug", genre: "Hip-Hop", year: 2016, album: "Jeffery" },
  { id: 1181, rank: 181, title: "Pick Up the Phone", artist: "Young Thug", genre: "Hip-Hop", year: 2016, album: "Jeffery" },
  { id: 1182, rank: 182, title: "Best Friend", artist: "Young Thug", genre: "Hip-Hop", year: 2021, album: "Slime Language 2" },
  { id: 1183, rank: 183, title: "Wishing", artist: "Young Thug", genre: "Hip-Hop", year: 2017, album: "Beautiful Thugger Girls" },
  { id: 1184, rank: 184, title: "The Box", artist: "Roddy Ricch", genre: "Hip-Hop", year: 2019, album: "Please Excuse Me for Being Antisocial" },
  { id: 1185, rank: 185, title: "Ballin", artist: "Roddy Ricch", genre: "Hip-Hop", year: 2020, album: "Please Excuse Me for Being Antisocial" },
  { id: 1186, rank: 186, title: "Through the Late Night", artist: "Travis Scott", genre: "Hip-Hop", year: 2018, album: "Astroworld" },
  { id: 1187, rank: 187, title: "Go Crazy", artist: "Chris Brown", genre: "Hip-Hop", year: 2020, album: "Single" },
  { id: 1188, rank: 188, title: "Whats Poppin", artist: "Jack Harlow", genre: "Hip-Hop", year: 2020, album: "Sweet Action" },
  { id: 1189, rank: 189, title: "Industry BABY", artist: "Lil Nas X", genre: "Hip-Hop", year: 2021, album: "MONTERO" },
  { id: 1190, rank: 190, title: "Old Town Road", artist: "Lil Nas X", genre: "Hip-Hop", year: 2019, album: "7" },
  { id: 1191, rank: 191, title: "Mo Bamba", artist: "Sheck Wes", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1192, rank: 192, title: "Godzilla", artist: "Eminem", genre: "Hip-Hop", year: 2020, album: "Music to Be Murdered By" },
  { id: 1193, rank: 193, title: "Rap God", artist: "Eminem", genre: "Hip-Hop", year: 2013, album: "The Marshall Mathers LP 2" },
  { id: 1194, rank: 194, title: "Without Me", artist: "Eminem", genre: "Hip-Hop", year: 2002, album: "The Eminem Show" },
  { id: 1195, rank: 195, title: "Cleanin' Out My Closet", artist: "Eminem", genre: "Hip-Hop", year: 2002, album: "The Eminem Show" },
  { id: 1196, rank: 196, title: "Kim", artist: "Eminem", genre: "Hip-Hop", year: 2000, album: "The Marshall Mathers LP" },
  { id: 1197, rank: 197, title: "97 Bonnie & Clyde", artist: "Eminem", genre: "Hip-Hop", year: 1999, album: "The Slim Shady LP" },
  { id: 1198, rank: 198, title: "My Name Is", artist: "Eminem", genre: "Hip-Hop", year: 1999, album: "The Slim Shady LP" },
  { id: 1199, rank: 199, title: "Rock Bottom", artist: "Eminem", genre: "Hip-Hop", year: 1999, album: "The Slim Shady LP" },
  { id: 1200, rank: 200, title: "Hailie's Song", artist: "Eminem", genre: "Hip-Hop", year: 2002, album: "The Eminem Show" },
  { id: 1201, rank: 201, title: "When I'm Gone", artist: "Eminem", genre: "Hip-Hop", year: 2005, album: "Curtain Call: The Hits" },
  { id: 1202, rank: 202, title: "Beautiful", artist: "Eminem", genre: "Hip-Hop", year: 2009, album: "Relapse" },
  { id: 1203, rank: 203, title: "Not Afraid", artist: "Eminem", genre: "Hip-Hop", year: 2010, album: "Recovery" },
  { id: 1204, rank: 204, title: "Love the Way You Lie", artist: "Eminem", genre: "Hip-Hop", year: 2010, album: "Recovery" },
  { id: 1205, rank: 205, title: "Space Bound", artist: "Eminem", genre: "Hip-Hop", year: 2010, album: "Recovery" },
  { id: 1206, rank: 206, title: "The Way I Am", artist: "Eminem", genre: "Hip-Hop", year: 2000, album: "The Marshall Mathers LP" },
  { id: 1207, rank: 207, title: "3 A.M.", artist: "Eminem", genre: "Hip-Hop", year: 2009, album: "Relapse" },
  { id: 1208, rank: 208, title: "Deja Vu", artist: "Eminem", genre: "Hip-Hop", year: 2009, album: "Relapse" },
  { id: 1209, rank: 209, title: "Going Through Changes", artist: "Eminem", genre: "Hip-Hop", year: 2010, album: "Recovery" },
  { id: 1210, rank: 210, title: "Phenomenal", artist: "Eminem", genre: "Hip-Hop", year: 2015, album: "Single" },
  { id: 1211, rank: 211, title: "The Search", artist: "NF", genre: "Hip-Hop", year: 2019, album: "The Search" },
  { id: 1212, rank: 212, title: "Lies", artist: "NF", genre: "Hip-Hop", year: 2016, album: "Mansion" },
  { id: 1213, rank: 213, title: "Hate Myself", artist: "NF", genre: "Hip-Hop", year: 2019, album: "The Search" },
  { id: 1214, rank: 214, title: "Ice Ice Baby", artist: "Vanilla Ice", genre: "Hip-Hop", year: 1990, album: "To the Extreme" },
  { id: 1215, rank: 215, title: "Jump Around", artist: "House of Pain", genre: "Hip-Hop", year: 1992, album: "House of Pain" },
  { id: 1216, rank: 216, title: "U Can't Touch This", artist: "MC Hammer", genre: "Hip-Hop", year: 1990, album: "Please Hammer, Don't Hurt 'Em" },
  { id: 1217, rank: 217, title: "Baby Got Back", artist: "Sir Mix-a-Lot", genre: "Hip-Hop", year: 1992, album: "Mack Daddy" },
  { id: 1218, rank: 218, title: "Informer", artist: "Snow", genre: "Hip-Hop", year: 1992, album: "12 Inches of Snow" },
  { id: 1219, rank: 219, title: "Whoomp! (There It Is)", artist: "Tag Team", genre: "Hip-Hop", year: 1993, album: "Whoomp! (There It Is)" },
  { id: 1220, rank: 220, title: "Summertime", artist: "DJ Jazzy Jeff & The Fresh Prince", genre: "Hip-Hop", year: 1991, album: "Homebase" },
  { id: 1221, rank: 221, title: "Parents Just Don't Understand", artist: "DJ Jazzy Jeff & The Fresh Prince", genre: "Hip-Hop", year: 1988, album: "He's the DJ, I'm the Rapper" },
  { id: 1222, rank: 222, title: "Gettin' Jiggy Wit It", artist: "Will Smith", genre: "Hip-Hop", year: 1997, album: "Big Willie Style" },
  { id: 1223, rank: 223, title: "Miami", artist: "Will Smith", genre: "Hip-Hop", year: 1998, album: "Big Willie Style" },
  { id: 1224, rank: 224, title: "Men in Black", artist: "Will Smith", genre: "Hip-Hop", year: 1997, album: "Men in Black Soundtrack" },
  { id: 1225, rank: 225, title: "Just the Two of Us", artist: "Will Smith", genre: "Hip-Hop", year: 1998, album: "Big Willie Style" },
  { id: 1226, rank: 226, title: "Push It", artist: "Salt-N-Pepa", genre: "Hip-Hop", year: 1987, album: "Hot, Cool & Vicious" },
  { id: 1227, rank: 227, title: "Shoop", artist: "Salt-N-Pepa", genre: "Hip-Hop", year: 1993, album: "Very Necessary" },
  { id: 1228, rank: 228, title: "Whatta Man", artist: "Salt-N-Pepa", genre: "Hip-Hop", year: 1993, album: "Very Necessary" },
  { id: 1229, rank: 229, title: "Ante Up", artist: "M.O.P.", genre: "Hip-Hop", year: 2000, album: "Warriorz" },
  { id: 1230, rank: 230, title: "Survival of the Fittest", artist: "Mobb Deep", genre: "Hip-Hop", year: 1995, album: "The Infamous" },
  { id: 1231, rank: 231, title: "Quiet Storm", artist: "Mobb Deep", genre: "Hip-Hop", year: 1999, album: "Murda Muzik" },
  { id: 1232, rank: 232, title: "Temperature", artist: "Sean Paul", genre: "Hip-Hop", year: 2005, album: "The Trinity" },
  { id: 1233, rank: 233, title: "We Be Burnin'", artist: "Sean Paul", genre: "Hip-Hop", year: 2005, album: "The Trinity" },
  { id: 1234, rank: 234, title: "Gasolina", artist: "Daddy Yankee", genre: "Hip-Hop", year: 2004, album: "Barrio Fino" },
  { id: 1235, rank: 235, title: "Con Calma", artist: "Daddy Yankee", genre: "Hip-Hop", year: 2019, album: "Single" },
  { id: 1236, rank: 236, title: "Lean On Me", artist: "Club Nouveau", genre: "Hip-Hop", year: 1987, album: "Life, Love & Pain" },
  { id: 1237, rank: 237, title: "Don't Believe the Hype", artist: "Public Enemy", genre: "Hip-Hop", year: 1988, album: "It Takes a Nation of Millions to Hold Us Back" },
  { id: 1238, rank: 238, title: "Black Steel in the Hour of Chaos", artist: "Public Enemy", genre: "Hip-Hop", year: 1988, album: "It Takes a Nation of Millions to Hold Us Back" },
  { id: 1239, rank: 239, title: "Welcome to the Terrordome", artist: "Public Enemy", genre: "Hip-Hop", year: 1990, album: "Fear of a Black Planet" },
  { id: 1240, rank: 240, title: "911 Is a Joke", artist: "Public Enemy", genre: "Hip-Hop", year: 1990, album: "Fear of a Black Planet" },
  { id: 1241, rank: 241, title: "Rebel Without a Pause", artist: "Public Enemy", genre: "Hip-Hop", year: 1987, album: "It Takes a Nation of Millions to Hold Us Back" },
  { id: 1242, rank: 242, title: "Paid in Full", artist: "Eric B. & Rakim", genre: "Hip-Hop", year: 1987, album: "Paid in Full" },
  { id: 1243, rank: 243, title: "I Know You Got Soul", artist: "Eric B. & Rakim", genre: "Hip-Hop", year: 1987, album: "Paid in Full" },
  { id: 1244, rank: 244, title: "Move the Crowd", artist: "Eric B. & Rakim", genre: "Hip-Hop", year: 1987, album: "Paid in Full" },
  { id: 1245, rank: 245, title: "Follow the Leader", artist: "Eric B. & Rakim", genre: "Hip-Hop", year: 1988, album: "Follow the Leader" },
  { id: 1246, rank: 246, title: "Know the Ledge", artist: "Eric B. & Rakim", genre: "Hip-Hop", year: 1992, album: "Juice Soundtrack" },
  { id: 1247, rank: 247, title: "Bring the Noise", artist: "Public Enemy", genre: "Hip-Hop", year: 1987, album: "It Takes a Nation of Millions to Hold Us Back" },
  { id: 1248, rank: 248, title: "Night of the Living Baseheads", artist: "Public Enemy", genre: "Hip-Hop", year: 1988, album: "It Takes a Nation of Millions to Hold Us Back" },
  { id: 1249, rank: 249, title: "People Everyday", artist: "Arrested Development", genre: "Hip-Hop", year: 1992, album: "3 Years, 5 Months and 2 Days in the Life Of..." },
  { id: 1250, rank: 250, title: "Tennessee", artist: "Arrested Development", genre: "Hip-Hop", year: 1992, album: "3 Years, 5 Months and 2 Days in the Life Of..." },
  { id: 1251, rank: 251, title: "Scenario", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1991, album: "The Low End Theory" },
  { id: 1252, rank: 252, title: "Can I Kick It?", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1990, album: "People's Instinctive Travels" },
  { id: 1253, rank: 253, title: "Check the Rhime", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1991, album: "The Low End Theory" },
  { id: 1254, rank: 254, title: "We the People....", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 2016, album: "We got it from Here... Thank You 4 Your service" },
  { id: 1255, rank: 255, title: "Excursions", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1991, album: "The Low End Theory" },
  { id: 1256, rank: 256, title: "Award Tour", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1993, album: "Midnight Marauders" },
  { id: 1257, rank: 257, title: "Buggin' Out", artist: "A Tribe Called Quest", genre: "Hip-Hop", year: 1991, album: "The Low End Theory" },
  { id: 1258, rank: 258, title: "One Love", artist: "Nas", genre: "Hip-Hop", year: 1994, album: "Illmatic" },
  { id: 1259, rank: 259, title: "Represent", artist: "Nas", genre: "Hip-Hop", year: 1994, album: "Illmatic" },
  { id: 1260, rank: 260, title: "The World Is Yours", artist: "Nas", genre: "Hip-Hop", year: 1994, album: "Illmatic" },
  { id: 1261, rank: 261, title: "Hate Me Now", artist: "Nas", genre: "Hip-Hop", year: 1999, album: "I Am..." },
  { id: 1262, rank: 262, title: "Ether", artist: "Nas", genre: "Hip-Hop", year: 2001, album: "Stillmatic" },
  { id: 1263, rank: 263, title: "One Mic", artist: "Nas", genre: "Hip-Hop", year: 2001, album: "Stillmatic" },
  { id: 1264, rank: 264, title: "Got Ur Self A...", artist: "Nas", genre: "Hip-Hop", year: 2001, album: "Stillmatic" },
  { id: 1265, rank: 265, title: "If I Ruled the World", artist: "Nas", genre: "Hip-Hop", year: 1996, album: "It Was Written" },
  { id: 1266, rank: 266, title: "Street Dreams", artist: "Nas", genre: "Hip-Hop", year: 1996, album: "It Was Written" },
  { id: 1267, rank: 267, title: "Nas Is Like", artist: "Nas", genre: "Hip-Hop", year: 1999, album: "I Am..." },
  { id: 1268, rank: 268, title: "Hip Hop Is Dead", artist: "Nas", genre: "Hip-Hop", year: 2006, album: "Hip Hop Is Dead" },
  { id: 1269, rank: 269, title: "Made You Look", artist: "Nas", genre: "Hip-Hop", year: 2002, album: "God's Son" },
  { id: 1270, rank: 270, title: "I Can", artist: "Nas", genre: "Hip-Hop", year: 2002, album: "God's Son" },
  { id: 1271, rank: 271, title: "Rosa Parks", artist: "Outkast", genre: "Hip-Hop", year: 1998, album: "Aquemini" },
  { id: 1272, rank: 272, title: "B.O.B.", artist: "Outkast", genre: "Hip-Hop", year: 2000, album: "Stankonia" },
  { id: 1273, rank: 273, title: "Hey Ya!", artist: "Outkast", genre: "Hip-Hop", year: 2003, album: "Speakerboxxx/The Love Below" },
  { id: 1274, rank: 274, title: "The Way You Move", artist: "Outkast", genre: "Hip-Hop", year: 2003, album: "Speakerboxxx/The Love Below" },
  { id: 1275, rank: 275, title: "Prototype", artist: "Outkast", genre: "Hip-Hop", year: 2003, album: "Speakerboxxx/The Love Below" },
  { id: 1276, rank: 276, title: "ATLiens", artist: "Outkast", genre: "Hip-Hop", year: 1996, album: "ATLiens" },
  { id: 1277, rank: 277, title: "Elevators (Me & You)", artist: "Outkast", genre: "Hip-Hop", year: 1996, album: "ATLiens" },
  { id: 1278, rank: 278, title: "Southernplayalisticadillacmuzik", artist: "Outkast", genre: "Hip-Hop", year: 1994, album: "Southernplayalisticadillacmuzik" },
  { id: 1279, rank: 279, title: "Aquemini", artist: "Outkast", genre: "Hip-Hop", year: 1998, album: "Aquemini" },
    { id: 1280, rank: 280, title: "Spottieottiedopaliscious", artist: "Outkast", genre: "Hip-Hop", year: 1998, album: "Aquemini" },
  { id: 1281, rank: 281, title: "Whole Lotta Lovin'", artist: "Lil Wayne", genre: "Hip-Hop", year: 2008, album: "Tha Carter III" },
  { id: 1282, rank: 282, title: "Mrs. Officer", artist: "Lil Wayne", genre: "Hip-Hop", year: 2008, album: "Tha Carter III" },
  { id: 1283, rank: 283, title: "6 Foot 7 Foot", artist: "Lil Wayne", genre: "Hip-Hop", year: 2010, album: "Tha Carter IV" },
  { id: 1284, rank: 284, title: "John", artist: "Lil Wayne", genre: "Hip-Hop", year: 2011, album: "Tha Carter IV" },
  { id: 1285, rank: 285, title: "Got Money", artist: "Lil Wayne", genre: "Hip-Hop", year: 2008, album: "Tha Carter III" },
  { id: 1286, rank: 286, title: "La La La", artist: "Lil Wayne", genre: "Hip-Hop", year: 2005, album: "Tha Carter II" },
  { id: 1287, rank: 287, title: "Fireman", artist: "Lil Wayne", genre: "Hip-Hop", year: 2005, album: "Tha Carter II" },
  { id: 1288, rank: 288, title: "Mirror", artist: "Lil Wayne", genre: "Hip-Hop", year: 2011, album: "Tha Carter IV" },
  { id: 1289, rank: 289, title: "How to Love", artist: "Lil Wayne", genre: "Hip-Hop", year: 2011, album: "Tha Carter IV" },
  { id: 1290, rank: 290, title: "Racks", artist: "YC", genre: "Hip-Hop", year: 2011, album: "Single" },
  { id: 1291, rank: 291, title: "Rack City", artist: "Tyga", genre: "Hip-Hop", year: 2011, album: "Careless World: Rise of the Last King" },
  { id: 1292, rank: 292, title: "Loyal", artist: "Chris Brown", genre: "Hip-Hop", year: 2014, album: "X" },
  { id: 1293, rank: 293, title: "Freaky Friday", artist: "Lil Dicky", genre: "Hip-Hop", year: 2018, album: "Single" },
  { id: 1294, rank: 294, title: "Russell Westbrook on a Farm", artist: "Lil Dicky", genre: "Hip-Hop", year: 2016, album: "Single" },
  { id: 1295, rank: 295, title: "Count on Me", artist: "Bruno Mars", genre: "Hip-Hop", year: 2010, album: "Doo-Wops & Hooligans" },
  { id: 1296, rank: 296, title: "Faded", artist: "Tyga", genre: "Hip-Hop", year: 2011, album: "Careless World" },
  { id: 1297, rank: 297, title: "Ayo", artist: "Tyga", genre: "Hip-Hop", year: 2015, album: "The Gold Album: 18th Dynasty" },
  { id: 1298, rank: 298, title: "Like a G6", artist: "Far East Movement", genre: "Hip-Hop", year: 2010, album: "Free Wired" },
  { id: 1299, rank: 299, title: "Where Them Girls At", artist: "David Guetta", genre: "Hip-Hop", year: 2011, album: "Nothing but the Beat" },
  { id: 1300, rank: 300, title: "Swimming", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1301, rank: 301, title: "Self Care", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1302, rank: 302, title: "Diablo", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1303, rank: 303, title: "Small Worlds", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1304, rank: 304, title: "Ladders", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1305, rank: 305, title: "Dang!", artist: "Mac Miller", genre: "Hip-Hop", year: 2016, album: "The Divine Feminine" },
  { id: 1306, rank: 306, title: "Watching Movies", artist: "Mac Miller", genre: "Hip-Hop", year: 2013, album: "Watching Movies with the Sound Off" },
  { id: 1307, rank: 307, title: "Objects in the Mirror", artist: "Mac Miller", genre: "Hip-Hop", year: 2013, album: "Watching Movies with the Sound Off" },
  { id: 1308, rank: 308, title: "Come Back to Earth", artist: "Mac Miller", genre: "Hip-Hop", year: 2018, album: "Swimming" },
  { id: 1309, rank: 309, title: "Best Day Ever", artist: "Mac Miller", genre: "Hip-Hop", year: 2011, album: "Best Day Ever" },
  { id: 1310, rank: 310, title: "Donald Trump", artist: "Mac Miller", genre: "Hip-Hop", year: 2011, album: "Best Day Ever" },
  { id: 1311, rank: 311, title: "Right Now", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2013, album: "Long. Live. ASAP" },
  { id: 1312, rank: 312, title: "Goldie", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2011, album: "LiveLoveASAP" },
  { id: 1313, rank: 313, title: "Fashion Killa", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2013, album: "Long. Live. ASAP" },
  { id: 1314, rank: 314, title: "Peso", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2011, album: "LiveLoveASAP" },
  { id: 1315, rank: 315, title: "Wild for the Night", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2013, album: "Long. Live. ASAP" },
  { id: 1316, rank: 316, title: "F**kin' Problems", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2012, album: "Long. Live. ASAP" },
  { id: 1317, rank: 317, title: "L$D", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2015, album: "At.Long.Last.ASAP" },
  { id: 1318, rank: 318, title: "Babushka Boi", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2019, album: "Single" },
  { id: 1319, rank: 319, title: "Praise the Lord (Da Shine)", artist: "ASAP Rocky", genre: "Hip-Hop", year: 2018, album: "Testing" },
  { id: 1320, rank: 320, title: "Lifestyle", artist: "Rich Gang", genre: "Hip-Hop", year: 2014, album: "Rich Gang: Tha Tour Pt. 1" },
  { id: 1321, rank: 321, title: "My Nigga", artist: "YG", genre: "Hip-Hop", year: 2013, album: "My Krazy Life" },
  { id: 1322, rank: 322, title: "Who Do You Love?", artist: "YG", genre: "Hip-Hop", year: 2014, album: "My Krazy Life" },
  { id: 1323, rank: 323, title: "Big Bank", artist: "YG", genre: "Hip-Hop", year: 2018, album: "Stay Dangerous" },
  { id: 1324, rank: 324, title: "Crew", artist: "GoldLink", genre: "Hip-Hop", year: 2017, album: "At What Cost" },
  { id: 1325, rank: 325, title: "Best Part", artist: "Daniel Caesar", genre: "Hip-Hop", year: 2017, album: "Freudian" },
  { id: 1326, rank: 326, title: "Location", artist: "Khalid", genre: "Hip-Hop", year: 2017, album: "American Teen" },
  { id: 1327, rank: 327, title: "Young Dumb & Broke", artist: "Khalid", genre: "Hip-Hop", year: 2017, album: "American Teen" },
  { id: 1328, rank: 328, title: "Talk", artist: "Khalid", genre: "Hip-Hop", year: 2019, album: "Free Spirit" },
  { id: 1329, rank: 329, title: "Saturday Nights", artist: "Khalid", genre: "Hip-Hop", year: 2018, album: "Free Spirit" },
  { id: 1330, rank: 330, title: "Gucci Gang", artist: "Lil Pump", genre: "Hip-Hop", year: 2017, album: "Lil Pump" },
  { id: 1331, rank: 331, title: "ESSKEETIT", artist: "Lil Pump", genre: "Hip-Hop", year: 2018, album: "Harverd Dropout" },
  { id: 1332, rank: 332, title: "I Love It", artist: "Kanye West", genre: "Hip-Hop", year: 2018, album: "Single" },
  { id: 1333, rank: 333, title: "All Girls Are the Same", artist: "Juice WRLD", genre: "Hip-Hop", year: 2018, album: "Goodbye & Good Riddance" },
  { id: 1334, rank: 334, title: "Robbery", artist: "Juice WRLD", genre: "Hip-Hop", year: 2018, album: "Death Race for Love" },
  { id: 1335, rank: 335, title: "Legends", artist: "Juice WRLD", genre: "Hip-Hop", year: 2018, album: "Goodbye & Good Riddance" },
  { id: 1336, rank: 336, title: "Wishing Well", artist: "Juice WRLD", genre: "Hip-Hop", year: 2020, album: "Legends Never Die" },
  { id: 1337, rank: 337, title: "Come & Go", artist: "Juice WRLD", genre: "Hip-Hop", year: 2020, album: "Legends Never Die" },
  { id: 1338, rank: 338, title: "Righteous", artist: "Juice WRLD", genre: "Hip-Hop", year: 2020, album: "Legends Never Die" },
  { id: 1339, rank: 339, title: "Changes", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1340, rank: 340, title: "Jocelyn Flores", artist: "XXXTentacion", genre: "Hip-Hop", year: 2017, album: "17" },
  { id: 1341, rank: 341, title: "Moonlight", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1342, rank: 342, title: "Infinity (888)", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1343, rank: 343, title: "Floor 555", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1344, rank: 344, title: "RIP ROACH", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1345, rank: 345, title: "Numb", artist: "XXXTentacion", genre: "Hip-Hop", year: 2018, album: "?" },
  { id: 1346, rank: 346, title: "King of the Dead", artist: "Big L", genre: "Hip-Hop", year: 1995, album: "Lifestylez ov da Poor & Dangerous" },
  { id: 1347, rank: 347, title: "Put It On", artist: "Big L", genre: "Hip-Hop", year: 1995, album: "Lifestylez ov da Poor & Dangerous" },
  { id: 1348, rank: 348, title: "M.V.P.", artist: "Big L", genre: "Hip-Hop", year: 1995, album: "Lifestylez ov da Poor & Dangerous" },
  { id: 1349, rank: 349, title: "Ebonics", artist: "Big L", genre: "Hip-Hop", year: 1998, album: "Single" },
  { id: 1350, rank: 350, title: "Flamboyant", artist: "Big L", genre: "Hip-Hop", year: 2000, album: "The Big Picture" },
  { id: 1351, rank: 351, title: "Devil's Son", artist: "Big L", genre: "Hip-Hop", year: 1995, album: "Lifestylez ov da Poor & Dangerous" },
  { id: 1352, rank: 352, title: "All Black", artist: "Big L", genre: "Hip-Hop", year: 2000, album: "The Big Picture" },
  { id: 1353, rank: 353, title: "Da Graveyard", artist: "Big L", genre: "Hip-Hop", year: 1993, album: "Single" },
  { id: 1354, rank: 354, title: "Danger Zone", artist: "Big L", genre: "Hip-Hop", year: 2000, album: "The Big Picture" },
  { id: 1355, rank: 355, title: "Who You Slidin Wit", artist: "Big L", genre: "Hip-Hop", year: 1995, album: "Lifestylez ov da Poor & Dangerous" },
  { id: 1356, rank: 356, title: "Impeach the President", artist: "The Honey Drippers", genre: "Hip-Hop", year: 1973, album: "Single" },
  { id: 1357, rank: 357, title: "Planet Rock", artist: "Afrika Bambaataa", genre: "Hip-Hop", year: 1982, album: "Single" },
  { id: 1358, rank: 358, title: "Buffalo Gals", artist: "Malcolm McLaren", genre: "Hip-Hop", year: 1982, album: "Duck Rock" },
  { id: 1359, rank: 359, title: "White Lines (Don't Don't Do It)", artist: "Grandmaster Flash", genre: "Hip-Hop", year: 1983, album: "Single" },
  { id: 1360, rank: 360, title: "The Breaks", artist: "Kurtis Blow", genre: "Hip-Hop", year: 1980, album: "Kurtis Blow" },
  { id: 1361, rank: 361, title: "Basketball", artist: "Kurtis Blow", genre: "Hip-Hop", year: 1984, album: "Ego Trip" },
  { id: 1362, rank: 362, title: "Beat Bop", artist: "Rammellzee vs. K-Rob", genre: "Hip-Hop", year: 1983, album: "Single" },
  { id: 1363, rank: 363, title: "South Bronx", artist: "Boogie Down Productions", genre: "Hip-Hop", year: 1986, album: "Criminal Minded" },
  { id: 1364, rank: 364, title: "Criminal Minded", artist: "Boogie Down Productions", genre: "Hip-Hop", year: 1987, album: "Criminal Minded" },
  { id: 1365, rank: 365, title: "Stop the Violence", artist: "Boogie Down Productions", genre: "Hip-Hop", year: 1988, album: "By All Means Necessary" },
  { id: 1366, rank: 366, title: "My Philosophy", artist: "Boogie Down Productions", genre: "Hip-Hop", year: 1988, album: "By All Means Necessary" },
  { id: 1367, rank: 367, title: "Self Destruction", artist: "Stop the Violence Movement", genre: "Hip-Hop", year: 1989, album: "Single" },
  { id: 1368, rank: 368, title: "Children's Story", artist: "Slick Rick", genre: "Hip-Hop", year: 1988, album: "The Great Adventures of Slick Rick" },
  { id: 1369, rank: 369, title: "La Di Da Di", artist: "Slick Rick", genre: "Hip-Hop", year: 1985, album: "Single" },
  { id: 1370, rank: 370, title: "Mona Lisa", artist: "Slick Rick", genre: "Hip-Hop", year: 1988, album: "The Great Adventures of Slick Rick" },
  { id: 1371, rank: 371, title: "Hey Young World", artist: "Slick Rick", genre: "Hip-Hop", year: 1988, album: "The Great Adventures of Slick Rick" },
  { id: 1372, rank: 372, title: "Lyte as a Rock", artist: "MC Lyte", genre: "Hip-Hop", year: 1988, album: "Lyte as a Rock" },
  { id: 1373, rank: 373, title: "Cha Cha Cha", artist: "MC Lyte", genre: "Hip-Hop", year: 1989, album: "Eyes on This" },
  { id: 1374, rank: 374, title: "Ladies First", artist: "Queen Latifah", genre: "Hip-Hop", year: 1989, album: "All Hail the Queen" },
  { id: 1375, rank: 375, title: "U.N.I.T.Y.", artist: "Queen Latifah", genre: "Hip-Hop", year: 1993, album: "Black Reign" },
  { id: 1376, rank: 376, title: "DKNY", artist: "Queen Latifah", genre: "Hip-Hop", year: 1993, album: "Black Reign" },
  { id: 1377, rank: 377, title: "Ill Street Blues", artist: "Kool G Rap", genre: "Hip-Hop", year: 1992, album: "Live and Let Die" },
  { id: 1378, rank: 378, title: "Road to the Riches", artist: "Kool G Rap", genre: "Hip-Hop", year: 1989, album: "Road to the Riches" },
  { id: 1379, rank: 379, title: "Talk Like Sex", artist: "Kool G Rap", genre: "Hip-Hop", year: 1990, album: "Wanted: Dead or Alive" },
  { id: 1380, rank: 380, title: "My Adidas", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1986, album: "Raising Hell" },
  { id: 1381, rank: 381, title: "Walk This Way", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1986, album: "Raising Hell" },
  { id: 1382, rank: 382, title: "It's Tricky", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1986, album: "Raising Hell" },
  { id: 1383, rank: 383, title: "Rock Box", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1984, album: "Run-D.M.C." },
  { id: 1384, rank: 384, title: "Sucker M.C.'s", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1983, album: "Run-D.M.C." },
  { id: 1385, rank: 385, title: "It's Like That", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1983, album: "Run-D.M.C." },
  { id: 1386, rank: 386, title: "King of Rock", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1985, album: "King of Rock" },
  { id: 1387, rank: 387, title: "Peter Piper", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1986, album: "Raising Hell" },
  { id: 1388, rank: 388, title: "Tougher Than Leather", artist: "Run-D.M.C.", genre: "Hip-Hop", year: 1988, album: "Tougher Than Leather" },
  { id: 1389, rank: 389, title: "It's All About the Benjamins", artist: "Puff Daddy", genre: "Hip-Hop", year: 1997, album: "No Way Out" },
  { id: 1390, rank: 390, title: "I'll Be Missing You", artist: "Puff Daddy", genre: "Hip-Hop", year: 1997, album: "No Way Out" },
  { id: 1391, rank: 391, title: "Shinin' Star", artist: "Puff Daddy", genre: "Hip-Hop", year: 1997, album: "No Way Out" },
  { id: 1392, rank: 392, title: "When Doves Cry", artist: "Bow Wow", genre: "Hip-Hop", year: 2001, album: "Beware of Dog" },
  { id: 1393, rank: 393, title: "Like You", artist: "Bow Wow", genre: "Hip-Hop", year: 2005, album: "Wanted" },
  { id: 1394, rank: 394, title: "Let Me Hold You", artist: "Bow Wow", genre: "Hip-Hop", year: 2005, album: "Wanted" },
  { id: 1395, rank: 395, title: "Shorty Wanna Ride", artist: "Young Buck", genre: "Hip-Hop", year: 2004, album: "Straight Outta Cashville" },
  { id: 1396, rank: 396, title: "Candy Shop", artist: "50 Cent", genre: "Hip-Hop", year: 2005, album: "The Massacre" },
  { id: 1397, rank: 397, title: "In da Club", artist: "50 Cent", genre: "Hip-Hop", year: 2003, album: "Get Rich or Die Tryin'" },
  { id: 1398, rank: 398, title: "21 Questions", artist: "50 Cent", genre: "Hip-Hop", year: 2003, album: "Get Rich or Die Tryin'" },
  { id: 1399, rank: 399, title: "P.I.M.P.", artist: "50 Cent", genre: "Hip-Hop", year: 2003, album: "Get Rich or Die Tryin'" },
  { id: 1400, rank: 400, title: "Many Men (Wish Death)", artist: "50 Cent", genre: "Hip-Hop", year: 2003, album: "Get Rich or Die Tryin'" },
  { id: 1401, rank: 401, title: "Hate It or Love It", artist: "The Game", genre: "Hip-Hop", year: 2005, album: "The Documentary" },
  { id: 1402, rank: 402, title: "How We Do", artist: "The Game", genre: "Hip-Hop", year: 2005, album: "The Documentary" },
  { id: 1403, rank: 403, title: "Westside Story", artist: "The Game", genre: "Hip-Hop", year: 2005, album: "The Documentary" },
  { id: 1404, rank: 404, title: "The Documentary 2", artist: "The Game", genre: "Hip-Hop", year: 2015, album: "The Documentary 2" },
  { id: 1405, rank: 405, title: "Higher", artist: "The Game", genre: "Hip-Hop", year: 2019, album: "Born 2 Rap" },
  { id: 1406, rank: 406, title: "Swimming Pools (Drank) (Extended Version)", artist: "Kendrick Lamar", genre: "Hip-Hop", year: 2012, album: "good kid, m.A.A.d city" },
  { id: 1407, rank: 407, title: "Look What You Made Me Do (Remix)", artist: "Taylor Swift & Jay-Z", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1408, rank: 408, title: "Boss", artist: "Rick Ross", genre: "Hip-Hop", year: 2006, album: "Port of Miami" },
  { id: 1409, rank: 409, title: "Hustlin'", artist: "Rick Ross", genre: "Hip-Hop", year: 2006, album: "Port of Miami" },
  { id: 1410, rank: 410, title: "B.M.F. (Blowin' Money Fast)", artist: "Rick Ross", genre: "Hip-Hop", year: 2010, album: "Teflon Don" },
  { id: 1411, rank: 411, title: "Aston Martin Music", artist: "Rick Ross", genre: "Hip-Hop", year: 2010, album: "Teflon Don" },
  { id: 1412, rank: 412, title: "Hold On", artist: "Rick Ross", genre: "Hip-Hop", year: 2012, album: "God Forgives, I Don't" },
  { id: 1413, rank: 413, title: "The Devil Is a Lie", artist: "Rick Ross", genre: "Hip-Hop", year: 2014, album: "Mastermind" },
  { id: 1414, rank: 414, title: "Trap Trap Trap", artist: "Rick Ross", genre: "Hip-Hop", year: 2017, album: "Rather You Than Me" },
  { id: 1415, rank: 415, title: "International Players Anthem", artist: "UGK", genre: "Hip-Hop", year: 2007, album: "Underground Kingz" },
  { id: 1416, rank: 416, title: "Pocket Full of Stones", artist: "UGK", genre: "Hip-Hop", year: 1992, album: "Too Hard to Swallow" },
  { id: 1417, rank: 417, title: "One Day", artist: "UGK", genre: "Hip-Hop", year: 1996, album: "Ridin' Dirty" },
  { id: 1418, rank: 418, title: "Murder Was the Case", artist: "Snoop Dogg", genre: "Hip-Hop", year: 1994, album: "Murder Was the Case Soundtrack" },
  { id: 1419, rank: 419, title: "Who Am I? (What's My Name?)", artist: "Snoop Dogg", genre: "Hip-Hop", year: 1993, album: "Doggystyle" },
  { id: 1420, rank: 420, title: "Doggy Dogg World", artist: "Snoop Dogg", genre: "Hip-Hop", year: 1993, album: "Doggystyle" },
  { id: 1421, rank: 421, title: "What's My Name? (Pt. 2)", artist: "Snoop Dogg", genre: "Hip-Hop", year: 1993, album: "Doggystyle" },
  { id: 1422, rank: 422, title: "Signs", artist: "Snoop Dogg", genre: "Hip-Hop", year: 2005, album: "R&G (Rhythm & Gangsta)" },
  { id: 1423, rank: 423, title: "Still D.R.E.", artist: "Dr. Dre", genre: "Hip-Hop", year: 1999, album: "2001" },
  { id: 1424, rank: 424, title: "Next Episode", artist: "Dr. Dre", genre: "Hip-Hop", year: 1999, album: "2001" },
  { id: 1425, rank: 425, title: "Let Me Ride", artist: "Dr. Dre", genre: "Hip-Hop", year: 1992, album: "The Chronic" },
  { id: 1426, rank: 426, title: "Dre Day", artist: "Dr. Dre", genre: "Hip-Hop", year: 1992, album: "The Chronic" },
  { id: 1427, rank: 427, title: "Xxplosive", artist: "Dr. Dre", genre: "Hip-Hop", year: 1999, album: "2001" },
  { id: 1428, rank: 428, title: "The Watcher", artist: "Dr. Dre", genre: "Hip-Hop", year: 1999, album: "2001" },
  { id: 1429, rank: 429, title: "Lil Ghetto Boy", artist: "Dr. Dre", genre: "Hip-Hop", year: 1992, album: "The Chronic" },
  { id: 1430, rank: 430, title: "Compton", artist: "Dr. Dre", genre: "Hip-Hop", year: 2015, album: "Compton" },
  { id: 1431, rank: 431, title: "Talk About It", artist: "YG", genre: "Hip-Hop", year: 2016, album: "Still Brazy" },
  { id: 1432, rank: 432, title: "Why You Always Hatin?", artist: "YG", genre: "Hip-Hop", year: 2016, album: "Still Brazy" },
  { id: 1433, rank: 433, title: "Fuck Donald Trump", artist: "YG", genre: "Hip-Hop", year: 2016, album: "Still Brazy" },
  { id: 1434, rank: 434, title: "Proud", artist: "2 Chainz", genre: "Hip-Hop", year: 2017, album: "Pretty Girls Like Trap Music" },
  { id: 1435, rank: 435, title: "Birthday Song", artist: "2 Chainz", genre: "Hip-Hop", year: 2012, album: "Based on a T.R.U. Story" },
  { id: 1436, rank: 436, title: "No Lie", artist: "2 Chainz", genre: "Hip-Hop", year: 2012, album: "Based on a T.R.U. Story" },
  { id: 1437, rank: 437, title: "I'm Different", artist: "2 Chainz", genre: "Hip-Hop", year: 2012, album: "Based on a T.R.U. Story" },
  { id: 1438, rank: 438, title: "Bounce", artist: "2 Chainz", genre: "Hip-Hop", year: 2013, album: "B.O.A.T.S. II: Me Time" },
  { id: 1439, rank: 439, title: "Work (Remix)", artist: "Rihanna", genre: "Hip-Hop", year: 2016, album: "Anti" },
  { id: 1440, rank: 440, title: "Humble & Kind", artist: "Lil Baby", genre: "Hip-Hop", year: 2018, album: "Harder Than Ever" },
  { id: 1441, rank: 441, title: "Drip Too Hard", artist: "Lil Baby", genre: "Hip-Hop", year: 2018, album: "Single" },
  { id: 1442, rank: 442, title: "Yes Indeed", artist: "Lil Baby", genre: "Hip-Hop", year: 2018, album: "Harder Than Ever" },
  { id: 1443, rank: 443, title: "Woah", artist: "Lil Baby", genre: "Hip-Hop", year: 2019, album: "Single" },
  { id: 1444, rank: 444, title: "Sum 2 Prove", artist: "Lil Baby", genre: "Hip-Hop", year: 2020, album: "My Turn" },
  { id: 1445, rank: 445, title: "The Bigger Picture", artist: "Lil Baby", genre: "Hip-Hop", year: 2020, album: "Single" },
  { id: 1446, rank: 446, title: "On Me", artist: "Lil Baby", genre: "Hip-Hop", year: 2020, album: "My Turn" },
  { id: 1447, rank: 447, title: "From the D to the LBC", artist: "Snoop Dogg", genre: "Hip-Hop", year: 2022, album: "BODR" },
  { id: 1448, rank: 448, title: "Back in Business", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2014, album: "The Pinkprint" },
  { id: 1449, rank: 449, title: "Anaconda", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2014, album: "The Pinkprint" },
  { id: 1450, rank: 450, title: "Bang Bang", artist: "Jessie J", genre: "Hip-Hop", year: 2014, album: "Single" },
  { id: 1451, rank: 451, title: "Moment 4 Life", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2010, album: "Pink Friday" },
  { id: 1452, rank: 452, title: "Starships", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2012, album: "Pink Friday: Roman Reloaded" },
  { id: 1453, rank: 453, title: "Only", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2014, album: "The Pinkprint" },
  { id: 1454, rank: 454, title: "Barbie Dreams", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2018, album: "Queen" },
  { id: 1455, rank: 455, title: "Chun-Li", artist: "Nicki Minaj", genre: "Hip-Hop", year: 2018, album: "Queen" },
  { id: 1456, rank: 456, title: "Up", artist: "Cardi B", genre: "Hip-Hop", year: 2021, album: "Single" },
  { id: 1457, rank: 457, title: "WAP", artist: "Cardi B", genre: "Hip-Hop", year: 2020, album: "Single" },
  { id: 1458, rank: 458, title: "Money", artist: "Cardi B", genre: "Hip-Hop", year: 2018, album: "Invasion of Privacy" },
  { id: 1459, rank: 459, title: "I Like It", artist: "Cardi B", genre: "Hip-Hop", year: 2018, album: "Invasion of Privacy" },
  { id: 1460, rank: 460, title: "Be Careful", artist: "Cardi B", genre: "Hip-Hop", year: 2018, album: "Invasion of Privacy" },
  { id: 1461, rank: 461, title: "Drip", artist: "Cardi B", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1462, rank: 462, title: "Bartier Cardi", artist: "Cardi B", genre: "Hip-Hop", year: 2017, album: "Single" },
  { id: 1463, rank: 463, title: "Ring", artist: "Cardi B", genre: "Hip-Hop", year: 2018, album: "Invasion of Privacy" },
  { id: 1464, rank: 464, title: "Stoney", artist: "Post Malone", genre: "Hip-Hop", year: 2016, album: "Stoney" },
  { id: 1465, rank: 465, title: "Too Young", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1466, rank: 466, title: "Take What You Want", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1467, rank: 467, title: "Die for Me", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1468, rank: 468, title: "Enemies", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1469, rank: 469, title: "Rich & Sad", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1470, rank: 470, title: "Candy Paint", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1471, rank: 471, title: "Feeling Whitney", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1472, rank: 472, title: "Psycho", artist: "Post Malone", genre: "Hip-Hop", year: 2018, album: "Beerbongs & Bentleys" },
  { id: 1473, rank: 473, title: "Over Now", artist: "Post Malone", genre: "Hip-Hop", year: 2019, album: "Hollywood's Bleeding" },
  { id: 1474, rank: 474, title: "Chemical", artist: "Post Malone", genre: "Hip-Hop", year: 2023, album: "Single" },
  { id: 1475, rank: 475, title: "One Right Now", artist: "Post Malone", genre: "Hip-Hop", year: 2021, album: "Single" },
  { id: 1476, rank: 476, title: "Eleven", artist: "Kodak Black", genre: "Hip-Hop", year: 2022, album: "Back for Everything" },
  { id: 1477, rank: 477, title: "Tunnel Vision", artist: "Kodak Black", genre: "Hip-Hop", year: 2017, album: "Painting Pictures" },
  { id: 1478, rank: 478, title: "ZEZE", artist: "Kodak Black", genre: "Hip-Hop", year: 2018, album: "Dying to Live" },
  { id: 1479, rank: 479, title: "Easter in Miami", artist: "Kodak Black", genre: "Hip-Hop", year: 2016, album: "Lil Big Pac" },
  { id: 1480, rank: 480, title: "No Flockin", artist: "Kodak Black", genre: "Hip-Hop", year: 2014, album: "Single" },
  { id: 1481, rank: 481, title: "Sicko Mode (Remix)", artist: "Travis Scott", genre: "Hip-Hop", year: 2019, album: "Astroworld" },
  { id: 1482, rank: 482, title: "Left Cheek Right Cheek", artist: "Wale", genre: "Hip-Hop", year: 2017, album: "Shine" },
  { id: 1483, rank: 483, title: "The Need to Know", artist: "Wale", genre: "Hip-Hop", year: 2015, album: "The Album About Nothing" },
  { id: 1484, rank: 484, title: "The Matrimony", artist: "Wale", genre: "Hip-Hop", year: 2015, album: "The Album About Nothing" },
  { id: 1485, rank: 485, title: "Ambition", artist: "Wale", genre: "Hip-Hop", year: 2011, album: "Ambition" },
  { id: 1486, rank: 486, title: "Chain Music", artist: "Wale", genre: "Hip-Hop", year: 2012, album: "Ambition" },
  { id: 1487, rank: 487, title: "Lotus Flower Bomb", artist: "Wale", genre: "Hip-Hop", year: 2012, album: "Ambition" },
  { id: 1488, rank: 488, title: "No Hands", artist: "Waka Flocka Flame", genre: "Hip-Hop", year: 2010, album: "Flockaveli" },
  { id: 1489, rank: 489, title: "Hard in da Paint", artist: "Waka Flocka Flame", genre: "Hip-Hop", year: 2009, album: "Flockaveli" },
  { id: 1490, rank: 490, title: "Grove St. Party", artist: "Wale", genre: "Hip-Hop", year: 2013, album: "The Gifted" },
  { id: 1491, rank: 491, title: "Champions", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1492, rank: 492, title: "30 Hours", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1493, rank: 493, title: "Father Stretch My Hands Pt. 1", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1494, rank: 494, title: "FML", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1495, rank: 495, title: "Waves", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1496, rank: 496, title: "Famous", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1497, rank: 497, title: "Feedback", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1498, rank: 498, title: "Low Lights", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1499, rank: 499, title: "Freestyle 4", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
  { id: 1500, rank: 500, title: "Wolves", artist: "Kanye West", genre: "Hip-Hop", year: 2016, album: "The Life of Pablo" },
];
