const SONGS_FOLK = [
  { id: 5501, rank: 1, title: "Blowin' in the Wind", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5502, rank: 2, title: "The Times They Are a-Changin'", artist: "Bob Dylan", genre: "Folk", year: 1964, album: "The Times They Are a-Changin'" },
  { id: 5503, rank: 3, title: "Mr. Tambourine Man", artist: "Bob Dylan", genre: "Folk", year: 1965, album: "Bringing It All Back Home" },
  { id: 5504, rank: 4, title: "Like a Rolling Stone", artist: "Bob Dylan", genre: "Folk", year: 1965, album: "Highway 61 Revisited" },
  { id: 5505, rank: 5, title: "Don't Think Twice It's All Right", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5506, rank: 6, title: "A Hard Rain's a-Gonna Fall", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5507, rank: 7, title: "The Answer Is Blowin' in the Wind", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5508, rank: 8, title: "Knockin' on Heaven's Door", artist: "Bob Dylan", genre: "Folk", year: 1973, album: "Pat Garrett & Billy the Kid" },
  { id: 5509, rank: 9, title: "Tangled Up in Blue", artist: "Bob Dylan", genre: "Folk", year: 1975, album: "Blood on the Tracks" },
  { id: 5510, rank: 10, title: "Simple Twist of Fate", artist: "Bob Dylan", genre: "Folk", year: 1975, album: "Blood on the Tracks" },
  { id: 5511, rank: 11, title: "Shelter from the Storm", artist: "Bob Dylan", genre: "Folk", year: 1975, album: "Blood on the Tracks" },
  { id: 5512, rank: 12, title: "Hurricane", artist: "Bob Dylan", genre: "Folk", year: 1976, album: "Desire" },
  { id: 5513, rank: 13, title: "Forever Young", artist: "Bob Dylan", genre: "Folk", year: 1974, album: "Planet Waves" },
  { id: 5514, rank: 14, title: "It Ain't Me Babe", artist: "Bob Dylan", genre: "Folk", year: 1964, album: "Another Side of Bob Dylan" },
  { id: 5515, rank: 15, title: "My Back Pages", artist: "Bob Dylan", genre: "Folk", year: 1964, album: "Another Side of Bob Dylan" },
  { id: 5516, rank: 16, title: "The Lonesome Death of Hattie Carroll", artist: "Bob Dylan", genre: "Folk", year: 1964, album: "The Times They Are a-Changin'" },
  { id: 5517, rank: 17, title: "Masters of War", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5518, rank: 18, title: "Subterranean Homesick Blues", artist: "Bob Dylan", genre: "Folk", year: 1965, album: "Bringing It All Back Home" },
  { id: 5519, rank: 19, title: "Mr. Tambourine Man (Live)", artist: "Bob Dylan", genre: "Folk", year: 1964, album: "Bootleg Series Vol. 6" },
  { id: 5520, rank: 20, title: "Lay Lady Lay", artist: "Bob Dylan", genre: "Folk", year: 1969, album: "Nashville Skyline" },
  { id: 5521, rank: 21, title: "Girl from the North Country", artist: "Bob Dylan", genre: "Folk", year: 1963, album: "The Freewheelin' Bob Dylan" },
  { id: 5522, rank: 22, title: "Desolation Row", artist: "Bob Dylan", genre: "Folk", year: 1965, album: "Highway 61 Revisited" },
  { id: 5523, rank: 23, title: "Visions of Johanna", artist: "Bob Dylan", genre: "Folk", year: 1966, album: "Blonde on Blonde" },
  { id: 5524, rank: 24, title: "Just Like a Woman", artist: "Bob Dylan", genre: "Folk", year: 1966, album: "Blonde on Blonde" },
  { id: 5525, rank: 25, title: "Rainy Day Women #12 & 35", artist: "Bob Dylan", genre: "Folk", year: 1966, album: "Blonde on Blonde" },
  { id: 5526, rank: 26, title: "Diamonds and Rust", artist: "Joan Baez", genre: "Folk", year: 1975, album: "Diamonds & Rust" },
  { id: 5527, rank: 27, title: "We Shall Overcome", artist: "Joan Baez", genre: "Folk", year: 1963, album: "Joan Baez in Concert" },
  { id: 5528, rank: 28, title: "Farewell Angelina", artist: "Joan Baez", genre: "Folk", year: 1965, album: "Farewell Angelina" },
  { id: 5529, rank: 29, title: "The Night They Drove Old Dixie Down", artist: "Joan Baez", genre: "Folk", year: 1971, album: "Blessed Are..." },
  { id: 5530, rank: 30, title: "Joe Hill", artist: "Joan Baez", genre: "Folk", year: 1969, album: "Any Day Now" },
  { id: 5531, rank: 31, title: "Silver Dagger", artist: "Joan Baez", genre: "Folk", year: 1960, album: "Joan Baez" },
  { id: 5532, rank: 32, title: "Mary Hamilton", artist: "Joan Baez", genre: "Folk", year: 1960, album: "Joan Baez" },
  { id: 5533, rank: 33, title: "Here's to You", artist: "Joan Baez", genre: "Folk", year: 1971, album: "Blessed Are..." },
  { id: 5534, rank: 34, title: "Sweet Sir Galahad", artist: "Joan Baez", genre: "Folk", year: 1969, album: "David's Album" },
  { id: 5535, rank: 35, title: "Careless Love", artist: "Joan Baez", genre: "Folk", year: 1960, album: "Joan Baez" },
  { id: 5536, rank: 36, title: "Children of Darkness", artist: "Joan Baez", genre: "Folk", year: 1963, album: "Joan Baez in Concert" },
  { id: 5537, rank: 37, title: "Love Is Just a Four-Letter Word", artist: "Joan Baez", genre: "Folk", year: 1969, album: "Any Day Now" },
  { id: 5538, rank: 38, title: "Let It Be", artist: "Joan Baez", genre: "Folk", year: 1971, album: "Blessed Are..." },
  { id: 5539, rank: 39, title: "Plaisir d'Amour", artist: "Joan Baez", genre: "Folk", year: 1960, album: "Joan Baez" },
  { id: 5540, rank: 40, title: "Pull Up a Chair", artist: "Joan Baez", genre: "Folk", year: 2008, album: "Day After Tomorrow" },
  { id: 5541, rank: 41, title: "If I Had a Hammer", artist: "Pete Seeger", genre: "Folk", year: 1958, album: "Pete Seeger" },
  { id: 5542, rank: 42, title: "Where Have All the Flowers Gone", artist: "Pete Seeger", genre: "Folk", year: 1961, album: "The Bitter and the Sweet" },
  { id: 5543, rank: 43, title: "Turn! Turn! Turn!", artist: "Pete Seeger", genre: "Folk", year: 1962, album: "The Bitter and the Sweet" },
  { id: 5544, rank: 44, title: "This Land Is Your Land", artist: "Pete Seeger", genre: "Folk", year: 1951, album: "American Favorite Ballads" },
  { id: 5545, rank: 45, title: "Goodnight Irene", artist: "Pete Seeger", genre: "Folk", year: 1951, album: "American Favorite Ballads" },
  { id: 5546, rank: 46, title: "We Shall Overcome", artist: "Pete Seeger", genre: "Folk", year: 1963, album: "We Shall Overcome" },
  { id: 5547, rank: 47, title: "Kisses Sweeter Than Wine", artist: "Pete Seeger", genre: "Folk", year: 1951, album: "American Favorite Ballads" },
  { id: 5548, rank: 48, title: "On Top of Old Smoky", artist: "Pete Seeger", genre: "Folk", year: 1951, album: "American Favorite Ballads" },
  { id: 5549, rank: 49, title: "Banks of the Ohio", artist: "Pete Seeger", genre: "Folk", year: 1951, album: "American Favorite Ballads" },
  { id: 5550, rank: 50, title: "Waist Deep in the Big Muddy", artist: "Pete Seeger", genre: "Folk", year: 1967, album: "Waist Deep in the Big Muddy" },
  { id: 5551, rank: 51, title: "This Land Is Your Land", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5552, rank: 52, title: "Dust Bowl Blues", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5553, rank: 53, title: "Oklahoma Hills", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5554, rank: 54, title: "So Long It's Been Good to Know Yuh", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5555, rank: 55, title: "Pastures of Plenty", artist: "Woody Guthrie", genre: "Folk", year: 1947, album: "Songs to Grow On" },
  { id: 5556, rank: 56, title: "Tom Joad", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5557, rank: 57, title: "Union Maid", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5558, rank: 58, title: "Pretty Boy Floyd", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5559, rank: 59, title: "Hard Travelin'", artist: "Woody Guthrie", genre: "Folk", year: 1944, album: "Dust Bowl Ballads" },
  { id: 5560, rank: 60, title: "Do Re Mi", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5561, rank: 61, title: "Both Sides Now", artist: "Joni Mitchell", genre: "Folk", year: 1969, album: "Clouds" },
  { id: 5562, rank: 62, title: "Big Yellow Taxi", artist: "Joni Mitchell", genre: "Folk", year: 1970, album: "Ladies of the Canyon" },
  { id: 5563, rank: 63, title: "The Circle Game", artist: "Joni Mitchell", genre: "Folk", year: 1970, album: "Ladies of the Canyon" },
  { id: 5564, rank: 64, title: "River", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5565, rank: 65, title: "A Case of You", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5566, rank: 66, title: "California", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5567, rank: 67, title: "Help Me", artist: "Joni Mitchell", genre: "Folk", year: 1974, album: "Court and Spark" },
  { id: 5568, rank: 68, title: "Free Man in Paris", artist: "Joni Mitchell", genre: "Folk", year: 1974, album: "Court and Spark" },
  { id: 5569, rank: 69, title: "Woodstock", artist: "Joni Mitchell", genre: "Folk", year: 1970, album: "Ladies of the Canyon" },
  { id: 5570, rank: 70, title: "Carey", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5571, rank: 71, title: "Chelsea Morning", artist: "Joni Mitchell", genre: "Folk", year: 1969, album: "Clouds" },
  { id: 5572, rank: 72, title: "Little Green", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5573, rank: 73, title: "The Last Time I Saw Richard", artist: "Joni Mitchell", genre: "Folk", year: 1971, album: "Blue" },
  { id: 5574, rank: 74, title: "Raised on Robbery", artist: "Joni Mitchell", genre: "Folk", year: 1974, album: "Court and Spark" },
  { id: 5575, rank: 75, title: "The Magdalene Laundries", artist: "Joni Mitchell", genre: "Folk", year: 1994, album: "Turbulent Indigo" },
  { id: 5576, rank: 76, title: "The Sound of Silence", artist: "Simon & Garfunkel", genre: "Folk", year: 1964, album: "Wednesday Morning 3 A.M." },
  { id: 5577, rank: 77, title: "Mrs. Robinson", artist: "Simon & Garfunkel", genre: "Folk", year: 1968, album: "Bookends" },
  { id: 5578, rank: 78, title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", genre: "Folk", year: 1970, album: "Bridge Over Troubled Water" },
  { id: 5579, rank: 79, title: "The Boxer", artist: "Simon & Garfunkel", genre: "Folk", year: 1970, album: "Bridge Over Troubled Water" },
  { id: 5580, rank: 80, title: "Scarborough Fair", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Parsley Sage Rosemary and Thyme" },
  { id: 5581, rank: 81, title: "El Condor Pasa", artist: "Simon & Garfunkel", genre: "Folk", year: 1970, album: "Bridge Over Troubled Water" },
  { id: 5582, rank: 82, title: "America", artist: "Simon & Garfunkel", genre: "Folk", year: 1968, album: "Bookends" },
  { id: 5583, rank: 83, title: "Old Friends", artist: "Simon & Garfunkel", genre: "Folk", year: 1968, album: "Bookends" },
  { id: 5584, rank: 84, title: "I Am a Rock", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Sounds of Silence" },
  { id: 5585, rank: 85, title: "The 59th Street Bridge Song", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Parsley Sage Rosemary and Thyme" },
  { id: 5586, rank: 86, title: "Homeward Bound", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Parsley Sage Rosemary and Thyme" },
  { id: 5587, rank: 87, title: "April Come She Will", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Sounds of Silence" },
  { id: 5588, rank: 88, title: "Kathy's Song", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Sounds of Silence" },
  { id: 5589, rank: 89, title: "The Dangling Conversation", artist: "Simon & Garfunkel", genre: "Folk", year: 1966, album: "Parsley Sage Rosemary and Thyme" },
  { id: 5590, rank: 90, title: "Cecilia", artist: "Simon & Garfunkel", genre: "Folk", year: 1970, album: "Bridge Over Troubled Water" },
  { id: 5591, rank: 91, title: "Heart of Gold", artist: "Neil Young", genre: "Folk", year: 1972, album: "Harvest" },
  { id: 5592, rank: 92, title: "The Needle and the Damage Done", artist: "Neil Young", genre: "Folk", year: 1972, album: "Harvest" },
  { id: 5593, rank: 93, title: "Old Man", artist: "Neil Young", genre: "Folk", year: 1972, album: "Harvest" },
  { id: 5594, rank: 94, title: "Helpless", artist: "Neil Young", genre: "Folk", year: 1970, album: "Déjà Vu" },
  { id: 5595, rank: 95, title: "After the Gold Rush", artist: "Neil Young", genre: "Folk", year: 1970, album: "After the Gold Rush" },
  { id: 5596, rank: 96, title: "Harvest Moon", artist: "Neil Young", genre: "Folk", year: 1992, album: "Harvest Moon" },
  { id: 5597, rank: 97, title: "Ohio", artist: "Neil Young", genre: "Folk", year: 1970, album: "So Far" },
  { id: 5598, rank: 98, title: "Southern Man", artist: "Neil Young", genre: "Folk", year: 1970, album: "After the Gold Rush" },
  { id: 5599, rank: 99, title: "Sugar Mountain", artist: "Neil Young", genre: "Folk", year: 1969, album: "Decade" },
  { id: 5600, rank: 100, title: "Only Love Can Break Your Heart", artist: "Neil Young", genre: "Folk", year: 1970, album: "After the Gold Rush" },
  { id: 5601, rank: 101, title: "Comes a Time", artist: "Neil Young", genre: "Folk", year: 1978, album: "Comes a Time" },
  { id: 5602, rank: 102, title: "Lotta Love", artist: "Neil Young", genre: "Folk", year: 1979, album: "Rust Never Sleeps" },
  { id: 5603, rank: 103, title: "Prairie Wind", artist: "Neil Young", genre: "Folk", year: 2005, album: "Prairie Wind" },
  { id: 5604, rank: 104, title: "The Painter", artist: "Neil Young", genre: "Folk", year: 2005, album: "Prairie Wind" },
  { id: 5605, rank: 105, title: "A Man Needs a Maid", artist: "Neil Young", genre: "Folk", year: 1972, album: "Harvest" },
  { id: 5606, rank: 106, title: "Suzanne", artist: "Leonard Cohen", genre: "Folk", year: 1967, album: "Songs of Leonard Cohen" },
  { id: 5607, rank: 107, title: "Famous Blue Raincoat", artist: "Leonard Cohen", genre: "Folk", year: 1971, album: "Songs of Love and Hate" },
  { id: 5608, rank: 108, title: "Hallelujah", artist: "Leonard Cohen", genre: "Folk", year: 1984, album: "Various Positions" },
  { id: 5609, rank: 109, title: "Bird on the Wire", artist: "Leonard Cohen", genre: "Folk", year: 1969, album: "Songs from a Room" },
  { id: 5610, rank: 110, title: "Sisters of Mercy", artist: "Leonard Cohen", genre: "Folk", year: 1967, album: "Songs of Leonard Cohen" },
  { id: 5611, rank: 111, title: "Hey That's No Way to Say Goodbye", artist: "Leonard Cohen", genre: "Folk", year: 1967, album: "Songs of Leonard Cohen" },
  { id: 5612, rank: 112, title: "Chelsea Hotel No. 2", artist: "Leonard Cohen", genre: "Folk", year: 1974, album: "New Skin for the Old Ceremony" },
  { id: 5613, rank: 113, title: "So Long Marianne", artist: "Leonard Cohen", genre: "Folk", year: 1967, album: "Songs of Leonard Cohen" },
  { id: 5614, rank: 114, title: "Dance Me to the End of Love", artist: "Leonard Cohen", genre: "Folk", year: 1984, album: "Various Positions" },
  { id: 5615, rank: 115, title: "Anthem", artist: "Leonard Cohen", genre: "Folk", year: 1992, album: "The Future" },
  { id: 5616, rank: 116, title: "Tower of Song", artist: "Leonard Cohen", genre: "Folk", year: 1988, album: "I'm Your Man" },
  { id: 5617, rank: 117, title: "Everybody Knows", artist: "Leonard Cohen", genre: "Folk", year: 1988, album: "I'm Your Man" },
  { id: 5618, rank: 118, title: "First We Take Manhattan", artist: "Leonard Cohen", genre: "Folk", year: 1988, album: "I'm Your Man" },
  { id: 5619, rank: 119, title: "The Future", artist: "Leonard Cohen", genre: "Folk", year: 1992, album: "The Future" },
  { id: 5620, rank: 120, title: "Closing Time", artist: "Leonard Cohen", genre: "Folk", year: 1992, album: "The Future" },
  { id: 5621, rank: 121, title: "River Man", artist: "Nick Drake", genre: "Folk", year: 1969, album: "Five Leaves Left" },
  { id: 5622, rank: 122, title: "Way to Blue", artist: "Nick Drake", genre: "Folk", year: 1969, album: "Five Leaves Left" },
  { id: 5623, rank: 123, title: "Pink Moon", artist: "Nick Drake", genre: "Folk", year: 1972, album: "Pink Moon" },
  { id: 5624, rank: 124, title: "Place to Be", artist: "Nick Drake", genre: "Folk", year: 1972, album: "Pink Moon" },
  { id: 5625, rank: 125, title: "Cello Song", artist: "Nick Drake", genre: "Folk", year: 1969, album: "Five Leaves Left" },
  { id: 5626, rank: 126, title: "Northern Sky", artist: "Nick Drake", genre: "Folk", year: 1970, album: "Bryter Layter" },
  { id: 5627, rank: 127, title: "Hazey Jane II", artist: "Nick Drake", genre: "Folk", year: 1970, album: "Bryter Layter" },
  { id: 5628, rank: 128, title: "Time Has Told Me", artist: "Nick Drake", genre: "Folk", year: 1969, album: "Five Leaves Left" },
  { id: 5629, rank: 129, title: "Fruit Tree", artist: "Nick Drake", genre: "Folk", year: 1969, album: "Five Leaves Left" },
  { id: 5630, rank: 130, title: "From the Morning", artist: "Nick Drake", genre: "Folk", year: 1972, album: "Pink Moon" },
  { id: 5631, rank: 131, title: "Wild World", artist: "Cat Stevens", genre: "Folk", year: 1970, album: "Tea for the Tillerman" },
  { id: 5632, rank: 132, title: "Father and Son", artist: "Cat Stevens", genre: "Folk", year: 1970, album: "Tea for the Tillerman" },
  { id: 5633, rank: 133, title: "Peace Train", artist: "Cat Stevens", genre: "Folk", year: 1971, album: "Teaser and the Firecat" },
  { id: 5634, rank: 134, title: "Morning Has Broken", artist: "Cat Stevens", genre: "Folk", year: 1971, album: "Teaser and the Firecat" },
  { id: 5635, rank: 135, title: "Moon Shadow", artist: "Cat Stevens", genre: "Folk", year: 1971, album: "Teaser and the Firecat" },
  { id: 5636, rank: 136, title: "Oh Very Young", artist: "Cat Stevens", genre: "Folk", year: 1974, album: "Buddha and the Chocolate Box" },
  { id: 5637, rank: 137, title: "Where Do the Children Play", artist: "Cat Stevens", genre: "Folk", year: 1970, album: "Tea for the Tillerman" },
  { id: 5638, rank: 138, title: "Hard Headed Woman", artist: "Cat Stevens", genre: "Folk", year: 1970, album: "Tea for the Tillerman" },
  { id: 5639, rank: 139, title: "Into White", artist: "Cat Stevens", genre: "Folk", year: 1970, album: "Tea for the Tillerman" },
  { id: 5640, rank: 140, title: "The Wind", artist: "Cat Stevens", genre: "Folk", year: 1971, album: "Teaser and the Firecat" },
  { id: 5641, rank: 141, title: "Fire and Rain", artist: "James Taylor", genre: "Folk", year: 1970, album: "Sweet Baby James" },
  { id: 5642, rank: 142, title: "You've Got a Friend", artist: "James Taylor", genre: "Folk", year: 1971, album: "Mud Slide Slim and the Blue Horizon" },
  { id: 5643, rank: 143, title: "Carolina in My Mind", artist: "James Taylor", genre: "Folk", year: 1968, album: "James Taylor" },
  { id: 5644, rank: 144, title: "Sweet Baby James", artist: "James Taylor", genre: "Folk", year: 1970, album: "Sweet Baby James" },
  { id: 5645, rank: 145, title: "Shower the People", artist: "James Taylor", genre: "Folk", year: 1976, album: "In the Pocket" },
  { id: 5646, rank: 146, title: "Handy Man", artist: "James Taylor", genre: "Folk", year: 1977, album: "JT" },
  { id: 5647, rank: 147, title: "How Sweet It Is", artist: "James Taylor", genre: "Folk", year: 1975, album: "Gorilla" },
  { id: 5648, rank: 148, title: "Mexico", artist: "James Taylor", genre: "Folk", year: 1975, album: "Gorilla" },
  { id: 5649, rank: 149, title: "Secret O' Life", artist: "James Taylor", genre: "Folk", year: 1977, album: "JT" },
  { id: 5650, rank: 150, title: "Country Road", artist: "James Taylor", genre: "Folk", year: 1970, album: "Sweet Baby James" },
  { id: 5651, rank: 151, title: "I Feel the Earth Move", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5652, rank: 152, title: "So Far Away", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5653, rank: 153, title: "It's Too Late", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5654, rank: 154, title: "You've Got a Friend", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5655, rank: 155, title: "Tapestry", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5656, rank: 156, title: "Will You Love Me Tomorrow", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5657, rank: 157, title: "I Really Love You", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5658, rank: 158, title: "Way Over Yonder", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5659, rank: 159, title: "Natural Woman", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5660, rank: 160, title: "Beautiful", artist: "Carole King", genre: "Folk", year: 1971, album: "Tapestry" },
  { id: 5661, rank: 161, title: "Catch the Wind", artist: "Donovan", genre: "Folk", year: 1965, album: "What's Bin Did and What's Bin Hid" },
  { id: 5662, rank: 162, title: "Season of the Witch", artist: "Donovan", genre: "Folk", year: 1966, album: "Sunshine Superman" },
  { id: 5663, rank: 163, title: "Mellow Yellow", artist: "Donovan", genre: "Folk", year: 1966, album: "Mellow Yellow" },
  { id: 5664, rank: 164, title: "Hurdy Gurdy Man", artist: "Donovan", genre: "Folk", year: 1968, album: "The Hurdy Gurdy Man" },
  { id: 5665, rank: 165, title: "Jennifer Juniper", artist: "Donovan", genre: "Folk", year: 1968, album: "The Hurdy Gurdy Man" },
  { id: 5666, rank: 166, title: "Sunshine Superman", artist: "Donovan", genre: "Folk", year: 1966, album: "Sunshine Superman" },
  { id: 5667, rank: 167, title: "Wear Your Love Like Heaven", artist: "Donovan", genre: "Folk", year: 1967, album: "Gift from a Flower to a Garden" },
  { id: 5668, rank: 168, title: "There Is a Mountain", artist: "Donovan", genre: "Folk", year: 1967, album: "Gift from a Flower to a Garden" },
  { id: 5669, rank: 169, title: "Colours", artist: "Donovan", genre: "Folk", year: 1965, album: "What's Bin Did and What's Bin Hid" },
  { id: 5670, rank: 170, title: "Isle of Islay", artist: "Donovan", genre: "Folk", year: 1965, album: "What's Bin Did and What's Bin Hid" },
  { id: 5671, rank: 171, title: "Who Knows Where the Time Goes", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Unhalfbricking" },
  { id: 5672, rank: 172, title: "Meet on the Ledge", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "What We Did on Our Holidays" },
  { id: 5673, rank: 173, title: "Matty Groves", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Liege & Lief" },
  { id: 5674, rank: 174, title: "Tam Lin", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Liege & Lief" },
  { id: 5675, rank: 175, title: "A Sailor's Life", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Unhalfbricking" },
  { id: 5676, rank: 176, title: "Fotheringay", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Unhalfbricking" },
  { id: 5677, rank: 177, title: "The Deserter", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Liege & Lief" },
  { id: 5678, rank: 178, title: "Crazy Man Michael", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Liege & Lief" },
  { id: 5679, rank: 179, title: "Sloth", artist: "Fairport Convention", genre: "Folk", year: 1970, album: "Full House" },
  { id: 5680, rank: 180, title: "The Bonny Black Hare", artist: "Fairport Convention", genre: "Folk", year: 1969, album: "Liege & Lief" },
  { id: 5681, rank: 181, title: "Light Flight", artist: "Pentangle", genre: "Folk", year: 1970, album: "Cruel Sister" },
  { id: 5682, rank: 182, title: "Hunting Song", artist: "Pentangle", genre: "Folk", year: 1968, album: "Sweet Child" },
  { id: 5683, rank: 183, title: "Basket of Light", artist: "Pentangle", genre: "Folk", year: 1969, album: "Basket of Light" },
  { id: 5684, rank: 184, title: "Once I Had a Sweetheart", artist: "Pentangle", genre: "Folk", year: 1969, album: "Basket of Light" },
  { id: 5685, rank: 185, title: "Sally Free and Easy", artist: "Pentangle", genre: "Folk", year: 1968, album: "Pentangle" },
  { id: 5686, rank: 186, title: "Springtime Promises", artist: "Pentangle", genre: "Folk", year: 1970, album: "Cruel Sister" },
  { id: 5687, rank: 187, title: "Jack Orion", artist: "Pentangle", genre: "Folk", year: 1969, album: "Basket of Light" },
  { id: 5688, rank: 188, title: "The Time Has Come", artist: "Pentangle", genre: "Folk", year: 1970, album: "Cruel Sister" },
  { id: 5689, rank: 189, title: "Bruton Town", artist: "Pentangle", genre: "Folk", year: 1968, album: "Sweet Child" },
  { id: 5690, rank: 190, title: "No More My Lord", artist: "Pentangle", genre: "Folk", year: 1968, album: "Pentangle" },
  { id: 5691, rank: 191, title: "Needle of Death", artist: "Bert Jansch", genre: "Folk", year: 1965, album: "Bert Jansch" },
  { id: 5692, rank: 192, title: "Angie", artist: "Bert Jansch", genre: "Folk", year: 1965, album: "Bert Jansch" },
  { id: 5693, rank: 193, title: "Running from Home", artist: "Bert Jansch", genre: "Folk", year: 1965, album: "Bert Jansch" },
  { id: 5694, rank: 194, title: "Do You Hear Me Now", artist: "Bert Jansch", genre: "Folk", year: 1966, album: "Jack Orion" },
  { id: 5695, rank: 195, title: "Black Water Side", artist: "Bert Jansch", genre: "Folk", year: 1966, album: "Jack Orion" },
  { id: 5696, rank: 196, title: "Strolling Down the Highway", artist: "Bert Jansch", genre: "Folk", year: 1965, album: "Bert Jansch" },
  { id: 5697, rank: 197, title: "Alice's Wonderland", artist: "Bert Jansch", genre: "Folk", year: 1966, album: "Birthday Blues" },
  { id: 5698, rank: 198, title: "A Woman Like You", artist: "Bert Jansch", genre: "Folk", year: 1966, album: "Birthday Blues" },
  { id: 5699, rank: 199, title: "Goodbye Pork Pie Hat", artist: "Bert Jansch", genre: "Folk", year: 1966, album: "Birthday Blues" },
  { id: 5700, rank: 200, title: "Lucky Thirteen", artist: "Bert Jansch", genre: "Folk", year: 1965, album: "Bert Jansch" },
  { id: 5701, rank: 201, title: "The Hermit", artist: "John Renbourn", genre: "Folk", year: 1968, album: "The Lady and the Unicorn" },
  { id: 5702, rank: 202, title: "John Henry", artist: "John Renbourn", genre: "Folk", year: 1966, album: "Another Monday" },
  { id: 5703, rank: 203, title: "The Lady and the Unicorn", artist: "John Renbourn", genre: "Folk", year: 1970, album: "The Lady and the Unicorn" },
  { id: 5704, rank: 204, title: "Lindisfarne", artist: "John Renbourn", genre: "Folk", year: 1969, album: "The Lady and the Unicorn" },
  { id: 5705, rank: 205, title: "Lord Franklin", artist: "John Renbourn", genre: "Folk", year: 1968, album: "Sir John Alot of Merrie Englandes Musyk" },
  { id: 5706, rank: 206, title: "Trotto", artist: "John Renbourn", genre: "Folk", year: 1968, album: "Sir John Alot of Merrie Englandes Musyk" },
  { id: 5707, rank: 207, title: "Buffalo Skinners", artist: "John Renbourn", genre: "Folk", year: 1966, album: "Another Monday" },
  { id: 5708, rank: 208, title: "Tell Me What You See", artist: "John Renbourn", genre: "Folk", year: 1966, album: "Another Monday" },
  { id: 5709, rank: 209, title: "Mist Covered Mountains", artist: "John Renbourn", genre: "Folk", year: 1969, album: "The Lady and the Unicorn" },
  { id: 5710, rank: 210, title: "The Pelican", artist: "John Renbourn", genre: "Folk", year: 1968, album: "Sir John Alot of Merrie Englandes Musyk" },
  { id: 5711, rank: 211, title: "Who Knows Where the Time Goes", artist: "Sandy Denny", genre: "Folk", year: 1967, album: "All Our Own Work" },
  { id: 5712, rank: 212, title: "It'll Take a Long Time", artist: "Sandy Denny", genre: "Folk", year: 1972, album: "Sandy" },
  { id: 5713, rank: 213, title: "The Quiet Joys of Brotherhood", artist: "Sandy Denny", genre: "Folk", year: 1971, album: "The North Star Grassman and the Ravens" },
  { id: 5714, rank: 214, title: "Late November", artist: "Sandy Denny", genre: "Folk", year: 1971, album: "The North Star Grassman and the Ravens" },
  { id: 5715, rank: 215, title: "John the Gun", artist: "Sandy Denny", genre: "Folk", year: 1971, album: "The North Star Grassman and the Ravens" },
  { id: 5716, rank: 216, title: "Next Time Around", artist: "Sandy Denny", genre: "Folk", year: 1972, album: "Sandy" },
  { id: 5717, rank: 217, title: "No End", artist: "Sandy Denny", genre: "Folk", year: 1972, album: "Sandy" },
  { id: 5718, rank: 218, title: "The Music Weaver", artist: "Sandy Denny", genre: "Folk", year: 1972, album: "Sandy" },
  { id: 5719, rank: 219, title: "Crazy Lady Blues", artist: "Sandy Denny", genre: "Folk", year: 1971, album: "The North Star Grassman and the Ravens" },
  { id: 5720, rank: 220, title: "Nothing More", artist: "Sandy Denny", genre: "Folk", year: 1974, album: "Like an Old Fashioned Waltz" },
  { id: 5721, rank: 221, title: "Both Sides Now", artist: "Judy Collins", genre: "Folk", year: 1967, album: "Wildflowers" },
  { id: 5722, rank: 222, title: "Send in the Clowns", artist: "Judy Collins", genre: "Folk", year: 1975, album: "Judith" },
  { id: 5723, rank: 223, title: "Amazing Grace", artist: "Judy Collins", genre: "Folk", year: 1970, album: "Whales & Nightingales" },
  { id: 5724, rank: 224, title: "Someday Soon", artist: "Judy Collins", genre: "Folk", year: 1968, album: "Who Knows Where the Time Goes" },
  { id: 5725, rank: 225, title: "Since You've Asked", artist: "Judy Collins", genre: "Folk", year: 1967, album: "Wildflowers" },
  { id: 5726, rank: 226, title: "Albatross", artist: "Judy Collins", genre: "Folk", year: 1967, album: "Wildflowers" },
  { id: 5727, rank: 227, title: "My Father", artist: "Judy Collins", genre: "Folk", year: 1968, album: "Who Knows Where the Time Goes" },
  { id: 5728, rank: 228, title: "Chelsea Morning", artist: "Judy Collins", genre: "Folk", year: 1969, album: "Recollections" },
  { id: 5729, rank: 229, title: "Open the Door", artist: "Judy Collins", genre: "Folk", year: 1967, album: "Wildflowers" },
  { id: 5730, rank: 230, title: "The Hostage", artist: "Judy Collins", genre: "Folk", year: 1971, album: "Living" },
  { id: 5731, rank: 231, title: "I Ain't Marching Anymore", artist: "Phil Ochs", genre: "Folk", year: 1965, album: "I Ain't Marching Anymore" },
  { id: 5732, rank: 232, title: "There but for Fortune", artist: "Phil Ochs", genre: "Folk", year: 1964, album: "All the News That's Fit to Sing" },
  { id: 5733, rank: 233, title: "Changes", artist: "Phil Ochs", genre: "Folk", year: 1966, album: "Phil Ochs in Concert" },
  { id: 5734, rank: 234, title: "Draft Dodger Rag", artist: "Phil Ochs", genre: "Folk", year: 1965, album: "I Ain't Marching Anymore" },
  { id: 5735, rank: 235, title: "Love Me I'm a Liberal", artist: "Phil Ochs", genre: "Folk", year: 1966, album: "Phil Ochs in Concert" },
  { id: 5736, rank: 236, title: "The War Is Over", artist: "Phil Ochs", genre: "Folk", year: 1968, album: "Tape from California" },
  { id: 5737, rank: 237, title: "Outside of a Small Circle of Friends", artist: "Phil Ochs", genre: "Folk", year: 1967, album: "Pleasures of the Harbor" },
  { id: 5738, rank: 238, title: "Pleasures of the Harbor", artist: "Phil Ochs", genre: "Folk", year: 1967, album: "Pleasures of the Harbor" },
  { id: 5739, rank: 239, title: "When I'm Gone", artist: "Phil Ochs", genre: "Folk", year: 1966, album: "Phil Ochs in Concert" },
  { id: 5740, rank: 240, title: "Crucifixion", artist: "Phil Ochs", genre: "Folk", year: 1967, album: "Pleasures of the Harbor" },
  { id: 5741, rank: 241, title: "Ramblin' Boy", artist: "Tom Paxton", genre: "Folk", year: 1964, album: "Ramblin' Boy" },
  { id: 5742, rank: 242, title: "I Can't Help but Wonder Where I'm Bound", artist: "Tom Paxton", genre: "Folk", year: 1964, album: "Ramblin' Boy" },
  { id: 5743, rank: 243, title: "The Last Thing on My Mind", artist: "Tom Paxton", genre: "Folk", year: 1964, album: "Ramblin' Boy" },
  { id: 5744, rank: 244, title: "My Ramblin' Boy", artist: "Tom Paxton", genre: "Folk", year: 1964, album: "Ramblin' Boy" },
  { id: 5745, rank: 245, title: "Ain't That News", artist: "Tom Paxton", genre: "Folk", year: 1965, album: "Ain't That News!" },
  { id: 5746, rank: 246, title: "Going to the Zoo", artist: "Tom Paxton", genre: "Folk", year: 1966, album: "Morning Again" },
  { id: 5747, rank: 247, title: "When Morning Rolls Around", artist: "Tom Paxton", genre: "Folk", year: 1966, album: "Morning Again" },
  { id: 5748, rank: 248, title: "The Willing Conscript", artist: "Tom Paxton", genre: "Folk", year: 1965, album: "Ain't That News!" },
  { id: 5749, rank: 249, title: "Peace Will Come", artist: "Tom Paxton", genre: "Folk", year: 1972, album: "Peace Will Come" },
  { id: 5750, rank: 250, title: "The Marvelous Toy", artist: "Tom Paxton", genre: "Folk", year: 1963, album: "Ramblin' Boy" },
  { id: 5751, rank: 251, title: "No Regrets", artist: "Tom Rush", genre: "Folk", year: 1968, album: "The Circle Game" },
  { id: 5752, rank: 252, title: "The Circle Game", artist: "Tom Rush", genre: "Folk", year: 1968, album: "The Circle Game" },
  { id: 5753, rank: 253, title: "Urge for Going", artist: "Tom Rush", genre: "Folk", year: 1968, album: "The Circle Game" },
  { id: 5754, rank: 254, title: "Something in the Way She Moves", artist: "Tom Rush", genre: "Folk", year: 1968, album: "The Circle Game" },
  { id: 5755, rank: 255, title: "Lo and Behold", artist: "Tom Rush", genre: "Folk", year: 1966, album: "Take a Little Walk with Me" },
  { id: 5756, rank: 256, title: "Who Do You Love", artist: "Tom Rush", genre: "Folk", year: 1966, album: "Take a Little Walk with Me" },
  { id: 5757, rank: 257, title: "Panama Limited", artist: "Tom Rush", genre: "Folk", year: 1966, album: "Take a Little Walk with Me" },
  { id: 5758, rank: 258, title: "Galveston Flood", artist: "Tom Rush", genre: "Folk", year: 1964, album: "Tom Rush" },
  { id: 5759, rank: 259, title: "On the Road Again", artist: "Tom Rush", genre: "Folk", year: 1964, album: "Tom Rush" },
  { id: 5760, rank: 260, title: "Wasn't That a Mighty Storm", artist: "Tom Rush", genre: "Folk", year: 1964, album: "Tom Rush" },
  { id: 5761, rank: 261, title: "Cocaine Blues", artist: "Dave Van Ronk", genre: "Folk", year: 1962, album: "Dave Van Ronk Sings the Blues" },
  { id: 5762, rank: 262, title: "House of the Rising Sun", artist: "Dave Van Ronk", genre: "Folk", year: 1963, album: "Dave Van Ronk" },
  { id: 5763, rank: 263, title: "Candy Man", artist: "Dave Van Ronk", genre: "Folk", year: 1962, album: "Dave Van Ronk Sings the Blues" },
  { id: 5764, rank: 264, title: "Careless Love", artist: "Dave Van Ronk", genre: "Folk", year: 1963, album: "Dave Van Ronk" },
  { id: 5765, rank: 265, title: "Green Rocky Road", artist: "Dave Van Ronk", genre: "Folk", year: 1963, album: "Dave Van Ronk" },
  { id: 5766, rank: 266, title: "Hang Me Oh Hang Me", artist: "Dave Van Ronk", genre: "Folk", year: 1962, album: "Dave Van Ronk Sings the Blues" },
  { id: 5767, rank: 267, title: "One For the Road", artist: "Dave Van Ronk", genre: "Folk", year: 1967, album: "Dave Van Ronk and the Hudson Dusters" },
  { id: 5768, rank: 268, title: "Big Rock Candy Mountain", artist: "Dave Van Ronk", genre: "Folk", year: 1966, album: "No Dirty Names" },
  { id: 5769, rank: 269, title: "Motherless Children", artist: "Dave Van Ronk", genre: "Folk", year: 1964, album: "In the Tradition" },
  { id: 5770, rank: 270, title: "St. James Infirmary", artist: "Dave Van Ronk", genre: "Folk", year: 1962, album: "Dave Van Ronk Sings the Blues" },
  { id: 5771, rank: 271, title: "If You Could Read My Mind", artist: "Gordon Lightfoot", genre: "Folk", year: 1970, album: "Sit Down Young Stranger" },
  { id: 5772, rank: 272, title: "Sundown", artist: "Gordon Lightfoot", genre: "Folk", year: 1974, album: "Sundown" },
  { id: 5773, rank: 273, title: "The Wreck of the Edmund Fitzgerald", artist: "Gordon Lightfoot", genre: "Folk", year: 1976, album: "Summertime Dream" },
  { id: 5774, rank: 274, title: "Carefree Highway", artist: "Gordon Lightfoot", genre: "Folk", year: 1974, album: "Sundown" },
  { id: 5775, rank: 275, title: "Early Morning Rain", artist: "Gordon Lightfoot", genre: "Folk", year: 1966, album: "Lightfoot!" },
  { id: 5776, rank: 276, title: "For Lovin' Me", artist: "Gordon Lightfoot", genre: "Folk", year: 1966, album: "Lightfoot!" },
  { id: 5777, rank: 277, title: "Cotton Jenny", artist: "Gordon Lightfoot", genre: "Folk", year: 1971, album: "Don Quixote" },
  { id: 5778, rank: 278, title: "Beautiful", artist: "Gordon Lightfoot", genre: "Folk", year: 1972, album: "Don Quixote" },
  { id: 5779, rank: 279, title: "Rainy Day People", artist: "Gordon Lightfoot", genre: "Folk", year: 1975, album: "Cold on the Shoulder" },
  { id: 5780, rank: 280, title: "Daylight Katy", artist: "Gordon Lightfoot", genre: "Folk", year: 1978, album: "Endless Wire" },
  { id: 5781, rank: 281, title: "Four Strong Winds", artist: "Ian & Sylvia", genre: "Folk", year: 1963, album: "Four Strong Winds" },
  { id: 5782, rank: 282, title: "You Were on My Mind", artist: "Ian & Sylvia", genre: "Folk", year: 1964, album: "Northern Journey" },
  { id: 5783, rank: 283, title: "Early Morning Rain", artist: "Ian & Sylvia", genre: "Folk", year: 1964, album: "Northern Journey" },
  { id: 5784, rank: 284, title: "Someday Soon", artist: "Ian & Sylvia", genre: "Folk", year: 1963, album: "Four Strong Winds" },
  { id: 5785, rank: 285, title: "This Wheel's on Fire", artist: "Ian & Sylvia", genre: "Folk", year: 1968, album: "Full Circle" },
  { id: 5786, rank: 286, title: "Lovin' Sound", artist: "Ian & Sylvia", genre: "Folk", year: 1967, album: "Lovin' Sound" },
  { id: 5787, rank: 287, title: "Canadian Railroad Trilogy", artist: "Ian & Sylvia", genre: "Folk", year: 1967, album: "So Much for Dreaming" },
  { id: 5788, rank: 288, title: "Morning", artist: "Ian & Sylvia", genre: "Folk", year: 1965, album: "Early Morning Rain" },
  { id: 5789, rank: 289, title: "Darcy Farrow", artist: "Ian & Sylvia", genre: "Folk", year: 1965, album: "Early Morning Rain" },
  { id: 5790, rank: 290, title: "Twenty-Four Hours from Tulsa", artist: "Ian & Sylvia", genre: "Folk", year: 1965, album: "Early Morning Rain" },
  { id: 5791, rank: 291, title: "Puff the Magic Dragon", artist: "Peter Paul & Mary", genre: "Folk", year: 1963, album: "Peter Paul and Mary" },
  { id: 5792, rank: 292, title: "If I Had a Hammer", artist: "Peter Paul & Mary", genre: "Folk", year: 1962, album: "Peter Paul and Mary" },
  { id: 5793, rank: 293, title: "Blowin' in the Wind", artist: "Peter Paul & Mary", genre: "Folk", year: 1963, album: "In the Wind" },
  { id: 5794, rank: 294, title: "Where Have All the Flowers Gone", artist: "Peter Paul & Mary", genre: "Folk", year: 1962, album: "Moving" },
  { id: 5795, rank: 295, title: "Leaving on a Jet Plane", artist: "Peter Paul & Mary", genre: "Folk", year: 1969, album: "Album 1700" },
  { id: 5796, rank: 296, title: "Lemon Tree", artist: "Peter Paul & Mary", genre: "Folk", year: 1962, album: "Peter Paul and Mary" },
  { id: 5797, rank: 297, title: "500 Miles", artist: "Peter Paul & Mary", genre: "Folk", year: 1963, album: "In the Wind" },
  { id: 5798, rank: 298, title: "The Times They Are a-Changin'", artist: "Peter Paul & Mary", genre: "Folk", year: 1964, album: "In the Wind" },
  { id: 5799, rank: 299, title: "Don't Think Twice It's All Right", artist: "Peter Paul & Mary", genre: "Folk", year: 1963, album: "In the Wind" },
  { id: 5800, rank: 300, title: "I Dig Rock and Roll Music", artist: "Peter Paul & Mary", genre: "Folk", year: 1967, album: "Album 1700" },
  { id: 5801, rank: 301, title: "Tom Dooley", artist: "The Kingston Trio", genre: "Folk", year: 1958, album: "The Kingston Trio" },
  { id: 5802, rank: 302, title: "Where Have All the Flowers Gone", artist: "The Kingston Trio", genre: "Folk", year: 1962, album: "New Frontier" },
  { id: 5803, rank: 303, title: "Scotch and Soda", artist: "The Kingston Trio", genre: "Folk", year: 1958, album: "The Kingston Trio" },
  { id: 5804, rank: 304, title: "Greenback Dollar", artist: "The Kingston Trio", genre: "Folk", year: 1963, album: "Sunny Side!" },
  { id: 5805, rank: 305, title: "M.T.A.", artist: "The Kingston Trio", genre: "Folk", year: 1959, album: "From the Hungry i" },
  { id: 5806, rank: 306, title: "The Tijuana Jail", artist: "The Kingston Trio", genre: "Folk", year: 1959, album: "At Large" },
  { id: 5807, rank: 307, title: "Reverend Mr. Black", artist: "The Kingston Trio", genre: "Folk", year: 1963, album: "Sunny Side!" },
  { id: 5808, rank: 308, title: "A Worried Man", artist: "The Kingston Trio", genre: "Folk", year: 1959, album: "At Large" },
  { id: 5809, rank: 309, title: "Desert Pete", artist: "The Kingston Trio", genre: "Folk", year: 1963, album: "Sunny Side!" },
  { id: 5810, rank: 310, title: "Turn Around", artist: "The Kingston Trio", genre: "Folk", year: 1963, album: "Sunny Side!" },
  { id: 5811, rank: 311, title: "Suite: Judy Blue Eyes", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5812, rank: 312, title: "Helplessly Hoping", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5813, rank: 313, title: "Wooden Ships", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5814, rank: 314, title: "Marrakesh Express", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5815, rank: 315, title: "Long Time Gone", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5816, rank: 316, title: "49 Bye-Byes", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5817, rank: 317, title: "Lady of the Island", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5818, rank: 318, title: "Guinnevere", artist: "Crosby Stills & Nash", genre: "Folk", year: 1969, album: "Crosby Stills & Nash" },
  { id: 5819, rank: 319, title: "Teach Your Children", artist: "Crosby Stills & Nash", genre: "Folk", year: 1970, album: "Déjà Vu" },
  { id: 5820, rank: 320, title: "Our House", artist: "Crosby Stills & Nash", genre: "Folk", year: 1970, album: "Déjà Vu" },
  { id: 5821, rank: 321, title: "Take Me Home Country Roads", artist: "John Denver", genre: "Folk", year: 1971, album: "Poems Prayers & Promises" },
  { id: 5822, rank: 322, title: "Rocky Mountain High", artist: "John Denver", genre: "Folk", year: 1972, album: "Rocky Mountain High" },
  { id: 5823, rank: 323, title: "Sunshine on My Shoulders", artist: "John Denver", genre: "Folk", year: 1971, album: "Poems Prayers & Promises" },
  { id: 5824, rank: 324, title: "Annie's Song", artist: "John Denver", genre: "Folk", year: 1974, album: "Back Home Again" },
  { id: 5825, rank: 325, title: "Leaving on a Jet Plane", artist: "John Denver", genre: "Folk", year: 1969, album: "Rhymes & Reasons" },
  { id: 5826, rank: 326, title: "Country Roads", artist: "John Denver", genre: "Folk", year: 1972, album: "Rocky Mountain High" },
  { id: 5827, rank: 327, title: "Calypso", artist: "John Denver", genre: "Folk", year: 1975, album: "Windsong" },
  { id: 5828, rank: 328, title: "Thank God I'm a Country Boy", artist: "John Denver", genre: "Folk", year: 1974, album: "Back Home Again" },
  { id: 5829, rank: 329, title: "For Baby", artist: "John Denver", genre: "Folk", year: 1969, album: "Rhymes & Reasons" },
  { id: 5830, rank: 330, title: "Poems Prayers & Promises", artist: "John Denver", genre: "Folk", year: 1971, album: "Poems Prayers & Promises" },
  { id: 5831, rank: 331, title: "Cat's in the Cradle", artist: "Harry Chapin", genre: "Folk", year: 1974, album: "Verities & Balderdash" },
  { id: 5832, rank: 332, title: "Taxi", artist: "Harry Chapin", genre: "Folk", year: 1972, album: "Heads & Tales" },
  { id: 5833, rank: 333, title: "W.O.L.D.", artist: "Harry Chapin", genre: "Folk", year: 1974, album: "Short Stories" },
  { id: 5834, rank: 334, title: "Story of a Life", artist: "Harry Chapin", genre: "Folk", year: 1981, album: "Sequel" },
  { id: 5835, rank: 335, title: "Sequel", artist: "Harry Chapin", genre: "Folk", year: 1980, album: "Sequel" },
  { id: 5836, rank: 336, title: "A Better Place to Be", artist: "Harry Chapin", genre: "Folk", year: 1972, album: "Heads & Tales" },
  { id: 5837, rank: 337, title: "Flowers Are Red", artist: "Harry Chapin", genre: "Folk", year: 1978, album: "Living Room Suite" },
  { id: 5838, rank: 338, title: "Circle", artist: "Harry Chapin", genre: "Folk", year: 1972, album: "Heads & Tales" },
  { id: 5839, rank: 339, title: "Mr. Tanner", artist: "Harry Chapin", genre: "Folk", year: 1973, album: "Short Stories" },
  { id: 5840, rank: 340, title: "Shooting Star", artist: "Harry Chapin", genre: "Folk", year: 1972, album: "Heads & Tales" },
  { id: 5841, rank: 341, title: "Time in a Bottle", artist: "Jim Croce", genre: "Folk", year: 1973, album: "I Got a Name" },
  { id: 5842, rank: 342, title: "Bad Bad Leroy Brown", artist: "Jim Croce", genre: "Folk", year: 1973, album: "Life and Times" },
  { id: 5843, rank: 343, title: "Operator", artist: "Jim Croce", genre: "Folk", year: 1972, album: "You Don't Mess Around with Jim" },
  { id: 5844, rank: 344, title: "I Have to Say I Love You in a Song", artist: "Jim Croce", genre: "Folk", year: 1974, album: "I Got a Name" },
  { id: 5845, rank: 345, title: "You Don't Mess Around with Jim", artist: "Jim Croce", genre: "Folk", year: 1972, album: "You Don't Mess Around with Jim" },
  { id: 5846, rank: 346, title: "Rapid Roy the Stock Car Boy", artist: "Jim Croce", genre: "Folk", year: 1972, album: "You Don't Mess Around with Jim" },
  { id: 5847, rank: 347, title: "Photographs and Memories", artist: "Jim Croce", genre: "Folk", year: 1974, album: "I Got a Name" },
  { id: 5848, rank: 348, title: "Workin' at the Car Wash Blues", artist: "Jim Croce", genre: "Folk", year: 1974, album: "I Got a Name" },
  { id: 5849, rank: 349, title: "Lover's Cross", artist: "Jim Croce", genre: "Folk", year: 1974, album: "I Got a Name" },
  { id: 5850, rank: 350, title: "One Less Set of Footsteps", artist: "Jim Croce", genre: "Folk", year: 1973, album: "Life and Times" },
  { id: 5851, rank: 351, title: "Leader of the Band", artist: "Dan Fogelberg", genre: "Folk", year: 1981, album: "The Innocent Age" },
  { id: 5852, rank: 352, title: "Longer", artist: "Dan Fogelberg", genre: "Folk", year: 1979, album: "Phoenix" },
  { id: 5853, rank: 353, title: "Same Auld Lang Syne", artist: "Dan Fogelberg", genre: "Folk", year: 1981, album: "The Innocent Age" },
  { id: 5854, rank: 354, title: "Run for the Roses", artist: "Dan Fogelberg", genre: "Folk", year: 1981, album: "The Innocent Age" },
  { id: 5855, rank: 355, title: "Part of the Plan", artist: "Dan Fogelberg", genre: "Folk", year: 1975, album: "Captured Angel" },
  { id: 5856, rank: 356, title: "There's a Place in the World for a Gambler", artist: "Dan Fogelberg", genre: "Folk", year: 1975, album: "Captured Angel" },
  { id: 5857, rank: 357, title: "The Power of Gold", artist: "Dan Fogelberg", genre: "Folk", year: 1978, album: "Twin Sons of Different Mothers" },
  { id: 5858, rank: 358, title: "Phoenix", artist: "Dan Fogelberg", genre: "Folk", year: 1979, album: "Phoenix" },
  { id: 5859, rank: 359, title: "Hard to Say", artist: "Dan Fogelberg", genre: "Folk", year: 1981, album: "The Innocent Age" },
  { id: 5860, rank: 360, title: "Make Love Stay", artist: "Dan Fogelberg", genre: "Folk", year: 1982, album: "Windows and Walls" },
  { id: 5861, rank: 361, title: "The Pretender", artist: "Jackson Browne", genre: "Folk", year: 1976, album: "The Pretender" },
  { id: 5862, rank: 362, title: "Running on Empty", artist: "Jackson Browne", genre: "Folk", year: 1977, album: "Running on Empty" },
  { id: 5863, rank: 363, title: "Fountain of Sorrow", artist: "Jackson Browne", genre: "Folk", year: 1974, album: "Late for the Sky" },
  { id: 5864, rank: 364, title: "Late for the Sky", artist: "Jackson Browne", genre: "Folk", year: 1974, album: "Late for the Sky" },
  { id: 5865, rank: 365, title: "Doctor My Eyes", artist: "Jackson Browne", genre: "Folk", year: 1972, album: "Jackson Browne" },
  { id: 5866, rank: 366, title: "Somebody's Baby", artist: "Jackson Browne", genre: "Folk", year: 1982, album: "Fast Times at Ridgemont High" },
  { id: 5867, rank: 367, title: "Tender Is the Night", artist: "Jackson Browne", genre: "Folk", year: 1983, album: "Lawyers in Love" },
  { id: 5868, rank: 368, title: "Take It Easy", artist: "Jackson Browne", genre: "Folk", year: 1972, album: "Jackson Browne" },
  { id: 5869, rank: 369, title: "These Days", artist: "Jackson Browne", genre: "Folk", year: 1973, album: "For Everyman" },
  { id: 5870, rank: 370, title: "Rock Me on the Water", artist: "Jackson Browne", genre: "Folk", year: 1972, album: "Jackson Browne" },
  { id: 5871, rank: 371, title: "Boulder to Birmingham", artist: "Emmylou Harris", genre: "Folk", year: 1975, album: "Pieces of the Sky" },
  { id: 5872, rank: 372, title: "Together Again", artist: "Emmylou Harris", genre: "Folk", year: 1975, album: "Pieces of the Sky" },
  { id: 5873, rank: 373, title: "Sweet Dreams", artist: "Emmylou Harris", genre: "Folk", year: 1976, album: "Elite Hotel" },
  { id: 5874, rank: 374, title: "Making Believe", artist: "Emmylou Harris", genre: "Folk", year: 1976, album: "Elite Hotel" },
  { id: 5875, rank: 375, title: "Roses in the Snow", artist: "Emmylou Harris", genre: "Folk", year: 1980, album: "Roses in the Snow" },
  { id: 5876, rank: 376, title: "Luxury Liner", artist: "Emmylou Harris", genre: "Folk", year: 1977, album: "Luxury Liner" },
  { id: 5877, rank: 377, title: "Two More Bottles of Wine", artist: "Emmylou Harris", genre: "Folk", year: 1978, album: "Quarter Moon in a Ten Cent Town" },
  { id: 5878, rank: 378, title: "From Boulder to Birmingham", artist: "Emmylou Harris", genre: "Folk", year: 1975, album: "Pieces of the Sky" },
  { id: 5879, rank: 379, title: "Grievous Angel", artist: "Emmylou Harris", genre: "Folk", year: 1974, album: "Grievous Angel" },
  { id: 5880, rank: 380, title: "Wheels", artist: "Emmylou Harris", genre: "Folk", year: 1980, album: "Roses in the Snow" },
  { id: 5881, rank: 381, title: "Copperhead Road", artist: "Steve Earle", genre: "Folk", year: 1988, album: "Copperhead Road" },
  { id: 5882, rank: 382, title: "Guitar Town", artist: "Steve Earle", genre: "Folk", year: 1986, album: "Guitar Town" },
  { id: 5883, rank: 383, title: "Galway Girl", artist: "Steve Earle", genre: "Folk", year: 2000, album: "Transcendental Blues" },
  { id: 5884, rank: 384, title: "The Revolution Starts Now", artist: "Steve Earle", genre: "Folk", year: 2004, album: "The Revolution Starts Now" },
  { id: 5885, rank: 385, title: "I'm Alright", artist: "Steve Earle", genre: "Folk", year: 1999, album: "The Mountain" },
  { id: 5886, rank: 386, title: "Goodbye", artist: "Steve Earle", genre: "Folk", year: 1987, album: "Exit 0" },
  { id: 5887, rank: 387, title: "Six Days on the Road", artist: "Steve Earle", genre: "Folk", year: 1987, album: "Exit 0" },
  { id: 5888, rank: 388, title: "Tom Ames' Prayer", artist: "Steve Earle", genre: "Folk", year: 1993, album: "The Hard Way" },
  { id: 5889, rank: 389, title: "Over Yonder", artist: "Steve Earle", genre: "Folk", year: 2002, album: "Jerusalem" },
  { id: 5890, rank: 390, title: "Jerusalem", artist: "Steve Earle", genre: "Folk", year: 2002, album: "Jerusalem" },
  { id: 5891, rank: 391, title: "Car Wheels on a Gravel Road", artist: "Lucinda Williams", genre: "Folk", year: 1998, album: "Car Wheels on a Gravel Road" },
  { id: 5892, rank: 392, title: "Passionate Kisses", artist: "Lucinda Williams", genre: "Folk", year: 1988, album: "Lucinda Williams" },
  { id: 5893, rank: 393, title: "Crescent City", artist: "Lucinda Williams", genre: "Folk", year: 1988, album: "Lucinda Williams" },
  { id: 5894, rank: 394, title: "Side of the Road", artist: "Lucinda Williams", genre: "Folk", year: 1988, album: "Lucinda Williams" },
  { id: 5895, rank: 395, title: "Drunken Angel", artist: "Lucinda Williams", genre: "Folk", year: 1998, album: "Car Wheels on a Gravel Road" },
  { id: 5896, rank: 396, title: "Right in Time", artist: "Lucinda Williams", genre: "Folk", year: 1998, album: "Car Wheels on a Gravel Road" },
  { id: 5897, rank: 397, title: "2 Kool 2 Be 4-Gotten", artist: "Lucinda Williams", genre: "Folk", year: 1998, album: "Car Wheels on a Gravel Road" },
  { id: 5898, rank: 398, title: "Still I Long for Your Kiss", artist: "Lucinda Williams", genre: "Folk", year: 2003, album: "World Without Tears" },
  { id: 5899, rank: 399, title: "Changed the Locks", artist: "Lucinda Williams", genre: "Folk", year: 1988, album: "Lucinda Williams" },
  { id: 5900, rank: 400, title: "Those Three Days", artist: "Lucinda Williams", genre: "Folk", year: 2003, album: "World Without Tears" },
  { id: 5901, rank: 401, title: "Everything Is Free", artist: "Gillian Welch", genre: "Folk", year: 2001, album: "Time (The Revelator)" },
  { id: 5902, rank: 402, title: "Revelator", artist: "Gillian Welch", genre: "Folk", year: 2001, album: "Time (The Revelator)" },
  { id: 5903, rank: 403, title: "April the 14th Part I", artist: "Gillian Welch", genre: "Folk", year: 2001, album: "Time (The Revelator)" },
  { id: 5904, rank: 404, title: "I Want to Sing That Rock and Roll", artist: "Gillian Welch", genre: "Folk", year: 1996, album: "Revival" },
  { id: 5905, rank: 405, title: "Annabelle", artist: "Gillian Welch", genre: "Folk", year: 1996, album: "Revival" },
  { id: 5906, rank: 406, title: "Orphan Girl", artist: "Gillian Welch", genre: "Folk", year: 1996, album: "Revival" },
  { id: 5907, rank: 407, title: "One More Dollar", artist: "Gillian Welch", genre: "Folk", year: 1998, album: "Hell Among the Yearlings" },
  { id: 5908, rank: 408, title: "By the Mark", artist: "Gillian Welch", genre: "Folk", year: 2001, album: "Time (The Revelator)" },
  { id: 5909, rank: 409, title: "The Way It Will Be", artist: "Gillian Welch", genre: "Folk", year: 1998, album: "Hell Among the Yearlings" },
  { id: 5910, rank: 410, title: "Rock of Ages", artist: "Gillian Welch", genre: "Folk", year: 1998, album: "Hell Among the Yearlings" },
  { id: 5911, rank: 411, title: "Naked as We Came", artist: "Iron & Wine", genre: "Folk", year: 2004, album: "Our Endless Numbered Days" },
  { id: 5912, rank: 412, title: "Flightless Bird American Mouth", artist: "Iron & Wine", genre: "Folk", year: 2004, album: "Our Endless Numbered Days" },
  { id: 5913, rank: 413, title: "Naked as We Came (Live)", artist: "Iron & Wine", genre: "Folk", year: 2005, album: "Woman King" },
  { id: 5914, rank: 414, title: "Trapeze Swinger", artist: "Iron & Wine", genre: "Folk", year: 2005, album: "Woman King" },
  { id: 5915, rank: 415, title: "Passing Afternoon", artist: "Iron & Wine", genre: "Folk", year: 2004, album: "Our Endless Numbered Days" },
  { id: 5916, rank: 416, title: "The Trapeze Swinger", artist: "Iron & Wine", genre: "Folk", year: 2005, album: "Woman King" },
  { id: 5917, rank: 417, title: "Jesus the Mexican Boy", artist: "Iron & Wine", genre: "Folk", year: 2002, album: "The Creek Drank the Cradle" },
  { id: 5918, rank: 418, title: "Upward Over the Mountain", artist: "Iron & Wine", genre: "Folk", year: 2002, album: "The Creek Drank the Cradle" },
  { id: 5919, rank: 419, title: "Lion's Mane", artist: "Iron & Wine", genre: "Folk", year: 2002, album: "The Creek Drank the Cradle" },
  { id: 5920, rank: 420, title: "Sodom South Georgia", artist: "Iron & Wine", genre: "Folk", year: 2004, album: "Our Endless Numbered Days" },
  { id: 5921, rank: 421, title: "White Winter Hymnal", artist: "Fleet Foxes", genre: "Folk", year: 2008, album: "Fleet Foxes" },
  { id: 5922, rank: 422, title: "Mykonos", artist: "Fleet Foxes", genre: "Folk", year: 2008, album: "Sun Giant" },
  { id: 5923, rank: 423, title: "Ragged Wood", artist: "Fleet Foxes", genre: "Folk", year: 2008, album: "Fleet Foxes" },
  { id: 5924, rank: 424, title: "Your Protector", artist: "Fleet Foxes", genre: "Folk", year: 2008, album: "Fleet Foxes" },
  { id: 5925, rank: 425, title: "Oliver James", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5926, rank: 426, title: "Helplessness Blues", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5927, rank: 427, title: "Bedouin Dress", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5928, rank: 428, title: "Grown Ocean", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5929, rank: 429, title: "Montezuma", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5930, rank: 430, title: "Blue Spotted Tail", artist: "Fleet Foxes", genre: "Folk", year: 2011, album: "Helplessness Blues" },
  { id: 5931, rank: 431, title: "Chicago", artist: "Sufjan Stevens", genre: "Folk", year: 2005, album: "Illinois" },
  { id: 5932, rank: 432, title: "Come On! Feel the Illinoise!", artist: "Sufjan Stevens", genre: "Folk", year: 2005, album: "Illinois" },
  { id: 5933, rank: 433, title: "John Wayne Gacy Jr.", artist: "Sufjan Stevens", genre: "Folk", year: 2005, album: "Illinois" },
  { id: 5934, rank: 434, title: "Casimir Pulaski Day", artist: "Sufjan Stevens", genre: "Folk", year: 2005, album: "Illinois" },
  { id: 5935, rank: 435, title: "Seven Swans", artist: "Sufjan Stevens", genre: "Folk", year: 2004, album: "Seven Swans" },
  { id: 5936, rank: 436, title: "The Dress Looks Nice on You", artist: "Sufjan Stevens", genre: "Folk", year: 2004, album: "Seven Swans" },
  { id: 5937, rank: 437, title: "Death with Dignity", artist: "Sufjan Stevens", genre: "Folk", year: 2015, album: "Carrie & Lowell" },
  { id: 5938, rank: 438, title: "Fourth of July", artist: "Sufjan Stevens", genre: "Folk", year: 2015, album: "Carrie & Lowell" },
  { id: 5939, rank: 439, title: "Should Have Known Better", artist: "Sufjan Stevens", genre: "Folk", year: 2015, album: "Carrie & Lowell" },
  { id: 5940, rank: 440, title: "No Shade in the Shadow of the Cross", artist: "Sufjan Stevens", genre: "Folk", year: 2015, album: "Carrie & Lowell" },
  { id: 5941, rank: 441, title: "Skinny Love", artist: "Bon Iver", genre: "Folk", year: 2008, album: "For Emma Forever Ago" },
  { id: 5942, rank: 442, title: "Flume", artist: "Bon Iver", genre: "Folk", year: 2008, album: "For Emma Forever Ago" },
  { id: 5943, rank: 443, title: "Re: Stacks", artist: "Bon Iver", genre: "Folk", year: 2008, album: "For Emma Forever Ago" },
  { id: 5944, rank: 444, title: "For Emma", artist: "Bon Iver", genre: "Folk", year: 2008, album: "For Emma Forever Ago" },
  { id: 5945, rank: 445, title: "Towers", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5946, rank: 446, title: "Calgary", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5947, rank: 447, title: "Holocene", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5948, rank: 448, title: "Michicant", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5949, rank: 449, title: "Beth/Rest", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5950, rank: 450, title: "Minnesota WI", artist: "Bon Iver", genre: "Folk", year: 2011, album: "Bon Iver, Bon Iver" },
  { id: 5951, rank: 451, title: "Rambling Man", artist: "Laura Marling", genre: "Folk", year: 2010, album: "I Speak Because I Can" },
  { id: 5952, rank: 452, title: "Devil's Spoke", artist: "Laura Marling", genre: "Folk", year: 2008, album: "Alas I Cannot Swim" },
  { id: 5953, rank: 453, title: "My Manic and I", artist: "Laura Marling", genre: "Folk", year: 2008, album: "Alas I Cannot Swim" },
  { id: 5954, rank: 454, title: "Night Terror", artist: "Laura Marling", genre: "Folk", year: 2010, album: "I Speak Because I Can" },
  { id: 5955, rank: 455, title: "The Beast", artist: "Laura Marling", genre: "Folk", year: 2010, album: "I Speak Because I Can" },
  { id: 5956, rank: 456, title: "Sophia", artist: "Laura Marling", genre: "Folk", year: 2013, album: "Once I Was an Eagle" },
  { id: 5957, rank: 457, title: "Master Hunter", artist: "Laura Marling", genre: "Folk", year: 2013, album: "Once I Was an Eagle" },
  { id: 5958, rank: 458, title: "I Was an Eagle", artist: "Laura Marling", genre: "Folk", year: 2013, album: "Once I Was an Eagle" },
  { id: 5959, rank: 459, title: "Once", artist: "Laura Marling", genre: "Folk", year: 2013, album: "Once I Was an Eagle" },
  { id: 5960, rank: 460, title: "Short Movie", artist: "Laura Marling", genre: "Folk", year: 2015, album: "Short Movie" },
  { id: 5961, rank: 461, title: "Whiskey in the Jar", artist: "Fairport Convention", genre: "Folk", year: 1970, album: "Full House" },
  { id: 5962, rank: 462, title: "Dirty Linen", artist: "Fairport Convention", genre: "Folk", year: 1971, album: "Angel Delight" },
  { id: 5963, rank: 463, title: "Red and Gold", artist: "Fairport Convention", genre: "Folk", year: 1988, album: "In Real Time" },
  { id: 5964, rank: 464, title: "Jewel in the Crown", artist: "Fairport Convention", genre: "Folk", year: 1995, album: "Jewel in the Crown" },
  { id: 5965, rank: 465, title: "Sol y Sombra", artist: "Fairport Convention", genre: "Folk", year: 2011, album: "Sense of Occasion" },
  { id: 5966, rank: 466, title: "Walk Awhile", artist: "Fairport Convention", genre: "Folk", year: 1970, album: "Full House" },
  { id: 5967, rank: 467, title: "Flowers of the Forest", artist: "Fairport Convention", genre: "Folk", year: 1970, album: "Full House" },
  { id: 5968, rank: 468, title: "The Hiring Fair", artist: "Fairport Convention", genre: "Folk", year: 1971, album: "Angel Delight" },
  { id: 5969, rank: 469, title: "Banks of the Nile", artist: "Fairport Convention", genre: "Folk", year: 1971, album: "Angel Delight" },
  { id: 5970, rank: 470, title: "Cropredy", artist: "Fairport Convention", genre: "Folk", year: 1979, album: "Tipplers Tales" },
  { id: 5971, rank: 471, title: "Lord of the Dance", artist: "Pete Seeger", genre: "Folk", year: 1963, album: "We Shall Overcome" },
  { id: 5972, rank: 472, title: "Little Boxes", artist: "Pete Seeger", genre: "Folk", year: 1963, album: "We Shall Overcome" },
  { id: 5973, rank: 473, title: "Old Devil Time", artist: "Pete Seeger", genre: "Folk", year: 1969, album: "Pete Seeger's Greatest Hits" },
  { id: 5974, rank: 474, title: "Rainbow Race", artist: "Pete Seeger", genre: "Folk", year: 1971, album: "Rainbow Race" },
  { id: 5975, rank: 475, title: "Living in the Country", artist: "Pete Seeger", genre: "Folk", year: 1973, album: "Banks of Marble" },
  { id: 5976, rank: 476, title: "If I Had a Hammer (Live)", artist: "Pete Seeger", genre: "Folk", year: 1963, album: "We Shall Overcome" },
  { id: 5977, rank: 477, title: "Garbage", artist: "Pete Seeger", genre: "Folk", year: 1963, album: "Pete Seeger's Greatest Hits" },
  { id: 5978, rank: 478, title: "Young vs Old", artist: "Pete Seeger", genre: "Folk", year: 1969, album: "Young vs Old" },
  { id: 5979, rank: 479, title: "This Ole World", artist: "Woody Guthrie", genre: "Folk", year: 1946, album: "Woody Guthrie Library of Congress" },
  { id: 5980, rank: 480, title: "Talking Dust Bowl Blues", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5981, rank: 481, title: "I Ain't Got No Home", artist: "Woody Guthrie", genre: "Folk", year: 1938, album: "Dust Bowl Ballads" },
  { id: 5982, rank: 482, title: "Vigilante Man", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5983, rank: 483, title: "The Grand Coulee Dam", artist: "Woody Guthrie", genre: "Folk", year: 1941, album: "Columbia River Songs" },
  { id: 5984, rank: 484, title: "New York Town", artist: "Woody Guthrie", genre: "Folk", year: 1940, album: "Dust Bowl Ballads" },
  { id: 5985, rank: 485, title: "East Texas Red", artist: "Woody Guthrie", genre: "Folk", year: 1944, album: "Songs to Grow On" },
  { id: 5986, rank: 486, title: "Ludlow Massacre", artist: "Woody Guthrie", genre: "Folk", year: 1944, album: "Songs to Grow On" },
  { id: 5987, rank: 487, title: "Jesus Christ", artist: "Woody Guthrie", genre: "Folk", year: 1944, album: "Songs to Grow On" },
  { id: 5988, rank: 488, title: "Reuben James", artist: "Woody Guthrie", genre: "Folk", year: 1942, album: "Songs to Grow On" },
  { id: 5989, rank: 489, title: "Roll On Columbia", artist: "Woody Guthrie", genre: "Folk", year: 1941, album: "Columbia River Songs" },
  { id: 5990, rank: 490, title: "People Are Crazy", artist: "Harry Chapin", genre: "Folk", year: 1975, album: "Portrait Gallery" },
  { id: 5991, rank: 491, title: "Dream Goes On Forever", artist: "Harry Chapin", genre: "Folk", year: 1974, album: "Short Stories" },
  { id: 5992, rank: 492, title: "WOLD", artist: "Harry Chapin", genre: "Folk", year: 1973, album: "Short Stories" },
  { id: 5993, rank: 493, title: "Better Place to Be", artist: "Harry Chapin", genre: "Folk", year: 1972, album: "Heads & Tales" },
  { id: 5994, rank: 494, title: "Corey's Coming", artist: "Harry Chapin", genre: "Folk", year: 1974, album: "Verities & Balderdash" },
  { id: 5995, rank: 495, title: "There Only Was One Choice", artist: "Harry Chapin", genre: "Folk", year: 1975, album: "Portrait Gallery" },
  { id: 5996, rank: 496, title: "What Made America Famous", artist: "Harry Chapin", genre: "Folk", year: 1974, album: "Verities & Balderdash" },
  { id: 5997, rank: 497, title: "Sandy", artist: "Harry Chapin", genre: "Folk", year: 1976, album: "Greatest Stories Live" },
  { id: 5998, rank: 498, title: "I Wanna Learn a Love Song", artist: "Harry Chapin", genre: "Folk", year: 1975, album: "Portrait Gallery" },
  { id: 5999, rank: 499, title: "She Sings Songs Without Words", artist: "Harry Chapin", genre: "Folk", year: 1975, album: "Portrait Gallery" },
  { id: 6000, rank: 500, title: "Operator (Live)", artist: "Jim Croce", genre: "Folk", year: 1973, album: "Photographs & Memories" }
];