const SONGS_METAL = [
  { id: 1501, rank: 1, title: "Master of Puppets", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1502, rank: 2, title: "Iron Man", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1503, rank: 3, title: "Paranoid", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1504, rank: 4, title: "The Trooper", artist: "Iron Maiden", genre: "Metal", year: 1983, album: "Piece of Mind" },
  { id: 1505, rank: 5, title: "Raining Blood", artist: "Slayer", genre: "Metal", year: 1986, album: "Reign in Blood" },
  { id: 1506, rank: 6, title: "Holy Wars... The Punishment Due", artist: "Megadeth", genre: "Metal", year: 1990, album: "Rust in Peace" },
  { id: 1507, rank: 7, title: "Cowboys from Hell", artist: "Pantera", genre: "Metal", year: 1990, album: "Cowboys from Hell" },
  { id: 1508, rank: 8, title: "One", artist: "Metallica", genre: "Metal", year: 1988, album: "...And Justice for All" },
  { id: 1509, rank: 9, title: "Hallowed Be Thy Name", artist: "Iron Maiden", genre: "Metal", year: 1982, album: "The Number of the Beast" },
  { id: 1510, rank: 10, title: "Breaking the Law", artist: "Judas Priest", genre: "Metal", year: 1980, album: "British Steel" },
  { id: 1511, rank: 11, title: "Ace of Spades", artist: "Motörhead", genre: "Metal", year: 1980, album: "Ace of Spades" },
  { id: 1512, rank: 12, title: "War Pigs", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1513, rank: 13, title: "Fade to Black", artist: "Metallica", genre: "Metal", year: 1984, album: "Ride the Lightning" },
  { id: 1514, rank: 14, title: "Number of the Beast", artist: "Iron Maiden", genre: "Metal", year: 1982, album: "The Number of the Beast" },
  { id: 1515, rank: 15, title: "Painkiller", artist: "Judas Priest", genre: "Metal", year: 1990, album: "Painkiller" },
  { id: 1516, rank: 16, title: "Black Sabbath", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Black Sabbath" },
  { id: 1517, rank: 17, title: "Run to the Hills", artist: "Iron Maiden", genre: "Metal", year: 1982, album: "The Number of the Beast" },
  { id: 1518, rank: 18, title: "Killing in the Name", artist: "Rage Against the Machine", genre: "Metal", year: 1992, album: "Rage Against the Machine" },
  { id: 1519, rank: 19, title: "Battery", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1520, rank: 20, title: "Angel of Death", artist: "Slayer", genre: "Metal", year: 1986, album: "Reign in Blood" },
  { id: 1521, rank: 21, title: "Creeping Death", artist: "Metallica", genre: "Metal", year: 1984, album: "Ride the Lightning" },
  { id: 1522, rank: 22, title: "Walk", artist: "Pantera", genre: "Metal", year: 1992, album: "Vulgar Display of Power" },
  { id: 1523, rank: 23, title: "Crazy Train", artist: "Ozzy Osbourne", genre: "Metal", year: 1980, album: "Blizzard of Ozz" },
  { id: 1524, rank: 24, title: "Schism", artist: "Tool", genre: "Metal", year: 2001, album: "Lateralus" },
  { id: 1525, rank: 25, title: "Spit It Out", artist: "Slipknot", genre: "Metal", year: 1999, album: "Slipknot" },
  { id: 1526, rank: 26, title: "Toxicity", artist: "System of a Down", genre: "Metal", year: 2001, album: "Toxicity" },
  { id: 1527, rank: 27, title: "Chop Suey!", artist: "System of a Down", genre: "Metal", year: 2001, album: "Toxicity" },
  { id: 1528, rank: 28, title: "Freak on a Leash", artist: "Korn", genre: "Metal", year: 1998, album: "Follow the Leader" },
  { id: 1529, rank: 29, title: "Down with the Sickness", artist: "Disturbed", genre: "Metal", year: 2000, album: "The Sickness" },
  { id: 1530, rank: 30, title: "In the End", artist: "Linkin Park", genre: "Metal", year: 2000, album: "Hybrid Theory" },
  { id: 1531, rank: 31, title: "Seek and Destroy", artist: "Metallica", genre: "Metal", year: 1983, album: "Kill 'Em All" },
  { id: 1532, rank: 32, title: "Peace Sells", artist: "Megadeth", genre: "Metal", year: 1986, album: "Peace Sells... but Who's Buying?" },
  { id: 1533, rank: 33, title: "Symphony of Destruction", artist: "Megadeth", genre: "Metal", year: 1992, album: "Countdown to Extinction" },
  { id: 1534, rank: 34, title: "The Unforgiven", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1535, rank: 35, title: "Enter Sandman", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1536, rank: 36, title: "Hangar 18", artist: "Megadeth", genre: "Metal", year: 1990, album: "Rust in Peace" },
  { id: 1537, rank: 37, title: "Mouth for War", artist: "Pantera", genre: "Metal", year: 1992, album: "Vulgar Display of Power" },
  { id: 1538, rank: 38, title: "Pantera Hell", artist: "Pantera", genre: "Metal", year: 1990, album: "Cowboys from Hell" },
  { id: 1539, rank: 39, title: "Wherever I May Roam", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1540, rank: 40, title: "Duality", artist: "Slipknot", genre: "Metal", year: 2004, album: "Vol. 3: The Subliminal Verses" },
  { id: 1541, rank: 41, title: "Before I Forget", artist: "Slipknot", genre: "Metal", year: 2004, album: "Vol. 3: The Subliminal Verses" },
  { id: 1542, rank: 42, title: "Wait and Bleed", artist: "Slipknot", genre: "Metal", year: 1999, album: "Slipknot" },
  { id: 1543, rank: 43, title: "Psychosocial", artist: "Slipknot", genre: "Metal", year: 2008, album: "All Hope Is Gone" },
  { id: 1544, rank: 44, title: "People = Shit", artist: "Slipknot", genre: "Metal", year: 2001, album: "Iowa" },
  { id: 1545, rank: 45, title: "Numb", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1546, rank: 46, title: "Crawling", artist: "Linkin Park", genre: "Metal", year: 2000, album: "Hybrid Theory" },
  { id: 1547, rank: 47, title: "Faint", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1548, rank: 48, title: "Blind", artist: "Korn", genre: "Metal", year: 1994, album: "Korn" },
  { id: 1549, rank: 49, title: "Got the Life", artist: "Korn", genre: "Metal", year: 1998, album: "Follow the Leader" },
  { id: 1550, rank: 50, title: "B.Y.O.B.", artist: "System of a Down", genre: "Metal", year: 2005, album: "Mezmerize" },
  { id: 1551, rank: 51, title: "Aerials", artist: "System of a Down", genre: "Metal", year: 2001, album: "Toxicity" },
  { id: 1552, rank: 52, title: "Clown", artist: "Slipknot", genre: "Metal", year: 1999, album: "Slipknot" },
  { id: 1553, rank: 53, title: "Roots Bloody Roots", artist: "Sepultura", genre: "Metal", year: 1996, album: "Roots" },
  { id: 1554, rank: 54, title: "Chaos A.D.", artist: "Sepultura", genre: "Metal", year: 1993, album: "Chaos A.D." },
  { id: 1555, rank: 55, title: "Refuse/Resist", artist: "Sepultura", genre: "Metal", year: 1993, album: "Chaos A.D." },
  { id: 1556, rank: 56, title: "Schizophrenia", artist: "Sepultura", genre: "Metal", year: 1987, album: "Schizophrenia" },
  { id: 1557, rank: 57, title: "Electric Eye", artist: "Judas Priest", genre: "Metal", year: 1982, album: "Screaming for Vengeance" },
  { id: 1558, rank: 58, title: "You've Got Another Thing Comin'", artist: "Judas Priest", genre: "Metal", year: 1982, album: "Screaming for Vengeance" },
  { id: 1559, rank: 59, title: "Heading Out to the Highway", artist: "Judas Priest", genre: "Metal", year: 1981, album: "Point of Entry" },
  { id: 1560, rank: 60, title: "Victim of Changes", artist: "Judas Priest", genre: "Metal", year: 1976, album: "Sad Wings of Destiny" },
  { id: 1561, rank: 61, title: "The Hellion / Electric Eye", artist: "Judas Priest", genre: "Metal", year: 1982, album: "Screaming for Vengeance" },
  { id: 1562, rank: 62, title: "Aces High", artist: "Iron Maiden", genre: "Metal", year: 1984, album: "Powerslave" },
  { id: 1563, rank: 63, title: "2 Minutes to Midnight", artist: "Iron Maiden", genre: "Metal", year: 1984, album: "Powerslave" },
  { id: 1564, rank: 64, title: "Fear of the Dark", artist: "Iron Maiden", genre: "Metal", year: 1992, album: "Fear of the Dark" },
  { id: 1565, rank: 65, title: "Wasted Years", artist: "Iron Maiden", genre: "Metal", year: 1986, album: "Somewhere in Time" },
  { id: 1566, rank: 66, title: "Powerslave", artist: "Iron Maiden", genre: "Metal", year: 1984, album: "Powerslave" },
  { id: 1567, rank: 67, title: "Phantom of the Opera", artist: "Iron Maiden", genre: "Metal", year: 1980, album: "Iron Maiden" },
  { id: 1568, rank: 68, title: "Moonchild", artist: "Iron Maiden", genre: "Metal", year: 1988, album: "Seventh Son of a Seventh Son" },
  { id: 1569, rank: 69, title: "Children of the Damned", artist: "Iron Maiden", genre: "Metal", year: 1982, album: "The Number of the Beast" },
  { id: 1570, rank: 70, title: "Caught Somewhere in Time", artist: "Iron Maiden", genre: "Metal", year: 1986, album: "Somewhere in Time" },
  { id: 1571, rank: 71, title: "Heaven and Hell", artist: "Black Sabbath", genre: "Metal", year: 1980, album: "Heaven and Hell" },
  { id: 1572, rank: 72, title: "Mob Rules", artist: "Black Sabbath", genre: "Metal", year: 1981, album: "Mob Rules" },
  { id: 1573, rank: 73, title: "Die Young", artist: "Black Sabbath", genre: "Metal", year: 1980, album: "Heaven and Hell" },
  { id: 1574, rank: 74, title: "Children of the Grave", artist: "Black Sabbath", genre: "Metal", year: 1971, album: "Master of Reality" },
  { id: 1575, rank: 75, title: "Symptom of the Universe", artist: "Black Sabbath", genre: "Metal", year: 1975, album: "Sabotage" },
  { id: 1576, rank: 76, title: "Sabbath Bloody Sabbath", artist: "Black Sabbath", genre: "Metal", year: 1973, album: "Sabbath Bloody Sabbath" },
  { id: 1577, rank: 77, title: "N.I.B.", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Black Sabbath" },
  { id: 1578, rank: 78, title: "Into the Void", artist: "Black Sabbath", genre: "Metal", year: 1971, album: "Master of Reality" },
  { id: 1579, rank: 79, title: "Mr. Crowley", artist: "Ozzy Osbourne", genre: "Metal", year: 1980, album: "Blizzard of Ozz" },
  { id: 1580, rank: 80, title: "Bark at the Moon", artist: "Ozzy Osbourne", genre: "Metal", year: 1983, album: "Bark at the Moon" },
  { id: 1581, rank: 81, title: "I Don't Know", artist: "Ozzy Osbourne", genre: "Metal", year: 1980, album: "Blizzard of Ozz" },
  { id: 1582, rank: 82, title: "Goodbye to Romance", artist: "Ozzy Osbourne", genre: "Metal", year: 1980, album: "Blizzard of Ozz" },
  { id: 1583, rank: 83, title: "Shot in the Dark", artist: "Ozzy Osbourne", genre: "Metal", year: 1986, album: "The Ultimate Sin" },
  { id: 1584, rank: 84, title: "Mama, I'm Coming Home", artist: "Ozzy Osbourne", genre: "Metal", year: 1991, album: "No More Tears" },
  { id: 1585, rank: 85, title: "No More Tears", artist: "Ozzy Osbourne", genre: "Metal", year: 1991, album: "No More Tears" },
  { id: 1586, rank: 86, title: "Rainbow in the Dark", artist: "Dio", genre: "Metal", year: 1983, album: "Holy Diver" },
  { id: 1587, rank: 87, title: "Holy Diver", artist: "Dio", genre: "Metal", year: 1983, album: "Holy Diver" },
  { id: 1588, rank: 88, title: "The Last in Line", artist: "Dio", genre: "Metal", year: 1984, album: "The Last in Line" },
  { id: 1589, rank: 89, title: "We Rock", artist: "Dio", genre: "Metal", year: 1984, album: "The Last in Line" },
  { id: 1590, rank: 90, title: "Rock 'n' Roll Children", artist: "Dio", genre: "Metal", year: 1985, album: "Sacred Heart" },
  { id: 1591, rank: 91, title: "Neon Knights", artist: "Black Sabbath", genre: "Metal", year: 1980, album: "Heaven and Hell" },
  { id: 1592, rank: 92, title: "Man on the Silver Mountain", artist: "Rainbow", genre: "Metal", year: 1975, album: "Ritchie Blackmore's Rainbow" },
  { id: 1593, rank: 93, title: "Kill the King", artist: "Rainbow", genre: "Metal", year: 1978, album: "Long Live Rock 'n' Roll" },
  { id: 1594, rank: 94, title: "Stargazer", artist: "Rainbow", genre: "Metal", year: 1976, album: "Rising" },
  { id: 1595, rank: 95, title: "Since You Been Gone", artist: "Rainbow", genre: "Metal", year: 1979, album: "Down to Earth" },
  { id: 1596, rank: 96, title: "Detroit Rock City", artist: "KISS", genre: "Metal", year: 1976, album: "Destroyer" },
  { id: 1597, rank: 97, title: "Rock and Roll All Nite", artist: "KISS", genre: "Metal", year: 1975, album: "Dressed to Kill" },
  { id: 1598, rank: 98, title: "Shout It Out Loud", artist: "KISS", genre: "Metal", year: 1976, album: "Destroyer" },
  { id: 1599, rank: 99, title: "I Was Made for Lovin' You", artist: "KISS", genre: "Metal", year: 1979, album: "Dynasty" },
  { id: 1600, rank: 100, title: "God of Thunder", artist: "KISS", genre: "Metal", year: 1976, album: "Destroyer" },
  { id: 1601, rank: 101, title: "Round and Round", artist: "Ratt", genre: "Metal", year: 1984, album: "Out of the Cellar" },
  { id: 1602, rank: 102, title: "Jump", artist: "Van Halen", genre: "Metal", year: 1984, album: "1984" },
  { id: 1603, rank: 103, title: "Eruption", artist: "Van Halen", genre: "Metal", year: 1978, album: "Van Halen" },
  { id: 1604, rank: 104, title: "Panama", artist: "Van Halen", genre: "Metal", year: 1984, album: "1984" },
  { id: 1605, rank: 105, title: "Runnin' with the Devil", artist: "Van Halen", genre: "Metal", year: 1978, album: "Van Halen" },
  { id: 1606, rank: 106, title: "Nothin' but a Good Time", artist: "Poison", genre: "Metal", year: 1988, album: "Open Up and Say...Ahh!" },
  { id: 1607, rank: 107, title: "Every Rose Has Its Thorn", artist: "Poison", genre: "Metal", year: 1988, album: "Open Up and Say...Ahh!" },
  { id: 1608, rank: 108, title: "Talk Dirty to Me", artist: "Poison", genre: "Metal", year: 1986, album: "Look What the Cat Dragged In" },
  { id: 1609, rank: 109, title: "Girls, Girls, Girls", artist: "Mötley Crüe", genre: "Metal", year: 1987, album: "Girls, Girls, Girls" },
  { id: 1610, rank: 110, title: "Dr. Feelgood", artist: "Mötley Crüe", genre: "Metal", year: 1989, album: "Dr. Feelgood" },
  { id: 1611, rank: 111, title: "Shout at the Devil", artist: "Mötley Crüe", genre: "Metal", year: 1983, album: "Shout at the Devil" },
  { id: 1612, rank: 112, title: "Home Sweet Home", artist: "Mötley Crüe", genre: "Metal", year: 1985, album: "Theatre of Pain" },
  { id: 1613, rank: 113, title: "Kickstart My Heart", artist: "Mötley Crüe", genre: "Metal", year: 1989, album: "Dr. Feelgood" },
  { id: 1614, rank: 114, title: "Welcome to the Jungle", artist: "Guns N' Roses", genre: "Metal", year: 1987, album: "Appetite for Destruction" },
  { id: 1615, rank: 115, title: "Paradise City", artist: "Guns N' Roses", genre: "Metal", year: 1987, album: "Appetite for Destruction" },
  { id: 1616, rank: 116, title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "Metal", year: 1987, album: "Appetite for Destruction" },
  { id: 1617, rank: 117, title: "November Rain", artist: "Guns N' Roses", genre: "Metal", year: 1991, album: "Use Your Illusion I" },
  { id: 1618, rank: 118, title: "Night Train", artist: "Guns N' Roses", genre: "Metal", year: 1987, album: "Appetite for Destruction" },
  { id: 1619, rank: 119, title: "Civil War", artist: "Guns N' Roses", genre: "Metal", year: 1990, album: "Use Your Illusion II" },
  { id: 1620, rank: 120, title: "You Could Be Mine", artist: "Guns N' Roses", genre: "Metal", year: 1991, album: "Use Your Illusion II" },
  { id: 1621, rank: 121, title: "Prick", artist: "Current 93", genre: "Metal", year: 1984, album: "Nature Unveiled" },
  { id: 1622, rank: 122, title: "Territorial Pissings", artist: "Nirvana", genre: "Metal", year: 1991, album: "Nevermind" },
  { id: 1623, rank: 123, title: "Spoonman", artist: "Soundgarden", genre: "Metal", year: 1994, album: "Superunknown" },
  { id: 1624, rank: 124, title: "Black Hole Sun", artist: "Soundgarden", genre: "Metal", year: 1994, album: "Superunknown" },
  { id: 1625, rank: 125, title: "Rusty Cage", artist: "Soundgarden", genre: "Metal", year: 1991, album: "Badmotorfinger" },
  { id: 1626, rank: 126, title: "Outshined", artist: "Soundgarden", genre: "Metal", year: 1991, album: "Badmotorfinger" },
  { id: 1627, rank: 127, title: "Burden in My Hand", artist: "Soundgarden", genre: "Metal", year: 1996, album: "Down on the Upside" },
  { id: 1628, rank: 128, title: "Jesus Christ Pose", artist: "Soundgarden", genre: "Metal", year: 1991, album: "Badmotorfinger" },
  { id: 1629, rank: 129, title: "Rooster", artist: "Alice in Chains", genre: "Metal", year: 1992, album: "Dirt" },
  { id: 1630, rank: 130, title: "Would?", artist: "Alice in Chains", genre: "Metal", year: 1992, album: "Dirt" },
  { id: 1631, rank: 131, title: "Them Bones", artist: "Alice in Chains", genre: "Metal", year: 1992, album: "Dirt" },
  { id: 1632, rank: 132, title: "Down in a Hole", artist: "Alice in Chains", genre: "Metal", year: 1992, album: "Dirt" },
  { id: 1633, rank: 133, title: "Angry Chair", artist: "Alice in Chains", genre: "Metal", year: 1992, album: "Dirt" },
  { id: 1634, rank: 134, title: "Again", artist: "Alice in Chains", genre: "Metal", year: 1995, album: "Alice in Chains" },
  { id: 1635, rank: 135, title: "Sludge Factory", artist: "Alice in Chains", genre: "Metal", year: 1995, album: "Alice in Chains" },
  { id: 1636, rank: 136, title: "Sober", artist: "Tool", genre: "Metal", year: 1993, album: "Undertow" },
  { id: 1637, rank: 137, title: "Prison Sex", artist: "Tool", genre: "Metal", year: 1993, album: "Undertow" },
  { id: 1638, rank: 138, title: "Forty Six & 2", artist: "Tool", genre: "Metal", year: 1996, album: "Aenima" },
  { id: 1639, rank: 139, title: "Stinkfist", artist: "Tool", genre: "Metal", year: 1996, album: "Aenima" },
  { id: 1640, rank: 140, title: "Lateralus", artist: "Tool", genre: "Metal", year: 2001, album: "Lateralus" },
  { id: 1641, rank: 141, title: "Vicarious", artist: "Tool", genre: "Metal", year: 2006, album: "10,000 Days" },
  { id: 1642, rank: 142, title: "The Pot", artist: "Tool", genre: "Metal", year: 2006, album: "10,000 Days" },
  { id: 1643, rank: 143, title: "Pneuma", artist: "Tool", genre: "Metal", year: 2019, album: "Fear Inoculum" },
  { id: 1644, rank: 144, title: "Sorrow", artist: "Bad Brains", genre: "Metal", year: 1993, album: "Rise" },
  { id: 1645, rank: 145, title: "Laid to Rest", artist: "Lamb of God", genre: "Metal", year: 2004, album: "Ashes of the Wake" },
  { id: 1646, rank: 146, title: "Redneck", artist: "Lamb of God", genre: "Metal", year: 2006, album: "Sacrament" },
  { id: 1647, rank: 147, title: "Blacken the Cursed Sun", artist: "Lamb of God", genre: "Metal", year: 2006, album: "Sacrament" },
  { id: 1648, rank: 148, title: "Contractor", artist: "Lamb of God", genre: "Metal", year: 2009, album: "Wrath" },
  { id: 1649, rank: 149, title: "Ghost Walking", artist: "Lamb of God", genre: "Metal", year: 2012, album: "Resolution" },
  { id: 1650, rank: 150, title: "Broken Hands", artist: "Lamb of God", genre: "Metal", year: 2015, album: "VII: Sturm und Drang" },
  { id: 1651, rank: 151, title: "Pull Me Under", artist: "Dream Theater", genre: "Metal", year: 1992, album: "Images and Words" },
  { id: 1652, rank: 152, title: "Metropolis—Part I", artist: "Dream Theater", genre: "Metal", year: 1992, album: "Images and Words" },
  { id: 1653, rank: 153, title: "A Change of Seasons", artist: "Dream Theater", genre: "Metal", year: 1995, album: "A Change of Seasons" },
  { id: 1654, rank: 154, title: "The Spirit Carries On", artist: "Dream Theater", genre: "Metal", year: 1999, album: "Metropolis Pt. 2: Scenes from a Memory" },
  { id: 1655, rank: 155, title: "In the Presence of Enemies", artist: "Dream Theater", genre: "Metal", year: 2007, album: "Systematic Chaos" },
  { id: 1656, rank: 156, title: "On the Backs of Angels", artist: "Dream Theater", genre: "Metal", year: 2011, album: "A Dramatic Turn of Events" },
  { id: 1657, rank: 157, title: "The Mirror", artist: "Dream Theater", genre: "Metal", year: 1994, album: "Awake" },
  { id: 1658, rank: 158, title: "Honor Thy Father", artist: "Dream Theater", genre: "Metal", year: 2003, album: "Train of Thought" },
  { id: 1659, rank: 159, title: "Ghost of Perdition", artist: "Opeth", genre: "Metal", year: 2005, album: "Ghost Reveries" },
  { id: 1660, rank: 160, title: "Blackwater Park", artist: "Opeth", genre: "Metal", year: 2001, album: "Blackwater Park" },
  { id: 1661, rank: 161, title: "The Leper Affinity", artist: "Opeth", genre: "Metal", year: 2001, album: "Blackwater Park" },
  { id: 1662, rank: 162, title: "Deliverance", artist: "Opeth", genre: "Metal", year: 2002, album: "Deliverance" },
  { id: 1663, rank: 163, title: "Demon of the Fall", artist: "Opeth", genre: "Metal", year: 1998, album: "My Arms, Your Hearse" },
  { id: 1664, rank: 164, title: "The Drapery Falls", artist: "Opeth", genre: "Metal", year: 2001, album: "Blackwater Park" },
  { id: 1665, rank: 165, title: "Harvester of Sorrow", artist: "Metallica", genre: "Metal", year: 1988, album: "...And Justice for All" },
  { id: 1666, rank: 166, title: "Sad but True", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1667, rank: 167, title: "King Nothing", artist: "Metallica", genre: "Metal", year: 1996, album: "Load" },
  { id: 1668, rank: 168, title: "Until It Sleeps", artist: "Metallica", genre: "Metal", year: 1996, album: "Load" },
  { id: 1669, rank: 169, title: "Fuel", artist: "Metallica", genre: "Metal", year: 1997, album: "Reload" },
  { id: 1670, rank: 170, title: "The Memory Remains", artist: "Metallica", genre: "Metal", year: 1997, album: "Reload" },
  { id: 1671, rank: 171, title: "Turn the Page", artist: "Metallica", genre: "Metal", year: 1998, album: "Garage Inc." },
  { id: 1672, rank: 172, title: "Nothing Else Matters", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1673, rank: 173, title: "For Whom the Bell Tolls", artist: "Metallica", genre: "Metal", year: 1984, album: "Ride the Lightning" },
  { id: 1674, rank: 174, title: "Ride the Lightning", artist: "Metallica", genre: "Metal", year: 1984, album: "Ride the Lightning" },
  { id: 1675, rank: 175, title: "The Four Horsemen", artist: "Metallica", genre: "Metal", year: 1983, album: "Kill 'Em All" },
  { id: 1676, rank: 176, title: "Phantom Lord", artist: "Metallica", genre: "Metal", year: 1983, album: "Kill 'Em All" },
  { id: 1677, rank: 177, title: "Motorbreath", artist: "Metallica", genre: "Metal", year: 1983, album: "Kill 'Em All" },
  { id: 1678, rank: 178, title: "Sanitarium (Welcome Home)", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1679, rank: 179, title: "Disposable Heroes", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1680, rank: 180, title: "Blackened", artist: "Metallica", genre: "Metal", year: 1988, album: "...And Justice for All" },
  { id: 1681, rank: 181, title: "Damage, Inc.", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1682, rank: 182, title: "Hardwired", artist: "Metallica", genre: "Metal", year: 2016, album: "Hardwired...to Self-Destruct" },
  { id: 1683, rank: 183, title: "Atlas, Rise!", artist: "Metallica", genre: "Metal", year: 2016, album: "Hardwired...to Self-Destruct" },
  { id: 1684, rank: 184, title: "72 Seasons", artist: "Metallica", genre: "Metal", year: 2023, album: "72 Seasons" },
  { id: 1685, rank: 185, title: "Lux Aeterna", artist: "Metallica", genre: "Metal", year: 2023, album: "72 Seasons" },
  { id: 1686, rank: 186, title: "Tornado of Souls", artist: "Megadeth", genre: "Metal", year: 1990, album: "Rust in Peace" },
  { id: 1687, rank: 187, title: "Sweating Bullets", artist: "Megadeth", genre: "Metal", year: 1992, album: "Countdown to Extinction" },
  { id: 1688, rank: 188, title: "A Tout le Monde", artist: "Megadeth", genre: "Metal", year: 1994, album: "Youthanasia" },
  { id: 1689, rank: 189, title: "In My Darkest Hour", artist: "Megadeth", genre: "Metal", year: 1988, album: "So Far, So Good... So What!" },
  { id: 1690, rank: 190, title: "Wake Up Dead", artist: "Megadeth", genre: "Metal", year: 1986, album: "Peace Sells... but Who's Buying?" },
  { id: 1691, rank: 191, title: "Mechanix", artist: "Megadeth", genre: "Metal", year: 1985, album: "Killing Is My Business..." },
  { id: 1692, rank: 192, title: "She-Wolf", artist: "Megadeth", genre: "Metal", year: 1994, album: "Youthanasia" },
  { id: 1693, rank: 193, title: "Trust", artist: "Megadeth", genre: "Metal", year: 1997, album: "Cryptic Writings" },
  { id: 1694, rank: 194, title: "99 Ways to Die", artist: "Megadeth", genre: "Metal", year: 1994, album: "Hidden Treasures" },
  { id: 1695, rank: 195, title: "Skin o' My Teeth", artist: "Megadeth", genre: "Metal", year: 1992, album: "Countdown to Extinction" },
  { id: 1696, rank: 196, title: "South of Heaven", artist: "Slayer", genre: "Metal", year: 1988, album: "South of Heaven" },
  { id: 1697, rank: 197, title: "Seasons in the Abyss", artist: "Slayer", genre: "Metal", year: 1990, album: "Seasons in the Abyss" },
  { id: 1698, rank: 198, title: "War Ensemble", artist: "Slayer", genre: "Metal", year: 1990, album: "Seasons in the Abyss" },
  { id: 1699, rank: 199, title: "Dead Skin Mask", artist: "Slayer", genre: "Metal", year: 1990, album: "Seasons in the Abyss" },
  { id: 1700, rank: 200, title: "Mandatory Suicide", artist: "Slayer", genre: "Metal", year: 1988, album: "South of Heaven" },
  { id: 1701, rank: 201, title: "Postmortem", artist: "Slayer", genre: "Metal", year: 1986, album: "Reign in Blood" },
  { id: 1702, rank: 202, title: "Hell Awaits", artist: "Slayer", genre: "Metal", year: 1985, album: "Hell Awaits" },
  { id: 1703, rank: 203, title: "Wrath Childlike", artist: "Slayer", genre: "Metal", year: 1985, album: "Hell Awaits" },
  { id: 1704, rank: 204, title: "Here Comes the Pain", artist: "Slayer", genre: "Metal", year: 2001, album: "God Hates Us All" },
  { id: 1705, rank: 205, title: "Flood", artist: "Pantera", genre: "Metal", year: 1994, album: "Far Beyond Driven" },
  { id: 1706, rank: 206, title: "This Love", artist: "Pantera", genre: "Metal", year: 1992, album: "Vulgar Display of Power" },
  { id: 1707, rank: 207, title: "Becoming", artist: "Pantera", genre: "Metal", year: 1994, album: "Far Beyond Driven" },
  { id: 1708, rank: 208, title: "5 Minutes Alone", artist: "Pantera", genre: "Metal", year: 1994, album: "Far Beyond Driven" },
  { id: 1709, rank: 209, title: "Hollow", artist: "Pantera", genre: "Metal", year: 1992, album: "Vulgar Display of Power" },
  { id: 1710, rank: 210, title: "A New Level", artist: "Pantera", genre: "Metal", year: 1992, album: "Vulgar Display of Power" },
  { id: 1711, rank: 211, title: "Cemetery Gates", artist: "Pantera", genre: "Metal", year: 1990, album: "Cowboys from Hell" },
  { id: 1712, rank: 212, title: "Domination", artist: "Pantera", genre: "Metal", year: 1990, album: "Cowboys from Hell" },
  { id: 1713, rank: 213, title: "I'm Broken", artist: "Pantera", genre: "Metal", year: 1994, album: "Far Beyond Driven" },
  { id: 1714, rank: 214, title: "25 Years", artist: "Pantera", genre: "Metal", year: 1994, album: "Far Beyond Driven" },
  { id: 1715, rank: 215, title: "The Great Southern Trendkill", artist: "Pantera", genre: "Metal", year: 1996, album: "The Great Southern Trendkill" },
  { id: 1716, rank: 216, title: "Drag the Waters", artist: "Pantera", genre: "Metal", year: 1996, album: "The Great Southern Trendkill" },
  { id: 1717, rank: 217, title: "Du Hast", artist: "Rammstein", genre: "Metal", year: 1997, album: "Sehnsucht" },
  { id: 1718, rank: 218, title: "Feuer Frei!", artist: "Rammstein", genre: "Metal", year: 2001, album: "Mutter" },
  { id: 1719, rank: 219, title: "Sonne", artist: "Rammstein", genre: "Metal", year: 2001, album: "Mutter" },
  { id: 1720, rank: 220, title: "Rammstein", artist: "Rammstein", genre: "Metal", year: 1995, album: "Herzeleid" },
  { id: 1721, rank: 221, title: "Mein Teil", artist: "Rammstein", genre: "Metal", year: 2004, album: "Reise, Reise" },
  { id: 1722, rank: 222, title: "Keine Lust", artist: "Rammstein", genre: "Metal", year: 2004, album: "Reise, Reise" },
  { id: 1723, rank: 223, title: "Amerika", artist: "Rammstein", genre: "Metal", year: 2004, album: "Reise, Reise" },
  { id: 1724, rank: 224, title: "Engel", artist: "Rammstein", genre: "Metal", year: 1997, album: "Sehnsucht" },
  { id: 1725, rank: 225, title: "Ich Will", artist: "Rammstein", genre: "Metal", year: 2001, album: "Mutter" },
  { id: 1726, rank: 226, title: "Benzin", artist: "Rammstein", genre: "Metal", year: 2005, album: "Rosenrot" },
  { id: 1727, rank: 227, title: "Radio", artist: "Rammstein", genre: "Metal", year: 2019, album: "Rammstein" },
  { id: 1728, rank: 228, title: "Macht Nichts", artist: "Rammstein", genre: "Metal", year: 2022, album: "Zeit" },
  { id: 1729, rank: 229, title: "Wochentag", artist: "Rammstein", genre: "Metal", year: 2022, album: "Zeit" },
  { id: 1730, rank: 230, title: "Bat Country", artist: "Avenged Sevenfold", genre: "Metal", year: 2005, album: "City of Evil" },
  { id: 1731, rank: 231, title: "Beast and the Harlot", artist: "Avenged Sevenfold", genre: "Metal", year: 2005, album: "City of Evil" },
  { id: 1732, rank: 232, title: "Afterlife", artist: "Avenged Sevenfold", genre: "Metal", year: 2007, album: "Avenged Sevenfold" },
  { id: 1733, rank: 233, title: "Nightmare", artist: "Avenged Sevenfold", genre: "Metal", year: 2010, album: "Nightmare" },
  { id: 1734, rank: 234, title: "Welcome to the Family", artist: "Avenged Sevenfold", genre: "Metal", year: 2010, album: "Nightmare" },
  { id: 1735, rank: 235, title: "Hail to the King", artist: "Avenged Sevenfold", genre: "Metal", year: 2013, album: "Hail to the King" },
  { id: 1736, rank: 236, title: "Carry On", artist: "Avenged Sevenfold", genre: "Metal", year: 2012, album: "Hail to the King" },
  { id: 1737, rank: 237, title: "So Far Away", artist: "Avenged Sevenfold", genre: "Metal", year: 2010, album: "Nightmare" },
  { id: 1738, rank: 238, title: "Almost Easy", artist: "Avenged Sevenfold", genre: "Metal", year: 2007, album: "Avenged Sevenfold" },
  { id: 1739, rank: 239, title: "Unholy Confessions", artist: "Avenged Sevenfold", genre: "Metal", year: 2003, album: "Waking the Fallen" },
  { id: 1740, rank: 240, title: "Scream", artist: "Avenged Sevenfold", genre: "Metal", year: 2005, album: "City of Evil" },
  { id: 1741, rank: 241, title: "Wish You Were Here", artist: "Avenged Sevenfold", genre: "Metal", year: 2016, album: "The Stage" },
  { id: 1742, rank: 242, title: "The Stage", artist: "Avenged Sevenfold", genre: "Metal", year: 2016, album: "The Stage" },
  { id: 1743, rank: 243, title: "Tears Don't Fall", artist: "Bullet for My Valentine", genre: "Metal", year: 2005, album: "The Poison" },
  { id: 1744, rank: 244, title: "All These Things I Hate (Revolve Around Me)", artist: "Bullet for My Valentine", genre: "Metal", year: 2005, album: "The Poison" },
  { id: 1745, rank: 245, title: "Waking the Demon", artist: "Bullet for My Valentine", genre: "Metal", year: 2008, album: "Scream Aim Fire" },
  { id: 1746, rank: 246, title: "Scream Aim Fire", artist: "Bullet for My Valentine", genre: "Metal", year: 2008, album: "Scream Aim Fire" },
  { id: 1747, rank: 247, title: "Your Betrayal", artist: "Bullet for My Valentine", genre: "Metal", year: 2010, album: "Fever" },
  { id: 1748, rank: 248, title: "Hearts Burst into Fire", artist: "Bullet for My Valentine", genre: "Metal", year: 2008, album: "Scream Aim Fire" },
  { id: 1749, rank: 249, title: "Hand of Blood", artist: "Bullet for My Valentine", genre: "Metal", year: 2004, album: "Hand of Blood" },
  { id: 1750, rank: 250, title: "Colossal", artist: "Trivium", genre: "Metal", year: 2008, album: "Shogun" },
  { id: 1751, rank: 251, title: "Like Light to the Flies", artist: "Trivium", genre: "Metal", year: 2004, album: "Ascendancy" },
  { id: 1752, rank: 252, title: "Pull Harder on the Strings of Your Martyr", artist: "Trivium", genre: "Metal", year: 2004, album: "Ascendancy" },
  { id: 1753, rank: 253, title: "Anthem (We Are the Fire)", artist: "Trivium", genre: "Metal", year: 2006, album: "The Crusade" },
  { id: 1754, rank: 254, title: "Built to Fall", artist: "Trivium", genre: "Metal", year: 2011, album: "In Waves" },
  { id: 1755, rank: 255, title: "Until the World Goes Cold", artist: "Trivium", genre: "Metal", year: 2015, album: "Silence in the Snow" },
  { id: 1756, rank: 256, title: "Wash It All Away", artist: "Five Finger Death Punch", genre: "Metal", year: 2007, album: "The Way of the Fist" },
  { id: 1757, rank: 257, title: "Under and Over It", artist: "Five Finger Death Punch", genre: "Metal", year: 2011, album: "American Capitalist" },
  { id: 1758, rank: 258, title: "The Bleeding", artist: "Five Finger Death Punch", genre: "Metal", year: 2009, album: "War Is the Answer" },
  { id: 1759, rank: 259, title: "Remember Everything", artist: "Five Finger Death Punch", genre: "Metal", year: 2011, album: "American Capitalist" },
  { id: 1760, rank: 260, title: "Witness", artist: "Five Finger Death Punch", genre: "Metal", year: 2018, album: "And Justice for None" },
  { id: 1761, rank: 261, title: "Bother", artist: "Stone Sour", genre: "Metal", year: 2002, album: "Stone Sour" },
  { id: 1762, rank: 262, title: "Through Glass", artist: "Stone Sour", genre: "Metal", year: 2006, album: "Come What(ever) May" },
  { id: 1763, rank: 263, title: "Stalemate", artist: "Stone Sour", genre: "Metal", year: 2017, album: "Hydrograd" },
  { id: 1764, rank: 264, title: "Ghost", artist: "Disturbed", genre: "Metal", year: 2002, album: "Believe" },
  { id: 1765, rank: 265, title: "The Sound of Silence", artist: "Disturbed", genre: "Metal", year: 2015, album: "Immortalized" },
  { id: 1766, rank: 266, title: "Stupify", artist: "Disturbed", genre: "Metal", year: 2000, album: "The Sickness" },
  { id: 1767, rank: 267, title: "Prayer", artist: "Disturbed", genre: "Metal", year: 2002, album: "Believe" },
  { id: 1768, rank: 268, title: "Inside the Fire", artist: "Disturbed", genre: "Metal", year: 2008, album: "Indestructible" },
  { id: 1769, rank: 269, title: "Indestructible", artist: "Disturbed", genre: "Metal", year: 2008, album: "Indestructible" },
  { id: 1770, rank: 270, title: "The Vengeful One", artist: "Disturbed", genre: "Metal", year: 2015, album: "Immortalized" },
  { id: 1771, rank: 271, title: "Voices", artist: "Disturbed", genre: "Metal", year: 2000, album: "The Sickness" },
  { id: 1772, rank: 272, title: "Stricken", artist: "Disturbed", genre: "Metal", year: 2005, album: "Ten Thousand Fists" },
  { id: 1773, rank: 273, title: "Ten Thousand Fists", artist: "Disturbed", genre: "Metal", year: 2005, album: "Ten Thousand Fists" },
  { id: 1774, rank: 274, title: "The Diary of Jane", artist: "Breaking Benjamin", genre: "Metal", year: 2006, album: "Phobia" },
  { id: 1775, rank: 275, title: "So Cold", artist: "Breaking Benjamin", genre: "Metal", year: 2004, album: "We Are Not Alone" },
  { id: 1776, rank: 276, title: "I Will Not Bow", artist: "Breaking Benjamin", genre: "Metal", year: 2009, album: "Dear Agony" },
  { id: 1777, rank: 277, title: "Blow Me Away", artist: "Breaking Benjamin", genre: "Metal", year: 2004, album: "We Are Not Alone" },
  { id: 1778, rank: 278, title: "Dear Agony", artist: "Breaking Benjamin", genre: "Metal", year: 2009, album: "Dear Agony" },
  { id: 1779, rank: 279, title: "Dig", artist: "Mudvayne", genre: "Metal", year: 2000, album: "L.D. 50" },
  { id: 1780, rank: 280, title: "Happy?", artist: "Mudvayne", genre: "Metal", year: 2002, album: "The End of All Things to Come" },
  { id: 1781, rank: 281, title: "Not Falling", artist: "Mudvayne", genre: "Metal", year: 2002, album: "The End of All Things to Come" },
  { id: 1782, rank: 282, title: "Davidian", artist: "Machine Head", genre: "Metal", year: 1994, album: "Burn My Eyes" },
  { id: 1783, rank: 283, title: "Imperium", artist: "Machine Head", genre: "Metal", year: 2003, album: "Through the Ashes of Empires" },
  { id: 1784, rank: 284, title: "Halo", artist: "Machine Head", genre: "Metal", year: 2007, album: "The Blackening" },
  { id: 1785, rank: 285, title: "Aesthetics of Hate", artist: "Machine Head", genre: "Metal", year: 2007, album: "The Blackening" },
  { id: 1786, rank: 286, title: "Ten Ton Hammer", artist: "Machine Head", genre: "Metal", year: 1999, album: "The Burning Red" },
  { id: 1787, rank: 287, title: "The Quiet Place", artist: "In Flames", genre: "Metal", year: 2004, album: "Soundtrack to Your Escape" },
  { id: 1788, rank: 288, title: "Cloud Connected", artist: "In Flames", genre: "Metal", year: 2002, album: "Come Clarity" },
  { id: 1789, rank: 289, title: "Take This Life", artist: "In Flames", genre: "Metal", year: 2006, album: "Come Clarity" },
  { id: 1790, rank: 290, title: "Bullet Ride", artist: "In Flames", genre: "Metal", year: 2000, album: "Clayman" },
  { id: 1791, rank: 291, title: "The Hive", artist: "Arch Enemy", genre: "Metal", year: 2011, album: "Khaos Legions" },
  { id: 1792, rank: 292, title: "Nemesis", artist: "Arch Enemy", genre: "Metal", year: 2004, album: "Doomsday Machine" },
  { id: 1793, rank: 293, title: "We Will Rise", artist: "Arch Enemy", genre: "Metal", year: 2004, album: "Doomsday Machine" },
  { id: 1794, rank: 294, title: "Ravenous", artist: "Arch Enemy", genre: "Metal", year: 2001, album: "Wages of Sin" },
  { id: 1795, rank: 295, title: "Dead Eyes See No Future", artist: "Arch Enemy", genre: "Metal", year: 2004, album: "Dead Eyes See No Future" },
  { id: 1796, rank: 296, title: "Symphony X - Sea of Lies", artist: "Symphony X", genre: "Metal", year: 1997, album: "The Divine Wings of Tragedy" },
  { id: 1797, rank: 297, title: "Of Sins and Shadows", artist: "Symphony X", genre: "Metal", year: 1997, album: "The Divine Wings of Tragedy" },
  { id: 1798, rank: 298, title: "Accolade II", artist: "Symphony X", genre: "Metal", year: 2000, album: "V: The New Mythology Suite" },
  { id: 1799, rank: 299, title: "Wishmaster", artist: "Nightwish", genre: "Metal", year: 2000, album: "Wishmaster" },
  { id: 1800, rank: 300, title: "Nemo", artist: "Nightwish", genre: "Metal", year: 2004, album: "Once" },
  { id: 1801, rank: 301, title: "Ghost Love Score", artist: "Nightwish", genre: "Metal", year: 2004, album: "Once" },
  { id: 1802, rank: 302, title: "Amaranth", artist: "Nightwish", genre: "Metal", year: 2007, album: "Dark Passion Play" },
  { id: 1803, rank: 303, title: "The Islander", artist: "Nightwish", genre: "Metal", year: 2007, album: "Dark Passion Play" },
  { id: 1804, rank: 304, title: "Storytime", artist: "Nightwish", genre: "Metal", year: 2011, album: "Imaginaerum" },
  { id: 1805, rank: 305, title: "Last Ride of the Day", artist: "Nightwish", genre: "Metal", year: 2011, album: "Imaginaerum" },
  { id: 1806, rank: 306, title: "Elan", artist: "Nightwish", genre: "Metal", year: 2015, album: "Endless Forms Most Beautiful" },
  { id: 1807, rank: 307, title: "Sleeping Sun", artist: "Nightwish", genre: "Metal", year: 1999, album: "Oceanborn" },
  { id: 1808, rank: 308, title: "Mother Earth", artist: "Within Temptation", genre: "Metal", year: 2000, album: "Mother Earth" },
  { id: 1809, rank: 309, title: "Ice Queen", artist: "Within Temptation", genre: "Metal", year: 2000, album: "Mother Earth" },
  { id: 1810, rank: 310, title: "Stand My Ground", artist: "Within Temptation", genre: "Metal", year: 2004, album: "The Silent Force" },
  { id: 1811, rank: 311, title: "Memories", artist: "Within Temptation", genre: "Metal", year: 2004, album: "The Silent Force" },
  { id: 1812, rank: 312, title: "Angels", artist: "Within Temptation", genre: "Metal", year: 2007, album: "The Heart of Everything" },
  { id: 1813, rank: 313, title: "What Have You Done", artist: "Within Temptation", genre: "Metal", year: 2007, album: "The Heart of Everything" },
  { id: 1814, rank: 314, title: "Paradise (What About Us?)", artist: "Within Temptation", genre: "Metal", year: 2011, album: "Hydra" },
  { id: 1815, rank: 315, title: "See Who I Am", artist: "Within Temptation", genre: "Metal", year: 2004, album: "The Silent Force" },
  { id: 1816, rank: 316, title: "Burn", artist: "Within Temptation", genre: "Metal", year: 2011, album: "The Unforgiving" },
  { id: 1817, rank: 317, title: "Jaded", artist: "Queensrÿche", genre: "Metal", year: 1997, album: "Hear in the Now Frontier" },
  { id: 1818, rank: 318, title: "Silent Lucidity", artist: "Queensrÿche", genre: "Metal", year: 1990, album: "Empire" },
  { id: 1819, rank: 319, title: "Jet City Woman", artist: "Queensrÿche", genre: "Metal", year: 1990, album: "Empire" },
  { id: 1820, rank: 320, title: "Empire", artist: "Queensrÿche", genre: "Metal", year: 1990, album: "Empire" },
  { id: 1821, rank: 321, title: "Eyes of a Stranger", artist: "Queensrÿche", genre: "Metal", year: 1988, album: "Operation: Mindcrime" },
  { id: 1822, rank: 322, title: "Suite Sister Mary", artist: "Queensrÿche", genre: "Metal", year: 1988, album: "Operation: Mindcrime" },
  { id: 1823, rank: 323, title: "I Don't Believe in Love", artist: "Queensrÿche", genre: "Metal", year: 1988, album: "Operation: Mindcrime" },
  { id: 1824, rank: 324, title: "Anthem", artist: "Queensrÿche", genre: "Metal", year: 1984, album: "The Warning" },
  { id: 1825, rank: 325, title: "Hammer Smashed Face", artist: "Cannibal Corpse", genre: "Metal", year: 1992, album: "Tomb of the Mutilated" },
  { id: 1826, rank: 326, title: "Stripped, Raped, and Strangled", artist: "Cannibal Corpse", genre: "Metal", year: 1994, album: "The Bleeding" },
  { id: 1827, rank: 327, title: "Symbolic", artist: "Death", genre: "Metal", year: 1995, album: "Symbolic" },
  { id: 1828, rank: 328, title: "Crystal Mountain", artist: "Death", genre: "Metal", year: 1995, album: "Symbolic" },
  { id: 1829, rank: 329, title: "Lack of Comprehension", artist: "Death", genre: "Metal", year: 1991, album: "Human" },
  { id: 1830, rank: 330, title: "Flesh and the Power It Holds", artist: "Death", genre: "Metal", year: 1998, album: "The Sound of Perseverance" },
  { id: 1831, rank: 331, title: "Empty Words", artist: "Death", genre: "Metal", year: 1991, album: "Human" },
  { id: 1832, rank: 332, title: "De Mysteriis Dom Sathanas", artist: "Mayhem", genre: "Metal", year: 1994, album: "De Mysteriis Dom Sathanas" },
  { id: 1833, rank: 333, title: "Freezing Moon", artist: "Mayhem", genre: "Metal", year: 1994, album: "De Mysteriis Dom Sathanas" },
  { id: 1834, rank: 334, title: "Deathcrush", artist: "Mayhem", genre: "Metal", year: 1987, album: "Deathcrush" },
  { id: 1835, rank: 335, title: "Black Metal", artist: "Venom", genre: "Metal", year: 1982, album: "Black Metal" },
  { id: 1836, rank: 336, title: "Welcome to Hell", artist: "Venom", genre: "Metal", year: 1981, album: "Welcome to Hell" },
  { id: 1837, rank: 337, title: "In the Sign of Evil", artist: "Sodom", genre: "Metal", year: 1984, album: "In the Sign of Evil" },
  { id: 1838, rank: 338, title: "Ausgebombt", artist: "Sodom", genre: "Metal", year: 1989, album: "Agent Orange" },
  { id: 1839, rank: 339, title: "Agent Orange", artist: "Sodom", genre: "Metal", year: 1989, album: "Agent Orange" },
  { id: 1840, rank: 340, title: "Nebelkanone", artist: "Sodom", genre: "Metal", year: 2001, album: "M-16" },
  { id: 1841, rank: 341, title: "Teutonic Terror", artist: "Sodom", genre: "Metal", year: 2001, album: "M-16" },
  { id: 1842, rank: 342, title: "The Saw Is the Law", artist: "Sodom", genre: "Metal", year: 1987, album: "Persecution Mania" },
  { id: 1843, rank: 343, title: "Persecution Mania", artist: "Sodom", genre: "Metal", year: 1987, album: "Persecution Mania" },
  { id: 1844, rank: 344, title: "A Question of Heaven", artist: "Iced Earth", genre: "Metal", year: 1995, album: "Burnt Offerings" },
  { id: 1845, rank: 345, title: "Dante's Inferno", artist: "Iced Earth", genre: "Metal", year: 1995, album: "Burnt Offerings" },
  { id: 1846, rank: 346, title: "Watching over Me", artist: "Iced Earth", genre: "Metal", year: 1997, album: "Something Wicked This Way Comes" },
  { id: 1847, rank: 347, title: "Travel in Stygian", artist: "Iced Earth", genre: "Metal", year: 1998, album: "Something Wicked This Way Comes" },
  { id: 1848, rank: 348, title: "Framing Armageddon", artist: "Iced Earth", genre: "Metal", year: 2007, album: "Framing Armageddon" },
  { id: 1849, rank: 349, title: "Blood Red Skies", artist: "Judas Priest", genre: "Metal", year: 1988, album: "Ram It Down" },
  { id: 1850, rank: 350, title: "Turbo Lover", artist: "Judas Priest", genre: "Metal", year: 1986, album: "Turbo" },
  { id: 1851, rank: 351, title: "Ram It Down", artist: "Judas Priest", genre: "Metal", year: 1988, album: "Ram It Down" },
  { id: 1852, rank: 352, title: "Rapid Fire", artist: "Judas Priest", genre: "Metal", year: 1980, album: "British Steel" },
  { id: 1853, rank: 353, title: "Metal Gods", artist: "Judas Priest", genre: "Metal", year: 1980, album: "British Steel" },
  { id: 1854, rank: 354, title: "Delivering the Goods", artist: "Judas Priest", genre: "Metal", year: 1979, album: "Killing Machine" },
  { id: 1855, rank: 355, title: "Hell Bent for Leather", artist: "Judas Priest", genre: "Metal", year: 1979, album: "Killing Machine" },
  { id: 1856, rank: 356, title: "Take on the World", artist: "Judas Priest", genre: "Metal", year: 1979, album: "Killing Machine" },
  { id: 1857, rank: 357, title: "Sinner", artist: "Judas Priest", genre: "Metal", year: 1977, album: "Sin After Sin" },
  { id: 1858, rank: 358, title: "Better by You, Better than Me", artist: "Judas Priest", genre: "Metal", year: 1978, album: "Stained Class" },
  { id: 1859, rank: 359, title: "Dreamer Deceiver", artist: "Judas Priest", genre: "Metal", year: 1976, album: "Sad Wings of Destiny" },
  { id: 1860, rank: 360, title: "Starbreaker", artist: "Judas Priest", genre: "Metal", year: 1977, album: "Sin After Sin" },
  { id: 1861, rank: 361, title: "Halls of Valhalla", artist: "Judas Priest", genre: "Metal", year: 2014, album: "Redeemer of Souls" },
  { id: 1862, rank: 362, title: "Lightning Strike", artist: "Judas Priest", genre: "Metal", year: 2018, album: "Firepower" },
  { id: 1863, rank: 363, title: "Firepower", artist: "Judas Priest", genre: "Metal", year: 2018, album: "Firepower" },
  { id: 1864, rank: 364, title: "Mr. Tinkertrain", artist: "Ozzy Osbourne", genre: "Metal", year: 1991, album: "No More Tears" },
  { id: 1865, rank: 365, title: "Gets Me Through", artist: "Ozzy Osbourne", genre: "Metal", year: 2001, album: "Down to Earth" },
  { id: 1866, rank: 366, title: "Patient Number 9", artist: "Ozzy Osbourne", genre: "Metal", year: 2022, album: "Patient Number 9" },
  { id: 1867, rank: 367, title: "Straight to Hell", artist: "Ozzy Osbourne", genre: "Metal", year: 2020, album: "Ordinary Man" },
  { id: 1868, rank: 368, title: "Under and Over It", artist: "Ozzy Osbourne", genre: "Metal", year: 2020, album: "Ordinary Man" },
  { id: 1869, rank: 369, title: "Ordinary Man", artist: "Ozzy Osbourne", genre: "Metal", year: 2020, album: "Ordinary Man" },
  { id: 1870, rank: 370, title: "Whole Lotta Love", artist: "Led Zeppelin", genre: "Metal", year: 1969, album: "Led Zeppelin II" },
  { id: 1871, rank: 371, title: "Communication Breakdown", artist: "Led Zeppelin", genre: "Metal", year: 1969, album: "Led Zeppelin" },
  { id: 1872, rank: 372, title: "Immigrant Song", artist: "Led Zeppelin", genre: "Metal", year: 1970, album: "Led Zeppelin III" },
  { id: 1873, rank: 373, title: "Heartbreaker", artist: "Led Zeppelin", genre: "Metal", year: 1969, album: "Led Zeppelin II" },
  { id: 1874, rank: 374, title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "Metal", year: 1986, album: "Slippery When Wet" },
  { id: 1875, rank: 375, title: "You Give Love a Bad Name", artist: "Bon Jovi", genre: "Metal", year: 1986, album: "Slippery When Wet" },
  { id: 1876, rank: 376, title: "Wanted Dead or Alive", artist: "Bon Jovi", genre: "Metal", year: 1986, album: "Slippery When Wet" },
  { id: 1877, rank: 377, title: "Bad Medicine", artist: "Bon Jovi", genre: "Metal", year: 1988, album: "New Jersey" },
  { id: 1878, rank: 378, title: "Shining", artist: "Ghost", genre: "Metal", year: 2018, album: "Prequelle" },
  { id: 1879, rank: 379, title: "Square Hammer", artist: "Ghost", genre: "Metal", year: 2016, album: "Popestar" },
  { id: 1880, rank: 380, title: "Cirice", artist: "Ghost", genre: "Metal", year: 2015, album: "Meliora" },
  { id: 1881, rank: 381, title: "Dance Macabre", artist: "Ghost", genre: "Metal", year: 2018, album: "Prequelle" },
  { id: 1882, rank: 382, title: "He Is", artist: "Ghost", genre: "Metal", year: 2015, album: "Meliora" },
  { id: 1883, rank: 383, title: "Rats", artist: "Ghost", genre: "Metal", year: 2018, album: "Prequelle" },
  { id: 1884, rank: 384, title: "Mary on a Cross", artist: "Ghost", genre: "Metal", year: 2019, album: "Seven Inches of Satanic Panic" },
  { id: 1885, rank: 385, title: "Spillways", artist: "Ghost", genre: "Metal", year: 2022, album: "Impera" },
  { id: 1886, rank: 386, title: "Year Zero", artist: "Ghost", genre: "Metal", year: 2013, album: "Infestissumam" },
  { id: 1887, rank: 387, title: "Hunters Moon", artist: "Ghost", genre: "Metal", year: 2021, album: "Halloween Kills Soundtrack" },
  { id: 1888, rank: 388, title: "From the Pinnacle to the Pit", artist: "Ghost", genre: "Metal", year: 2015, album: "Meliora" },
  { id: 1889, rank: 389, title: "I Am a Viking", artist: "Yngwie Malmsteen", genre: "Metal", year: 1985, album: "Marching Out" },
  { id: 1890, rank: 390, title: "Black Star", artist: "Yngwie Malmsteen", genre: "Metal", year: 1984, album: "Rising Force" },
  { id: 1891, rank: 391, title: "Far Beyond the Sun", artist: "Yngwie Malmsteen", genre: "Metal", year: 1984, album: "Rising Force" },
  { id: 1892, rank: 392, title: "I'll See the Light Tonight", artist: "Yngwie Malmsteen", genre: "Metal", year: 1985, album: "Marching Out" },
  { id: 1893, rank: 393, title: "Kingdom Come", artist: "Helloween", genre: "Metal", year: 1987, album: "Keeper of the Seven Keys Pt. 1" },
  { id: 1894, rank: 394, title: "I Want Out", artist: "Helloween", genre: "Metal", year: 1988, album: "Keeper of the Seven Keys Pt. 2" },
  { id: 1895, rank: 395, title: "Eagle Fly Free", artist: "Helloween", genre: "Metal", year: 1988, album: "Keeper of the Seven Keys Pt. 2" },
  { id: 1896, rank: 396, title: "Dr. Stein", artist: "Helloween", genre: "Metal", year: 1988, album: "Keeper of the Seven Keys Pt. 2" },
  { id: 1897, rank: 397, title: "Future World", artist: "Helloween", genre: "Metal", year: 1987, album: "Keeper of the Seven Keys Pt. 1" },
  { id: 1898, rank: 398, title: "Halloween", artist: "Helloween", genre: "Metal", year: 1987, album: "Keeper of the Seven Keys Pt. 1" },
  { id: 1899, rank: 399, title: "A Tale That Wasn't Right", artist: "Helloween", genre: "Metal", year: 1987, album: "Keeper of the Seven Keys Pt. 1" },
  { id: 1900, rank: 400, title: "Power", artist: "Helloween", genre: "Metal", year: 1997, album: "Better Than Raw" },
  { id: 1901, rank: 401, title: "Keeper of the Seven Keys", artist: "Helloween", genre: "Metal", year: 1987, album: "Keeper of the Seven Keys Pt. 1" },
  { id: 1902, rank: 402, title: "Heavy Metal Is the Law", artist: "Helloween", genre: "Metal", year: 1985, album: "Walls of Jericho" },
  { id: 1903, rank: 403, title: "March of Time", artist: "Helloween", genre: "Metal", year: 1988, album: "Keeper of the Seven Keys Pt. 2" },
  { id: 1904, rank: 404, title: "Stone Cold", artist: "Helloween", genre: "Metal", year: 2010, album: "7 Sinners" },
  { id: 1905, rank: 405, title: "Best Time", artist: "Helloween", genre: "Metal", year: 2021, album: "Helloween" },
  { id: 1906, rank: 406, title: "Kill Devil Hill", artist: "Dio", genre: "Metal", year: 1990, album: "Lock Up the Wolves" },
  { id: 1907, rank: 407, title: "Strange Highways", artist: "Dio", genre: "Metal", year: 1993, album: "Strange Highways" },
  { id: 1908, rank: 408, title: "Invisible", artist: "Dio", genre: "Metal", year: 2000, album: "Magica" },
  { id: 1909, rank: 409, title: "Push", artist: "Dio", genre: "Metal", year: 1990, album: "Lock Up the Wolves" },
  { id: 1910, rank: 410, title: "Don't Talk to Strangers", artist: "Dio", genre: "Metal", year: 1983, album: "Holy Diver" },
  { id: 1911, rank: 411, title: "Die Hard the Hunter", artist: "Def Leppard", genre: "Metal", year: 1983, album: "Pyromania" },
  { id: 1912, rank: 412, title: "Rock of Ages", artist: "Def Leppard", genre: "Metal", year: 1983, album: "Pyromania" },
  { id: 1913, rank: 413, title: "Pour Some Sugar on Me", artist: "Def Leppard", genre: "Metal", year: 1987, album: "Hysteria" },
  { id: 1914, rank: 414, title: "Photograph", artist: "Def Leppard", genre: "Metal", year: 1983, album: "Pyromania" },
  { id: 1915, rank: 415, title: "Hysteria", artist: "Def Leppard", genre: "Metal", year: 1987, album: "Hysteria" },
  { id: 1916, rank: 416, title: "Love Bites", artist: "Def Leppard", genre: "Metal", year: 1987, album: "Hysteria" },
  { id: 1917, rank: 417, title: "Animal", artist: "Def Leppard", genre: "Metal", year: 1987, album: "Hysteria" },
  { id: 1918, rank: 418, title: "Armageddon It", artist: "Def Leppard", genre: "Metal", year: 1987, album: "Hysteria" },
  { id: 1919, rank: 419, title: "Sabotage", artist: "Black Sabbath", genre: "Metal", year: 1975, album: "Sabotage" },
  { id: 1920, rank: 420, title: "Am I Going Insane (Radio)", artist: "Black Sabbath", genre: "Metal", year: 1975, album: "Sabotage" },
  { id: 1921, rank: 421, title: "Hole in the Sky", artist: "Black Sabbath", genre: "Metal", year: 1975, album: "Sabotage" },
  { id: 1922, rank: 422, title: "After Forever", artist: "Black Sabbath", genre: "Metal", year: 1971, album: "Master of Reality" },
  { id: 1923, rank: 423, title: "Lord of This World", artist: "Black Sabbath", genre: "Metal", year: 1971, album: "Master of Reality" },
  { id: 1924, rank: 424, title: "Supernaut", artist: "Black Sabbath", genre: "Metal", year: 1972, album: "Vol. 4" },
  { id: 1925, rank: 425, title: "Cornucopia", artist: "Black Sabbath", genre: "Metal", year: 1972, album: "Vol. 4" },
  { id: 1926, rank: 426, title: "Wheels of Confusion", artist: "Black Sabbath", genre: "Metal", year: 1972, album: "Vol. 4" },
  { id: 1927, rank: 427, title: "Electric Funeral", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1928, rank: 428, title: "Hand of Doom", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1929, rank: 429, title: "Fairies Wear Boots", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1930, rank: 430, title: "Planet Caravan", artist: "Black Sabbath", genre: "Metal", year: 1970, album: "Paranoid" },
  { id: 1931, rank: 431, title: "Iron Curtain", artist: "Accept", genre: "Metal", year: 1982, album: "Restless and Wild" },
  { id: 1932, rank: 432, title: "Balls to the Wall", artist: "Accept", genre: "Metal", year: 1983, album: "Balls to the Wall" },
  { id: 1933, rank: 433, title: "Fast as a Shark", artist: "Accept", genre: "Metal", year: 1982, album: "Restless and Wild" },
  { id: 1934, rank: 434, title: "Restless and Wild", artist: "Accept", genre: "Metal", year: 1982, album: "Restless and Wild" },
  { id: 1935, rank: 435, title: "Metal Heart", artist: "Accept", genre: "Metal", year: 1985, album: "Metal Heart" },
  { id: 1936, rank: 436, title: "Midnight Mover", artist: "Accept", genre: "Metal", year: 1985, album: "Metal Heart" },
  { id: 1937, rank: 437, title: "Teutonic Terror", artist: "Accept", genre: "Metal", year: 2010, album: "Blood of the Nations" },
  { id: 1938, rank: 438, title: "Blood of the Nations", artist: "Accept", genre: "Metal", year: 2010, album: "Blood of the Nations" },
  { id: 1939, rank: 439, title: "Straight Shooter", artist: "Accept", genre: "Metal", year: 1983, album: "Balls to the Wall" },
  { id: 1940, rank: 440, title: "Burning", artist: "Accept", genre: "Metal", year: 1979, album: "I'm a Rebel" },
  { id: 1941, rank: 441, title: "Orion", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1942, rank: 442, title: "Leper Messiah", artist: "Metallica", genre: "Metal", year: 1986, album: "Master of Puppets" },
  { id: 1943, rank: 443, title: "My Friend of Misery", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1944, rank: 444, title: "Through the Never", artist: "Metallica", genre: "Metal", year: 1991, album: "Metallica" },
  { id: 1945, rank: 445, title: "St. Anger", artist: "Metallica", genre: "Metal", year: 2003, album: "St. Anger" },
  { id: 1946, rank: 446, title: "The Day That Never Comes", artist: "Metallica", genre: "Metal", year: 2008, album: "Death Magnetic" },
  { id: 1947, rank: 447, title: "All Nightmare Long", artist: "Metallica", genre: "Metal", year: 2008, album: "Death Magnetic" },
  { id: 1948, rank: 448, title: "My Apocalypse", artist: "Metallica", genre: "Metal", year: 2008, album: "Death Magnetic" },
  { id: 1949, rank: 449, title: "Cyanide", artist: "Metallica", genre: "Metal", year: 2008, album: "Death Magnetic" },
  { id: 1950, rank: 450, title: "The Unforgiven II", artist: "Metallica", genre: "Metal", year: 1997, album: "Reload" },
  { id: 1951, rank: 451, title: "Whiskey in the Jar", artist: "Metallica", genre: "Metal", year: 1998, album: "Garage Inc." },
  { id: 1952, rank: 452, title: "The Unforgiven III", artist: "Metallica", genre: "Metal", year: 2008, album: "Death Magnetic" },
  { id: 1953, rank: 453, title: "Wherever We May Roam", artist: "Motörhead", genre: "Metal", year: 1992, album: "March or Die" },
  { id: 1954, rank: 454, title: "Overkill", artist: "Motörhead", genre: "Metal", year: 1979, album: "Overkill" },
  { id: 1955, rank: 455, title: "Motorhead", artist: "Motörhead", genre: "Metal", year: 1977, album: "Motörhead" },
  { id: 1956, rank: 456, title: "Iron Fist", artist: "Motörhead", genre: "Metal", year: 1982, album: "Iron Fist" },
  { id: 1957, rank: 457, title: "Killed by Death", artist: "Motörhead", genre: "Metal", year: 1984, album: "No Remorse" },
  { id: 1958, rank: 458, title: "Bomber", artist: "Motörhead", genre: "Metal", year: 1979, album: "Bomber" },
  { id: 1959, rank: 459, title: "The Game", artist: "Motörhead", genre: "Metal", year: 1992, album: "March or Die" },
  { id: 1960, rank: 460, title: "We Are the Road Crew", artist: "Motörhead", genre: "Metal", year: 1980, album: "Ace of Spades" },
  { id: 1961, rank: 461, title: "Riding with the Driver", artist: "Motörhead", genre: "Metal", year: 2015, album: "Bad Magic" },
  { id: 1962, rank: 462, title: "Sympathy for the Devil", artist: "Motörhead", genre: "Metal", year: 2000, album: "We Are Motörhead" },
  { id: 1963, rank: 463, title: "When the Levee Breaks", artist: "Motörhead", genre: "Metal", year: 2000, album: "We Are Motörhead" },
  { id: 1964, rank: 464, title: "Leave Me Alone", artist: "Korn", genre: "Metal", year: 2002, album: "Untouchables" },
  { id: 1965, rank: 465, title: "Falling Away from Me", artist: "Korn", genre: "Metal", year: 1999, album: "Issues" },
  { id: 1966, rank: 466, title: "Somebody Someone", artist: "Korn", genre: "Metal", year: 2002, album: "Untouchables" },
  { id: 1967, rank: 467, title: "Did My Time", artist: "Korn", genre: "Metal", year: 2003, album: "Take a Look in the Mirror" },
  { id: 1968, rank: 468, title: "Here to Stay", artist: "Korn", genre: "Metal", year: 2002, album: "Untouchables" },
  { id: 1969, rank: 469, title: "Twisted Transistor", artist: "Korn", genre: "Metal", year: 2005, album: "See You on the Other Side" },
  { id: 1970, rank: 470, title: "Coming Undone", artist: "Korn", genre: "Metal", year: 2005, album: "See You on the Other Side" },
  { id: 1971, rank: 471, title: "Shoots and Ladders", artist: "Korn", genre: "Metal", year: 1994, album: "Korn" },
  { id: 1972, rank: 472, title: "Numb/Encore", artist: "Linkin Park & Jay-Z", genre: "Metal", year: 2004, album: "Collision Course" },
  { id: 1973, rank: 473, title: "Papercut", artist: "Linkin Park", genre: "Metal", year: 2000, album: "Hybrid Theory" },
  { id: 1974, rank: 474, title: "One Step Closer", artist: "Linkin Park", genre: "Metal", year: 2000, album: "Hybrid Theory" },
  { id: 1975, rank: 475, title: "Points of Authority", artist: "Linkin Park", genre: "Metal", year: 2000, album: "Hybrid Theory" },
  { id: 1976, rank: 476, title: "Breaking the Habit", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1977, rank: 477, title: "Somewhere I Belong", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1978, rank: 478, title: "Lying from You", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1979, rank: 479, title: "Given Up", artist: "Linkin Park", genre: "Metal", year: 2007, album: "Minutes to Midnight" },
  { id: 1980, rank: 480, title: "Burn It Down", artist: "Linkin Park", genre: "Metal", year: 2012, album: "Living Things" },
  { id: 1981, rank: 481, title: "From the Inside", artist: "Linkin Park", genre: "Metal", year: 2003, album: "Meteora" },
  { id: 1982, rank: 482, title: "Victimized", artist: "Linkin Park", genre: "Metal", year: 2012, album: "Living Things" },
  { id: 1983, rank: 483, title: "Institutionalized", artist: "Suicidal Tendencies", genre: "Metal", year: 1983, album: "Suicidal Tendencies" },
  { id: 1984, rank: 484, title: "You Can't Bring Me Down", artist: "Suicidal Tendencies", genre: "Metal", year: 1990, album: "Lights...Camera...Revolution!" },
  { id: 1985, rank: 485, title: "Send Me Your Money", artist: "Suicidal Tendencies", genre: "Metal", year: 1990, album: "Lights...Camera...Revolution!" },
  { id: 1986, rank: 486, title: "How Will I Laugh Tomorrow", artist: "Suicidal Tendencies", genre: "Metal", year: 1988, album: "How Will I Laugh Tomorrow..." },
  { id: 1987, rank: 487, title: "She's My Dirty Little Secret", artist: "Sevendust", genre: "Metal", year: 2003, album: "Seasons" },
  { id: 1988, rank: 488, title: "Face to Face", artist: "Sevendust", genre: "Metal", year: 1997, album: "Sevendust" },
  { id: 1989, rank: 489, title: "Denial", artist: "Sevendust", genre: "Metal", year: 2001, album: "Animosity" },
  { id: 1990, rank: 490, title: "Black", artist: "Sevendust", genre: "Metal", year: 1997, album: "Sevendust" },
  { id: 1991, rank: 491, title: "Inside", artist: "Sevendust", genre: "Metal", year: 1997, album: "Sevendust" },
  { id: 1992, rank: 492, title: "Gasoline", artist: "Sevendust", genre: "Metal", year: 2001, album: "Animosity" },
  { id: 1993, rank: 493, title: "Stricken", artist: "Avatar", genre: "Metal", year: 2016, album: "Feathers & Flesh" },
  { id: 1994, rank: 494, title: "The Eagle Has Landed", artist: "Saxon", genre: "Metal", year: 1982, album: "The Eagle Has Landed" },
  { id: 1995, rank: 495, title: "Wheels of Steel", artist: "Saxon", genre: "Metal", year: 1980, album: "Wheels of Steel" },
  { id: 1996, rank: 496, title: "747 (Strangers in the Night)", artist: "Saxon", genre: "Metal", year: 1980, album: "Wheels of Steel" },
  { id: 1997, rank: 497, title: "Strong Arm of the Law", artist: "Saxon", genre: "Metal", year: 1980, album: "Strong Arm of the Law" },
  { id: 1998, rank: 498, title: "Princess of the Night", artist: "Saxon", genre: "Metal", year: 1981, album: "Denim and Leather" },
  { id: 1999, rank: 499, title: "Denim and Leather", artist: "Saxon", genre: "Metal", year: 1981, album: "Denim and Leather" },
  { id: 2000, rank: 500, title: "And the Bands Played On", artist: "Saxon", genre: "Metal", year: 1981, album: "Denim and Leather" },
];
