const SONGS_JAZZ = [
  { id: 4501, rank: 1, title: "Kind of Blue - So What", artist: "Miles Davis", genre: "Jazz", year: 1959, album: "Kind of Blue" },
  { id: 4502, rank: 2, title: "Kind of Blue - Freddie Freeloader", artist: "Miles Davis", genre: "Jazz", year: 1959, album: "Kind of Blue" },
  { id: 4503, rank: 3, title: "Kind of Blue - Blue in Green", artist: "Miles Davis", genre: "Jazz", year: 1959, album: "Kind of Blue" },
  { id: 4504, rank: 4, title: "Kind of Blue - All Blues", artist: "Miles Davis", genre: "Jazz", year: 1959, album: "Kind of Blue" },
  { id: 4505, rank: 5, title: "Kind of Blue - Flamenco Sketches", artist: "Miles Davis", genre: "Jazz", year: 1959, album: "Kind of Blue" },
  { id: 4506, rank: 6, title: "Bitches Brew - Bitches Brew", artist: "Miles Davis", genre: "Jazz", year: 1970, album: "Bitches Brew" },
  { id: 4507, rank: 7, title: "Bitches Brew - Miles Runs the Voodoo Down", artist: "Miles Davis", genre: "Jazz", year: 1970, album: "Bitches Brew" },
  { id: 4508, rank: 8, title: "Miles Smiles - Footprints", artist: "Miles Davis", genre: "Jazz", year: 1967, album: "Miles Smiles" },
  { id: 4509, rank: 9, title: "Round About Midnight - 'Round Midnight", artist: "Miles Davis", genre: "Jazz", year: 1957, album: "Round About Midnight" },
  { id: 4510, rank: 10, title: "Walkin' - Walkin'", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Walkin'" },
  { id: 4511, rank: 11, title: "Birth of the Cool - Boplicity", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4512, rank: 12, title: "Birth of the Cool - Moon Dreams", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4513, rank: 13, title: "In a Silent Way - In a Silent Way", artist: "Miles Davis", genre: "Jazz", year: 1969, album: "In a Silent Way" },
  { id: 4514, rank: 14, title: "Sketches of Spain - Concierto de Aranjuez", artist: "Miles Davis", genre: "Jazz", year: 1960, album: "Sketches of Spain" },
  { id: 4515, rank: 15, title: "E.S.P. - E.S.P.", artist: "Miles Davis", genre: "Jazz", year: 1965, album: "E.S.P." },
  { id: 4516, rank: 16, title: "Four & More - Four", artist: "Miles Davis", genre: "Jazz", year: 1964, album: "Four & More" },
  { id: 4517, rank: 17, title: "Nefertiti - Nefertiti", artist: "Miles Davis", genre: "Jazz", year: 1968, album: "Nefertiti" },
  { id: 4518, rank: 18, title: "On the Corner - On the Corner", artist: "Miles Davis", genre: "Jazz", year: 1972, album: "On the Corner" },
  { id: 4519, rank: 19, title: "Jack Johnson - Right Off", artist: "Miles Davis", genre: "Jazz", year: 1971, album: "Jack Johnson" },
  { id: 4520, rank: 20, title: "Tutu - Tutu", artist: "Miles Davis", genre: "Jazz", year: 1986, album: "Tutu" },
  { id: 4521, rank: 21, title: "A Love Supreme - Part I: Acknowledgement", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "A Love Supreme" },
  { id: 4522, rank: 22, title: "A Love Supreme - Part II: Resolution", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "A Love Supreme" },
  { id: 4523, rank: 23, title: "A Love Supreme - Part III: Pursuance", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "A Love Supreme" },
  { id: 4524, rank: 24, title: "A Love Supreme - Part IV: Psalm", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "A Love Supreme" },
  { id: 4525, rank: 25, title: "Giant Steps - Giant Steps", artist: "John Coltrane", genre: "Jazz", year: 1960, album: "Giant Steps" },
  { id: 4526, rank: 26, title: "Giant Steps - Naima", artist: "John Coltrane", genre: "Jazz", year: 1960, album: "Giant Steps" },
  { id: 4527, rank: 27, title: "Giant Steps - Cousin Mary", artist: "John Coltrane", genre: "Jazz", year: 1960, album: "Giant Steps" },
  { id: 4528, rank: 28, title: "My Favorite Things - My Favorite Things", artist: "John Coltrane", genre: "Jazz", year: 1961, album: "My Favorite Things" },
  { id: 4529, rank: 29, title: "Impressions - Impressions", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Impressions" },
  { id: 4530, rank: 30, title: "Ballads - All or Nothing at All", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Ballads" },
  { id: 4531, rank: 31, title: "Crescent - Crescent", artist: "John Coltrane", genre: "Jazz", year: 1964, album: "Crescent" },
  { id: 4532, rank: 32, title: "Coltrane Jazz - Village Blues", artist: "John Coltrane", genre: "Jazz", year: 1961, album: "Coltrane Jazz" },
  { id: 4533, rank: 33, title: "Blue Train - Blue Train", artist: "John Coltrane", genre: "Jazz", year: 1958, album: "Blue Train" },
  { id: 4534, rank: 34, title: "Blue Train - Moment's Notice", artist: "John Coltrane", genre: "Jazz", year: 1958, album: "Blue Train" },
  { id: 4535, rank: 35, title: "Meditations - The Father and the Son and the Holy Ghost", artist: "John Coltrane", genre: "Jazz", year: 1966, album: "Meditations" },
  { id: 4536, rank: 36, title: "Om - Om", artist: "John Coltrane", genre: "Jazz", year: 1967, album: "Om" },
  { id: 4537, rank: 37, title: "Ko-Ko", artist: "Charlie Parker", genre: "Jazz", year: 1945, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4538, rank: 38, title: "Ornithology", artist: "Charlie Parker", genre: "Jazz", year: 1946, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4539, rank: 39, title: "Yardbird Suite", artist: "Charlie Parker", genre: "Jazz", year: 1946, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4540, rank: 40, title: "Donna Lee", artist: "Charlie Parker", genre: "Jazz", year: 1947, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4541, rank: 41, title: "Confirmation", artist: "Charlie Parker", genre: "Jazz", year: 1946, album: "Bird: The Complete Charlie Parker on Verve" },
  { id: 4542, rank: 42, title: "Now's the Time", artist: "Charlie Parker", genre: "Jazz", year: 1945, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4543, rank: 43, title: "Billie's Bounce", artist: "Charlie Parker", genre: "Jazz", year: 1945, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4544, rank: 44, title: "Parker's Mood", artist: "Charlie Parker", genre: "Jazz", year: 1948, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4545, rank: 45, title: "Anthropology", artist: "Charlie Parker", genre: "Jazz", year: 1946, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4546, rank: 46, title: "Au Privave", artist: "Charlie Parker", genre: "Jazz", year: 1951, album: "Bird: The Complete Charlie Parker on Verve" },
  { id: 4547, rank: 47, title: "Relaxin' at Camarillo", artist: "Charlie Parker", genre: "Jazz", year: 1947, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4548, rank: 48, title: "'Round Midnight", artist: "Thelonious Monk", genre: "Jazz", year: 1944, album: "Monk's Music" },
  { id: 4549, rank: 49, title: "Straight, No Chaser", artist: "Thelonious Monk", genre: "Jazz", year: 1951, album: "Genius of Modern Music" },
  { id: 4550, rank: 50, title: "Well, You Needn't", artist: "Thelonious Monk", genre: "Jazz", year: 1944, album: "Genius of Modern Music" },
  { id: 4551, rank: 51, title: "Blue Monk", artist: "Thelonious Monk", genre: "Jazz", year: 1954, album: "Monk's Music" },
  { id: 4552, rank: 52, title: "Epistrophy", artist: "Thelonious Monk", genre: "Jazz", year: 1948, album: "Genius of Modern Music" },
  { id: 4553, rank: 53, title: "Mysterioso", artist: "Thelonious Monk", genre: "Jazz", year: 1948, album: "Genius of Modern Music" },
  { id: 4554, rank: 54, title: "Monk's Dream - Monk's Dream", artist: "Thelonious Monk", genre: "Jazz", year: 1963, album: "Monk's Dream" },
  { id: 4555, rank: 55, title: "In Walked Bud", artist: "Thelonious Monk", genre: "Jazz", year: 1947, album: "Genius of Modern Music" },
  { id: 4556, rank: 56, title: "Thelonious", artist: "Thelonious Monk", genre: "Jazz", year: 1947, album: "Genius of Modern Music" },
  { id: 4557, rank: 57, title: "Nutty", artist: "Thelonious Monk", genre: "Jazz", year: 1957, album: "Brilliant Corners" },
  { id: 4558, rank: 58, title: "Take the A Train", artist: "Duke Ellington", genre: "Jazz", year: 1941, album: "Never No Lament" },
  { id: 4559, rank: 59, title: "Mood Indigo", artist: "Duke Ellington", genre: "Jazz", year: 1930, album: "Early Ellington" },
  { id: 4560, rank: 60, title: "Sophisticated Lady", artist: "Duke Ellington", genre: "Jazz", year: 1933, album: "Early Ellington" },
  { id: 4561, rank: 61, title: "It Don't Mean a Thing (If It Ain't Got That Swing)", artist: "Duke Ellington", genre: "Jazz", year: 1932, album: "Early Ellington" },
  { id: 4562, rank: 62, title: "Caravan", artist: "Duke Ellington", genre: "Jazz", year: 1937, album: "Early Ellington" },
  { id: 4563, rank: 63, title: "In a Mellow Tone", artist: "Duke Ellington", genre: "Jazz", year: 1940, album: "Never No Lament" },
  { id: 4564, rank: 64, title: "Prelude to a Kiss", artist: "Duke Ellington", genre: "Jazz", year: 1938, album: "Early Ellington" },
  { id: 4565, rank: 65, title: "Cottontail", artist: "Duke Ellington", genre: "Jazz", year: 1940, album: "Never No Lament" },
  { id: 4566, rank: 66, title: "Solitude", artist: "Duke Ellington", genre: "Jazz", year: 1934, album: "Early Ellington" },
  { id: 4567, rank: 67, title: "Satin Doll", artist: "Duke Ellington", genre: "Jazz", year: 1953, album: "Ellington Uptown" },
  { id: 4568, rank: 68, title: "Black and Tan Fantasy", artist: "Duke Ellington", genre: "Jazz", year: 1927, album: "Early Ellington" },
  { id: 4569, rank: 69, title: "East St. Louis Toodle-Oo", artist: "Duke Ellington", genre: "Jazz", year: 1926, album: "Early Ellington" },
  { id: 4570, rank: 70, title: "Ko-Ko", artist: "Duke Ellington", genre: "Jazz", year: 1940, album: "Never No Lament" },
  { id: 4571, rank: 71, title: "Such Sweet Thunder - Such Sweet Thunder", artist: "Duke Ellington", genre: "Jazz", year: 1957, album: "Such Sweet Thunder" },
  { id: 4572, rank: 72, title: "What a Wonderful World", artist: "Louis Armstrong", genre: "Jazz", year: 1967, album: "What a Wonderful World" },
  { id: 4573, rank: 73, title: "La Vie En Rose", artist: "Louis Armstrong", genre: "Jazz", year: 1950, album: "Rare Items" },
  { id: 4574, rank: 74, title: "St. James Infirmary Blues", artist: "Louis Armstrong", genre: "Jazz", year: 1928, album: "Hot Five and Hot Seven" },
  { id: 4575, rank: 75, title: "Heebie Jeebies", artist: "Louis Armstrong", genre: "Jazz", year: 1926, album: "Hot Five and Hot Seven" },
  { id: 4576, rank: 76, title: "West End Blues", artist: "Louis Armstrong", genre: "Jazz", year: 1928, album: "Hot Five and Hot Seven" },
  { id: 4577, rank: 77, title: "Potato Head Blues", artist: "Louis Armstrong", genre: "Jazz", year: 1927, album: "Hot Five and Hot Seven" },
  { id: 4578, rank: 78, title: "Struttin' with Some Barbecue", artist: "Louis Armstrong", genre: "Jazz", year: 1927, album: "Hot Five and Hot Seven" },
  { id: 4579, rank: 79, title: "Stardust", artist: "Louis Armstrong", genre: "Jazz", year: 1931, album: "Stardust" },
  { id: 4580, rank: 80, title: "Ain't Misbehavin'", artist: "Louis Armstrong", genre: "Jazz", year: 1929, album: "Ain't Misbehavin'" },
  { id: 4581, rank: 81, title: "Hello, Dolly!", artist: "Louis Armstrong", genre: "Jazz", year: 1964, album: "Hello, Dolly!" },
  { id: 4582, rank: 82, title: "A Night in Tunisia", artist: "Dizzy Gillespie", genre: "Jazz", year: 1946, album: "A Night in Tunisia" },
  { id: 4583, rank: 83, title: "Salt Peanuts", artist: "Dizzy Gillespie", genre: "Jazz", year: 1945, album: "The Complete RCA Victor Recordings" },
  { id: 4584, rank: 84, title: "Groovin' High", artist: "Dizzy Gillespie", genre: "Jazz", year: 1945, album: "The Complete RCA Victor Recordings" },
  { id: 4585, rank: 85, title: "Manteca", artist: "Dizzy Gillespie", genre: "Jazz", year: 1948, album: "Afro" },
  { id: 4586, rank: 86, title: "Oop Bop Sh'Bam", artist: "Dizzy Gillespie", genre: "Jazz", year: 1946, album: "The Complete RCA Victor Recordings" },
  { id: 4587, rank: 87, title: "Con Alma", artist: "Dizzy Gillespie", genre: "Jazz", year: 1954, album: "Afro" },
  { id: 4588, rank: 88, title: "Night in Tunisia (alternate)", artist: "Dizzy Gillespie", genre: "Jazz", year: 1946, album: "Dizzy Gillespie's Big 4" },
  { id: 4589, rank: 89, title: "Waltz for Debby", artist: "Bill Evans", genre: "Jazz", year: 1961, album: "Waltz for Debby" },
  { id: 4590, rank: 90, title: "Alice in Wonderland", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Waltz for Debby" },
  { id: 4591, rank: 91, title: "My Foolish Heart", artist: "Bill Evans", genre: "Jazz", year: 1961, album: "Waltz for Debby" },
  { id: 4592, rank: 92, title: "Peace Piece", artist: "Bill Evans", genre: "Jazz", year: 1958, album: "Everybody Digs Bill Evans" },
  { id: 4593, rank: 93, title: "Nardis", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "At the Village Vanguard" },
  { id: 4594, rank: 94, title: "Autumn Leaves", artist: "Bill Evans", genre: "Jazz", year: 1959, album: "Portrait in Jazz" },
  { id: 4595, rank: 95, title: "Blue in Green", artist: "Bill Evans", genre: "Jazz", year: 1959, album: "Portrait in Jazz" },
  { id: 4596, rank: 96, title: "Re: Person I Knew", artist: "Bill Evans", genre: "Jazz", year: 1974, album: "Since We Met" },
  { id: 4597, rank: 97, title: "Gloria's Step", artist: "Bill Evans", genre: "Jazz", year: 1961, album: "Sunday at the Village Vanguard" },
  { id: 4598, rank: 98, title: "Jade Visions", artist: "Bill Evans", genre: "Jazz", year: 1961, album: "Sunday at the Village Vanguard" },
  { id: 4599, rank: 99, title: "Turn Out the Stars", artist: "Bill Evans", genre: "Jazz", year: 1968, album: "Bill Evans at Town Hall" },
  { id: 4600, rank: 100, title: "Take Five", artist: "Dave Brubeck", genre: "Jazz", year: 1959, album: "Time Out" },
  { id: 4601, rank: 101, title: "Blue Rondo à la Turk", artist: "Dave Brubeck", genre: "Jazz", year: 1959, album: "Time Out" },
  { id: 4602, rank: 102, title: "Strange Meadow Lark", artist: "Dave Brubeck", genre: "Jazz", year: 1959, album: "Time Out" },
  { id: 4603, rank: 103, title: "Three to Get Ready", artist: "Dave Brubeck", genre: "Jazz", year: 1959, album: "Time Out" },
  { id: 4604, rank: 104, title: "Unsquare Dance", artist: "Dave Brubeck", genre: "Jazz", year: 1961, album: "Time Further Out" },
  { id: 4605, rank: 105, title: "It's a Raggy Waltz", artist: "Dave Brubeck", genre: "Jazz", year: 1961, album: "Time Further Out" },
  { id: 4606, rank: 106, title: "The Real Ambassadors - Everybody's Comin'", artist: "Dave Brubeck", genre: "Jazz", year: 1962, album: "The Real Ambassadors" },
  { id: 4607, rank: 107, title: "My Funny Valentine", artist: "Chet Baker", genre: "Jazz", year: 1954, album: "Chet Baker Sings" },
  { id: 4608, rank: 108, title: "Let's Get Lost", artist: "Chet Baker", genre: "Jazz", year: 1954, album: "Chet Baker Sings" },
  { id: 4609, rank: 109, title: "Almost Blue", artist: "Chet Baker", genre: "Jazz", year: 1988, album: "Chet Baker Sings" },
  { id: 4610, rank: 110, title: "But Not for Me", artist: "Chet Baker", genre: "Jazz", year: 1954, album: "Chet Baker Sings" },
  { id: 4611, rank: 111, title: "Almost Blue (1988)", artist: "Chet Baker", genre: "Jazz", year: 1988, album: "My Favourite Songs" },
  { id: 4612, rank: 112, title: "You'd Be So Nice to Come Home To", artist: "Chet Baker", genre: "Jazz", year: 1955, album: "Chet Baker in New York" },
  { id: 4613, rank: 113, title: "There Will Never Be Another You", artist: "Chet Baker", genre: "Jazz", year: 1955, album: "Chet Baker in New York" },
  { id: 4614, rank: 114, title: "Joy Spring", artist: "Clifford Brown", genre: "Jazz", year: 1954, album: "Study in Brown" },
  { id: 4615, rank: 115, title: "Cherokee", artist: "Clifford Brown", genre: "Jazz", year: 1956, album: "At Basin Street" },
  { id: 4616, rank: 116, title: "Jordu", artist: "Clifford Brown", genre: "Jazz", year: 1954, album: "Study in Brown" },
  { id: 4617, rank: 117, title: "The Blues Walk", artist: "Clifford Brown", genre: "Jazz", year: 1954, album: "Study in Brown" },
  { id: 4618, rank: 118, title: "I'll Remember April", artist: "Clifford Brown", genre: "Jazz", year: 1956, album: "At Basin Street" },
  { id: 4619, rank: 119, title: "St. Thomas", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Saxophone Colossus" },
  { id: 4620, rank: 120, title: "Blue Seven", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Saxophone Colossus" },
  { id: 4621, rank: 121, title: "Moritat (Mack the Knife)", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Saxophone Colossus" },
  { id: 4622, rank: 122, title: "Strode Rode", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Saxophone Colossus" },
  { id: 4623, rank: 123, title: "The Bridge - Without a Song", artist: "Sonny Rollins", genre: "Jazz", year: 1962, album: "The Bridge" },
  { id: 4624, rank: 124, title: "Alfie", artist: "Sonny Rollins", genre: "Jazz", year: 1966, album: "Alfie" },
  { id: 4625, rank: 125, title: "Don't Stop the Carnival", artist: "Sonny Rollins", genre: "Jazz", year: 1978, album: "Don't Stop the Carnival" },
  { id: 4626, rank: 126, title: "West Coast Blues", artist: "Wes Montgomery", genre: "Jazz", year: 1960, album: "The Incredible Jazz Guitar of Wes Montgomery" },
  { id: 4627, rank: 127, title: "Airegin", artist: "Wes Montgomery", genre: "Jazz", year: 1960, album: "The Incredible Jazz Guitar of Wes Montgomery" },
  { id: 4628, rank: 128, title: "Four on Six", artist: "Wes Montgomery", genre: "Jazz", year: 1960, album: "The Incredible Jazz Guitar of Wes Montgomery" },
  { id: 4629, rank: 129, title: "Round Midnight", artist: "Wes Montgomery", genre: "Jazz", year: 1965, album: "Smokin' at the Half Note" },
  { id: 4630, rank: 130, title: "California Dreamin'", artist: "Wes Montgomery", genre: "Jazz", year: 1966, album: "California Dreamin'" },
  { id: 4631, rank: 131, title: "Windy", artist: "Wes Montgomery", genre: "Jazz", year: 1967, album: "A Day in the Life" },
  { id: 4632, rank: 132, title: "Bright Size Life", artist: "Pat Metheny", genre: "Jazz", year: 1976, album: "Bright Size Life" },
  { id: 4633, rank: 133, title: "Phase Dance", artist: "Pat Metheny", genre: "Jazz", year: 1977, album: "Pat Metheny Group" },
  { id: 4634, rank: 134, title: "Offramp - Are You Going With Me?", artist: "Pat Metheny", genre: "Jazz", year: 1982, album: "Offramp" },
  { id: 4635, rank: 135, title: "Letter From Home - Better Days Ahead", artist: "Pat Metheny", genre: "Jazz", year: 1989, album: "Letter From Home" },
  { id: 4636, rank: 136, title: "Secret Story - Finding and Believing", artist: "Pat Metheny", genre: "Jazz", year: 1992, album: "Secret Story" },
  { id: 4637, rank: 137, title: "The Way Up - Part One", artist: "Pat Metheny", genre: "Jazz", year: 2005, album: "The Way Up" },
  { id: 4638, rank: 138, title: "Unity Village", artist: "Pat Metheny", genre: "Jazz", year: 1976, album: "Bright Size Life" },
  { id: 4639, rank: 139, title: "Maiden Voyage - Maiden Voyage", artist: "Herbie Hancock", genre: "Jazz", year: 1965, album: "Maiden Voyage" },
  { id: 4640, rank: 140, title: "Speak Like a Child - Speak Like a Child", artist: "Herbie Hancock", genre: "Jazz", year: 1968, album: "Speak Like a Child" },
  { id: 4641, rank: 141, title: "Head Hunters - Chameleon", artist: "Herbie Hancock", genre: "Jazz", year: 1973, album: "Head Hunters" },
  { id: 4642, rank: 142, title: "Head Hunters - Watermelon Man", artist: "Herbie Hancock", genre: "Jazz", year: 1973, album: "Head Hunters" },
  { id: 4643, rank: 143, title: "Thrust - Actual Proof", artist: "Herbie Hancock", genre: "Jazz", year: 1974, album: "Thrust" },
  { id: 4644, rank: 144, title: "Inventions and Dimensions - Inventions and Dimensions", artist: "Herbie Hancock", genre: "Jazz", year: 1964, album: "Inventions and Dimensions" },
  { id: 4645, rank: 145, title: "Cantaloupe Island", artist: "Herbie Hancock", genre: "Jazz", year: 1964, album: "Empyrean Isles" },
  { id: 4646, rank: 146, title: "Rockit", artist: "Herbie Hancock", genre: "Jazz", year: 1983, album: "Future Shock" },
  { id: 4647, rank: 147, title: "Spain", artist: "Chick Corea", genre: "Jazz", year: 1972, album: "Light as a Feather" },
  { id: 4648, rank: 148, title: "La Fiesta", artist: "Chick Corea", genre: "Jazz", year: 1972, album: "Light as a Feather" },
  { id: 4649, rank: 149, title: "500 Miles High", artist: "Chick Corea", genre: "Jazz", year: 1972, album: "Light as a Feather" },
  { id: 4650, rank: 150, title: "The Matrix", artist: "Chick Corea", genre: "Jazz", year: 1968, album: "Now He Sings, Now He Sobs" },
  { id: 4651, rank: 151, title: "Tones for Joan's Bones", artist: "Chick Corea", genre: "Jazz", year: 1966, album: "Tones for Joan's Bones" },
  { id: 4652, rank: 152, title: "Crystal Silence - Crystal Silence", artist: "Chick Corea", genre: "Jazz", year: 1972, album: "Crystal Silence" },
  { id: 4653, rank: 153, title: "Children's Songs - No. 1", artist: "Chick Corea", genre: "Jazz", year: 1984, album: "Children's Songs" },
  { id: 4654, rank: 154, title: "Search for Peace", artist: "McCoy Tyner", genre: "Jazz", year: 1967, album: "The Real McCoy" },
  { id: 4655, rank: 155, title: "Passion Dance", artist: "McCoy Tyner", genre: "Jazz", year: 1967, album: "The Real McCoy" },
  { id: 4656, rank: 156, title: "Contemplation", artist: "McCoy Tyner", genre: "Jazz", year: 1967, album: "The Real McCoy" },
  { id: 4657, rank: 157, title: "Fly with the Wind - Fly with the Wind", artist: "McCoy Tyner", genre: "Jazz", year: 1976, album: "Fly with the Wind" },
  { id: 4658, rank: 158, title: "Speak No Evil - Speak No Evil", artist: "Wayne Shorter", genre: "Jazz", year: 1964, album: "Speak No Evil" },
  { id: 4659, rank: 159, title: "Speak No Evil - Wild Flower", artist: "Wayne Shorter", genre: "Jazz", year: 1964, album: "Speak No Evil" },
  { id: 4660, rank: 160, title: "Infant Eyes", artist: "Wayne Shorter", genre: "Jazz", year: 1964, album: "Speak No Evil" },
  { id: 4661, rank: 161, title: "Ju Ju - Ju Ju", artist: "Wayne Shorter", genre: "Jazz", year: 1965, album: "Ju Ju" },
  { id: 4662, rank: 162, title: "Adam's Apple - Adam's Apple", artist: "Wayne Shorter", genre: "Jazz", year: 1966, album: "Adam's Apple" },
  { id: 4663, rank: 163, title: "Footprints", artist: "Wayne Shorter", genre: "Jazz", year: 1966, album: "Adam's Apple" },
  { id: 4664, rank: 164, title: "Mysterious Traveller - Mysterious Traveller", artist: "Wayne Shorter", genre: "Jazz", year: 1974, album: "Mysterious Traveller" },
  { id: 4665, rank: 165, title: "Mercy, Mercy, Mercy!", artist: "Cannonball Adderley", genre: "Jazz", year: 1966, album: "Mercy, Mercy, Mercy!" },
  { id: 4666, rank: 166, title: "Somethin' Else - Autumn Leaves", artist: "Cannonball Adderley", genre: "Jazz", year: 1958, album: "Somethin' Else" },
  { id: 4667, rank: 167, title: "Somethin' Else - Somethin' Else", artist: "Cannonball Adderley", genre: "Jazz", year: 1958, album: "Somethin' Else" },
  { id: 4668, rank: 168, title: "Work Song", artist: "Cannonball Adderley", genre: "Jazz", year: 1960, album: "Them Dirty Blues" },
  { id: 4669, rank: 169, title: "Jive Samba", artist: "Cannonball Adderley", genre: "Jazz", year: 1962, album: "Jazz Workshop Revisited" },
  { id: 4670, rank: 170, title: "Moanin' - Moanin'", artist: "Art Blakey", genre: "Jazz", year: 1958, album: "Moanin'" },
  { id: 4671, rank: 171, title: "Are You Real - Are You Real", artist: "Art Blakey", genre: "Jazz", year: 1958, album: "Moanin'" },
  { id: 4672, rank: 172, title: "Along Came Betty", artist: "Art Blakey", genre: "Jazz", year: 1958, album: "Moanin'" },
  { id: 4673, rank: 173, title: "Blues March", artist: "Art Blakey", genre: "Jazz", year: 1958, album: "Moanin'" },
  { id: 4674, rank: 174, title: "A Night in Tunisia", artist: "Art Blakey", genre: "Jazz", year: 1954, album: "A Night at Birdland" },
  { id: 4675, rank: 175, title: "Free for All - Free for All", artist: "Art Blakey", genre: "Jazz", year: 1964, album: "Free for All" },
  { id: 4676, rank: 176, title: "Ugetsu - Ping-Pong", artist: "Art Blakey", genre: "Jazz", year: 1963, album: "Ugetsu" },
  { id: 4677, rank: 177, title: "Freedom Now Suite - Driva Man", artist: "Max Roach", genre: "Jazz", year: 1960, album: "We Insist!" },
  { id: 4678, rank: 178, title: "Clifford Brown and Max Roach - Daahoud", artist: "Max Roach", genre: "Jazz", year: 1954, album: "Clifford Brown and Max Roach" },
  { id: 4679, rank: 179, title: "The Max Roach Trio - Two Bass Hit", artist: "Max Roach", genre: "Jazz", year: 1956, album: "Jazz in 3/4 Time" },
  { id: 4680, rank: 180, title: "It's Time - It's Time", artist: "Max Roach", genre: "Jazz", year: 1962, album: "It's Time" },
  { id: 4681, rank: 181, title: "Un Poco Loco", artist: "Bud Powell", genre: "Jazz", year: 1951, album: "The Genius of Bud Powell" },
  { id: 4682, rank: 182, title: "Tempus Fugue-it", artist: "Bud Powell", genre: "Jazz", year: 1949, album: "The Genius of Bud Powell" },
  { id: 4683, rank: 183, title: "Hallucinations", artist: "Bud Powell", genre: "Jazz", year: 1949, album: "The Genius of Bud Powell" },
  { id: 4684, rank: 184, title: "Glass Enclosure", artist: "Bud Powell", genre: "Jazz", year: 1953, album: "The Amazing Bud Powell Vol. 3" },
  { id: 4685, rank: 185, title: "Celia", artist: "Bud Powell", genre: "Jazz", year: 1949, album: "The Genius of Bud Powell" },
  { id: 4686, rank: 186, title: "Ain't Misbehavin'", artist: "Fats Waller", genre: "Jazz", year: 1929, album: "The Joint Is Jumpin'" },
  { id: 4687, rank: 187, title: "Honeysuckle Rose", artist: "Fats Waller", genre: "Jazz", year: 1928, album: "The Joint Is Jumpin'" },
  { id: 4688, rank: 188, title: "Squeeze Me", artist: "Fats Waller", genre: "Jazz", year: 1925, album: "The Joint Is Jumpin'" },
  { id: 4689, rank: 189, title: "I'm Gonna Sit Right Down and Write Myself a Letter", artist: "Fats Waller", genre: "Jazz", year: 1935, album: "The Joint Is Jumpin'" },
  { id: 4690, rank: 190, title: "Jitterbug Waltz", artist: "Fats Waller", genre: "Jazz", year: 1942, album: "The Joint Is Jumpin'" },
  { id: 4691, rank: 191, title: "One O'Clock Jump", artist: "Count Basie", genre: "Jazz", year: 1937, album: "The Definitive Count Basie" },
  { id: 4692, rank: 192, title: "April in Paris", artist: "Count Basie", genre: "Jazz", year: 1955, album: "April in Paris" },
  { id: 4693, rank: 193, title: "Swingin' the Blues", artist: "Count Basie", genre: "Jazz", year: 1938, album: "The Definitive Count Basie" },
  { id: 4694, rank: 194, title: "Jumpin' at the Woodside", artist: "Count Basie", genre: "Jazz", year: 1938, album: "The Definitive Count Basie" },
  { id: 4695, rank: 195, title: "Lester Leaps In", artist: "Count Basie", genre: "Jazz", year: 1939, album: "The Definitive Count Basie" },
  { id: 4696, rank: 196, title: "Shiny Stockings", artist: "Count Basie", genre: "Jazz", year: 1956, album: "April in Paris" },
  { id: 4697, rank: 197, title: "Sing, Sing, Sing", artist: "Benny Goodman", genre: "Jazz", year: 1937, album: "Carnegie Hall Jazz Concert" },
  { id: 4698, rank: 198, title: "King Porter Stomp", artist: "Benny Goodman", genre: "Jazz", year: 1935, album: "The Complete RCA Victor Small Group Recordings" },
  { id: 4699, rank: 199, title: "Let's Dance", artist: "Benny Goodman", genre: "Jazz", year: 1935, album: "The Complete RCA Victor Small Group Recordings" },
  { id: 4700, rank: 200, title: "Don't Be That Way", artist: "Benny Goodman", genre: "Jazz", year: 1938, album: "Carnegie Hall Jazz Concert" },
  { id: 4701, rank: 201, title: "Stompin' at the Savoy", artist: "Benny Goodman", genre: "Jazz", year: 1936, album: "The Complete RCA Victor Small Group Recordings" },
  { id: 4702, rank: 202, title: "Moonglow", artist: "Benny Goodman", genre: "Jazz", year: 1936, album: "The Complete RCA Victor Small Group Recordings" },
  { id: 4703, rank: 203, title: "In the Mood", artist: "Glenn Miller", genre: "Jazz", year: 1939, album: "A Memorial" },
  { id: 4704, rank: 204, title: "Moonlight Serenade", artist: "Glenn Miller", genre: "Jazz", year: 1939, album: "A Memorial" },
  { id: 4705, rank: 205, title: "Chattanooga Choo Choo", artist: "Glenn Miller", genre: "Jazz", year: 1941, album: "A Memorial" },
  { id: 4706, rank: 206, title: "Pennsylvania 6-5000", artist: "Glenn Miller", genre: "Jazz", year: 1940, album: "A Memorial" },
  { id: 4707, rank: 207, title: "String of Pearls", artist: "Glenn Miller", genre: "Jazz", year: 1941, album: "A Memorial" },
  { id: 4708, rank: 208, title: "Little Brown Jug", artist: "Glenn Miller", genre: "Jazz", year: 1939, album: "A Memorial" },
  { id: 4709, rank: 209, title: "Tuxedo Junction", artist: "Glenn Miller", genre: "Jazz", year: 1940, album: "A Memorial" },
  { id: 4710, rank: 210, title: "The Girl from Ipanema", artist: "Stan Getz", genre: "Jazz", year: 1964, album: "Getz/Gilberto" },
  { id: 4711, rank: 211, title: "Corcovado (Quiet Nights of Quiet Stars)", artist: "Stan Getz", genre: "Jazz", year: 1964, album: "Getz/Gilberto" },
  { id: 4712, rank: 212, title: "Desafinado", artist: "Stan Getz", genre: "Jazz", year: 1962, album: "Jazz Samba" },
  { id: 4713, rank: 213, title: "Early Autumn", artist: "Stan Getz", genre: "Jazz", year: 1948, album: "Early Stan Getz" },
  { id: 4714, rank: 214, title: "Stan Getz & J.J. Johnson - Yesterdays", artist: "Stan Getz", genre: "Jazz", year: 1957, album: "Stan Getz & J.J. Johnson at the Opera House" },
  { id: 4715, rank: 215, title: "Autumn Leaves", artist: "Stan Getz", genre: "Jazz", year: 1962, album: "Focus" },
  { id: 4716, rank: 216, title: "Walking Shoes", artist: "Gerry Mulligan", genre: "Jazz", year: 1952, album: "The Gerry Mulligan Quartet" },
  { id: 4717, rank: 217, title: "Bernie's Tune", artist: "Gerry Mulligan", genre: "Jazz", year: 1952, album: "The Gerry Mulligan Quartet" },
  { id: 4718, rank: 218, title: "Jeru", artist: "Gerry Mulligan", genre: "Jazz", year: 1952, album: "The Gerry Mulligan Quartet" },
  { id: 4719, rank: 219, title: "Night Lights - Night Lights", artist: "Gerry Mulligan", genre: "Jazz", year: 1963, album: "Night Lights" },
  { id: 4720, rank: 220, title: "Take Five", artist: "Paul Desmond", genre: "Jazz", year: 1959, album: "Time Out" },
  { id: 4721, rank: 221, title: "Embarcadero", artist: "Paul Desmond", genre: "Jazz", year: 1959, album: "Two of a Mind" },
  { id: 4722, rank: 222, title: "Late Lament", artist: "Paul Desmond", genre: "Jazz", year: 1961, album: "Desmond Blue" },
  { id: 4723, rank: 223, title: "Glad to Be Unhappy", artist: "Paul Desmond", genre: "Jazz", year: 1963, album: "Desmond Blue" },
  { id: 4724, rank: 224, title: "The Sidewinder - The Sidewinder", artist: "Lee Morgan", genre: "Jazz", year: 1964, album: "The Sidewinder" },
  { id: 4725, rank: 225, title: "Tom Cat - Tom Cat", artist: "Lee Morgan", genre: "Jazz", year: 1964, album: "Tom Cat" },
  { id: 4726, rank: 226, title: "Cornbread - Ceora", artist: "Lee Morgan", genre: "Jazz", year: 1965, album: "Cornbread" },
  { id: 4727, rank: 227, title: "Search for the New Land - Search for the New Land", artist: "Lee Morgan", genre: "Jazz", year: 1966, album: "Search for the New Land" },
  { id: 4728, rank: 228, title: "The Gigolo - Gary's Notebook", artist: "Lee Morgan", genre: "Jazz", year: 1965, album: "The Gigolo" },
  { id: 4729, rank: 229, title: "Red Clay - Red Clay", artist: "Freddie Hubbard", genre: "Jazz", year: 1970, album: "Red Clay" },
  { id: 4730, rank: 230, title: "Straight Life - Straight Life", artist: "Freddie Hubbard", genre: "Jazz", year: 1970, album: "Straight Life" },
  { id: 4731, rank: 231, title: "Hub-Tones - Hub-Tones", artist: "Freddie Hubbard", genre: "Jazz", year: 1962, album: "Hub-Tones" },
  { id: 4732, rank: 232, title: "First Light - First Light", artist: "Freddie Hubbard", genre: "Jazz", year: 1971, album: "First Light" },
  { id: 4733, rank: 233, title: "The Shape of Jazz to Come - Lonely Woman", artist: "Ornette Coleman", genre: "Jazz", year: 1959, album: "The Shape of Jazz to Come" },
  { id: 4734, rank: 234, title: "The Shape of Jazz to Come - Peace", artist: "Ornette Coleman", genre: "Jazz", year: 1959, album: "The Shape of Jazz to Come" },
  { id: 4735, rank: 235, title: "Free Jazz - Free Jazz", artist: "Ornette Coleman", genre: "Jazz", year: 1961, album: "Free Jazz" },
  { id: 4736, rank: 236, title: "Sound Grammar - Sound Grammar", artist: "Ornette Coleman", genre: "Jazz", year: 2006, album: "Sound Grammar" },
  { id: 4737, rank: 237, title: "The Empty Foxhole", artist: "Ornette Coleman", genre: "Jazz", year: 1966, album: "The Empty Foxhole" },
  { id: 4738, rank: 238, title: "Out to Lunch - Hat and Beard", artist: "Eric Dolphy", genre: "Jazz", year: 1964, album: "Out to Lunch!" },
  { id: 4739, rank: 239, title: "Out to Lunch - Something Sweet, Something Tender", artist: "Eric Dolphy", genre: "Jazz", year: 1964, album: "Out to Lunch!" },
  { id: 4740, rank: 240, title: "Out to Lunch - Gazzelloni", artist: "Eric Dolphy", genre: "Jazz", year: 1964, album: "Out to Lunch!" },
  { id: 4741, rank: 241, title: "Far Cry - Miss Ann", artist: "Eric Dolphy", genre: "Jazz", year: 1960, album: "Far Cry" },
  { id: 4742, rank: 242, title: "Mingus Ah Um - Goodbye Pork Pie Hat", artist: "Charles Mingus", genre: "Jazz", year: 1959, album: "Mingus Ah Um" },
  { id: 4743, rank: 243, title: "Mingus Ah Um - Better Git It in Your Soul", artist: "Charles Mingus", genre: "Jazz", year: 1959, album: "Mingus Ah Um" },
  { id: 4744, rank: 244, title: "Mingus Ah Um - Boogie Stop Shuffle", artist: "Charles Mingus", genre: "Jazz", year: 1959, album: "Mingus Ah Um" },
  { id: 4745, rank: 245, title: "The Black Saint and the Sinner Lady - Mode D, E, F", artist: "Charles Mingus", genre: "Jazz", year: 1963, album: "The Black Saint and the Sinner Lady" },
  { id: 4746, rank: 246, title: "Pithecanthropus Erectus - Pithecanthropus Erectus", artist: "Charles Mingus", genre: "Jazz", year: 1956, album: "Pithecanthropus Erectus" },
  { id: 4747, rank: 247, title: "Haitian Fight Song", artist: "Charles Mingus", genre: "Jazz", year: 1957, album: "The Clown" },
  { id: 4748, rank: 248, title: "Eat That Chicken", artist: "Charles Mingus", genre: "Jazz", year: 1961, album: "Oh Yeah" },
  { id: 4749, rank: 249, title: "Heavy Sounds - Heavy Sounds", artist: "Elvin Jones", genre: "Jazz", year: 1967, album: "Heavy Sounds" },
  { id: 4750, rank: 250, title: "Puttin' It Together - Puttin' It Together", artist: "Elvin Jones", genre: "Jazz", year: 1968, album: "Puttin' It Together" },
  { id: 4751, rank: 251, title: "Coalition - Coalition", artist: "Elvin Jones", genre: "Jazz", year: 1970, album: "Coalition" },
  { id: 4752, rank: 252, title: "Emergency! - Emergency", artist: "Tony Williams", genre: "Jazz", year: 1969, album: "Emergency!" },
  { id: 4753, rank: 253, title: "Ego - Ego", artist: "Tony Williams", genre: "Jazz", year: 1971, album: "Ego" },
  { id: 4754, rank: 254, title: "Spring - Spring", artist: "Tony Williams", genre: "Jazz", year: 1965, album: "Spring" },
  { id: 4755, rank: 255, title: "Special Edition - Zoot Suite", artist: "Jack DeJohnette", genre: "Jazz", year: 1980, album: "Special Edition" },
  { id: 4756, rank: 256, title: "New Directions - New Directions", artist: "Jack DeJohnette", genre: "Jazz", year: 1979, album: "New Directions" },
  { id: 4757, rank: 257, title: "Album Album - Monk's Mood", artist: "Jack DeJohnette", genre: "Jazz", year: 1984, album: "Album Album" },
  { id: 4758, rank: 258, title: "The Köln Concert - Part I", artist: "Keith Jarrett", genre: "Jazz", year: 1975, album: "The Köln Concert" },
  { id: 4759, rank: 259, title: "The Köln Concert - Part IIa", artist: "Keith Jarrett", genre: "Jazz", year: 1975, album: "The Köln Concert" },
  { id: 4760, rank: 260, title: "The Köln Concert - Part IIb", artist: "Keith Jarrett", genre: "Jazz", year: 1975, album: "The Köln Concert" },
  { id: 4761, rank: 261, title: "Belonging - Belonging", artist: "Keith Jarrett", genre: "Jazz", year: 1974, album: "Belonging" },
  { id: 4762, rank: 262, title: "The Melody at Night, with You - My Wild Irish Rose", artist: "Keith Jarrett", genre: "Jazz", year: 1999, album: "The Melody at Night, with You" },
  { id: 4763, rank: 263, title: "Standards, Vol. 1 - All the Things You Are", artist: "Keith Jarrett", genre: "Jazz", year: 1983, album: "Standards, Vol. 1" },
  { id: 4764, rank: 264, title: "Facing You - Lalene", artist: "Keith Jarrett", genre: "Jazz", year: 1972, album: "Facing You" },
  { id: 4765, rank: 265, title: "Sun Bear Concerts - Part I", artist: "Keith Jarrett", genre: "Jazz", year: 1976, album: "Sun Bear Concerts" },
  { id: 4766, rank: 266, title: "Night Train - Night Train", artist: "Oscar Peterson", genre: "Jazz", year: 1963, album: "Night Train" },
  { id: 4767, rank: 267, title: "Night Train - Bags' Groove", artist: "Oscar Peterson", genre: "Jazz", year: 1963, album: "Night Train" },
  { id: 4768, rank: 268, title: "Tenderly", artist: "Oscar Peterson", genre: "Jazz", year: 1962, album: "West Side Story" },
  { id: 4769, rank: 269, title: "Hymn to Freedom", artist: "Oscar Peterson", genre: "Jazz", year: 1963, album: "Night Train" },
  { id: 4770, rank: 270, title: "Oscar Peterson Trio - C Jam Blues", artist: "Oscar Peterson", genre: "Jazz", year: 1963, album: "Night Train" },
  { id: 4771, rank: 271, title: "Place Saint-Henri", artist: "Oscar Peterson", genre: "Jazz", year: 1958, album: "The Oscar Peterson Trio at the Stratford Shakespearean Festival" },
  { id: 4772, rank: 272, title: "Poinciana", artist: "Ahmad Jamal", genre: "Jazz", year: 1958, album: "Ahmad Jamal at the Pershing" },
  { id: 4773, rank: 273, title: "But Not for Me", artist: "Ahmad Jamal", genre: "Jazz", year: 1958, album: "Ahmad Jamal at the Pershing" },
  { id: 4774, rank: 274, title: "Music! Music! Music! - Music! Music! Music!", artist: "Ahmad Jamal", genre: "Jazz", year: 1958, album: "Ahmad Jamal at the Pershing" },
  { id: 4775, rank: 275, title: "Pavanne", artist: "Ahmad Jamal", genre: "Jazz", year: 1955, album: "Chamber Music of the New Jazz" },
  { id: 4776, rank: 276, title: "Misty", artist: "Erroll Garner", genre: "Jazz", year: 1954, album: "Contrasts" },
  { id: 4777, rank: 277, title: "Dreamy - Dreamy", artist: "Erroll Garner", genre: "Jazz", year: 1961, album: "Dreamstreet" },
  { id: 4778, rank: 278, title: "Play Piano Play - Play Piano Play", artist: "Erroll Garner", genre: "Jazz", year: 1968, album: "Campus Concert" },
  { id: 4779, rank: 279, title: "Concert by the Sea - I'll Remember April", artist: "Erroll Garner", genre: "Jazz", year: 1955, album: "Concert by the Sea" },
  { id: 4780, rank: 280, title: "Lullaby of Birdland", artist: "George Shearing", genre: "Jazz", year: 1952, album: "George Shearing and His Quintet" },
  { id: 4781, rank: 281, title: "Conception", artist: "George Shearing", genre: "Jazz", year: 1952, album: "Shearing on Stage!" },
  { id: 4782, rank: 282, title: "Pick Yourself Up", artist: "George Shearing", genre: "Jazz", year: 1956, album: "Satin Brass" },
  { id: 4783, rank: 283, title: "The In Crowd", artist: "Ramsey Lewis", genre: "Jazz", year: 1965, album: "The In Crowd" },
  { id: 4784, rank: 284, title: "Hang On Sloopy", artist: "Ramsey Lewis", genre: "Jazz", year: 1965, album: "The In Crowd" },
  { id: 4785, rank: 285, title: "Wade in the Water", artist: "Ramsey Lewis", genre: "Jazz", year: 1966, album: "Wade in the Water" },
  { id: 4786, rank: 286, title: "Come Away with Me", artist: "Norah Jones", genre: "Jazz", year: 2002, album: "Come Away with Me" },
  { id: 4787, rank: 287, title: "Don't Know Why", artist: "Norah Jones", genre: "Jazz", year: 2002, album: "Come Away with Me" },
  { id: 4788, rank: 288, title: "Feels Like Home - Sunrise", artist: "Norah Jones", genre: "Jazz", year: 2004, album: "Feels Like Home" },
  { id: 4789, rank: 289, title: "Turn Me On", artist: "Norah Jones", genre: "Jazz", year: 2002, album: "Come Away with Me" },
  { id: 4790, rank: 290, title: "The Look of Love", artist: "Diana Krall", genre: "Jazz", year: 2001, album: "The Look of Love" },
  { id: 4791, rank: 291, title: "Fly Me to the Moon", artist: "Diana Krall", genre: "Jazz", year: 1995, album: "Only Trust Your Heart" },
  { id: 4792, rank: 292, title: "Love Scenes - Peel Me a Grape", artist: "Diana Krall", genre: "Jazz", year: 1997, album: "Love Scenes" },
  { id: 4793, rank: 293, title: "When I Look in Your Eyes - I Can't Give You Anything But Love", artist: "Diana Krall", genre: "Jazz", year: 1999, album: "When I Look in Your Eyes" },
  { id: 4794, rank: 294, title: "Autumn Leaves", artist: "Miles Davis", genre: "Jazz", year: 1958, album: "Cannonball Adderley Quintet in Chicago" },
  { id: 4795, rank: 295, title: "All the Things You Are", artist: "Charlie Parker", genre: "Jazz", year: 1947, album: "Bird: The Complete Charlie Parker on Verve" },
  { id: 4796, rank: 296, title: "Body and Soul", artist: "Coleman Hawkins", genre: "Jazz", year: 1939, album: "Body and Soul" },
  { id: 4797, rank: 297, title: "Star Dust", artist: "Coleman Hawkins", genre: "Jazz", year: 1940, album: "Hawk in Germany" },
  { id: 4798, rank: 298, title: "Blue Skies", artist: "Benny Goodman", genre: "Jazz", year: 1935, album: "The Complete RCA Victor Small Group Recordings" },
  { id: 4799, rank: 299, title: "How High the Moon", artist: "Charlie Parker", genre: "Jazz", year: 1946, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4800, rank: 300, title: "Sweet Georgia Brown", artist: "Benny Goodman", genre: "Jazz", year: 1936, album: "Carnegie Hall Jazz Concert" },
  { id: 4801, rank: 301, title: "I Got Rhythm", artist: "Charlie Parker", genre: "Jazz", year: 1950, album: "Bird: The Complete Charlie Parker on Verve" },
  { id: 4802, rank: 302, title: "Summertime", artist: "Miles Davis", genre: "Jazz", year: 1958, album: "Porgy and Bess" },
  { id: 4803, rank: 303, title: "Cherokee", artist: "Charlie Parker", genre: "Jazz", year: 1942, album: "Early Bird" },
  { id: 4804, rank: 304, title: "What Is This Thing Called Love", artist: "Bud Powell", genre: "Jazz", year: 1950, album: "The Amazing Bud Powell Vol. 1" },
  { id: 4805, rank: 305, title: "There Will Never Be Another You", artist: "Miles Davis", genre: "Jazz", year: 1953, album: "Miles Davis with Sonny Rollins" },
  { id: 4806, rank: 306, title: "Have You Met Miss Jones?", artist: "Thelonious Monk", genre: "Jazz", year: 1956, album: "Brilliant Corners" },
  { id: 4807, rank: 307, title: "Just Friends", artist: "Charlie Parker", genre: "Jazz", year: 1949, album: "Bird: The Complete Charlie Parker on Verve" },
  { id: 4808, rank: 308, title: "Night and Day", artist: "Art Tatum", genre: "Jazz", year: 1933, album: "The Art Tatum Solo Masterpieces" },
  { id: 4809, rank: 309, title: "Begin the Beguine", artist: "Art Tatum", genre: "Jazz", year: 1944, album: "The Art Tatum Solo Masterpieces" },
  { id: 4810, rank: 310, title: "Tea for Two", artist: "Art Tatum", genre: "Jazz", year: 1933, album: "The Art Tatum Solo Masterpieces" },
  { id: 4811, rank: 311, title: "Tiger Rag", artist: "Art Tatum", genre: "Jazz", year: 1933, album: "The Art Tatum Solo Masterpieces" },
  { id: 4812, rank: 312, title: "Over the Rainbow", artist: "Art Tatum", genre: "Jazz", year: 1954, album: "The Art Tatum Solo Masterpieces" },
  { id: 4813, rank: 313, title: "The Man I Love", artist: "Billie Holiday", genre: "Jazz", year: 1935, album: "The Quintessential Billie Holiday" },
  { id: 4814, rank: 314, title: "Strange Fruit", artist: "Billie Holiday", genre: "Jazz", year: 1939, album: "The Quintessential Billie Holiday" },
  { id: 4815, rank: 315, title: "God Bless the Child", artist: "Billie Holiday", genre: "Jazz", year: 1941, album: "The Quintessential Billie Holiday" },
  { id: 4816, rank: 316, title: "Lover Man", artist: "Billie Holiday", genre: "Jazz", year: 1944, album: "The Quintessential Billie Holiday" },
  { id: 4817, rank: 317, title: "I'll Be Seeing You", artist: "Billie Holiday", genre: "Jazz", year: 1944, album: "The Quintessential Billie Holiday" },
  { id: 4818, rank: 318, title: "Round Midnight", artist: "Billie Holiday", genre: "Jazz", year: 1957, album: "Songs for Distingue Lovers" },
  { id: 4819, rank: 319, title: "How Deep Is the Ocean?", artist: "Billie Holiday", genre: "Jazz", year: 1952, album: "Billie Holiday at Jazz at the Philharmonic" },
  { id: 4820, rank: 320, title: "East of the Sun", artist: "Lester Young", genre: "Jazz", year: 1945, album: "Prez at His Very Best" },
  { id: 4821, rank: 321, title: "These Foolish Things", artist: "Lester Young", genre: "Jazz", year: 1945, album: "Prez at His Very Best" },
  { id: 4822, rank: 322, title: "D.B. Blues", artist: "Lester Young", genre: "Jazz", year: 1945, album: "Prez at His Very Best" },
  { id: 4823, rank: 323, title: "Lady Be Good", artist: "Lester Young", genre: "Jazz", year: 1936, album: "Prez at His Very Best" },
  { id: 4824, rank: 324, title: "Shoe Shine Boy", artist: "Lester Young", genre: "Jazz", year: 1936, album: "Prez at His Very Best" },
  { id: 4825, rank: 325, title: "Laura", artist: "Charlie Parker", genre: "Jazz", year: 1948, album: "The Complete Savoy & Dial Studio Recordings" },
  { id: 4826, rank: 326, title: "Out of Nowhere", artist: "Clifford Brown", genre: "Jazz", year: 1956, album: "At Basin Street" },
  { id: 4827, rank: 327, title: "I Remember Clifford", artist: "Benny Golson", genre: "Jazz", year: 1956, album: "Philadelphia Roots" },
  { id: 4828, rank: 328, title: "Whisper Not", artist: "Benny Golson", genre: "Jazz", year: 1958, album: "The Other Side of Benny Golson" },
  { id: 4829, rank: 329, title: "Killer Joe", artist: "Benny Golson", genre: "Jazz", year: 1959, album: "At the Jazz Workshop" },
  { id: 4830, rank: 330, title: "Blues on the Corner", artist: "McCoy Tyner", genre: "Jazz", year: 1963, album: "Reaching Fourth" },
  { id: 4831, rank: 331, title: "Inception", artist: "McCoy Tyner", genre: "Jazz", year: 1962, album: "Inception" },
  { id: 4832, rank: 332, title: "Sun Song", artist: "Sun Ra", genre: "Jazz", year: 1956, album: "Sun Song" },
  { id: 4833, rank: 333, title: "Interstellar Low Ways", artist: "Sun Ra", genre: "Jazz", year: 1965, album: "The Heliocentric Worlds of Sun Ra Vol. 1" },
  { id: 4834, rank: 334, title: "Night Walk", artist: "John Lewis", genre: "Jazz", year: 1955, album: "Django" },
  { id: 4835, rank: 335, title: "Django", artist: "John Lewis", genre: "Jazz", year: 1955, album: "Django" },
  { id: 4836, rank: 336, title: "Skating in Central Park", artist: "John Lewis", genre: "Jazz", year: 1960, album: "The Comedy" },
  { id: 4837, rank: 337, title: "Lonely Woman", artist: "Modern Jazz Quartet", genre: "Jazz", year: 1962, album: "Lonely Woman" },
  { id: 4838, rank: 338, title: "Blue Rondo à la Turk", artist: "Modern Jazz Quartet", genre: "Jazz", year: 1960, album: "Fontessa" },
  { id: 4839, rank: 339, title: "Moanin'", artist: "Modern Jazz Quartet", genre: "Jazz", year: 1960, album: "Fontessa" },
  { id: 4840, rank: 340, title: "The Sidewinder", artist: "Lee Morgan", genre: "Jazz", year: 1964, album: "The Sidewinder" },
  { id: 4841, rank: 341, title: "Ceora", artist: "Lee Morgan", genre: "Jazz", year: 1965, album: "Cornbread" },
  { id: 4842, rank: 342, title: "Caramba", artist: "Lee Morgan", genre: "Jazz", year: 1968, album: "The Rajah" },
  { id: 4843, rank: 343, title: "Locomotion", artist: "John Coltrane", genre: "Jazz", year: 1957, album: "Blue Train" },
  { id: 4844, rank: 344, title: "I Want to Talk About You", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Live at Birdland" },
  { id: 4845, rank: 345, title: "Afro Blue", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Live at Birdland" },
  { id: 4846, rank: 346, title: "Dear Lord", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "Transition" },
  { id: 4847, rank: 347, title: "Welcome", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "Transition" },
  { id: 4848, rank: 348, title: "Acknowledgement", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "A Love Supreme" },
  { id: 4849, rank: 349, title: "Interplay - Interplay", artist: "Bill Evans", genre: "Jazz", year: 1963, album: "Interplay" },
  { id: 4850, rank: 350, title: "The Solo Sessions - I Loves You Porgy", artist: "Bill Evans", genre: "Jazz", year: 1963, album: "Solo Sessions, Vol. 1" },
  { id: 4851, rank: 351, title: "We Will Meet Again - We Will Meet Again", artist: "Bill Evans", genre: "Jazz", year: 1979, album: "We Will Meet Again" },
  { id: 4852, rank: 352, title: "Letter to Evan", artist: "Bill Evans", genre: "Jazz", year: 1979, album: "We Will Meet Again" },
  { id: 4853, rank: 353, title: "Peri's Scope", artist: "Bill Evans", genre: "Jazz", year: 1959, album: "Portrait in Jazz" },
  { id: 4854, rank: 354, title: "Very Early", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Moonbeams" },
  { id: 4855, rank: 355, title: "Detour Ahead", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Moonbeams" },
  { id: 4856, rank: 356, title: "Elsa", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Moonbeams" },
  { id: 4857, rank: 357, title: "Explorations - Haunted Heart", artist: "Bill Evans", genre: "Jazz", year: 1961, album: "Explorations" },
  { id: 4858, rank: 358, title: "Israel", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4859, rank: 359, title: "Rocker", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4860, rank: 360, title: "Venus de Milo", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4861, rank: 361, title: "Deception", artist: "Miles Davis", genre: "Jazz", year: 1950, album: "Birth of the Cool" },
  { id: 4862, rank: 362, title: "Milestones - Milestones", artist: "Miles Davis", genre: "Jazz", year: 1958, album: "Milestones" },
  { id: 4863, rank: 363, title: "Two Bass Hit", artist: "Miles Davis", genre: "Jazz", year: 1958, album: "Milestones" },
  { id: 4864, rank: 364, title: "Compulsion", artist: "Miles Davis", genre: "Jazz", year: 1958, album: "Milestones" },
  { id: 4865, rank: 365, title: "Autumn Leaves", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Portrait in Jazz" },
  { id: 4866, rank: 366, title: "All About Rosie", artist: "George Russell", genre: "Jazz", year: 1957, album: "Jazz in the Space Age" },
  { id: 4867, rank: 367, title: "Ezz-thetic", artist: "George Russell", genre: "Jazz", year: 1961, album: "Ezz-thetics" },
  { id: 4868, rank: 368, title: "Concerto for Billy the Kid", artist: "George Russell", genre: "Jazz", year: 1956, album: "The Jazz Workshop" },
  { id: 4869, rank: 369, title: "Relaxin' - If I Were a Bell", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Relaxin'" },
  { id: 4870, rank: 370, title: "Relaxin' - You're My Everything", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Relaxin'" },
  { id: 4871, rank: 371, title: "Cookin' - My Funny Valentine", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Cookin'" },
  { id: 4872, rank: 372, title: "Steamin' - Surrey with the Fringe on Top", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Steamin'" },
  { id: 4873, rank: 373, title: "Workin' - It Never Entered My Mind", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Workin'" },
  { id: 4874, rank: 374, title: "Bags' Groove - Bags' Groove", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Bags' Groove" },
  { id: 4875, rank: 375, title: "Miles Davis and Milt Jackson - Bemsha Swing", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Bags' Groove" },
  { id: 4876, rank: 376, title: "The Theme", artist: "Miles Davis", genre: "Jazz", year: 1964, album: "Four & More" },
  { id: 4877, rank: 377, title: "Walkin'", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Walkin'" },
  { id: 4878, rank: 378, title: "Blue Haze", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Blue Haze" },
  { id: 4879, rank: 379, title: "Dig - Dig", artist: "Miles Davis", genre: "Jazz", year: 1951, album: "Dig" },
  { id: 4880, rank: 380, title: "The New Miles Davis Quintet - S.R.O.", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "The New Miles Davis Quintet" },
  { id: 4881, rank: 381, title: "Bye Bye Blackbird", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Round About Midnight" },
  { id: 4882, rank: 382, title: "Sweet Sue, Just You", artist: "Miles Davis", genre: "Jazz", year: 1956, album: "Round About Midnight" },
  { id: 4883, rank: 383, title: "Straight Ahead", artist: "Cannonball Adderley", genre: "Jazz", year: 1961, album: "Cannonball in Europe!" },
  { id: 4884, rank: 384, title: "This Here", artist: "Cannonball Adderley", genre: "Jazz", year: 1959, album: "Somethin' Else" },
  { id: 4885, rank: 385, title: "Autumn Leaves", artist: "Cannonball Adderley", genre: "Jazz", year: 1958, album: "Somethin' Else" },
  { id: 4886, rank: 386, title: "One for Daddy-O", artist: "Cannonball Adderley", genre: "Jazz", year: 1958, album: "Somethin' Else" },
  { id: 4887, rank: 387, title: "Sermonette", artist: "Cannonball Adderley", genre: "Jazz", year: 1955, album: "In the Land of Hi-Fi" },
  { id: 4888, rank: 388, title: "Bohemia After Dark", artist: "Cannonball Adderley", genre: "Jazz", year: 1955, album: "Bohemia After Dark" },
  { id: 4889, rank: 389, title: "Groovin' High - Donna Lee", artist: "Dizzy Gillespie", genre: "Jazz", year: 1945, album: "The Complete RCA Victor Recordings" },
  { id: 4890, rank: 390, title: "Birk's Works", artist: "Dizzy Gillespie", genre: "Jazz", year: 1951, album: "The Complete RCA Victor Recordings" },
  { id: 4891, rank: 391, title: "Blue 'n Boogie", artist: "Dizzy Gillespie", genre: "Jazz", year: 1945, album: "The Complete RCA Victor Recordings" },
  { id: 4892, rank: 392, title: "Things to Come", artist: "Dizzy Gillespie", genre: "Jazz", year: 1946, album: "The Complete RCA Victor Recordings" },
  { id: 4893, rank: 393, title: "Cubano Be, Cubano Bop", artist: "Dizzy Gillespie", genre: "Jazz", year: 1947, album: "The Complete RCA Victor Recordings" },
  { id: 4894, rank: 394, title: "Tin Tin Deo", artist: "Dizzy Gillespie", genre: "Jazz", year: 1947, album: "The Complete RCA Victor Recordings" },
  { id: 4895, rank: 395, title: "Hot House", artist: "Dizzy Gillespie", genre: "Jazz", year: 1945, album: "The Complete RCA Victor Recordings" },
  { id: 4896, rank: 396, title: "Lover Come Back to Me", artist: "Dizzy Gillespie", genre: "Jazz", year: 1947, album: "The Complete RCA Victor Recordings" },
  { id: 4897, rank: 397, title: "Good Bait", artist: "Count Basie", genre: "Jazz", year: 1944, album: "Good Bait" },
  { id: 4898, rank: 398, title: "Taps Miller", artist: "Count Basie", genre: "Jazz", year: 1947, album: "Good Bait" },
  { id: 4899, rank: 399, title: "Swinging at the Daisy Chain", artist: "Count Basie", genre: "Jazz", year: 1937, album: "The Definitive Count Basie" },
  { id: 4900, rank: 400, title: "Blue and Sentimental", artist: "Count Basie", genre: "Jazz", year: 1938, album: "The Definitive Count Basie" },
  { id: 4901, rank: 401, title: "Every Tub", artist: "Count Basie", genre: "Jazz", year: 1938, album: "The Definitive Count Basie" },
  { id: 4902, rank: 402, title: "Topsy", artist: "Count Basie", genre: "Jazz", year: 1937, album: "The Definitive Count Basie" },
  { id: 4903, rank: 403, title: "Straight Life", artist: "Freddie Hubbard", genre: "Jazz", year: 1970, album: "Straight Life" },
  { id: 4904, rank: 404, title: "Sky Dive", artist: "Freddie Hubbard", genre: "Jazz", year: 1972, album: "Sky Dive" },
  { id: 4905, rank: 405, title: "Birdlike", artist: "Freddie Hubbard", genre: "Jazz", year: 1960, album: "Open Sesame" },
  { id: 4906, rank: 406, title: "Gingerbread Boy", artist: "Freddie Hubbard", genre: "Jazz", year: 1966, album: "Backlash" },
  { id: 4907, rank: 407, title: "Little Sunflower", artist: "Freddie Hubbard", genre: "Jazz", year: 1966, album: "Backlash" },
  { id: 4908, rank: 408, title: "Mr. Clean", artist: "Freddie Hubbard", genre: "Jazz", year: 1963, album: "Hub-Tones" },
  { id: 4909, rank: 409, title: "Up Jumped Spring", artist: "Freddie Hubbard", genre: "Jazz", year: 1965, album: "The Night of the Cookers" },
  { id: 4910, rank: 410, title: "Prophet Jennings", artist: "Woody Shaw", genre: "Jazz", year: 1965, album: "The Moontrane" },
  { id: 4911, rank: 411, title: "The Moontrane", artist: "Woody Shaw", genre: "Jazz", year: 1974, album: "The Moontrane" },
  { id: 4912, rank: 412, title: "Blackstone Legacy", artist: "Woody Shaw", genre: "Jazz", year: 1970, album: "Blackstone Legacy" },
  { id: 4913, rank: 413, title: "In the Land of the Blacks", artist: "Woody Shaw", genre: "Jazz", year: 1975, album: "Little Red's Fantasy" },
  { id: 4914, rank: 414, title: "Theme for Maxine", artist: "Woody Shaw", genre: "Jazz", year: 1975, album: "Little Red's Fantasy" },
  { id: 4915, rank: 415, title: "Duet", artist: "Bill Evans", genre: "Jazz", year: 1974, album: "Alone (Again)" },
  { id: 4916, rank: 416, title: "Never Let Me Go", artist: "Bill Evans", genre: "Jazz", year: 1977, album: "Crosscurrents" },
  { id: 4917, rank: 417, title: "Days of Wine and Roses", artist: "Bill Evans", genre: "Jazz", year: 1964, album: "In Concert: The Bill Evans Trio" },
  { id: 4918, rank: 418, title: "Here's That Rainy Day", artist: "Bill Evans", genre: "Jazz", year: 1968, album: "Bill Evans at Town Hall" },
  { id: 4919, rank: 419, title: "My Romance", artist: "Bill Evans", genre: "Jazz", year: 1978, album: "The Paris Concert, Edition One" },
  { id: 4920, rank: 420, title: "On a Clear Day You Can See Forever", artist: "Bill Evans", genre: "Jazz", year: 1968, album: "California Here I Come" },
  { id: 4921, rank: 421, title: "I Concentrate on You", artist: "Bill Evans", genre: "Jazz", year: 1962, album: "Moon Beams" },
  { id: 4922, rank: 422, title: "Someday My Prince Will Come", artist: "Miles Davis", genre: "Jazz", year: 1961, album: "Someday My Prince Will Come" },
  { id: 4923, rank: 423, title: "Pfrancing (No Blues)", artist: "Miles Davis", genre: "Jazz", year: 1961, album: "Someday My Prince Will Come" },
  { id: 4924, rank: 424, title: "Old Devil Moon", artist: "Miles Davis", genre: "Jazz", year: 1961, album: "Someday My Prince Will Come" },
  { id: 4925, rank: 425, title: "Neo", artist: "Miles Davis", genre: "Jazz", year: 1952, album: "Blue Period" },
  { id: 4926, rank: 426, title: "When Lights Are Low", artist: "Miles Davis", genre: "Jazz", year: 1952, album: "Blue Period" },
  { id: 4927, rank: 427, title: "Airegin", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Bags' Groove" },
  { id: 4928, rank: 428, title: "Oleo", artist: "Miles Davis", genre: "Jazz", year: 1954, album: "Bags' Groove" },
  { id: 4929, rank: 429, title: "Doxy", artist: "Sonny Rollins", genre: "Jazz", year: 1954, album: "Bags' Groove" },
  { id: 4930, rank: 430, title: "Pent-Up House", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Sonny Rollins Plus 4" },
  { id: 4931, rank: 431, title: "Valse Hot", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Sonny Rollins Plus 4" },
  { id: 4932, rank: 432, title: "Tenor Madness", artist: "Sonny Rollins", genre: "Jazz", year: 1956, album: "Tenor Madness" },
  { id: 4933, rank: 433, title: "Newk's Fadeaway", artist: "Sonny Rollins", genre: "Jazz", year: 1957, album: "Way Out West" },
  { id: 4934, rank: 434, title: "Wagon Wheels", artist: "Sonny Rollins", genre: "Jazz", year: 1957, album: "Way Out West" },
  { id: 4935, rank: 435, title: "Way Out West - I'm an Old Cowhand", artist: "Sonny Rollins", genre: "Jazz", year: 1957, album: "Way Out West" },
  { id: 4936, rank: 436, title: "Freedom Suite - Freedom Suite", artist: "Sonny Rollins", genre: "Jazz", year: 1958, album: "Freedom Suite" },
  { id: 4937, rank: 437, title: "Autumn Nocturne", artist: "Sonny Rollins", genre: "Jazz", year: 1965, album: "Now's the Time" },
  { id: 4938, rank: 438, title: "Love Letters", artist: "Sonny Rollins", genre: "Jazz", year: 1966, album: "Alfie" },
  { id: 4939, rank: 439, title: "Round Midnight", artist: "Wes Montgomery", genre: "Jazz", year: 1965, album: "Smokin' at the Half Note" },
  { id: 4940, rank: 440, title: "One for My Baby", artist: "Wes Montgomery", genre: "Jazz", year: 1965, album: "Smokin' at the Half Note" },
  { id: 4941, rank: 441, title: "No Blues", artist: "Wes Montgomery", genre: "Jazz", year: 1965, album: "Smokin' at the Half Note" },
  { id: 4942, rank: 442, title: "D-Natural Blues", artist: "Wes Montgomery", genre: "Jazz", year: 1960, album: "The Incredible Jazz Guitar of Wes Montgomery" },
  { id: 4943, rank: 443, title: "In Your Own Sweet Way", artist: "Wes Montgomery", genre: "Jazz", year: 1960, album: "The Incredible Jazz Guitar of Wes Montgomery" },
  { id: 4944, rank: 444, title: "Missile Blues", artist: "Wes Montgomery", genre: "Jazz", year: 1961, album: "So Much Guitar!" },
  { id: 4945, rank: 445, title: "OGD (Round Midnight)", artist: "Wes Montgomery", genre: "Jazz", year: 1965, album: "Smokin' at the Half Note" },
  { id: 4946, rank: 446, title: "A Day in the Life", artist: "Wes Montgomery", genre: "Jazz", year: 1967, album: "A Day in the Life" },
  { id: 4947, rank: 447, title: "Going Out of My Head", artist: "Wes Montgomery", genre: "Jazz", year: 1966, album: "California Dreamin'" },
  { id: 4948, rank: 448, title: "In a Sentimental Mood", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Duke Ellington and John Coltrane" },
  { id: 4949, rank: 449, title: "Big Nick", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Duke Ellington and John Coltrane" },
  { id: 4950, rank: 450, title: "Alabama", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Live at Birdland" },
  { id: 4951, rank: 451, title: "The Night Has a Thousand Eyes", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Live at Birdland" },
  { id: 4952, rank: 452, title: "Wise One", artist: "John Coltrane", genre: "Jazz", year: 1964, album: "Crescent" },
  { id: 4953, rank: 453, title: "Lonnie's Lament", artist: "John Coltrane", genre: "Jazz", year: 1964, album: "Crescent" },
  { id: 4954, rank: 454, title: "The Drum Thing", artist: "John Coltrane", genre: "Jazz", year: 1964, album: "Crescent" },
  { id: 4955, rank: 455, title: "Song of Praise", artist: "John Coltrane", genre: "Jazz", year: 1966, album: "Meditations" },
  { id: 4956, rank: 456, title: "Sun Ship", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "Sun Ship" },
  { id: 4957, rank: 457, title: "Dearly Beloved", artist: "John Coltrane", genre: "Jazz", year: 1965, album: "Sun Ship" },
  { id: 4958, rank: 458, title: "Miles' Mode", artist: "John Coltrane", genre: "Jazz", year: 1963, album: "Coltrane" },
  { id: 4959, rank: 459, title: "Tunji", artist: "John Coltrane", genre: "Jazz", year: 1962, album: "Coltrane" },
  { id: 4960, rank: 460, title: "Out of This World", artist: "John Coltrane", genre: "Jazz", year: 1962, album: "Coltrane" },
  { id: 4961, rank: 461, title: "Mr. P.C.", artist: "John Coltrane", genre: "Jazz", year: 1960, album: "Giant Steps" },
  { id: 4962, rank: 462, title: "Countdown", artist: "John Coltrane", genre: "Jazz", year: 1960, album: "Giant Steps" },
  { id: 4963, rank: 463, title: "Spiritual", artist: "John Coltrane", genre: "Jazz", year: 1961, album: "Live at the Village Vanguard" },
  { id: 4964, rank: 464, title: "Chasin' the Trane", artist: "John Coltrane", genre: "Jazz", year: 1961, album: "Live at the Village Vanguard" },
  { id: 4965, rank: 465, title: "Birdland", artist: "Weather Report", genre: "Jazz", year: 1977, album: "Heavy Weather" },
  { id: 4966, rank: 466, title: "Teen Town", artist: "Weather Report", genre: "Jazz", year: 1977, album: "Heavy Weather" },
  { id: 4967, rank: 467, title: "A Remark You Made", artist: "Weather Report", genre: "Jazz", year: 1977, album: "Heavy Weather" },
  { id: 4968, rank: 468, title: "Boogie Woogie Waltz", artist: "Weather Report", genre: "Jazz", year: 1973, album: "Sweetnighter" },
  { id: 4969, rank: 469, title: "Night Passage - Night Passage", artist: "Weather Report", genre: "Jazz", year: 1980, album: "Night Passage" },
  { id: 4970, rank: 470, title: "Spain", artist: "Return to Forever", genre: "Jazz", year: 1972, album: "Light as a Feather" },
  { id: 4971, rank: 471, title: "Medieval Overture", artist: "Return to Forever", genre: "Jazz", year: 1974, album: "Romantic Warrior" },
  { id: 4972, rank: 472, title: "After the Cosmic Rain", artist: "Return to Forever", genre: "Jazz", year: 1976, album: "The Leprechaun" },
  { id: 4973, rank: 473, title: "Vulcan Worlds", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1973, album: "Birds of Fire" },
  { id: 4974, rank: 474, title: "Birds of Fire", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1973, album: "Birds of Fire" },
  { id: 4975, rank: 475, title: "One Word", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1973, album: "Birds of Fire" },
  { id: 4976, rank: 476, title: "Meeting of the Spirits", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1971, album: "The Inner Mounting Flame" },
  { id: 4977, rank: 477, title: "Vital Transformation", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1971, album: "The Inner Mounting Flame" },
  { id: 4978, rank: 478, title: "You Know You Know", artist: "Mahavishnu Orchestra", genre: "Jazz", year: 1971, album: "The Inner Mounting Flame" },
  { id: 4979, rank: 479, title: "Bright Size Life", artist: "Pat Metheny", genre: "Jazz", year: 1976, album: "Bright Size Life" },
  { id: 4980, rank: 480, title: "Sirabhorn", artist: "Pat Metheny", genre: "Jazz", year: 1977, album: "Pat Metheny Group" },
  { id: 4981, rank: 481, title: "San Lorenzo", artist: "Pat Metheny", genre: "Jazz", year: 1980, album: "80/81" },
  { id: 4982, rank: 482, title: "James", artist: "Pat Metheny", genre: "Jazz", year: 1980, album: "80/81" },
  { id: 4983, rank: 483, title: "As Falls Wichita, So Falls Wichita Falls", artist: "Pat Metheny", genre: "Jazz", year: 1981, album: "As Falls Wichita, So Falls Wichita Falls" },
  { id: 4984, rank: 484, title: "Travels - Farmer's Trust", artist: "Pat Metheny", genre: "Jazz", year: 1983, album: "Travels" },
  { id: 4985, rank: 485, title: "First Circle", artist: "Pat Metheny", genre: "Jazz", year: 1984, album: "First Circle" },
  { id: 4986, rank: 486, title: "Last Train Home", artist: "Pat Metheny", genre: "Jazz", year: 1987, album: "Still Life (Talking)" },
  { id: 4987, rank: 487, title: "Have You Heard", artist: "Pat Metheny", genre: "Jazz", year: 1994, album: "Zero Tolerance for Silence" },
  { id: 4988, rank: 488, title: "Song for Bilbao", artist: "Pat Metheny", genre: "Jazz", year: 1977, album: "Pat Metheny Group" },
  { id: 4989, rank: 489, title: "Straight On Red", artist: "Herbie Hancock", genre: "Jazz", year: 1972, album: "Crossings" },
  { id: 4990, rank: 490, title: "Butterfly", artist: "Herbie Hancock", genre: "Jazz", year: 1974, album: "Thrust" },
  { id: 4991, rank: 491, title: "Spank-A-Lee", artist: "Herbie Hancock", genre: "Jazz", year: 1974, album: "Thrust" },
  { id: 4992, rank: 492, title: "Hang Up Your Hang Ups", artist: "Herbie Hancock", genre: "Jazz", year: 1975, album: "Man-Child" },
  { id: 4993, rank: 493, title: "Come Running to Me", artist: "Herbie Hancock", genre: "Jazz", year: 1977, album: "Sunlight" },
  { id: 4994, rank: 494, title: "I Thought It Was You", artist: "Herbie Hancock", genre: "Jazz", year: 1978, album: "Sunlight" },
  { id: 4995, rank: 495, title: "Tell Everybody", artist: "Herbie Hancock", genre: "Jazz", year: 1975, album: "Man-Child" },
  { id: 4996, rank: 496, title: "Watermelon Man (original)", artist: "Herbie Hancock", genre: "Jazz", year: 1962, album: "Takin' Off" },
  { id: 4997, rank: 497, title: "Driftin'", artist: "Herbie Hancock", genre: "Jazz", year: 1962, album: "Takin' Off" },
  { id: 4998, rank: 498, title: "The Maze", artist: "Herbie Hancock", genre: "Jazz", year: 1963, album: "My Point of View" },
  { id: 4999, rank: 499, title: "Riot", artist: "Herbie Hancock", genre: "Jazz", year: 1965, album: "Maiden Voyage" },
  { id: 5000, rank: 500, title: "Dolphin Dance", artist: "Herbie Hancock", genre: "Jazz", year: 1965, album: "Maiden Voyage" }
];
